### ISSUE TITLE
Dataset request: Singapore KML file by Postal Code

### ISSUE THREAD

**Issue by hafilahmohd** [datagovsg/datagovsg-datasets#100]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Singapore KML file by Postal Code

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
SLA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Hi, I am currently working in Institute of Mental Health. I am working on a GIS project. We require a kml polygon of Singapore based on postal code regions. Examples are attached below
![singapore-map-postal-code](https://user-images.githubusercontent.com/13796084/35431122-3f6a5b94-02b6-11e8-8f75-8d7ba55f33ca.png) 
![sg-postcode-map](https://user-images.githubusercontent.com/13796084/35431161-63440be6-02b6-11e8-879e-d3d081281e29.jpg)

We will be using this kml to create a heatmap of patients living in the particular district (eg: Number of patients living in area with postal code of first two digits starting with "53". 
With this heatmap, it will facilitate us in concentrating and improving our patient care on "heated" areas. 

Would really appreciate your help. Thank you.

**Comment by iewil** [comment]
@hafilahmohd unfortunately, this dataset is currently not available on our site. To get an updated version  of this dataset, Singpost currently provides a service for mapping postal codes. You can find out more via this [link](https://www.singpost.com/find-postal-code)
