### ISSUE TITLE
Hawker food and market stalls

### ISSUE THREAD

**Issue by TomFeraud** [datagovsg/datagovsg-datasets#1001]
### Please provide the name of the dataset or describe the dataset that you're requesting:

A list of hawkers already exists but I didn't found a list of stalls in the hawkers.
Could you help on this please ?

### Do you know which agency provides/can provide this data?

National Environment Agency ?

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

hawker | stall name | number | type
------|---------|-------------|--------|
Lau Pa Sat | Foodie Cuisine | #01-01 | food
Lau Pa Sat | MarketPlace | #01-43 | market

### How frequently would you need this dataset to be updated?

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@TomFeraud We are not able to provide the stall listings only the locations https://data.gov.sg/dataset/hawker-centres
