### ISSUE TITLE
Dataset request: Healthier Eateries

### ISSUE THREAD

**Issue by Journeyman1998** [datagovsg/datagovsg-datasets#1004]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Healthier Eateries

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### If there's an issue with a dataset, please provide a description of the problem
I am using this resource id: cf48cea3-dcc7-45e3-821e-b576c31ac69d to fetch the data, but it gives me a "Not found error". 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
Can you try this https://data.gov.sg/dataset/healthier-eateries you probably should download the KML to get the data. The dataset has also been updated.
