### ISSUE TITLE
Dataset request: Number of Patients under Pallative and/or Hospice Home Care

### ISSUE THREAD

**Issue by yewchinning** [datagovsg/datagovsg-datasets#1005]
### Please provide the name of the dataset or describe the dataset that you're requesting:
https://data.gov.sg/dataset/palliative-home-care-visits - This dataset published describes the number of palliative home care visits, however, it is uncertain if the palliative home care statistics include hospice care as well. 

The number of patients utilising such services is unclear as well since the number of visits does not denote the number of patients. 

### Do you know which agency provides/can provide this data?

Ministry of Health

### Please provide the fields expected in this dataset:

year | country | patients
------|---------|-------------
2017|Singapore|10000

year | country | visits
------|---------|-------------
2017|Singapore|10000

### How frequently would you need this dataset to be updated?

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For research-related school projects, where the above information will allow for insights into the landscape of such patients in Singapore.

**Comment by lennardl** [comment]
@yewchinning We have approached MOH on this and waiting for a response from them

**Comment by lennardl** [comment]
@yewchinning MOH has responded with the following

Home Palliative Care refers to non-residential palliative care that are offered to clients in their own homes, and hence do not include inpatient hospice care, which are considered as residential services. Statistics for inpatient hospice admissions up to 2020 can be found in MOH’s website:

https://www.moh.gov.sg/resources-statistics/singapore-health-facts/admissions-and-outpatient-attendances.

Statistics on the number of patients utilizing home palliative care are not available.
