### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by qwea1** [datagovsg/datagovsg-datasets#1006]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Number of foreign workers by Nationality

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Manpower

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Using it as infomediary for educational purpose

**Comment by lennardl** [comment]
@qwea1 That data is not available
