### ISSUE TITLE
Dataset request: <Management Corporation Strata Title>

### ISSUE THREAD

**Issue by khorrupt** [datagovsg/datagovsg-datasets#1007]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Management Corporation Strata Title

### Do you know which agency provides/can provide this data?
Building and Construction Authority

### If there's an issue with a dataset, please provide a description of the problem
NIL

### Please provide the fields expected in this dataset:
usr_mcno, usr_devtname, devt_location, mcst_houseno, mcst_roadname, mcst_unitno, mcst_buildingname, mcst_postalcode, mcst_telno, ust_status, mcst_stratalota, managementname, management_tel_no, mc_form_date

### How frequently would you need this dataset to be updated?

- [ ] Annually
- [X ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I'm developing a property management mobile app

**Comment by lennardl** [comment]
@khorrupt The dataset is available here https://data.gov.sg/dataset/management-corporation-strata-title as well as the APIs

**Comment by khorrupt** [comment]
Thank you @lennardl, the dataset says there are 9036 data, however the download dataset only has 4596. I'm wondering if there's anyway to get the full 9036 data?

**Comment by lennardl** [comment]
@khorrupt There was duplicative data there are only 4,596 line items and the frontend is now reflecting that correctly

**Comment by khorrupt** [comment]
Oh you're brilliant @lennardl. Thank you so much for the clarification.
