### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by Annalal37** [datagovsg/datagovsg-datasets#1008]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Is there a way we can know more statistics about the pass type distribution, for example we want to know how many new EPs are issued in each year (not including renewals)?

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
MOM

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

year | pass holder type | new issued or renewal? | population number
-----|------------------|------------------------|--------------------
2020| employment pass| new issued | 10000
2020| employment pass| renewal | 1000000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For company internal usage only

**Comment by lennardl** [comment]
@Annalal37 MOM only provides these numbers https://data.gov.sg/dataset/foreign-workforce-numbers-annual

**Comment by Annalal37** [comment]
已收到您的邮件，我会尽快查看，谢谢
