### ISSUE TITLE
Dataset request: List of pharmacies in Singapore

### ISSUE THREAD

**Issue by 1278513** [datagovsg/datagovsg-datasets#101]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Search list of retail pharmacies

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by iewil** [comment]
@1278513 there currently isn't such a dataset on our site. However, you can make use of this service provided by the Singapore Pharmacy Council to retrieve the required information [link here](https://prs.moh.gov.sg/prs/internet/profSearch/main.action?hpe=SPC).

**Comment by 1278513** [comment]
Thanks.
