### ISSUE TITLE
Dataset request: <Chronic Kidney Disease and Dietary Intake>

### ISSUE THREAD

**Issue by evelynlim** [datagovsg/datagovsg-datasets#1010]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I would like to request for the dataset of Singaporean/PR patients with Chronic Kidney Disease (CKD. 
The data should contain their demographics data, dietary intake data such as salt intake, death status, diabetes status, hypertension status, Cardiovascular Disease status  
I would also like to know among the CKD patients, how many worsen to develop ESKD. 
Important dates such as date of diagnosis and date of death are required for survival curves analysis. 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Health Promotion Board (HPB)
Immigration Checkpoint Authority (ICA)

### Please provide the fields expected in this dataset:

Age at diagnosis of CKD |Date of Diagnosis of CKD | eGFR | ACR | gender | race  | BMI | smoking status | Diabetes status | Date of Diabetes Diagnosis |  Cardiovascular Disease Status |  Hypertension status | Sodium intake | Total Energy Intake | Nutrition Index | Phosphate Intake | Potassium Intake | Date of nutrition survey | Death Status | Date of Death | Cause of Death (ICD) | ESKD status |

------|---------|-------------
29 | DDMMYY | 60ml/min/1.73m2| 30mg/g | F | Chinese | 25kg/m2 | Yes | Yes | DDMMYY | Yes | Yes | 1g/day | 2000kcal | 4 | 2g/day | 2g/day | DDMMYY | Yes | DDMMYY | 090 | 

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [X] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am a graduate student currently taking the Master in Public Health Course at NUS. This data will strictly be used for my masters project only.

**Comment by lennardl** [comment]
@evelynlim The level of detail you require is not available on the site. For such details, you would need to approach MOH/HPB for it
