### ISSUE TITLE
Dataset request: <cloud images with irradiance value>

### ISSUE THREAD

**Issue by lahiruprabath94617** [datagovsg/datagovsg-datasets#1011]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [x] Real-time

**Comment by lahiruprabath94617** [comment]
make a real time cloud detection project for reduce power fluctuation

**Comment by lennardl** [comment]
@lahiruprabath94617 We do not have that data on our site and NEA does not plan to provide that data to us
