### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by jmurrayhamilton** [datagovsg/datagovsg-datasets#1012]
### Do you know which agency provides/can provide this data? Government singapore
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

2020-12 | Singapore | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@jmurrayhamilton What sort of transport statistics do you need?

**Comment by jmurrayhamilton** [comment]
Hi!
I am studying the decline in public transport during COVID-19 in major
cities such as Singapore for a report.
Can you help? Or are the statistics only up until 2016?
many thanks
Jill

**Comment by lennardl** [comment]
@jmurrayhamilton there's limited data on it. You can check out https://datamall.lta.gov.sg/content/datamall/en/static-data.html#Public%20Transport
