### ISSUE TITLE
Dataset request: Realtime Historical Rainfall data by specific weather stations not working

### ISSUE THREAD

**Issue by marcusphang81** [datagovsg/datagovsg-datasets#1013]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I would like to request for realtime historical rainfall data by specific weather stations. By right the data can be obtained via https://api.data.gov.sg/v1/environment/rainfall?date=2021-03-03, however, upon looking through the data, there seems to be something wrong with the data as all the values was "0". Looking through the data for the entire February 2021 shows the same value=0 for all stations throughout the entire month of February, which is definitely inaccurate. 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
NEA, specifically Meteorological Service Singapore (MSS)

### If there's an issue with a dataset, please provide a description of the problem
By right the data can be obtained via https://api.data.gov.sg/v1/environment/rainfall?date=2021-03-03, however, upon looking through the data, there seems to be something wrong with the data as all the values was "0". Looking through the data for the entire February 2021 shows the same value=0 for all stations throughout the entire month of February, which is definitely inaccurate. 

### Please provide the fields expected in this dataset:
timestamp| station_id| value
------|---------|-------------
2021-03-03T00:05:00+08:00|S90|145

### How frequently would you need this dataset to be updated?
Example: 
- [X] Hourly

### Can you give a short explanation on how you're planning to use this dataset?
I am intending to use the data as inputs to my Artificial Intelligence model for predicting the possibility of rainfall in the next hour.

**Comment by lennardl** [comment]
@marcusphang81 Thanks for highlighting. I'll bring this up with NEA.

**Comment by marcusphang81** [comment]
@lennardl, thanks for the swift response. Shall await your updates. :)
