### ISSUE TITLE
Dataset request: <Taxi Data>

### ISSUE THREAD

**Issue by gengbin-p** [datagovsg/datagovsg-datasets#1015]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I would like to know if any taxi data on completed trips can be avaliable. To give a sense, here is what NYC is providing:
https://www1.nyc.gov/site/tlc/about/tlc-trip-record-data.page

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Should be Land Transport Authority

### Please provide the fields expected in this dataset:
variables:
Taxi id
Pick up location
Pick up time
Drop off location
drop off time
Length of the trip
Pricing metrics (price per mile, upfront price etc.)
Tips (if any)

NYC's data has dealt with privacy issues using a random generated taxi id (but constant across time), rounded time. 

### How frequently would you need this dataset to be updated?

- [ ] Annually
- [ ] Monthly
- [X ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To study the dynamic matching between taxis and riders in Singapore.

**Comment by lennardl** [comment]
@gengbin-p the completed trips data belong to the individual private companies hence we are not able to provide it.
