### ISSUE TITLE
Dates of hawker centre closure

### ISSUE THREAD

**Issue by emantpl** [datagovsg/datagovsg-datasets#1017]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Dates of hawker centre closure

### Do you know which agency provides/can provide this data?
NEA

### If there's an issue with a dataset, please provide a description of the problem
I started using it last week but the dataset has disappeared

### Please provide the fields expected in this dataset:
NA

### How frequently would you need this dataset to be updated?
- [ ] Annually
- [ ] Monthly
- [X] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
We provide tourists and residents self guided walk and eat tours. The hawker centre closure dates will be useful when users plan their tours so that the hawker centre is open when they visit

https://singaporetours.com.sg/hawker-centre

We are using cached data

**Comment by lennardl** [comment]
@emantpl I've approached NEA requesting for the data

**Comment by emantpl** [comment]
@lennardl  Thank you

**Comment by emantpl** [comment]
In the dataset, is the column name "serial_no" uniquely tied to a hawker centre

for example if I lookup serial_no "114" does it refers to data related to "Zion Riverside Food Centre" even in future data updates.

OR the serial_no is just a running number and can change in future updates and can refer to a different hawker centre

**Comment by lennardl** [comment]
@emantpl The serial no is just a running number

**Comment by emantpl** [comment]
OK 

The dataset is back up so this issue. is closed

Thanks again for your help
