### ISSUE TITLE
Dataset request: park connector network

### ISSUE THREAD

**Issue by LimJiaJing** [datagovsg/datagovsg-datasets#1019]
### Please provide the name of the dataset or describe the dataset that you're requesting:
A color-coded map of park connector network like the one shown on the National Parks Board website

### Do you know which agency provides/can provide this data?
National Park Board

### If there's an issue with a dataset, please provide a description of the problem
All loops are in the same color, would be better if each loop has a different color like the one shown on the National Parks Board website

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
lat|long|colour(loop)

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For an application revolving around the park connector network

**Comment by lennardl** [comment]
@RyzielleLim Our platform does not support colour coding. It's possible for you to download the KML and colour code based on the ID of the connectors? https://data.gov.sg/dataset/park-connector-loop
