### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by shan-rama** [datagovsg/datagovsg-datasets#1020]
I wld like to request 
1)data for 2020 waste produced/disposed/recycled. 
2)list of wastes categorised as  domestic/non domestic waste
3)list of domestic/non domestic wastes been disposed, produced, recycled

**Comment by lennardl** [comment]
@shan-rama 

The available data can be found at the following links, the dataset itself is outdated and I've requested for an update from NEA.

https://data.gov.sg/dataset/solid-waste-management-total-domestic-waste-disposed
https://data.gov.sg/dataset/solid-waste-management-total-waste-recycled
https://data.gov.sg/dataset/resource-conservation-recycling-rate-by-waste-type
https://data.gov.sg/dataset/solid-waste-management-total-waste-generated
