### ISSUE TITLE
Dataset request: <foreign workforce numbers>

### ISSUE THREAD

**Issue by CaitlinCF** [datagovsg/datagovsg-datasets#1021]
### Do you know which agency provides/can provide this data?
Ministry of Manpower

### Please provide the fields expected in this dataset:
*(e.g. year | country | number of workers)*

### How frequently would you need this dataset to be updated?
- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Using it in research for a MOE Tier 2 grant

**Comment by lennardl** [comment]
@CaitlinCF You can find the latest data here https://data.gov.sg/dataset/foreign-workforce-numbers-annual
