### ISSUE TITLE
Dataset request: Parks

### ISSUE THREAD

**Issue by sck32** [datagovsg/datagovsg-datasets#1022]
Dear,
I am a researcher at the Polytechnic of Turin (Italy). I am developing research on parks and green areas in Singapore.
In particular, on how the proximity of these urban green infrastructures have affected property prices.
I saw that shapefiles of urban green polygons updated to 2020 are available on the data.gov portal. I would need older data if it were possible, as the study would consider the transformation of the island from 1995 to 2017.
It would be very useful to have data on greenery relating to the various years taken into consideration.

Thanks for the attention,

Federico Dell'Anna

**Comment by lennardl** [comment]
@sck32 We do not have prior datasets especially those before 2016. In this case, you might want to reach out to NEA/NParks to see if they have the historical data for sharing
