### ISSUE TITLE
Dataset request: MRT Data

### ISSUE THREAD

**Issue by jloh02** [datagovsg/datagovsg-datasets#1023]
### Please provide the name of the dataset or describe the dataset that you're requesting:
MRT data similar to bus data in LTA's [DataMall](https://datamall.lta.gov.sg/content/datamall/en/dynamic-data.html). Specifically, MRT operation timings and frequency. 

### Do you know which agency provides/can provide this data?
LTA

### If there's an issue with a dataset, please provide a description of the problem
Currently, only [SHP files of MRT stations](https://datamall.lta.gov.sg/content/datamall/en/dynamic-data.html#Geospatial) are provided. This simply provides estimates of distance between MRT stations but does not provide frequency nor operation timings of MRTs.

### Please provide the fields expected in this dataset:
Based off DataMall's bus format. Due to the branching nature of Singapore's MRT system, a format similar to an "adjacency list" is proposed.

**TrainStops**
| stationCode | stationName |
|-|-|
| NS99 | Raffles City | 

**TrainRoutes**
| stationCode | nextStationCode | WD_firstTrain | WD_lastTrain | SAT_firstTrain | SAT_lastTrain | SUN_firstTrain | SUN_lastTrain | AM_Peak_Freq | AM_Offpeak_Freq |  PM_Peak_Freq | PM_Offpeak_Freq |
|-|-|-|-|-|-|-|-|-|-|-|-|
| DT01 | DT02 | 0000 | 2359 | 0000 | 2359 | 0000 | 2359 | 3 | 6 | 3 | 6 |

### How frequently would you need this dataset to be updated?
Example: 
- [x] Ad-Hoc
- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [X] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Combining this data with the bus data provided by LTA, a full transit network can be built which integrates both major forms of public transport. The dataset can then be used for various public transport projects such as developing an efficient routing algorithm for Singapore's public transport system. 

This data is already provided on multiple web pages, including Google Maps. Exposing an API would aid developers in more efficient development of transit-related applications.

**Comment by lennardl** [comment]
@jloh02 We do not have the data on our site, I've reached out to LTA to see if they can make it available.

**Comment by bjornlll** [comment]
I would also love to see this dataset. @lennardl do you think there's any chance? :)

**Comment by lennardl** [comment]
@bjornlll I can approach LTA to request but since it belongs to SMRT which is a private entity it's unlikely. But I will update once I have a response.

**Comment by bjornlll** [comment]
Got you @lennardl. Appreciate you keeping us in the loop.
