### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by hhoupt** [datagovsg/datagovsg-datasets#1024]
Hi! I am doing a project for school on how refugees or immigrants have been impacted by Coronavirus. If you have any datasets on this topic, I would really appreciate if you sent them to me. I haven't decided the geographical location for my project, so I am flexible with any dataset you have. 

Thank you!

**Comment by lennardl** [comment]
@hhoupt For Coronavirus related data, you would have to refer to https://www.moh.gov.sg/covid-19 from the Ministery of Health
