### ISSUE TITLE
Dataset request: Dengue and Weather historical dataset

### ISSUE THREAD

**Issue by briankbng** [datagovsg/datagovsg-datasets#1026]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Dengue data for the last 10 years
Weather data for the last 10 years

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
NEA

### If there's an issue with a dataset, please provide a description of the problem
NA

### Please provide the fields expected in this dataset:
Dengue dataset:
date | dengue cases | location  (lat, lon) | severity (mild/serious/vital) | zone (town)

Weather dataset:
date | sunshine duration | rain fall | temperature | weather (cloudy/sunny/rainy) | zone (town)

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am a part-time Postgraduate Master degree student from NUS ISS and my team is doing a project to determine the 2 to 4 weeks trend of dengue in zones/areas of Singapore based on past historical data and current dengue status and weather data.

**Comment by lennardl** [comment]
@kbokng We have limited data before 2016.

https://data.gov.sg/dataset/weekly-number-of-dengue-and-dengue-haemorrhagic-fever-cases
https://data.gov.sg/dataset/weekly-infectious-disease-bulletin-cases (Dengue Cases)
https://data.gov.sg/dataset/realtime-weather-readings (you can parse in previous dates to get historical data)
