### ISSUE TITLE
Dataset request: <Singapore Diesel Consumption>

### ISSUE THREAD

**Issue by khushikarnawat** [datagovsg/datagovsg-datasets#1028]
### Please provide the name of the dataset or describe the dataset that you're requesting:

We are looking for total consumption of diesel per year

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Land Transport Authority or Energy Market Authority

### If there's an issue with a dataset, please provide a description of the problem
Cannot find the dataset 

### Please provide the fields expected in this dataset:

Years  | Total number of cars  | total diesel used
------|---------|-------------
2015-20| 

### How frequently would you need this dataset to be updated?
Annually

### Can you give a short explanation on how you're planning to use this dataset?

We are a group of students at NTU working on a group project about diesel tax in Singapore. Thus, we are seeking the data set to conduct a cost-benefit analysis for our university project.

**Comment by lennardl** [comment]
@khushikarnawat Unfortunately we do not have the data
