### ISSUE TITLE
Dataset request: <dataset title>Location of Fire Hydrants in Singapore

### ISSUE THREAD

**Issue by georgeleem** [datagovsg/datagovsg-datasets#1029]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Location of Fire Hydrants in Singapore

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
SLA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@georgeleem We have approached the agency for the data, waiting on their response.
