### ISSUE TITLE
Dataset request: <dataset title>singapore dengue dataset

### ISSUE THREAD

**Issue by fatinfatihah** [datagovsg/datagovsg-datasets#103]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Singapore dengue dataset and climatic dataset (temperature, rainfall and humidity) for each districts/regions for monthly (2003-2017) 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

year|month | country | region/districts| dengue cases| temperature (celcius)| rainfall (mm) | relative humidity| population
------|---------|-------------

2017|January|Singapore|central Singapore|30|300|89|200000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
for academic purpose only

**Comment by iewil** [comment]
@fatinfatihah this dataset is already available on our site as geospatial layers and APIs. 
- https://data.gov.sg/developer
- https://data.gov.sg/dataset/dengue-cases
