### ISSUE TITLE
Dataset request: Supplementary Retirement Scheme (SRS) - Contributions Patterns by Demographic Profile of Account Holders 

### ISSUE THREAD

**Issue by timochow** [datagovsg/datagovsg-datasets#1034]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Supplementary Retirement Scheme (SRS) - Contributions Patterns by Demographic Profile of Account Holders

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Finance
https://www.mof.gov.sg/schemes/individuals/supplementary-retirement-scheme

### If there's an issue with a dataset, please provide a description of the problem
N/A

### Please provide the fields expected in this dataset:
Field list:

- Year (int) 
- Total SRS Contributions made by all SRS account holders in Year (float)
- SRS Contributions made by SRS account holders in age group 18-35 in Year (float)
- Median SRS Contributions made by SRS account holders in age group 18-35 in Year (float) excluding those who made no contribution
- SRS Contributions made by SRS account holders in age group 36-45 in Year (float)
- Median SRS Contributions made by SRS account holders in age group 36-45 in Year (float) excluding those who made no contribution
- SRS Contributions made by SRS account holders in age group 46-55 in Year (float)
- Median SRS Contributions made by SRS account holders in age group 46-55 in Year (float) excluding those who made no contribution
- SRS Contributions made by SRS account holders in age group 56-61 in Year (float)
- Median SRS Contributions made by SRS account holders in age group 56-61 in Year (float) excluding those who made no contribution
- SRS Contributions made by SRS account holders in age group >=62 in Year (float)
- Median SRS Contributions made by SRS account holders in age group >=62 in Year (float) excluding those who made no contribution
- Percentage of SRS account holders in each age group who made an SRS contribution within the Year

### How frequently would you need this dataset to be updated?
- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To understand the how different demographic groups (by age) make contributions to SRS accounts 
The data available on the MOF website is inadequate to do so.

**Comment by lennardl** [comment]
@timochow The detailed data is not available and you would need to approach MOF for it
