### ISSUE TITLE
Dataset request: <School Directory and Information>

### ISSUE THREAD

**Issue by tb960** [datagovsg/datagovsg-datasets#1037]
### Do you know which agency provides/can provide this data?
https://data.gov.sg/organization

### If there's an issue with a dataset, please provide a description of the problem
The dataset which is previously available at https://data.gov.sg/search, with resource id = ede26d32-01af-4228-b1ed-f05c45a1d8ee is removed, and we need it for a school project for Nanyang Technological University. We have to fetch the data in real time and we need the dataset to be available.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
The few dataset which is associated with this resourse id is:
school_name, moe_programme, distinctive_programme, subject and cca

school_name | subjects | 
------|---------|-------------
Admiralty Primary School|English|
Admiralty Primary School|Chinese|

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ X] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
We are currently developing a mobile app for a school finder application and it is a private education purpose.
We have to fetch the data in real time and display matching school according to the user input for criteria.

**Comment by lennardl** [comment]
@tb960 There was an update to the dataset, it's back up now https://data.gov.sg/dataset/school-directory-and-information

**Comment by Abhigyan14** [comment]
This link still gives a 404 error

**Comment by Abhigyan14** [comment]
> @tb960 There was an update to the dataset, it's back up now https://data.gov.sg/dataset/school-directory-and-information

I tried this gives a 404 error

**Comment by Abhigyan14** [comment]
@lennardl 
<img width="1440" alt="Screenshot 2021-03-25 at 10 32 00 PM" src="https://user-images.githubusercontent.com/60545536/112490118-10c96680-8dba-11eb-9881-548cfe1327ed.png">

**Comment by lennardl** [comment]
@tb960 Can you try again now?
