### ISSUE TITLE
Dataset request: Education Outcomes Data for Individuals

### ISSUE THREAD

**Issue by jinfu93** [datagovsg/datagovsg-datasets#1041]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I would like to request access to individual level data for schooling outcomes at various levels of education. Understandably, privacy is an important issue so it would still be incredibly helpful to either have redacted data or data aggregated at a higher level i.e. class. Pertinent schooling outcomes would include PSLE scores, O Levels, A Levels and other benchmarks along the way. I would like to have a sense of what schools and streams students were filtered into as well.

### Do you know which agency provides/can provide this data?
I believe that the data source would primarily be from the Ministry of Education. What is currently publicly available is only aggregate level data by cohorts.

### If there's an issue with a dataset, please provide a description of the problem
NA.

### Please provide the fields expected in this dataset:

Ideally, the data would look as follows:
Student_ID | Primary School | PSLE | Secondary School | Secondary School Stream | O Levels | Junior College | A Levels | Other Education Characteristics |

### How frequently would you need this dataset to be updated?
I only need historical data, so no real need to update with the latest cohorts although extra data would be helpful as well.

### Can you give a short explanation on how you're planning to use this dataset?
I am trying to study the impact of early streaming on subsequent education outcomes. Thank you very much for taking the time to look through my request. Any level of data that is more granular than cohort level data would be greatly appreciated!

**Comment by lennardl** [comment]
@jinfu93 For such data, you would need to approach MOE directly for it.
