### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by Chee-waiHo** [datagovsg/datagovsg-datasets#1042]
### Please provide the name of the dataset or describe the dataset that you're requesting:

COE Results (Prevailing Quota Premium)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
LTA
This is already provided. However, it does not seem to be updated. https://data.gov.sg/dataset/coe-bidding-results?resource_id=85deb904-fbf9-46bc-80fd-9676213bbf1f

### If there's an issue with a dataset, please provide a description of the problem

The PQP values are provided only up to Apr-2020

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
The current dataset fields are adequate. The dataset needs to be updated with the latest PQP values.

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

This is a very useful resource for my trainees doing a course in Data Analytics. While PQP values are available from many internet resources, data.gov.sg has a very useful Data API that can be accessed from a program, e.g. Python or Javascript. We have made use of this for two runs and we will like to continue to do so. I believe this should not be difficult to address. Thank you.

**Comment by lennardl** [comment]
@Chee-waiHo We currently do not host the COE results. We have been trying to get it published here. For now the best source is LTA's site.
