### ISSUE TITLE
Dataset request: Income disparity among married couples.

### ISSUE THREAD

**Issue by Fireronin** [datagovsg/datagovsg-datasets#1047]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Income disparity among married couples. 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

Inland Revenue Authority of Singapore

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

This income can be yearly or monthly, in any currency 

Household id| Husband's income | Wife's income 
------|---------|-------------
1 | 73000 | 75000

I'm not sure about your policy but something like 

Household id (row id) | Total household income | (Husband's income  - wife's income) / Total household income 
------|---------|-------------
1 | 148000 | 0.0135 (precision of this field can be taken such to anonymize data)

As for same-sex marriages they can be either dropped signified by one more collumn. eg. ( Is_same_sex | No/Gay/Lesbian) 

#### If this is too granular data, how about aggregates like this:

This would be a 2D grid of data.
where it would have 2 axes:
1. TOTAL - Yearly total household income (in brackets, I'm not sure how wide brackets should be as smaller brackets give more data) 
2. DIFFERENCE ((Husband's income  - wife's income) / Total household income ) * 100% (in brackets, for example, every 0.1, again smaller this constant more data)

And for each point on this 2D, there would be the proportion of people who fall in there.

example: (here is use brackets of 10usd and 1% but I don't know data and I don't know whether everything will fall into one of them or more) 
TOTAL\DIFFERENCE | < -2.5  | -2.5~-1.5 | -1.5~-0.5 | -0.5~0.5 | 1.5~2.5 |  > 2.5
0-10k USD              |       0.3% | 1% | ...
10k-20k USD          |     0.7% | ...
...                            | ...
250k usd and over |

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

I would like to look better understand how much bias there is from income when choosing a partner.

**Comment by lennardl** [comment]
@Fireronin Unfortunately that data is not available
