### ISSUE TITLE
Dataset request: Singapore Monthly Dengue Cases

### ISSUE THREAD

**Issue by Flooblecrank** [datagovsg/datagovsg-datasets#105]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Singapore Monthly Dengue Cases dataset (table)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
National Environmental Agency
Ministry of Health

### If there's an issue with a dataset, please provide a description of the problem
NA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [x] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I intend to use this data for a school project regarding monthly Dengue cases in Singapore.

**Comment by iewil** [comment]
@Flooblecrank this is a duplicated request. You can find out more in this issue #103
