### ISSUE TITLE
Dataset request: MND Town Council Boundaries

### ISSUE THREAD

**Issue by glchua2** [datagovsg/datagovsg-datasets#1050]
### Please provide the name of the dataset or describe the dataset that you're requesting:
MND Town Council Boundaries, like the one shown in OneMap. Please refer to screenshot below.

![image](https://user-images.githubusercontent.com/2323076/114483437-e8a38980-9c3a-11eb-8d27-e0b6b93a1311.png)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
MND (Ministry of National Development).

### Please provide the fields expected in this dataset:
Name of Town Council, boundary of Town Council.

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
As additional map layer within web application.

**Comment by lennardl** [comment]
@glchua2 We are not given permission to host this map layer. You can only access it from MND/URA site

**Comment by glchua2** [comment]
@lennardl We are ok with including this map layer ourselves and host it internally. The issue is that I am unable to find any shp or KML file alike for this map layer within https://data.gov.sg/

**Comment by lennardl** [comment]
@glchua2 Yes its just that we are not given the permission to host it which in turn means we are not able to share it with anyone too

**Comment by glchua2** [comment]
@lennardl Thanks for the clarification. So the only way to go forward will be to request from MND, is that right?

**Comment by lennardl** [comment]
@glchua2 Yes, unless MND is willing to give you the data
