### ISSUE TITLE
Dataset request: Singapore Postal Codes with Lat Long 

### ISSUE THREAD

**Issue by rachelsubscribe01** [datagovsg/datagovsg-datasets#1051]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Singapore Postal Codes with Lat Long 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
URA, HDB?

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Postalcodenum| Lat | Long
------|---------|-------------
311138|1.33660|103.84530

### How frequently would you need this dataset to be updated?
Example: 
Annually

### Can you give a short explanation on how you're planning to use this dataset?
Services coverage analysis based on postal codes.

**Comment by lennardl** [comment]
@rachelsubscribe01 Postal code information is owned by Singapore Post. You will need to approach them for the data.
