### ISSUE TITLE
Dataset request: <Micro-level data on Income of Individuals, Annual>

### ISSUE THREAD

**Issue by RuruHoong** [datagovsg/datagovsg-datasets#1052]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Income of Individuals, Annual (e.g., https://data.gov.sg/dataset/income-of-individuals-by-income-type-annual, but on a more granular level but on a micro data level)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
IRAS

### If there's an issue with a dataset, please provide a description of the problem
-

### Please provide the fields expected in this dataset:
year | total income | tax-deductible donations | non-tax-deductible donations (if available) | other tax deductions | tax rate | assessable_income | income_type | total tax payable

### How frequently would you need this dataset to be updated?
Example: 
- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I hope to use it for a research project on charitable giving: what is the impact of the variation of tax-deductible rate on donations, and tax revenue? What is the optimal way for the government to allocate between providing a social service/ support Singapore's economic and social programmes directly themselves vs. through government support to charitable foundations vs. by incentivising others to donate by instrumental changes in the tax-deductible rate? Please feel free to contact me -- I would be open to having a discussion about how my research may be of use to IRAS as well.

**Comment by lennardl** [comment]
@RuruHoong Micro level data is not available. You would need to approach IRAS or the Department of Statistics to ask if the data can be made available for the purposes of your research

**Comment by RuruHoong** [comment]
Thanks!
