### ISSUE TITLE
Dataset request: Heart attack dataset of Singaporean

### ISSUE THREAD

**Issue by hoshihl** [datagovsg/datagovsg-datasets#1055]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Request for heart attack dataset of Singaporean

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
https://data.gov.sg/

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Age|Gender|Chest Pain Type|resting blood pressure (in mm Hg)|cholestoral in mg/dl fetched via BMI sensor|(fasting blood sugar > 120 mg/dl) (1 = true; 0 = false)|resting electrocardiographic results|maximum heart rate achieved|exercise induced angina (1 = yes; 0 = no)|Previous peak|Slope|number of major vessels (0-3)|Thal rate|Target variable

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [X ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I will be using the dataset for my datascience project.

**Comment by lennardl** [comment]
@hoshihl I have approached MOH asking if the data can be made available

**Comment by hoshihl** [comment]
Hi Lennard

Thanks for your assistant on this request!

Thanks and Regards
Hwi Ling

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lennardl** [comment]
@hoshihl MOH has responded that the data is not available

**Comment by hoshihl** [comment]
Hi Lennard

Thanks for the reply and noted data is not available. 

Regards
Hwi Ling
