### ISSUE TITLE
Dataset request: Age-Standardised Mortality Rate for Ischaemic Heart Disease, Stroke and Cancer

### ISSUE THREAD

**Issue by hoshihl** [datagovsg/datagovsg-datasets#1056]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Age-Standardised Mortality Rate for Ischaemic Heart Disease, Stroke and Cancer

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
https://data.gov.sg/MOH

### If there's an issue with a dataset, please provide a description of the problem
Kindly provide the raw data set with details on the factors that will cause Ischaemic Heart Disease. Thank you.

### Please provide the fields expected in this dataset:
Age of the person|Gender of the person|Chest Pain type chest pain type|resting blood pressure (in mm Hg)|cholestoral in mg/dl fetched via BMI sensor|(fasting blood sugar > 120 mg/dl) (1 = true; 0 = false)|resting electrocardiographic results|maximum heart rate achieved|exercise induced angina (1 = yes; 0 = no)|Previous peak|Slope|number of major vessels (0-3)|Thal rate|outputTarget variable

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For project purposes (IBM SGUnited AI course)

**Comment by lennardl** [comment]
@hoshihl Similar to the other request, have asked MOH in the same request

**Comment by lennardl** [comment]
@hoshihl MOH has updated the dataset here https://data.gov.sg/dataset/age-standardised-mortality-rate-for-ischaemic-heart-disease-stroke-and-cancer
