### ISSUE TITLE
Dataset request: Average Household Income, Income Decile, by Ethnic Group of Lead of Household

### ISSUE THREAD

**Issue by stxhxh** [datagovsg/datagovsg-datasets#1057]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Average Household Income, Income Decile, by Ethnic Group of Lead of Household

### Do you know which agency provides/can provide this data?
IRAS

### Please provide the fields expected in this dataset:

year | ethnic group | income decile | average household income
------|---------|-----------|---------------
2019 | chinese | lowest 10% | 5000
2019 | chinese | 11% to 20% | 5000
...
2019 | chinese | top 10% | 5000
2019 | malay| lowest 10% | 5000
2019 | malay | 11% to 20% | 5000
...
2019 | malay | top 10% | 5000
...
2019 | malay| lowest 10% | 5000
2019 | malay | 11% to 20% | 5000
...
2020 | chinese | lowest 10% | 5000
2020 | chinese | 11% to 20% | 5000
...
2020 | chinese | top 10% | 5000

### How frequently would you need this dataset to be updated?
- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

For as long as data is available

### Can you give a short explanation on how you're planning to use this dataset?

Research into income inequality by ethnic group

**Comment by lennardl** [comment]
@stxhxh That breakdown is not available. You would need to approach IRAS directly to see if they can give you the data.
