### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by yeoqiwei** [datagovsg/datagovsg-datasets#1058]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Monthly / 2015-2019/ Singapore approx 60 observations, 360 individual data sets
Fields expected indicated below in message 

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

Dear Department, 

I'm YEO QI WEI, a Singapore citizen currently studying part-time at University of Essex. I'm in my final term and undertaking a module, Finance research Capstone project, which requires me to find a topic that's related to finance, of which expects me to complete a 6000 word essay with quantitative modelling using EViews.

As such, i've decided to embark to study the relationship between wages and prices of STI index. Can the STI be forecasted by wages? or to be specific, wages of certain sector to ultimately forecast STI i.e. 

STI = GDP + Median monthly wage (agri, ind, svc,1,2,3,4 ) + unemployment rate + inflation rate + import + export (how employment of industry specific performance affects the STI, is there a relationship, can it be explained? 

However due to the nature of limited datasets available, I've combed through
https://data.gov.sg/group/economy & https://www.singstat.gov.sg/ only to find limited data sets or data sets that are only limited to the recent times and only in denomination of annual figures. 

I'm looking for Monthly data (wages) from 2015-2019 (approx 60 observation per data sets) and these are the data sets that I'm looking for 

1) Monthly Gross Wages 50Pctile by Major Occupation (PME, associate professional, etc)  followed by Industry (manufacturing, f&b, etc) and lastly by Occupational Description (mechanical engineer, sales manager, etc)

An example would be the screenshot, Image 1A, however it’s in annual figures. Estimation of 360 individual monthly data sets with 60 observation for each individual data sets base on research requirements.

 
2)Monthly unemployment rate (cumulative) 
3)Monthly Inflation rate 
4)Monthly imports (cumulative)
5)Monthly Exports (cumulative)
6)Monthly National Debt to GDP 
7)Monthly GDP 

I'm willing to pay the cost of recovery-fee though my lecturer has advise me to find ways to not have to pay but i'm willing to do it for my assignment sake and i have strong interest and passion in forecasting. If required and requested, I'm able to produce my completed findings at the end to prove my legitimate use of data. 

Thanks for taking the time to read and i hope to be able to obtain the data for assignment related purpose.

![1A](https://user-images.githubusercontent.com/82786611/115168421-69f09580-a0ed-11eb-8337-18e39663699f.jpg) e.g. of required & requested data sets in monthly figures from 2015-2019 (approx 60 observations per data sets across 360 individual segments)

![1B](https://user-images.githubusercontent.com/82786611/115168517-d53a6780-a0ed-11eb-8444-f290f27fb636.jpg)  proof of studies

**Comment by lennardl** [comment]
@yeoqiwei we do not have the data breakdown on a monthly basis, you might need to approach the department of statistics to see if they can breakdown the number for you to a monthly basis.

**Comment by yeoqiwei** [comment]
thanks lennardl. Will approach stats dept for breakdown.
