### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by nkghan96** [datagovsg/datagovsg-datasets#1059]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Chewing Gums brands available in Singapore (licensed import)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
No - But maybe HSA/HPB

### If there's an issue with a dataset, please provide a description of the problem
I cannot find relevant dataset

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Product | Country of origins | License expiry date

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am doing research on chewing gum in Singapore, thus wanting to know if any brands are legally available in Singapore

**Comment by lennardl** [comment]
@nkghan96 I've approached SFA to ask for this

**Comment by lennardl** [comment]
@nkghan96 I've been informed by HSA to let you know to contact them directly for this at HSA_Info@hsa.gov.sg i

**Comment by nkghan96** [comment]
Hi Lennard,

I've found the data I needed from HSA website. Thank you! Please close this
ticket upon receipt of this email.

Best Regards,

Océane Han Nguyen
