### ISSUE TITLE
10 year government bond yield Monthly Data

### ISSUE THREAD

**Issue by Haleema137** [datagovsg/datagovsg-datasets#106]
### Please provide the name of the dataset or describe the dataset that you're requesting:

**I need monthly data on 10 year government bond yield for the period 1984M1-2017M12**
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Monthly data
Singapore

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [x] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by Haleema137** [comment]
I need data for calculating soveriegn risk that is a component/variable in my PhD Dissertation

**Comment by iewil** [comment]
@Haleema137 you might be able to find what you're looking for on [MAS's website](https://secure.sgs.gov.sg/fdanet/SgsBenchmarkIssuePrices.aspx).
