### ISSUE TITLE
Dataset request: Singapore Greenhouse Gas Emissions 2017 to 2020

### ISSUE THREAD

**Issue by himmelz** [datagovsg/datagovsg-datasets#1061]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Singapore Greenhouse Gas Emissions 2017 to 2020

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
National Environment Agency

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Emissions profile - sector, % of emission, year

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [x ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For research

**Comment by lennardl** [comment]
@himmelz I've approached NEA for this.

**Comment by lennardl** [comment]
@himmelz Can you let us know what specific data items would be needed so that NEA can add them? We are aware there is an existing dataset on carbon dioxide emission which needs updating as well https://data.gov.sg/dataset/climate-change-and-energy-carbon-dioxide-emissions-from-combustion-of-fossil-fuels

**Comment by himmelz** [comment]
Hi.

If possible, provide an update on the existing dataset to show up to year 2020. If dataset has breakdown by sector, that would be useful. I’m doing an analysis for carbon emission for manufacturing sector in singapore.

Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lennardl** [comment]
@himmelz thanks let me check with NEA and get back to you

**Comment by lennardl** [comment]
@himmelz I've been asked by NEA to direct you here https://www.nea.gov.sg/our-services/climate-change-energy-efficiency/climate-change/national-communications-and-biennial-update-reports

**Comment by himmelz** [comment]
Ok. Thank you

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
