### ISSUE TITLE
Hourly rainfall record for 2020

### ISSUE THREAD

**Issue by joekyaw1** [datagovsg/datagovsg-datasets#1062]
Hi, I am a student who studies hydrology for my final year project. I would like to request an hourly rainfall record for 2020 for my final year project paper. 

Please kindly contact me at 81180537. 

Your kind response would be deeply appreciated.

Thanks& Regards,

KYAW SWAR TUN
81180537
kokyawswartun@gmail.com

**Comment by lennardl** [comment]
@joekyaw1 Its possible to use this API to retrieve the hourly rainfall for 2020 by parsing in the dates https://data.gov.sg/dataset/realtime-weather-readings?resource_id=8bd37e06-cdd7-4ca4-9ad8-5754eb70a33d
