### ISSUE TITLE
Dataset request: HDB Carpark Information

### ISSUE THREAD

**Issue by natznano** [datagovsg/datagovsg-datasets#1065]
### Please provide the name of the dataset or describe the dataset that you're requesting:
HDB Carpark Information - Extended

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Housing Development Board

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

car_park_no | no_car_park_lots | no_motorcycle_park_lots
------|---------|-------------
YHS | 250 | 30

### How frequently would you need this dataset to be updated?
Example: 
- [] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I work in a Singaporean company invited for an RFI to LTA on EV chargers in HDB car parking lots. This information will be used for a comprehensive report as part of the RFI.

**Comment by lennardl** [comment]
@natznano I've written to HDB asking if those data points can be added.

**Comment by natznano** [comment]
@lennardl Thanks a lot for your prompt response!

**Comment by natznano** [comment]
@lennardl Any news from HDB? Sorry to keep pushing

**Comment by lennardl** [comment]
@natznano Apologies but HDB has not responded to me yet

**Comment by natznano** [comment]
@lennardl got it, awaiting your response, thanks a lot

**Comment by natznano** [comment]
@lennardl anything yet? If they haven't responded by now, maybe they are not keen on sharing or don't have the info. You may close this case.

**Comment by lennardl** [comment]
@natznano Its likely the new points won't be added as I've not heard back

**Comment by natznano** [comment]
@lennardl Thanks a lot, I am closing this case.
