### ISSUE TITLE
Dataset request: <First Born Outcomes Data for Individual New Homeowners>

### ISSUE THREAD

**Issue by paulteh** [datagovsg/datagovsg-datasets#1066]
Dataset request: < First Born Outcomes Data for Individual New Homeowners >

### Please provide the name of the dataset or describe the dataset that you're requesting:

We would like to request access to individual level data for firstborn outcomes at various duration of marriage and HDB ownership, so as to create an analysis and prediction model for likelihood of new home owners to start a family within the first 5 years. This is to help childcare centres to allocate space and resources accordingly.

As privacy is an important issue, we only need redacted data.

### Please provide the fields expected in this dataset:

12yrs    |    2004 - 2019     |    sample size: 385/yr

First time homeowner ID
HDB flat types
HDB Address  
Date of key collection
Price of HDB
Proximity Grant
Highest educational Level

Household income
Date of birth wife of house owner (age range) 
Date of marriage

Date of birth of first born

Address of first born's childcare centre
No. of childcare centres within 1km of home address

### Can you give a short explanation on how you're planning to use this dataset?

Our group project objective is to predict the number of firstborns in a given HDB block within the first 5 years of moving in.

**Comment by lennardl** [comment]
@paulteh The data on the site is mostly aggregated. For individual-level data, you will need to approach the individual ministries for the data.

**Comment by paulteh** [comment]
@lennardl okay noted with thanks!
