### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by kartallar42** [datagovsg/datagovsg-datasets#1067]
Hello! I'm writing from Turkey. My name is Yalçın. I am writing to you because my homework is related to your open data portal. Could you tell us which institution and organization is responsible for the shared data and how many people have used all the shared data so far? Thank you very much in advance.

**Comment by lennardl** [comment]
@kartallar42 The site itself is developed under the Government Technology Agency (GovTech). The data on the site is contributed by the individual agencies. The list of agencies can be found on the drop-down menu on the left hand side of this page https://data.gov.sg/search
