### ISSUE TITLE
Dataset request: <cardiac arrest cases in Singapore over 10 or more years>

### ISSUE THREAD

**Issue by L-jiaxuan** [datagovsg/datagovsg-datasets#1068]
I am requesting for data on the total number of out of hospital cardiac arrest cases in Singapore per year over a period of 10 or more years. 

Agency provides/can provide this data?
Health Promotion Board, Health Sciences Authority. 

there are no raw data or data of total out of hospital cardiac arrest cases over a few years in Singapore.

year | Singapore | patients
2010-2020|Singapore|-

How frequently I would need this dataset to be updated?

- [x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

This data will be used to explain why we have started our project addressing the need for increasing importance of addressing cardiac arrest in Singapore

**Comment by lennardl** [comment]
@L-jiaxuan There was a similar request recently and MOH had responded that the data is not available.
