### ISSUE TITLE
Dataset request: Income by Electoral Boundaries 2011

### ISSUE THREAD

**Issue by jogramphy** [datagovsg/datagovsg-datasets#1069]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I'm interested in understanding the spatial distribution of household income across electoral boundaries.

### Do you know which agency provides/can provide this data?
Department of Statistics
Census Dataset

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

boundary | income
------|---------
Bukit Timah GRC | 123000

### How frequently would you need this dataset to be updated?
Example: 

- [x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I'm interested in creating a visualization (cartographic) that highlights distribution of income across electoral boundaries

**Comment by lennardl** [comment]
@jogramphy The data of household income is not available at the town/electoral boundary level.
