### ISSUE TITLE
Dataset request: ACRA Information on Corporate Entities

### ISSUE THREAD

**Issue by susanshtan** [datagovsg/datagovsg-datasets#107]
### Please provide the name of the dataset or describe the dataset that you're requesting: 
ACRA Information on Corporate Entities

### Do you know which agency provides/can provide this data?
Accounting and Corporate Regulatory Authority

### How frequently would you need this dataset to be updated?

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
As Procurement in the company, we would like to explore the opportunity of using this dataset to reconcile our supplier database, to stay up to date on the supplier's status as well as maintain accuracy of our supplier record. Appreciate if this dataset can be updated on a monthly basis.

**Comment by jieling1502** [comment]
Hi, 

I think the info you require is already available from NOV 2017 onward. 

You may refer to this link:
https://data.gov.sg/dataset/acra-information-on-corporate-entities

**Comment by susanshtan** [comment]
Hi,

It did mention that the update is on monthly basis. However, the last update is 2 Nov 2017, which means the dataset is not being updated for 3 months now.

**Comment by susanshtan** [comment]
Hi GovTech team, I notice that this data set is updated yesterday. Thank you for the effort to keep it updated...
