### ISSUE TITLE
Dataset request: Realtime Weather Readings across Singapore

### ISSUE THREAD

**Issue by ForceLightning** [datagovsg/datagovsg-datasets#1070]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Realtime Weather Readings across Singapore

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
National Environment Agency

### If there's an issue with a dataset, please provide a description of the problem
Too few locations for hourly data.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

location | temperature
------|---------|
Western Water Catchment | 33.9

### How frequently would you need this dataset to be updated?

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [x] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Dissemination of temperatures of SAF training plots for training.

**Comment by lennardl** [comment]
@ForceLightning The data we receive is directly from NEA the locations vary depending on whether the weather stations send data over to us.

**Comment by ForceLightning** [comment]
Is the data in this API the same as the one being used in the myEnv app?

**Comment by lennardl** [comment]
@ForceLightning There are separate APIs that are used within NEA for NEA.
