### ISSUE TITLE
Dataset request: <Internship Salary in Singapore over the years>

### ISSUE THREAD

**Issue by sh3rmain3** [datagovsg/datagovsg-datasets#1071]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Internship Salary in Singapore over the years

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

country | salary | industry | role
Singapore | $1800 | IT | Software Developer

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@sh3rmain3 That data is not available on our site, you will have to approach MOM to ask if that data is available.
