### ISSUE TITLE
Dataset request: Rainfall radar area image

### ISSUE THREAD

**Issue by eomcisumina** [datagovsg/datagovsg-datasets#1072]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Rainfall radar area image.

Main Page: https://www.nea.gov.sg/weather/rain-areas or http://www.weather.gov.sg/weather-rain-area-50km
Direct image link: https://www.nea.gov.sg/docs/default-source/rain-area/dpsri_70km_2021050506550000dbr.dpsri.png or http://www.weather.gov.sg/files/rainarea/50km/v2/dpsri_70km_2021050507050000dBR.dpsri.png

### Do you know which agency provides/can provide this data?
NEA / MSS

### If there's an issue with a dataset, please provide a description of the problem
The data accessible via NEA / MSS websites only go back for a few months / days respectively. 

I have emailed NEA, and for access to the radar images for the same time period (2017 onwards) as the other weather data (wind/temperature/rainfall/etc) available on data.gov.sg, NEA quoted me a sum of SGD$1,602.00.

These are 217x200 images, and the estimated size for the dataset for 2017 till present is ~1.1GB (~700 byte/file).

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

DateTime | Rainfall radar image
------|---------|-------------
2016-12-09T00:00:59+08:00 | image file

### How frequently would you need this dataset to be updated?
Example: 

- [X] Weekly

Reason: I can scrape from NEA / MSS going forward, but the historical data isn't available.

### Can you give a short explanation on how you're planning to use this dataset?

Personal project regarding data analysis.

Thanks!

**Comment by lennardl** [comment]
@eomcisumina I have approached NEA for similar data before and they were not able to provide it to me. We are in the process of getting their lighting data but not the rainfall image.
