### ISSUE TITLE
Locations for Covid 19 test 

### ISSUE THREAD

**Issue by yudancuks** [datagovsg/datagovsg-datasets#1073]
### Please provide the name of the dataset or description:
Hi can you provide dataset for covid 19 locations test like swab and pcr test

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
ministry of health

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@yudancuks For Covid-19 related data you need to refer back to https://www.moh.gov.sg/covid-19
