### ISSUE TITLE
Dataset request: Building Footprints With Heights

### ISSUE THREAD

**Issue by gispeople** [datagovsg/datagovsg-datasets#1074]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Building Footprints With Heights

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Unsure

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

Annually

### Can you give a short explanation on how you're planning to use this dataset?

Visualizations on interactive web maps and in native mobile apps.

**Comment by lennardl** [comment]
@gispeople At best we can provide the height ratio. We do not have that specific data, you would need to approach SLA for this.
