### ISSUE TITLE
Dataset request: PWCS community list

### ISSUE THREAD

**Issue by wudunxu** [datagovsg/datagovsg-datasets#1076]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
According to Zero Waste Masterplan (https://www.towardszerowaste.gov.sg/zero-waste-masterplan/chapter4/), 
`To increase the adoption of PWCS, since 1 April 2018, new development applications for non-landed private residential developments with 500 Dwelling Units (DUs) or more have been required to implement the system. This adds to over 140 existing private residential and commercial developments with PWCS.`

Is there any public data on the full list of communities that adds PWCS?

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@wudunxu Apologies but the data is not available
