### ISSUE TITLE
Dataset request: Previously Available Dataset missing

### ISSUE THREAD

**Issue by IllumiNinja** [datagovsg/datagovsg-datasets#1078]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Corporate Entities
https://data.gov.sg/dataset/acra-information-on-corporate-entities?resource_id=67e879b2-84e4-4353-9904-3fa3c004deba

### Do you know which agency provides/can provide this data?
ACRA

### If there's an issue with a dataset, please provide a description of the problem
The dataset is missing.

### Please provide the fields expected in this dataset:
NA

### How frequently would you need this dataset to be updated?
NA

### Can you give a short explanation on how you're planning to use this dataset?
NA

**Comment by lennardl** [comment]
@IllumiNinja The dataset is back up

**Comment by IllumiNinja** [comment]
@lennardl Saw it, thank you!

**Comment by gdelazzer** [comment]
Hi, sorry to reopen this issue but this dataset is missing again:

it was there on the 18th but disappeared from the 19th. Is it normal to have this dataset disappearing from time to time? I am asking so that we can plan accordingly :)

Thank you in advance for your help!

**Comment by IllumiNinja** [comment]
@lennardl The dataset seem to be unavailable again. Are there any procedures in place to prevent such situation from happening again?

**Comment by lennardl** [comment]
@IllumiNinja The dataset is back up. There isn't, the dataset moves to an offline state whenever there's an update to the dataset.

**Comment by IllumiNinja** [comment]
@lennardl Thank you so much for getting the dataset back up and for the clarification!

**Comment by gdelazzer** [comment]
Thanks @lennardl !

One more quick question: so we should expect to have the dataset offline for 2-3 days at every update? Is the update happening at the same date(s) every month?

Thanks!

**Comment by lennardl** [comment]
@gdelazzer It typically happens in the 3rd week of the month. The duration depends, it usually takes 1 - 2 days (sporadic up and downs) as the update cycle through the alphabets with validation and all.

**Comment by gdelazzer** [comment]
Got it! Thanks for the clarifications and your quick updates :)

**Comment by gdelazzer** [comment]
@lennardl I am sorry but the dataset still isn't there, when trying to retrieve it with `package_show` API  it returns a 404 error and it doesn't show in the list returned by `package_list` API

**Comment by lennardl** [comment]
@gdelazzer Can I check which alphabet you are trying to retrieve?
