### ISSUE TITLE
Dataset request: Singapore Islamic Prayer Times and Key Islamic Events

### ISSUE THREAD

**Issue by abanghazrul** [datagovsg/datagovsg-datasets#108]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Singapore Islamic Prayer Times and Key Islamic Events

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Majlis Ugama Islam Singapura

### If there's an issue with a dataset, please provide a description of the problem
It's in PDF and cannot be used to build our own prayer time applications. Currently we would have to crawl the MUIS website on a daily basis to get the time table daily. Or we would need to do data entry regularly. This often results in our apps breaking as we cannot get a consistent format for use in our apps. We need in a Restful JSON API.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

gregorian_date | hijri_date | subuh | syuruk | zuhur | asar | maghrib | isyak |
--------------- |----------|-------|--------|-------|------|---------|-------|
2018-01-18       | 1439-05-01 | 05:52 | 07:14 | 13:17 | 16:40 | 19:18 | 20:31 |

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [X] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I'm making an app that needs the Singapore prayer time. Although we can use openly available algorithms to determine prayer time, for some reason, MUIS prayer time never matches the algo's output exactly. Thus, this makes our prayer time apps for Singapore inaccurate and forces many developers to either crawl daily, or churn the PDF data into a database they need to call which they also need to update annually or from time to time.

**Comment by abanghazrul** [comment]
Appears to be a duplicate of https://github.com/datagovsg/datagovsg-datasets/issues/38 @iewil the dataset requested is similar. This needs to be bumped up. Is there a reason why MUIS is unable to give JSON at this time?

**Comment by iewil** [comment]
@abanghazrul I've forwarded your request to our colleagues at MUIS and I'll let you know when we've heard back from them. I agree that this could be provided as an API with a JSON response, and we'll suggest this as an alternative to what is currently provided
