### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by yeuann** [datagovsg/datagovsg-datasets#1081]
### Please provide the name of the dataset or describe the dataset that you're requesting:

https://data.gov.sg/api/action/datastore_search?resource_id=65c1093b-0c34-41cf-8f0e-f11318766298

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

LTA

### If there's an issue with a dataset, please provide a description of the problem
The list of MRT stations is outdated. 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

E.g. Telok Blangah MRT is missing.

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually

### Can you give a short explanation on how you're planning to use this dataset?

Use in app to list MRT stations as a location proxy for locating homeless people

**Comment by lennardl** [comment]
@yeuann I've reached out to LTA asking for an update
