### ISSUE TITLE
Pharmaceutical companies in SG

### ISSUE THREAD

**Issue by TriciaHong** [datagovsg/datagovsg-datasets#1082]
To understand the list of pharmaceutical companies in SG including location or address.

**Comment by lennardl** [comment]
@TriciaHong We have approached the relevant government agency asking if they can made the data available.

**Comment by TriciaHong** [comment]
Noted


Thanks and regards,



Tricia Chen

________________________________

**Comment by TriciaHong** [comment]
Hi,

May I know if there is further update.

Thanks,
Tricia

**Comment by lennardl** [comment]
@TriciaHong We have been informed by MOH/HSA that you would need to approach ACRA for the data

**Comment by TriciaHong** [comment]
Hi,

Actually I have first contacted ACRA (Support Mark Mah) and was diverted to datagov. Maybe can someone call me so that I can explain further?

Best regards,

Tricia Chen
Mobile: +65 8218 8463

**Comment by lennardl** [comment]
@TriciaHong I'm assuming ACRA would like you to refer to this dataset https://data.gov.sg/dataset/acra-information-on-corporate-entities and retrieve companies where the SSIC is related to the Pharmaecutical industry

**Comment by TriciaHong** [comment]
Hi,

Tried the link but it is in error. Can you help to send the actual excel please or resend an active link?
Thank you.

Best regards,
Tricia

**Comment by lennardl** [comment]
@TriciaHong Can you try again, should work now
