### ISSUE TITLE
Dataset request: Singapore business Breakdown by size and industry

### ISSUE THREAD

**Issue by joeyttk2001** [datagovsg/datagovsg-datasets#1083]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Number of singapore businesses breakdown by size and SICC code

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Accounting and Corporate Regulatory Authority

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

YEAR| SSIC Code | Number of company active | number of company who has Prior Entity and SSIC Code
2017 |  01120 | 200 | 10

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am doing a research on the resilience of Singapore SMB by measuring their transformation effort and agility in changing their business model/industry over time

**Comment by lennardl** [comment]
@joeyttk2001 We do not have the breakdown by size and SSIC. You might want to approach ACRA for this.
