### ISSUE TITLE
Dataset request: Total Revenue by Industry

### ISSUE THREAD

**Issue by IllumiNinja** [datagovsg/datagovsg-datasets#1084]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I am looking for a breakdown of the total revenue earned by each industry. I managed to find a dataset for Infocomm (https://data.gov.sg/dataset/revenue-of-infocomm-industry-by-market-segment) and hoping to find out for the other industries as well.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Probably MTI or ACRA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Month | Industry | Revenue ($)
------|---------|-------------
01-2020 | Manufacturing | $9 Million

### How frequently would you need this dataset to be updated?
- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For research purpose

**Comment by lennardl** [comment]
@IllumiNinja I've reached out to MTI asking if they have the data

**Comment by IllumiNinja** [comment]
@lennardl Thank you. Do you know roughly how long would they need before they can get back to you?

**Comment by lennardl** [comment]
@IllumiNinja They reached out to their respective divisions but they might take between 3 to 5 working days typically.

**Comment by lennardl** [comment]
@IllumiNinja I was directed by SingStat to redirect you to their page on http://www.singstat.gov.sg/tablebuilder

Select under:
Subject: Industry > Services
Topic: Annual Services Statistics – All Services Industries
Title: Key Indicators By Detailed Industry in All Services Industries, Annual 

Industry Statistics
a.       Number of establishments
b.       Operating receipts
c.       Operating expenditure
d.       Operating surplus
e.       Value Added

**Comment by IllumiNinja** [comment]
@lennardl Cool, thank you. I will explore more in depth later.

While I was scrolling through the dataset, I could only see 2019 Dataset. Any idea when would be their publish date at each year?

**Comment by lennardl** [comment]
@IllumiNinja I'm not certain you might need to reach out to SingStat contact us for that information

**Comment by IllumiNinja** [comment]
@lennardl Okay, thank you so much for your assistance!
