### ISSUE TITLE
Dataset request: Drinking water quality 2017 2018

### ISSUE THREAD

**Issue by francescomitis** [datagovsg/datagovsg-datasets#1086]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Drinking water quality fot the years 2017 and 2018

### Do you know which agency provides/can provide this data?
PUB, Singapore's national water agency

### Please provide the fields expected in this dataset:
year | pollutant | value

### How frequently would you need this dataset to be updated?
Example: 
- [ ] Annually

### Can you give a short explanation on how you're planning to use this dataset?
WHO/UNICEF Joint Monitoring Programme for the calculation of the safely managed drinking water indicator

**Comment by lennardl** [comment]
@francescomitis I've approached PUB asking if the historical data can be made available. Otherwise data from 2019 can be found here for now https://data.gov.sg/dataset/drinking-water-quality

**Comment by francescomitis** [comment]
Thanks so much!
I have already data for 2019 and for some previous years, this is why I am searching 2017 and 2018, the only years I miss. When available I will collect 2020 data too!
Thanks and have a wonderful day
francecsco

From: lennardl ***@***.***>
Sent: Friday, May 14, 2021 3:47 AM
To: datagovsg/datagovsg-datasets ***@***.***>
Cc: MITIS, Francesco ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [datagovsg/datagovsg-datasets] Dataset request: Drinking water quality 2017 2018 (#1086)


@francescomitis<https://github.com/francescomitis> I've approached PUB asking if the historical data can be made available. Otherwise data from 2019 can be found here for now https://data.gov.sg/dataset/drinking-water-quality
