### ISSUE TITLE
Dataset request: Daily Vehicles at Singapore-Johor Link

### ISSUE THREAD

**Issue by Cakiesu** [datagovsg/datagovsg-datasets#1088]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Daily Vehicles at Singapore-Johor Link, One Way (Not Return) Trip

### Do you know which agency provides/can provide this data?
LTA? Not certain.

### Please provide the fields expected in this dataset:

Number of Vehicles Daily | Types of Vehicles (Motorcycle, Cars, Trucks/Lorries)

### How frequently would you need this dataset to be updated?
Annually

### Can you give a short explanation on how you're planning to use this dataset?
Used as part of an assignment to udnerstand how infrastructure can be built to aid in the overpopulation of vehicles passing between Singapore and Johor

**Comment by lennardl** [comment]
@Cakiesu That data is not available
