### ISSUE TITLE
Dataset request: HDB Launch Prices 

### ISSUE THREAD

**Issue by rilly84** [datagovsg/datagovsg-datasets#1089]
Hi, 

I'm looking for:
1. HDB launch prices since 2012 for the various types of flats for a dataset comparison with the resale figures.
2. Launch prices and resale prices for private condos and landed properties over the past 10 years 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
 - Date
 - Town
 - Property Type
 - Block Number
 - Street
 - Storey Range
 - Lease Remaining
 - Resale Price
 - Launch Price

### How frequently would you need this dataset to be updated?
Example: 
Anually / Monthly

### Can you give a short explanation on how you're planning to use this dataset?
Creation of a PowerBI template as my personal project to compare make comparison of price changes over the years

**Comment by lennardl** [comment]
@rilly84 we only have this https://data.gov.sg/dataset/price-range-of-hdb-flats-offered
