### ISSUE TITLE
Dataset request: relative humidiy, temperature data| terengganu, malaysia| 1992-2018

### ISSUE THREAD

**Issue by Nrnshuha** [datagovsg/datagovsg-datasets#1090]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
1992-01 until 2018-01|Terengganu,Malaysia|Relative humidity, temperature data, solar radiation data, wind speed data

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@Nrnshuha We only provide data from Singapore
