### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by HeZhuConnie** [datagovsg/datagovsg-datasets#1092]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

Ministry of Manpower

### If there's an issue with a dataset, please provide a description of the problem
I can't get the public holiday data of the following year. For example, I can't get 2022 public holiday date through the API they provide. But I can get the 2022 public holiday information in Ministry of Manpower website. I mean they did not update or integrate the data to their API call.

### Please provide the fields expected in this dataset:

2022 all year round | Singapore | public holiday data

### How frequently would you need this dataset to be updated?

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@HeZhuConnie You can access the dataset here https://data.gov.sg/dataset/singapore-public-holidays?resource_id=04a78f5b-2d12-4695-a6cd-d2b072bc93fe

**Comment by HeZhuConnie** [comment]
> @HeZhuConnie You can access the dataset here https://data.gov.sg/dataset/singapore-public-holidays?resource_id=04a78f5b-2d12-4695-a6cd-d2b072bc93fe

I got a 404 page not found error when I try to access this link.
