### ISSUE TITLE
Dataset request: <ura private property residential transactions>

### ISSUE THREAD

**Issue by cjt-andy** [datagovsg/datagovsg-datasets#1093]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Resale private property residential transactions 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
URA

### If there's an issue with a dataset, please provide a description of the problem
-

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Project Name | Street Name | Type | Postal District | Market Segment | Tenure | Type of Sale | No. ofUnits | Price($) | Nett Price($) | Area (Sqft)¹ | Type of Area² | Floor Level | Unit Price ($psf)³ | Date of Sale⁴
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [x] Monthly

### Can you give a short explanation on how you're planning to use this dataset?

To analyse Singapore property transactions.

**Comment by lennardl** [comment]
@cjt-andy We have been asked to direct you to https://www.ura.gov.sg/realEstateIIWeb/transaction/search.action?utm_source=Public-PropertyMarketData&utm_medium=website&utm_campaign=Home-quicklinks&utm_content=Home-quicklinks
