### ISSUE TITLE
Dataset request: Body Temperature Data in Relation to incidence of fever

### ISSUE THREAD

**Issue by Sinzo3** [datagovsg/datagovsg-datasets#1096]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Hi I would to know if there is any body temperature database available in relation to an incidence of fever. I would like to know the daily temperature readings. 

### Do you know which agency provides/can provide this data?
Ministry of Health

### Please provide the fields expected in this dataset:
Gender, Date, Time, Temperature Reading, Thermometer Used, Mode of Temperature Taking,  Fever (Yes/No)

### How frequently would you need this dataset to be updated?
Example: 
- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am doing a study to understand the variability of an individual body temperature and in relation to fever. The study hopes to further understand the trends in normal body temperature as well as during a fever episode.

**Comment by lennardl** [comment]
@Sinzo3 We do not have any data on the individual body temperatures.
