### ISSUE TITLE
Dataset request: Financial Report of Zakat in Singapore

### ISSUE THREAD

**Issue by Wahyu0301** [datagovsg/datagovsg-datasets#1097]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@Wahyu0301 Have approached the MUIS asking if the data can be made available.

**Comment by lennardl** [comment]
@Wahyu0301 MUIS does not have the data in the format to put on Data.gov.sg but have advised that you can get the data from their annual reports
