### ISSUE TITLE
Dataset request: <LTA Lamppost> <OG Boxes>

### ISSUE THREAD

**Issue by SKKOH5** [datagovsg/datagovsg-datasets#11]
### Please provide the name of the dataset or describe the dataset that you're requesting:
1. LTA Lamp Post
2. SingPower OG Box 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
1. LTA for Lamp post
2. SingPower for OG Boxes 
3. IMDA for OG Boxes

### If there's an issue with a dataset, please provide a description of the problem
Data set is not available or distributed across many agencies.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
in SVY21 format 

month | country | Format
------|---------|-------------
2017-09|Singapore|SVY21

### How frequently would you need this dataset to be updated?

- [X] Annually or every 6 months

### Can you give a short explanation on how you're planning to use this dataset?
I am working on a research project with PUB DTSS team, under zweec.com
i am contactable at skkoh@zweec.com , 98425518

**Comment by chrissng** [comment]
@SKKOH5 You should be able to get lamp post locations from MyTransport.SG Data Mall (https://www.mytransport.sg/content/dam/mytransport/DataMall_StaticData/Geospatial/LampPost.zip) if it is urgent. They also have Control Box data (https://www.mytransport.sg/content/dam/mytransport/DataMall_StaticData/Geospatial/ControlBox.zip) but I am not sure if it is the OG Boxes which you are referring to.

**Comment by SKKOH5** [comment]
Thanks  Chris for the quick response

Let me try
