### ISSUE TITLE
Dataset request: Dengue Clusters

### ISSUE THREAD

**Issue by sgusjustinchua** [datagovsg/datagovsg-datasets#1100]
### Please provide the name of the dataset or describe the dataset that you're requesting:
"Dengue Clusters"

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
NEA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
month | Town | No. of Outbreaks 
2017-09|Ang Mo Kio|10

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For school's dataset project in predicting outbreak based on rainfall

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/dengue-clusters
