### ISSUE TITLE
Dataset request: <Singapore Coastal Habitats Map from High Resolution Satellite Imagery (2010/2011)>

### ISSUE THREAD

**Issue by gawainpek** [datagovsg/datagovsg-datasets#1101]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Singapore Coastal Habitats Map from High Resolution Satellite Imagery (2010/2011)

### Do you know which agency provides/can provide this data?
National Parks Board

### If there's an issue with a dataset, please provide a description of the problem
NA

### Please provide the fields expected in this dataset:
NA

### How frequently would you need this dataset to be updated?
NA

### Can you give a short explanation on how you're planning to use this dataset?
I am working on a series of short documentary film featuring the Singapore's shores. The dataset with the map data will help generate animations of Singapore's diverse shoreline types.

**Comment by gawainpek** [comment]
Data is listed here: https://data.gov.sg/dataset/singapore-coastal-habitats-map-from-high-resolution-satellite-imagery-20102011 

but no file download option available. Thanks!

**Comment by lennardl** [comment]
I've updated the dataset, you can try downloading the data
