### ISSUE TITLE
Dataset request: Cataracts records

### ISSUE THREAD

**Issue by yanlling** [datagovsg/datagovsg-datasets#1102]
Hi,

I need dataset on the patients diagnosed with both cataract and without cataract. Dataset should contain the age, race, gender, with or without cataract, undergo surgery, any treatment .etc

Thanks.

**Comment by lennardl** [comment]
@yanlling We do not have data on cataracts records

**Comment by yanlling** [comment]
Hi,

Thanks. May I check if there is any dataset on mental health?

Thanks.

On 7 Jun 2021, at 9:57 AM, lennardl ***@***.***> wrote:

﻿

@yanlling<https://github.com/yanlling> We do not have data on cataracts records

**Comment by lennardl** [comment]
We only have this but HPB has discontinued the survey https://data.gov.sg/dataset/mental-well-being-survey

**Comment by yanlling** [comment]
Hi,

Thanks, may I know if there’s is something related to stress management? Like the cause of stress?

Thanks

On 7 Jun 2021, at 2:16 PM, lennardl ***@***.***> wrote:

﻿

We only have this but HPB has discontinued the survey https://data.gov.sg/dataset/mental-well-being-survey

**Comment by lennardl** [comment]
@yanlling We do not have that, probably best to approach IMH for that

**Comment by yanlling** [comment]
Hi,

May I know if you have diabetes prediction or related dataset with over 1000 records?



Thanks

On 8 Jun 2021, at 10:08 AM, lennardl ***@***.***> wrote:

﻿

@yanlling<https://github.com/yanlling> We do not have that, probably best to approach IMH for that

**Comment by lennardl** [comment]
It would be here https://data.gov.sg/dataset/prevalence-of-hypertension-diabetes-high-total-cholesterol-obesity-and-daily-smoking
