### ISSUE TITLE
Dataset request: Distribution of Electric Motor Vehicles 

### ISSUE THREAD

**Issue by chewhongjun** [datagovsg/datagovsg-datasets#1103]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I am a researcher with NTU, and we are doing research in the electric vehicle market 
Could you please provide us with  Distribution of Motor Vehicles but with the inclusion of electric vehicles? 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
LTA

### If there's an issue with a dataset, please provide a description of the problem
NIL

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | make | type | count
------|---------|-------------
2017-09|Toyota| electric |10000

### How frequently would you need this dataset to be updated?

- [ ] Annually
- [ X ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am a researcher with ntu working to help plan and locate potential areas where we can place
Electric charging points, at the same time conduct market sizing to determine number of these points.

**Comment by lennardl** [comment]
@chewhongjun In a previous request, I understand that the data is not available and LTA/EMA was consolidating their data. Might be more efficient for you to make a request to the respective agencies directly
