### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by ongcheehong** [datagovsg/datagovsg-datasets#1104]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Cancer patient incidence and survival data in Singapore. The data that I'm requesting requires age of patient, sex, personal demographics (household income etc.), type of cancer, tumor site, histologic type, survived?, how long since first detected.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
MOH

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

2010-01 to latest month | Singapore | all the data within the duration
month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I'm currently preparing to do a capstone project for post-graduate program in SMU. I'm interested in gathering insights from the cancer incidence and survival rate in Singapore. I may also use the dataset to conduct other CDA analysis such as predictive analytics to determine whether a patient is likely to survive based on certain parameters.

**Comment by lennardl** [comment]
@ongcheehong We only have limited data on cancer which can be found here https://data.gov.sg/search?q=cancer
Typically MOH does not provide the data in such detailed breakdown unless you approach them for a specific request.
