### ISSUE TITLE
Dataset request: <education>

### ISSUE THREAD

**Issue by snayal** [datagovsg/datagovsg-datasets#1107]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@snayal Can I get more information on what kind of education data you are looking for?

**Comment by snayal** [comment]
Hi,  Thank you.  I was looking education/literacy data for study purpose.

**Comment by lennardl** [comment]
@snayal We have a number of datasets under https://data.gov.sg/search?groups=education ranging from enrollment, course listings to graduate cohort data if that works?

**Comment by snayal** [comment]
thanks.  It will work for sure.

regards
Shashi
