### ISSUE TITLE
Dataset request: Employment mapped against SSOC Codes

### ISSUE THREAD

**Issue by clairelyl** [datagovsg/datagovsg-datasets#1109]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I am writing to request a dataset for research purposes. I would like to find employment numbers at the granular level, i.e against each of the SSOC codes. For example, the exact number of code 93100 Civil engineering/Building construction labourers. 

Currently, we can only find the numbers at a high level e.g. 137900 Science and engineering professionals. 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Manpower 

### If there's an issue with a dataset, please provide a description of the problem
Currently, we can only find the numbers at a high level e.g. 137900 Science and engineering professionals. 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
SSOC Code and population size against each of these codes 

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Research into manpower skills proficiency and transition between industries

**Comment by lennardl** [comment]
@clairelyl For that level of details you have to approach MOM for this

**Comment by lennardl** [comment]
It would be through https://service2.mom.gov.sg/efeedback/Forms/eFeedback.aspx
