### ISSUE TITLE
Hawker Dataset Missing

### ISSUE THREAD

**Issue by crjacinro** [datagovsg/datagovsg-datasets#1111]
Hi.

I want to report missing hawker center entries in the dataset, which is near my area. 

- Happy Hawker (near Ranggung LRT)
- Sengkang 256 (near Rivervale Link)

**Comment by lennardl** [comment]
@crjacinro Can I check if this is in relation to this dataset? https://data.gov.sg/dataset/hawker-centres

**Comment by crjacinro** [comment]
Yes. Sorry if I forgot to add some label or tag

**Comment by lennardl** [comment]
@crjacinro I'll inform the data owners.

**Comment by lennardl** [comment]
@crjacinro NEA has reverted and said as these are coffee shops they will not appear in that dataset.

**Comment by crjacinro** [comment]
Oh. Thanks for the revert. I didn't know that "coffee shops" are different from hawker centers. May I know what makes it a "coffee shop"? I would like to use this API to gather all available hawkers in a certain location.

**Comment by lennardl** [comment]
@crjacinro I might be wrong but its depending on who manages the local. Coffeeshops are self managed. NEA only reports on the Hawker Centre locations. We do not have an API for coffeeshop locations.
