### ISSUE TITLE
Dataset request: Voluntary Disclosed Building Performance Data from 2002-2020

### ISSUE THREAD

**Issue by RenH96** [datagovsg/datagovsg-datasets#1112]
### Please provide the name of the dataset or describe the dataset that you're requesting:

I am from the University of Melbourne doing a masters research thesis on the relationship between BCA Green Mark disclosure of Singapore commercial properties under S-REITs and these S-REITs' financial performance. I would like to request for voluntary disclosed building performance data of green mark buildings in terms of their certification as well as energy performance metrics annually between the years of 2002-2020?

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

Building and Construction Authority (BCA)

### If there's an issue with a dataset, please provide a description of the problem

NIL

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Building Name | Building Address | Building Type | Building Size | Green Mark Rating | Green Mark Year of Award | Gross Floor Area (m2) | Energy Use Intensity | Voluntary Disclosure

------|---------|-------------
Building Name | Building Address | Office/Retail/Industrial/Health/etc. | Large/Small | Platinum/Gold/Certified/NA | 2002/.../2020 | 1,000 | 500 | Y/N

### How frequently would you need this dataset to be updated?

- [x] Annually (I only require the past data from 2002-2020 to conduct the research)
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

From these Voluntary Disclosed Building Energy Performance Data from 2002-2020, previous certification/re-certification years and the energy use metrics of Singapore commercial buildings under S-REITs will be studied against respective S-REIT financial performance indicators to find any causal relationship over the long-term.

**Comment by lennardl** [comment]
@RenH96 We do not have that data on hand, you would need to approach BCA directly
