### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by tanjoe912** [datagovsg/datagovsg-datasets#1114]
### Hello i would like to request all Commercial Heavy duty Trucks from year 2005 to 2021 in operation for Brands : 

MERCEDES BENZ
SCANIA, 
VOLVO,
HINO,
FUSO

### LTA is able to provide it as it trace the registration 
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ X] Annually
- [X ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@tanjoe912 Neither Data.gov.sg nor LTADataMall has that. You might need to approach LTA directly for this.
