### ISSUE TITLE
Dataset request: <Reverse Vending Machine Waste Collection>

### ISSUE THREAD

**Issue by cpayoung** [datagovsg/datagovsg-datasets#1115]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Reverse Vending Machine waste collection data. Ideally daily data collection but expect any frequency of data is available. 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
National Environment Agency

### If there's an issue with a dataset, please provide a description of the problem
No problem with data, but unclear what format the data is in. 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

2020-07 | Vending Machine ID | waste type | quantity of waste

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Intent is to use the data collected from the Reverse Vending Machines to model material flows of plastic and packaging waste. i.e. to determine how much waste is collected and where.  If the data is available would like to know how much waste is collected by type of waste.

**Comment by lennardl** [comment]
@cpayoung I've approached NEA asking if the data is available
