### ISSUE TITLE
Dataset request: Tide Timings

### ISSUE THREAD

**Issue by vincentneo** [datagovsg/datagovsg-datasets#1117]
### Please provide the name of the dataset or describe the dataset that you're requesting: 
low/high tide timings, with 4 rows of data daily, updated per every 2 months

### Do you know which agency provides/can provide this data?
NEA/MPA
Basically data seen here in the table, https://www.nea.gov.sg/weather/tide-timings, but in a (maybe) csv format

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

datetime | height | tide
------|---------|-------------
2021-06-01T02:31:00|2.8|H
2021-06-01T09:45:00|0.3|L

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

I see value in this dataset for third party apps to show tidal information to users that may use it, especially when integrated in weather or maritime apps.

**Comment by lennardl** [comment]
@vincentneo NEA does not pass us this data. Will check in with them if they can make it available.

**Comment by vincentneo** [comment]
Hi @lennardl, any updates on this?

**Comment by lennardl** [comment]
@vincentneo NEA has not reverted back to me

**Comment by vincentneo** [comment]
@lennardl its been about 2 months now, any updates? thanks
