### ISSUE TITLE
Dataset request: Weekly Number of Dengue Cases

### ISSUE THREAD

**Issue by sebdart** [datagovsg/datagovsg-datasets#1118]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Weekly Number of Dengue and Dengue Haemorrhagic Fever Cases from 2000 to present

### Do you know which agency provides/can provide this data?
Ministry of Health

### Please provide the fields expected in this dataset:
weekly | Singapore | from 2000 to 2021

### How frequently would you need this dataset to be updated?
Example: 
- [X ] Weekly

### Can you give a short explanation on how you're planning to use this dataset?
Non linear Time Series analysis of weekly Dengue Fever in many part of the world (where weekly Dengue Case data exist) modeling, both forensic/causal analysis and predictive/forecast analysis

**Comment by lennardl** [comment]
@sebdart We have limited past data but it can be found here https://data.gov.sg/dataset/weekly-infectious-disease-bulletin-cases
