### ISSUE TITLE
Dataset request: LTA Bicycle Rack

### ISSUE THREAD

**Issue by dominicling** [datagovsg/datagovsg-datasets#1119]
### Do you know which agency provides/can provide this data?
LTA
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Existing dataset available

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

research on number of bicycle racks in Singapore to guage storage space availability

**Comment by lennardl** [comment]
@dominicling LTA does not have that dataset available for us
