### ISSUE TITLE
Dataset request: <dataset title> Diabetes

### ISSUE THREAD

**Issue by poojaankaiah** [datagovsg/datagovsg-datasets#1122]
Diabetes and Hypertension dataset
I'm kindly requesting to provide Diabetes and Hypertension dataset. This dataset I using to do my final year Engineering project

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [x] Real-time

**Comment by lennardl** [comment]
@poojaankaiah We only have the data on its prevalence https://data.gov.sg/dataset/prevalence-of-hypertension-diabetes-high-total-cholesterol-obesity-and-daily-smoking
