### ISSUE TITLE
Dataset request: Certificate of Entitlement (COE) Bidding Results

### ISSUE THREAD

**Issue by kwangyu** [datagovsg/datagovsg-datasets#1123]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Certificate of Entitlement (COE) Bidding Results
https://data.gov.sg/dataset/coe-bidding-results

### Do you know which agency provides/can provide this data?

Land Transport Authority

### If there's an issue with a dataset, please provide a description of the problem

Results are not updated since 2020-03

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

vehicle_class | premium

### How frequently would you need this dataset to be updated?
Example: 

- [ ] Annually
- [ ] Monthly
- [X] Weekly
- [ ] Daily
- [ ] Hourly
- [X] Real-time

or whenever COE results are announced bi-weekly

### Can you give a short explanation on how you're planning to use this dataset?

Hi! As an classifieds/car-selling platform, we want to automate and update COE results to our users, whenever it is released. Currently it's a manual process and I'm not sure if there are any other sources or ways to automate this. Thanks!

**Comment by lennardl** [comment]
@kwangyu Can you get it from LTA/OneMotoring. They have consolidated their COE results and are only updating one location.
