### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by JCHU010** [datagovsg/datagovsg-datasets#1124]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I would like to request for the data set for the crowd level around singapore public area such as shopping malls, parks and markets. I am trying to create a mobile app version of spaced out which is currently available as a website only.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Urban Redevelopment Authority 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [X] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am a final year student from Nanyang Technological University studying Electrical and Electronics Engineering. I am starting on my final year project which woud be on a mobile app development using datasets from data.gov.sg. I woud want to create a mobile app version of spaced out including other features which could aid residents to avoid crowded places in singapore.

**Comment by lennardl** [comment]
@JCHU010 That data is not shared to us on Data.gov.sg.
