### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by Wang-Zerui** [datagovsg/datagovsg-datasets#1125]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Hypotension 
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Hospitals/health boards

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

age-group | gender | morality rate
------|---------|-------------
https://www.singstat.gov.sg/-/media/files/standards_and_classifications/nsa.pdf | M/F | %

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] *Annually*
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
School projects

**Comment by lennardl** [comment]
@Wang-Zerui We only have data on the prevalence of hypertension here https://data.gov.sg/dataset/prevalence-of-hypertension-diabetes-high-total-cholesterol-obesity-and-daily-smoking
