### ISSUE TITLE
Wind

### ISSUE THREAD

**Issue by jodyswright** [datagovsg/datagovsg-datasets#1126]

**Comment by lennardl** [comment]
Wind Direction: https://data.gov.sg/dataset/realtime-weather-readings?resource_id=5dcf8aa5-cf6a-44e4-b359-1173eecfdf4c

Wind Speed: https://data.gov.sg/dataset/realtime-weather-readings?resource_id=16035f22-37b4-4a5c-b024-ca2381f11b48
