### ISSUE TITLE
Dataset request: annual motor vehicle population 2020

### ISSUE THREAD

**Issue by AARONKOKAD01** [datagovsg/datagovsg-datasets#1127]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@AARONKOKAD01 You can get them from here while we get LTA to push the data to us.
https://datamall.lta.gov.sg/content/datamall/en/search_datasets.html?searchText=vehicle

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/annual-motor-vehicle-population-by-vehicle-type?view_id=6aca1157-ea79-4e39-9e58-3e5313a9a715&resource_id=dec53407-9f97-47b8-ba89-b2070569a09e
