### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by zhao-weijie** [datagovsg/datagovsg-datasets#1128]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Monthly summary of passenger and freight departures from Singapore, with destination. Similar to this US stat: https://transtats.bts.gov/DL_SelectFields.asp?gnoyr_VQ=FLM&QO_fu146_anzr=b4vtv0%20n0q%20Qr56v0n6v10%20f748rB

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
https://data.gov.sg/organization/civil-aviation-authority-of-singapore

### If there's an issue with a dataset, please provide a description of the problem
N/A

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | destination | flight_count
------|---------|-------------
2020-09|LAX|50

### How frequently would you need this dataset to be updated?
Example: 
- [] *Test*
- [x]One-off
- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I would like to use this for a data visualisation illustrating the impact of COVID19 on Singapore's passenger & air cargo volume. My idea is to vary the thickness or colour of lines radiating out from Singapore to the destination city according to the frequency.

**Comment by lennardl** [comment]
@zhao-weijie I've wrote to CAAS asking if the similar data can be made available, pending their response
