### ISSUE TITLE
Public Holiday API Change Request: Change How holidays are queried 

### ISSUE THREAD

**Issue by hsmaheen** [datagovsg/datagovsg-datasets#1129]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Singapore Public Holiday

### Do you know which agency provides/can provide this data?
https://data.gov.sg/dataset/singapore-public-holiday

### If there's an issue with a dataset, please provide a description of the problem
Currently, we need to query for public holidays using resource_id, which means every year someone needs to update their API with the resource id to ensure that the data is updated every year, alternatively the API could be changed in such a way that the API call is based on year e.g. https://data.gov.sg/dataset/singapore-public-holidays?year=2022

### Please provide the fields expected in this dataset:
same as the fields in the existing API response : https://data.gov.sg/api/action/datastore_search?resource_id=04a78f5b-2d12-4695-a6cd-d2b072bc93fe

### How frequently would you need this dataset to be updated?
Example: 
- [x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
This change will be useful for anyone who wishes to use the public holiday API to determine when are the public holiday in Singapore.

**Comment by lennardl** [comment]
@hsmaheen Thanks for your suggestion and it's a valid one, however, the platform is under maintenance mode. We are hoping to revamp the codebase by next year and will take this into account.
