### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by cwtan188** [datagovsg/datagovsg-datasets#1130]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Relative Humidity - Weekly Means since year 1983. Or alternative Daily Means so that we can derive Weekly dataset mmyself

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
National Environment Agency and / or Meteorological Service Singapore

### If there's an issue with a dataset, please provide a description of the problem
N.A

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Year | Week | Start Date | End Date | Means
1983 | 01     | 1-Jan-1983 | 7-Jan-1983 | 80%

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [X] Weekly or
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Currently, I am a student from Singapore University of Technology (SUTD) and is working on a data science project, which needs the humidity data. The project is to understand the impact on the Singapore Weather to the Dengue cases and its relationship.

**Comment by lennardl** [comment]
We have the humidity data in various details but we do not have data that goes all the way back to 1983
https://data.gov.sg/search?q=humidity
