### ISSUE TITLE
Dataset request: footwear sales in Singapore

### ISSUE THREAD

**Issue by Ahdelle** [datagovsg/datagovsg-datasets#1133]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Retail and e-commerce Footwear in Singapore 

### Do you know which agency provides/can provide this data?
( Refer to this link for a full list of agencies: https://data.gov.sg/organization )

### Please provide the fields expected in this dataset:

month | country | company | Brand | physical store | online store | footwear category | genre| price | material
------|---------|-------------
2017-09|Singapore|Pedro|orchard outlet|website|heels|woman|100|leather

### Can you give a short explanation on how you're planning to use this dataset?
would like to request for this dataset as part of my studies in analyzing and predicting footwear sales trend through retail and e-commerce store in Singapore context.

**Comment by lennardl** [comment]
@ADLMF We do not have details of retails sales broken down to the level of detail you require.
