### ISSUE TITLE
Dataset request: <weather for the past 4 years on a daily bases>

### ISSUE THREAD

**Issue by ishaannair** [datagovsg/datagovsg-datasets#1136]
### Please provide the name of the dataset or describe the dataset that you're requesting:

weather for the past 4 years on a daily basis that includes: temperature, humidity, rainfall quantity, if possible wind speed as well, from the Changi region.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
NA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [X] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation of how you're planning to use this dataset?
I am using the data for my internship, to build an irradiance prediction model using past weather data.

**Comment by lennardl** [comment]
@ishaannair You can use this https://data.gov.sg/dataset/realtime-weather-readings and pass in the dates to retrieve past weather.
