### ISSUE TITLE
Dataset request: <LTA arrow marking>

### ISSUE THREAD

**Issue by wwwwyw** [datagovsg/datagovsg-datasets#1139]
### Please provide the name of the dataset or describe the dataset that you're requesting:
LTA arrow marking

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
LTA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] Annually

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [x] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I plan to use this for pre-training

**Comment by lennardl** [comment]
The data can be found here but due to its size, there is no preview. You can try downloading it: https://data.gov.sg/dataset/lta-arrow-marking
