### ISSUE TITLE
Dataset request: EV charger information

### ISSUE THREAD

**Issue by geneho** [datagovsg/datagovsg-datasets#1140]
### Please provide the name of the dataset or describe the dataset that you're requesting:

[Similar to https://github.com/datagovsg/datagovsg-datasets/issues/629]
I am looking for data on current locations of electric vehicle (EV) charging stations in Singapore. Ideally, the data should include this information:

geographical location of charging stations (using longitude and latitude or equivalent)
how many chargers are available at each site
type of charger (charging capacity)
provider (e.g. BlueSG, Greenlots/Shell, Charge+, )
Optional: Charging price per kWh

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Energy Market Authority (under Ministry of Trade and Industry)

### How frequently would you need this dataset to be updated?
Example: 
- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I'm planning to aggregate the information into an app. Like the previous similar requests, I hope to be able to get the information this time round.

**Comment by lennardl** [comment]
@geneho This data has not been made available by EMA yet.
