### ISSUE TITLE
API to access kWh data measured by SP Power 

### ISSUE THREAD

**Issue by benjaminlai2017** [datagovsg/datagovsg-datasets#1141]
### Please provide the name of the dataset or describe the dataset that you're requesting:
half hourly electricity and water consumption for households, tenants in commercial buildings, building owners and industrial factories  

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
SP Power

### If there's an issue with a dataset, please provide a description of the problem
SP Power provides half hourly data in mobile app, but data cannot be exported via API for further analysis and application

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

date | time (every 30 mins) | electricity consumption in kWh | water consumption in kWh | household address |
month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [x ] Real-time, every 30 mins, as per SP Nmobile app

### Can you give a short explanation on how you're planning to use this dataset?
To encourage households and business owners to track utilities consumption, to encourage Tech companies to develop solution to track energy and water savings without the need to install additional power and water meters, as long as permission is granted by the household or business owner to access the data, promote EE and sustainability from the community and businesses,

**Comment by lennardl** [comment]
@benjaminlai2017 The data from SP belongs to SP Pte Ltd which is a private company
