### ISSUE TITLE
dengueDataset request: <dataset title>

### ISSUE THREAD

**Issue by katpgong** [datagovsg/datagovsg-datasets#1142]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@katpgong We have some dengue-related datasets here https://data.gov.sg/search?q=dengue as well as https://data.gov.sg/dataset/weekly-infectious-disease-bulletin-cases if it fits your use case.
