### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by ewsgan** [datagovsg/datagovsg-datasets#1143]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Noise complaints from the residential area in Singapore

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
HDB, NEA, MSO, Traffic Police, Town Council

### If there's an issue with a dataset, please provide a description of the problem
There is no such dataset.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
2019-01 to current| Singapore|
month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [x ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
We are working on  City of Tomorrow projects on noise control and mitigation and soundscape, we are compiling this information to understand the key complaints.

**Comment by lennardl** [comment]
@ewsgan We do not have the data on this, you might need to approach NEA for the data.
