### ISSUE TITLE
Dataset issue of Resale Flat Prices: Duplicate transactions of the same entry. Everything same except for field "id"

### ISSUE THREAD

**Issue by JavynThun** [datagovsg/datagovsg-datasets#1145]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@JavynThun Thanks for highlighting we are informing HDB on this

**Comment by JavynThun** [comment]
@lennardl is this dataset down?

**Comment by lennardl** [comment]
@JavynThun To close the loop the data was updated yesterday
