### ISSUE TITLE
Dataset request: Authentication Token to Real-time Weather API

### ISSUE THREAD

**Issue by quek-zhiheng** [datagovsg/datagovsg-datasets#1147]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Real-time weather readings API token

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
National Environmental Agency

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

date | average daily temperature | average daily rainfall
------|---------|-------------
2017-09-28|28.1|3.6

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ X] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am using the data to feed it into a machine learning model that uses such data and manipulate them into features to generate predictions of child abuse cases for MSF every 2-3 days. As the NEA only publishes the dataset on a monthly basis, it is unable to meet our constant demand for updated datasets and data to be fed into the ML model.

**Comment by lennardl** [comment]
@quek-zhiheng our APIs do not need any authentication token however there is a limit cap on calls. Can I check what datasets you are looking at?

**Comment by quek-zhiheng** [comment]
@lennardl i was referring to https://api.data.gov.sg/v1/environment/air-temperature

I added a date parameter after this url and coverted it to json, but it came back with:

{
    "message": "Missing Authentication Token"
}

**Comment by lennardl** [comment]
@quek-zhiheng That is very odd as no auth is necessary. Can I ask how are you trying to access the link and if you can access it via the browser at least? Can I also check if this link works for you https://api.data.gov.sg/v1/environment/air-temperature?date=2021-07-28

**Comment by quek-zhiheng** [comment]
for date in dates_for_update:
    dd, mm, yyyy = date.strftime('%d'), date.strftime('%m'), date.strftime('%Y')
    temperature_url = 'https://api.data.gov.sg/v1/environment/air-temperature?date=' + f'{yyyy}-{mm}-{dd}'
    temp_json = requests.post(temperature_url).json()
    d = json.dumps(temp_json, indent=4)

print(d)

This is the python code that I'm using to attempt to access the API, currently the url you provided yielded the same results.
However, it works on my browser. It could also be because I coded to ignore SSL certificate errors but I highly doubt this is the reason.

**Comment by lennardl** [comment]
@quek-zhiheng Are you attempting to run this off some cloud service? It seems unlikely that Data.gov.sg would be throwing that at most it would be that the rate-limiting error.

**Comment by quek-zhiheng** [comment]
I'm actually running this on my personal PC, unless I can only run this on a government laptop with VPN? Because the status code is still 403 with the same response.

**Comment by lennardl** [comment]
@quek-zhiheng then you shouldn't be running into any errors. I just ran a postman GET and was able to retrieve the data. Are you able to retrieve the data via means other than the python script?

**Comment by quek-zhiheng** [comment]
@lennardl thanks for the advice! I managed to import the data on another GET requests and import the data onto my python code. Thank you for your help!
