### ISSUE TITLE
Dataset request: Data on Manufacturers in Singapre

### ISSUE THREAD

**Issue by sincm1811** [datagovsg/datagovsg-datasets#1148]
### Please provide the name of the dataset or describe the dataset that you're requesting:
How many manufacturers are there in Singapore
Breakdown percentage of the type of manufacturing (Eg. Discrete manufacturing, processing manufacturing and others)
Breakdown percentage of manufacturers belonging to different region of origin (Eg. North America, South America, Europe, South-East Asia etc 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@sincm1811 We do not have that data available, you might want to approach SingStat for this.
