### ISSUE TITLE
Dataset request: <acra information of corporate entities>

### ISSUE THREAD

**Issue by DanLohky** [datagovsg/datagovsg-datasets#1150]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/acra-information-on-corporate-entities

**Comment by henrym12** [comment]
@lennardl Hello, I cannot find this anymore. What happened?
