### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by ishaannair** [datagovsg/datagovsg-datasets#1151]
### Please provide the name of the dataset or describe the dataset that you're requesting:
cloud coverage in Singapore for the past 2 years (from 2019 if possible) and the present and future (predicted) cloud coverage in Singapore. (If possible, kindly provide the cloud coverage with region-specific).
 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | cloud coverage|Region 
------|---------|-------------
2019-01 to 2021-08|Singapore|0-100%|changi,tampanies,etc

### How frequently would you need this dataset to be updated?
Example: 

- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation of how you're planning to use this dataset?
I want to create a machine learning model to predict solar irradiance in a few regions in Singapore. and cloud coverage is an important factor that is required to build this.

**Comment by lennardl** [comment]
@ishaannair We do not have cloud coverage data, you will need to approach NEA for this.
