### ISSUE TITLE
Dataset request: Registered Entities with Unique Entity Number

### ISSUE THREAD

**Issue by Dino198** [datagovsg/datagovsg-datasets#1153]
### Do you know which agency provides/can provide this data?
ACRA

### If there's an issue with a dataset, please provide a description of the problem
In the documentation, it is stated that overall dataset has about 1.7million records. However, when I tried the API, the total records returned is only 6k. 

### Can you give a short explanation on how you're planning to use this dataset?
Retrieve entity name in registration form when customer enters UEN.

**Comment by Dino198** [comment]
Hi @lennardl, just wanna clarify. Is this endpoint only returning 6k records?

https://data.gov.sg/api/action/datastore_search?resource_id=39201285-b73e-487a-a971-3a12d34ab8d9

**Comment by lennardl** [comment]
6k is the limit on the API there are more than 6k records

**Comment by lennardl** [comment]
@Dino198 Can you give me some examples? I understand that the fuzzy search is not performing as best and we are due for a technical overhaul later in the year.

**Comment by Dino198** [comment]
@lennardl this is the example - https://data.gov.sg/api/action/datastore_search?resource_id=39201285-b73e-487a-a971-3a12d34ab8d9&q=201304665W.

The UEN of 201304665W is for an existing company incorporated in 2013. I double checked on bizfile.gov.sg and could get the result however by using the API endpoint (the example link above), it does not return any results.

**Comment by lennardl** [comment]
@Dino198 It belongs under "v" here: https://data.gov.sg/dataset/acra-information-on-corporate-entities?resource_id=a740cd7d-8c08-4825-bcdc-b5c8d2a80a81

The API call: https://data.gov.sg/api/action/datastore_search?resource_id=a740cd7d-8c08-4825-bcdc-b5c8d2a80a81&q=201304665W
