### ISSUE TITLE
Government Procurement

### ISSUE THREAD

**Issue by lenardlee123** [datagovsg/datagovsg-datasets#1154]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Government procurement data by supplier

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
GeBIZ

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000
2002-2021

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@lenardlee123 The dataset can be found here https://data.gov.sg/dataset/government-procurement
I've raised a request for MOF to update it. The last update was due in July.

**Comment by lenardlee123** [comment]
@lennardl many thanks. would MOF be able to provide data stretching back further than 2015?

**Comment by lennardl** [comment]
@lenardlee123 They usually only provide the latest data and do not backdate.

**Comment by lenardlee123** [comment]
@lennardl many thanks for the clarification. would it be possible to request it from MOF anyway (regardless of whether they decide to provide it). appreciate the help!
