### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by NeverGiveUp-RC** [datagovsg/datagovsg-datasets#1155]
## Please provide the name of the dataset or describe the dataset that you're requesting:
_Bulk current and historical real-time weather datasets._

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
_NEA._

### If there's an issue with a dataset, please provide a description of the problem
_Unable to make a batch request as only a single date/time parameter is allowed._

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
_- [X] Real-time_

### Can you give a short explanation on how you're planning to use this dataset?
_To understand the weather variations over a date range and reducing overheads when making data requests._

**Comment by lennardl** [comment]
You can use the APIs here https://data.gov.sg/dataset/realtime-weather-readings to get prior daily data.

**Comment by NeverGiveUp-RC** [comment]
Hi lennardl, thank you for responding. I am aware of this API but as mentioned, it only takes in a single date and/or time parameter for the API call. This is pretty inefficient if I wish to acquire historical data. It is still manageable if it is under 50 days, but not years though. There will be overheads and data acquisition has been super slow.

**Comment by lennardl** [comment]
We do have historical data but it would be on a monthly basis and probably does not include all the fields you require. The other way to go about this is to request from NEA and see if they can help.
