### ISSUE TITLE
Dataset request: Wholesale Electricity Pricing

### ISSUE THREAD

**Issue by MW-gitcode** [datagovsg/datagovsg-datasets#1158]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Wholesale electricity pricing via API format for home/non-profit use. 

### Do you know which agency provides/can provide this data?
Energy Market Authority 

### If there's an issue with a dataset, please provide a description of the problem
N/A

### Please provide the fields expected in this dataset:
RT: Wholesale Electricity Pricing (do not need detailed breakdown - just the bottom line number that affects consumers)

### How frequently would you need this dataset to be updated?
- [X] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Simple visualisation for home automation + potential automation of household appliances e.g. washing machines, pool pumps to run at lowest electricity cost

**Comment by lennardl** [comment]
@MW-gitcode I've approached EMA asking if they can share the data

**Comment by lennardl** [comment]
@MW-gitcode I was directed by EMA to this https://www.emcsg.com/marketdata/priceinformation#priceDataView

**Comment by MW-gitcode** [comment]
@lennardl thanks for this - appreciate the response. Presume the only way to obtain this data would be to scrape the CSV i.e. no API available?

**Comment by lennardl** [comment]
@MW-gitcode Not at this point as EMA is directing to a single point which is the site provided. While I could get them to port it to Data.gov.sg it might not be as updated as the site.
