### ISSUE TITLE
Dataset request: Property Estate Agents and Sales Persons

### ISSUE THREAD

**Issue by mtaiyabm** [datagovsg/datagovsg-datasets#1160]
Hi There,

### Please provide the name of the dataset or describe the dataset that you're requesting:
Property Estate Agents and Sales Persons Data
resource_id: a41ce851-728e-4d65-8dc5-e0515a01ff31

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
CEA

### If there's an issue with a dataset, please provide a description of the problem
Suddenly the source file is not available anymore. Accessing the said resource (the API) gives "Unauthorised to edit this resource" error and redirects to login page.
https://data.gov.sg/api/action/datastore_search?resource_id=a41ce851-728e-4d65-8dc5-e0515a01ff31&limit=5

It's also not appearing here anymore: https://data.gov.sg/search?q=cea

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

agency_cea_license | broker_reg_no | agency_name
---------------------|----------------|---------------
X0000000X               | X000000X        | ABC PTE. LTD.
---------------------|----------------|---------------

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
We are a technology company providing our services in real estate domain. Linking buyers, sales persons and property developers to close deals remotely and in a simple and secure manner. We verify sales person's details from gov. provided authentic data source before they can register with us and can complete the sales.

Regards,
Muhammad Taiyab
www.showsuite.com

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/cea-salesperson-info

**Comment by mtaiyabm** [comment]
Great, thanks @lennardl 🙏 
The resource is up and available same as before. Much appreciated.
