### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by bhanlam** [datagovsg/datagovsg-datasets#1163]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Noise complaints (e.g. traffic, aircraft, construction, community)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

1. Land Transport Authority
2. Housing and Development Board
3. National Environment Agency
4. Municipal Services Office / Ministry of National Development

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | first three digits of postal code | complaint source | noise type | remarks
------|---------|-------------|-----------|---------|
2017-09 | 639 | residential | construction | renovation

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

According to the world health organisation (WHO), there is now strong evidence that urban noise exposure has led to a myriad of health risks, such as the increased risk of hypertension and cardiovascular disease. Noise complaints provide valuable insight into the psychological nature of noise, which is correlated to the perceived annoyance and overall mental stress. The emergence of COVID-19 has rapidly increased the urgency of addressing the impacts of noise as work-from-home arrangements become the norm even after the pandemic. The reopening of the economy will also see a surge in noise-generating events, such as community noise, construction noise, transportation noise, and aircraft noise. Hence, it is necessary to collate noise complaint data from various stakeholders in the interest of protecting public health. 

Open data will allow the research community to derive insights and recommendations for noise mitigation measures and also expose other non-acoustical factors in play such as socioeconomic or location-specific factors. These have direct implications for land allocation (URA, SLA) and building design (HDB, property developers) 

Attached is a recent study from the UK on the increase in noise complaints during the COVID-19 lockdown. The research team at NTU is planning to analyse the trend of noise complaints in Singapore before, during, and after the COVID-19 pandemic. This study will tease out the most concerning noise source, which allows us to redirect our noise mitigation technology developments to achieve the greatest benefit for Singaporeans.
 
[2021 - Tong et al. - Science of The Total Environment - Increases in noise complaints during the COVID-19 lockdown in Spring 2020 A c(2).pdf](https://github.com/datagovsg/datagovsg-datasets/files/6965339/2021.-.Tong.et.al.-.Science.of.The.Total.Environment.-.Increases.in.noise.complaints.during.the.COVID-19.lockdown.in.Spring.2020.A.c.2.pdf)

**Comment by lennardl** [comment]
@bhanlam We have asked for this before but the de-identified/aggregate data is not available from the agencies

**Comment by bhanlam** [comment]
@lennardl thanks for the reply.
