### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by smartpropertyadmin** [datagovsg/datagovsg-datasets#1170]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Management Corporation Strata Title

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
BCA

### If there's an issue with a dataset, please provide a description of the problem
Additional field for the database

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Total Shares|MF rate|SF rate|Last Financial Year
------|---------|-------------
1,000|25.00|5.00|31/12/2020

### How frequently would you need this dataset to be updated?
Example: 
- [x] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
As a MA firm it will allow the centralized team to track for discrepancy rates and ease start up for during handover/takeover to MA

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/management-corporation-strata-title

**Comment by smartpropertyadmin** [comment]
Would appreciate if the database could include the following additional field

Total Shares|MF rate|SF rate|Last Financial Year
------|---------|-------------
1,000|25.00|5.00|31/12/2020

**Comment by lennardl** [comment]
@smartpropertyadmin Will raise this with the data owner.
