### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by Pemimp** [datagovsg/datagovsg-datasets#1171]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Requesting for API access to MOH websites to pull relevant info on Covid

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
MOH websites

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

No dataset, just API calls to publicly published sites to pull relevant data from page

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*
 None - updates based on what is updated in the web page

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

Data used to create a chatbot to respond to covid rueries

**Comment by lennardl** [comment]
@Pemimp We have been directed by MOH to forward all data requests to the MOH COVID-19 site
