### ISSUE TITLE
List of NEA Licensed Eating Establishments with Grades, Demerit Points and Suspension History

### ISSUE THREAD

**Issue by karahmat** [datagovsg/datagovsg-datasets#1172]
### Please provide the name of the dataset or describe the dataset that you're requesting:
List of NEA Licensed Eating Establishments with Grades, Demerit Points and Suspension History

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
NEA

### If there's an issue with a dataset, please provide a description of the problem
The current dataset was last updated in September 2016. I would be grateful if NEA/Govtech could provide a more updated dataset.

### Please provide the fields expected in this dataset:
The current fields are fine but it will be good if NEA could add more fields, such as the name of the hawker stall, and whether the stall is intending to sell halal food or not. 
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [x] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I plan to create a Hawker Centre stall "wikipedia" for my project with General Assembly. I plan to gather a group of like-minded friends who are passionate about helping our hawker centre stall owners. This group of friends will use my app to populate the data on what each of this hawker stalls sell and their price. The data can then be publicised online for all to see. Since there is no central repository containing the information I want, it would be good to get the community to help out with the populating of data, since everyone goes to hawker centres.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/list-of-nea-licensed-eating-establishments-with-grades-demerit-points-and-suspension-history
