### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by NeverGiveUp-RC** [datagovsg/datagovsg-datasets#1173]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Geospatial dengue cases.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
NEA.

### If there's an issue with a dataset, please provide a description of the problem
Currently, the coordinates provided in the datasets are only at cluster-level. Exact locations will be useful.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

Year, Latitude, Longitude, Postal Code, Number of Cases

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

To understand the distribution of dengue cases over a date range with a deeper dive into the exact locations.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/dengue-clusters

**Comment by NeverGiveUp-RC** [comment]
Hi lennardl, thank you for sharing the link. But I am looking at actual locations instead of clusters though.

**Comment by lennardl** [comment]
@NeverGiveUp-RC The exact locations are not provided by NEA to us.
