### ISSUE TITLE
Dataset request: <Accidents on Motorcycle 2009-2013(numbers on injuries and fatalities, causes of motorcycle accidents)>

### ISSUE THREAD

**Issue by EmranNJC** [datagovsg/datagovsg-datasets#1174]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Accidents on Motorcycles 2009-2013(data on injuries and fatalities, causes of motorcycle accidents)
Accidents on All Vehicle Types 2009 2013(data on injuries and fatalities, causes of all vehicle accidents)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Singapore Traffic Police

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
We will be using this dataset for our GCSE A-Level Project Work that is focusing on the transformation in the registration of
Class 2B Licenses over the course of 11 years(2009-2021) Hence, we will need to look at the cause of motorcycle accidents
from 2009-2013. On top of that, we will also need to consider accidents on other vehicle types.
Similar to the dataset found here:
https://data.gov.sg/dataset/causes-of-road-accidents-causes-of-accidents-by-severity-of-injury-sustained

**Comment by lennardl** [comment]
@EmranNJC the data provided by SPF is the dataset you mentioned in your post. It's unlikely they can provide more detailed breakdown as I've requested for it before.
