### ISSUE TITLE
PSIDataset request: <dataset title>

### ISSUE THREAD

**Issue by qyunc** [datagovsg/datagovsg-datasets#1175]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@qyunc Can you provide more details on what you are looking for?

**Comment by lennardl** [comment]
@qyunc Can you provide more details on what you are looking for?

**Comment by qyunc** [comment]
Hi,  I’ve found what I wanted already! Thanks a lot From: lennardlSent: 23 August 2021 15:24To: datagovsg/datagovsg-datasetsCc: qyunc; MentionSubject: Re: [datagovsg/datagovsg-datasets] PSIDataset request: <dataset title> ***@***.*** Can you provide more details on what you are looking for?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
