### ISSUE TITLE
Dataset request: Requesting for MRT LRT list with location

### ISSUE THREAD

**Issue by rasfarrf5** [datagovsg/datagovsg-datasets#1176]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Is there any possible to provide complete set of MRT and LRT train service list with location. So far all the apis contains only bus related information.

**Comment by lennardl** [comment]
Does this work? https://data.gov.sg/dataset/master-plan-2019-rail-station-name-layer

**Comment by rasfarrf5** [comment]
Looks good. But I need more information like

Station name, station code, station color code, lat/lng.

**Comment by lennardl** [comment]
@rasfarrf5 That is currently not provided by LTA to us. Checking on their side it seems like they do not have a single layer with all the information.

**Comment by rasfarrf5** [comment]
Got it. Thanks Lennardl. 

Appreciate your quick response.
