### ISSUE TITLE
Dataset request: <  Resident Students Aged 5 Years and Over by Residential Area of Residence and Level of Education Attending >

### ISSUE THREAD

**Issue by ZacChee01** [datagovsg/datagovsg-datasets#1179]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Resident Students Aged 5 Years and Over by Residential Area of Residence and Level of Education Attending

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

------|---------|-------------
2021-01|Singapore|Total | Pre-Primary | Primary | Secondary | Post-Secondary   (Non-Tertiary) | Polytechnic   Diploma | Professional   Qualification and Other Diploma | University

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [-x] Real-time

**Comment by lennardl** [comment]
@ZacChee01 This is dependant on the population census survey done by SingStat. They conducted it once every ten years. The last one was done in 2020, the data can be found https://data.gov.sg/dataset/resident-students-by-planning-area-of-residence-and-level-of-education-2020
