### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by TangKamYin** [datagovsg/datagovsg-datasets#1181]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Breast Cancer, Radiotherapy and Radiation Pneumonities

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Any hospital

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am working on the prediction model of Radiation Pneumonitis (RP) of Breast Cancer Patient who received Radiotherapy Treatment by using dosimetric and non dosimetric parameter

**Comment by lennardl** [comment]
@TangKamYin We do not have such detailed data and specific treatments on certain diseases. You would need to approach MOH for this
