### ISSUE TITLE
Dataset request: <Number of People Taking Buses In Different Hours of A Day>

### ISSUE THREAD

**Issue by JohnnyL517** [datagovsg/datagovsg-datasets#1182]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Number of People Taking Buses in Different Hours of A Day

### Do you know which agency provides/can provide this data?
Land Transport Authority

### Please provide the fields expected in this dataset:
time | country | routes
any seven days in 2020/2021 | Singapore | 3 to 5

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [x] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Needed for research purpose to investigate accuracy of the bus arriving on time, and whether the number of taking buses has an effect on the accuracy.

**Comment by lennardl** [comment]
@JohnnyL517 LTA only provided data on the bus utilisation as well as passenger volume by origin which can be found on 

https://datamall.lta.gov.sg/content/datamall/en/dynamic-data.html
https://datamall.lta.gov.sg/content/datamall/en/static-data.html
