### ISSUE TITLE
Dataset request: <Unlicensed Moneylending (UML) and Harassment by NPC>

### ISSUE THREAD

**Issue by DarenLo** [datagovsg/datagovsg-datasets#1184]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by DarenLo** [comment]
My SUSS graduate class final end course assignment requires I use this dataset to answer a question

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/unlicensed-moneylending-uml-and-harassment-by-npc
