### ISSUE TITLE
Dataset request: <shoppingmalls.csv>

### ISSUE THREAD

**Issue by Venkysgithu** [datagovsg/datagovsg-datasets#1185]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [x] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by Venkysgithu** [comment]
i'm a novice in data science 
im doing a project on HBD resale prices of singapore 
shopping malls are one of the features that can help.

**Comment by lennardl** [comment]
@Venkysgithu We do not have the mall data as it falls under the individual private companies
