### ISSUE TITLE
Dataset request: <Search UEN>

### ISSUE THREAD

**Issue by weiliangg** [datagovsg/datagovsg-datasets#1190]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Hi I would like to request for the search UEN dataset

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Accounting and Corporate Regulatory Authority

### If there's an issue with a dataset, please provide a description of the problem
Tried to pull the data, the UENs could not be found although the correct ones were type into the search. 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

UEN | Issuance Agency ID | UEN Status | Entity name | Entity type | UEN Issue date | Registered street name | Registered postal code
------|---------|-------------
T21TU0001E | MOM | R | ST Engineering staff union | TU | 2021-04-01 | West camp road | 797654

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
We want to verify if our users has a registered company by doing a cross check with ACRA data so as to weed out fake or scams.

**Comment by lennardl** [comment]
@weiliangg our search works on fuzzy search and at times you might not get the correct information. The information is also not up to date and I would suggest if you need up to date information that you retrieve it from ACRA directly

**Comment by weiliangg** [comment]
> @weiliangg our search works on fuzzy search and at times you might not get the correct information. The information is also not up to date and I would suggest if you need up to date information that you retrieve it from ACRA directly

Hello @lennardl thank you for the swift reply, may i know if there is an email or contact you can point us to, to ask for this information?  thank you

**Comment by lennardl** [comment]
@weiliangg https://www.bizfile.gov.sg/ngbbizfileinternet/faces/oracle/webcenter/portalapp/pages/BizfileHomepage.jspx
