### ISSUE TITLE
Dataset request: <Flood incidents>

### ISSUE THREAD

**Issue by bladerail** [datagovsg/datagovsg-datasets#1191]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Singapore's flood incidences/occurrences 50-100years, in the form of shapefile points if possible. 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
PUB

### If there's an issue with a dataset, please provide a description of the problem
The Flood Prone Areas dataset available (provided by PUB) on data.gov.sg does not provide spatial attributes. 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

year of occurrence | Singapore | sub-regions | height of water level
------|---------|-------------

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Research purposes

**Comment by lennardl** [comment]
@bladerail We do not have that data, you might need to approach PUB directly to see if they are willing to share the data.
