### ISSUE TITLE
Dataset request: Number of hair salons in Singapore

### ISSUE THREAD

**Issue by ktayyyy** [datagovsg/datagovsg-datasets#1192]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | area | no. of salons
------|---------|-------------
2021-08|Singapore|North/East/South/West|99999

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

I would like to know how many hair salons there are in Singapore to estimate the number of hair stylists. These are a group of professionals who could benefit from up scaling their skills which I’m looking to help with.

**Comment by lennardl** [comment]
@ktayyyy We do not have the breakdown to just hair salons. The department of statistics does provide high level numbers on the service industry as a whole https://www.tablebuilder.singstat.gov.sg/publicfacing/createDataTable.action?refId=14745
