### ISSUE TITLE
Workplace Injuries, Annual

### ISSUE THREAD

**Issue by siizsaphhire** [datagovsg/datagovsg-datasets#1197]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [x] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@siizsaphhire The data can be found here https://data.gov.sg/dataset/workplace-injuries-annual
It is outdated and I've sent a request for MOM to update it.
