### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by Patricia8878** [datagovsg/datagovsg-datasets#1200]
### Please provide the name of the dataset or describe the dataset that you're requesting:
mp14-sdcp-lha-plan-landed-housing-area

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Urban Redevelopment Authority

### If there's an issue with a dataset, please provide a description of the problem
I would like to know if there any way i can access / pull this dataset?

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2020-08|Singapore|1000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I would like to pull this dataset to know whether the land is feasible for building up to the control height limit

**Comment by lennardl** [comment]
@Patricia8878 The KML is available here https://data.gov.sg/dataset/mp14-sdcp-lha-plan-landed-housing-area
Would suggest using these for control height https://data.gov.sg/search?q=master+plan+control+height
