### ISSUE TITLE
Tourism Receipts Statistics

### ISSUE THREAD

**Issue by unknown0324** [datagovsg/datagovsg-datasets#1201]
Tourism Receipts Statistics

Singapore tourism board

The dataset provide on the website is aggregated, is there a more raw form of the data or CSV form or a dataset with all columns in one sheet. 

fields expected in this dataset:

Year, Region, country, Major components(shopping, F&B ...), Value 

year | region| country | major components| value
------|---------|-------------
2017 | America | Canada | shopping | 149000000

### How frequently would you need this dataset to be updated?
_Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time
- [X] One-time

This dataset will be used in a project on the analysis of tourism in Singapore.

**Comment by lennardl** [comment]
@unknown0324 that data is not available
