### ISSUE TITLE
Dataset request: Hansards

### ISSUE THREAD

**Issue by tehtea** [datagovsg/datagovsg-datasets#1202]
### Please provide the name of the dataset or describe the dataset that you're requesting:
There is an existing search engine for parliament Hansards: https://sprs.parl.gov.sg/search/home, but it will be useful (and probably more legal!) to expose the raw dataset either as a public API or a CSV for custom analysis

### Do you know which agency provides/can provide this data?
Parliament of Singapore

### Please provide the fields expected in this dataset:
Same as the existing API, a list of debates along with their metadata, and also a list of exchanges by each parliamentarian in each debate

### How frequently would you need this dataset to be updated?

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation of how you're planning to use this dataset?
An open-source data analysis project to assess hot button issues in parliament and the performance of each MP

**Comment by lennardl** [comment]
@tehtea Due to the structure and length of the speeches data.gov.sg might not be the right platform.
