### ISSUE TITLE
Dataset request: <Real Time data set of Electrical Vehicles charging stations in Singapore>

### ISSUE THREAD

**Issue by Lohibits** [datagovsg/datagovsg-datasets#1207]
Real Time data set of Electrical Vehicles charging stations in Singapore

### Do you know which agency provides/can provide this data?

https://data.gov.sg/organization/land-transport-authority
https://data.gov.sg/organization/energy-market-authority

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | company| available lots| location |
------|---------|-------------
2017-2021 |Singapore|name|10000| Funan Mall 

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [x ] Annually
- [x ] Monthly
- [x ] Weekly
- [x ] Daily
- [x ] Hourly
- [x] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To create a website displaying the availability of all EV charging stations for users. The site aims to provide EV owners with information on pricing, location, lot availability, rated charging power (Watts), charging duration and amenities around the various charging spots.

**Comment by lennardl** [comment]
@Lohibits that data is not available yet. We are trying to get the location of the EV chargers.
