### ISSUE TITLE
Dataset request: <URA 2020 with Census data>

### ISSUE THREAD

**Issue by Stancey** [datagovsg/datagovsg-datasets#1208]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Dear who concerned data providing,

Greetings from Shuting. I'd like to know if there is data for planning area census in year 2020. If so, would you please share one with me? Thanks in advance! 

Take care and stay safe.

Best,
Shuting

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@Stancey You can get the data here https://www.singstat.gov.sg/-/media/files/publications/cop2020/sr2/cop2020sr2.pdf

SingStat has not provided the data in csv formats.

**Comment by Stancey** [comment]
Thanks a lot!

Take care and stay safe.

Best,
Shuting
