### ISSUE TITLE
Dataset request: <Differences in vaccination willingness according to Social Vulnerability Index in Singapore, Differences in the completion rate of 1st and 2nd vaccinations according to the SVI index in Singapore>

### ISSUE THREAD

**Issue by JisooJo36** [datagovsg/datagovsg-datasets#1209]
### Please provide the name of the dataset or describe the dataset that you're requesting:
1. Differences in vaccination willingness according to Social Vulnerability Index in Singapore
2. Differences in the completion rate of 1st and 2nd vaccinations according to the SVI index in Singapore

### Do you know which agency provides/can provide this data?
https://data.gov.sg/organization

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Jan, 2020~August, 2021|Singapore|10000

### How frequently would you need this dataset to be updated?
- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [o] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
This data will be used to write a paper.

**Comment by lennardl** [comment]
@JisooJo36 We do not have the data and generally anything that is Covid-19 related will have to be redirect to MOH
