### ISSUE TITLE
Dataset request: <dataset title> e-payment

### ISSUE THREAD

**Issue by Juliwati** [datagovsg/datagovsg-datasets#1210]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@Juliwati Can you provide more details on what you need? Also judging on the title, we generally do not have e-payments data as it belongs to the individual private companies

**Comment by Juliwati** [comment]
Hai Mr Lennardi, thanks for your email.
I need statistics on usage of various non-cash payments (value and velocity
of transaction per capita) in Singapore Period 2009 - 2020 monthly

**Comment by lennardl** [comment]
@Juliwati That is not available as the majority of transactions belong the the private companies (Banks, GrabPay, FavePay, Nets)
