### ISSUE TITLE
Dataset request: <Price of All Prepaid Mobile Plans in Singapore>

### ISSUE THREAD

**Issue by Rachealthong** [datagovsg/datagovsg-datasets#1211]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Price Of SIM Card Prepaid Plans in Singapore

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Infocomm Media Development Authority

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Service Provider | data allocated | number of calls | number of SMS | Validity days | price of prepaid plan

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For assignment use. To create a multiple regression model on this issue to help overseas students analyse the best price on buying a SIM card.

**Comment by lennardl** [comment]
@Rachealthong That data is not available as it belong to the individual private companies
