### ISSUE TITLE
Dataset request: <Container Throughput, Hourly>

### ISSUE THREAD

**Issue by clarencecodes** [datagovsg/datagovsg-datasets#1212]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Container Throughput, Hourly. Something like this (https://data.gov.sg/dataset/container-throughput-monthly-total) but hourly.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Maritime and Port Authority of Singapore

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Datetime | Container Throughput (No. of Twenty-Foot Equivalent Units)
------|---------|
2021-09-23 00:00:00|1419.74721
2021-09-23 01:00:00|3135.523
2021-09-23 02:00:00|2847.234

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [X] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For my university's capstone project, I am looking to analyse the correlation between tides which change every hour and container throughput at container terminals.

**Comment by lennardl** [comment]
@clarencecodes Unfortunately MPA is not able to provide us with hour by hour data.

**Comment by clarencecodes** [comment]
@lennardl that's cool, thanks for checking!
