### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by datasciencerachit** [datagovsg/datagovsg-datasets#1215]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [ ] Annually
- [x] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by datasciencerachit** [comment]
Planning to use the dataset for testing purposes

**Comment by lennardl** [comment]
@datasciencerachit Can you provide more details on the data you are looking for?
