### ISSUE TITLE
Dataset request: <CHAS Clinics (Annual List)>

### ISSUE THREAD

**Issue by lhwmich** [datagovsg/datagovsg-datasets#1216]
### Please provide the name of the dataset or describe the dataset that you're requesting:
List of addresses of CHAS participating medical and dental provider.

### Do you know which agency provides/can provide this data?
CHAS (https://www.chas.sg/clinic_locator.aspx?id=90 provides only current list) 

### Please provide the fields expected in this dataset:
(Year | Name | Address | Telephone | Type | Pap Test Services
)

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

Visualize # of participating medical and dental healthcare providers in the CHAS program annually, ideally from 2000 (program implemented)

**Comment by lennardl** [comment]
We only have data on existing known not prior https://data.gov.sg/dataset/chas-clinics

**Comment by lhwmich** [comment]
thanks!
