### ISSUE TITLE
Dataset request: <4 day weather forecast>

### ISSUE THREAD

**Issue by redwhirl11** [datagovsg/datagovsg-datasets#1217]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Weather forcast of Singapore for the next 4 days

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
NEA has datasets of weather forecasts for the next 2 hours, next 24 hours and the next 4 days

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Visualise weather forecast for next 4 days

**Comment by lennardl** [comment]
You can get it here https://data.gov.sg/dataset/weather-forecast?resource_id=4df6d890-f23e-47f0-add1-fd6d580447d1
