### ISSUE TITLE
Dataset request: NEA 2-hr and 24hr Forecast Data - Not Available

### ISSUE THREAD

**Issue by henrylimcher** [datagovsg/datagovsg-datasets#1219]
### Please provide the name of the dataset or describe the dataset that you're requesting:
NEA 2-hr and 24hr Forecast 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
NEA

### If there's an issue with a dataset, please provide a description of the problem
No data provided since yesterday (3/Oct/2021)

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [X] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To be able to know the forecast for the next 2 hour as well as 24-hour.

**Comment by lennardl** [comment]
@henrylimcher We are aware of the problem and checking with NEA on this.
