### ISSUE TITLE
Dataset request: Singapore Crime Rates by Neighbourhood

### ISSUE THREAD

**Issue by hicksbean** [datagovsg/datagovsg-datasets#122]
### Do you know which agency provides/can provide this data?
*Singapore Police Force*

### If there's an issue with a dataset, please provide a description of the problem
*I can't find any data on the internet currently classifying crime rates by neighbourhood*

### Please provide the fields expected in this dataset

year | neighbourhood | number
------|---------|-------------
2017|yishun|10000

### How frequently would you need this dataset to be updated?

- [x] Annually

### Can you give a short explanation on how you're planning to use this dataset?

School research project

**Comment by iewil** [comment]
@hicksbean this is a duplicated request. Please follow this request for further updates #119
