### ISSUE TITLE
Dataset request: Food Delivery app Industry market share

### ISSUE THREAD

**Issue by IlyaR117** [datagovsg/datagovsg-datasets#1223]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Food delivery app industry market share

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | firm | revenue/market share(%)
------|---------|-------------

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I will use this information for my IB diploma program extended essay for economics to characterize the food industry.

**Comment by lennardl** [comment]
@IlyaR117 We do not have that private industry data
