### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by projwork123** [datagovsg/datagovsg-datasets#1224]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Number of preschool teachers 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
ECDA, MOE

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

years2015-2019|singapore|numberofteachers

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Needed urgently for Project Work. We are students from National JC researching about the preschool sector and would appreciate if we got a response as soon as possible.

**Comment by lennardl** [comment]
@projwork123 We do not have the number of teachers
