### ISSUE TITLE
Dataset request: <COVID-19 case numbers>

### ISSUE THREAD

**Issue by HYMacq** [datagovsg/datagovsg-datasets#1225]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Health

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

Exactly the same as on data.gov.sg but just with historicals.

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Research

**Comment by HYMacq** [comment]
I saw it there, but i note the data set is being overwritten?

**Comment by lennardl** [comment]
I understand MOH is still adjusting the dataset so some data are added/removed
