### ISSUE TITLE
Dataset request: the University names of "Number of Overseas Dental and Pharmacy Schools in the Schedule"

### ISSUE THREAD

**Issue by Johnchensg** [datagovsg/datagovsg-datasets#1226]
the name of the dataset :
Number of Overseas Dental and Pharmacy Schools in the Schedule

the fields expected in this dataset:
Names of the overseas dental schools

how i am planning to use this dataset:
School application

**Comment by lennardl** [comment]
@Johnchensg Directed to the following by MOH
The list of recognised overseas pharmacy schools can be found at the Singapore Dental Council website: http://www.healthprofessionals.gov.sg/content/dam/hprof/sdc/docs/publication/THE%20SCHEDULE%20%28020108%29.pdf

The list of recognised overseas pharmacy schools can be found at the Singapore Pharmacy Council website: http://www.healthprofessionals.gov.sg/content/dam/hprof/spc/docs/Others/SPC_Recognised_Qualifications.pdf
