### ISSUE TITLE
Dataset request: Carpark Availability

### ISSUE THREAD

**Issue by heyjared** [datagovsg/datagovsg-datasets#1228]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Carpark Availability

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
GovTech

### If there's an issue with a dataset, please provide a description of the problem
Appears to be missing some carparks
https://data.gov.sg/dataset/hdb-carpark-information?resource_id=139a3035-e624-4f56-b63f-89ae28d4ae4c shows there are a total of 2162 carparks but this data set only has availability data for 1952.

**Comment by lennardl** [comment]
@heyjared I've sent the query to HDB asking if they know why there's a difference in the number.

**Comment by heyjared** [comment]
It's still not available.
