### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by yinkaku** [datagovsg/datagovsg-datasets#1230]
### Please provide the name of the dataset or describe the dataset that you're requesting:
WOODLANDS CAUSEWAY – TOWARDS JOHOR (live traffic camera)
TUAS CHECKPOINT (live traffic camera)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
LTA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 

- [X] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Help the people visiting our website to see if the traffic is busy

**Comment by lennardl** [comment]
You can get it from https://onemotoring.lta.gov.sg/content/onemotoring/home/driving/traffic_information/traffic-cameras/woodlands.html
