### ISSUE TITLE
Dataset request: Proportion of Daily Singapore confirmed Covid cases by vaccination status

### ISSUE THREAD

**Issue by HotSnapZ** [datagovsg/datagovsg-datasets#1237]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Proportion of Daily Singapore confirmed Covid cases by vaccination status

### Do you know which agency provides/can provide this data?
Singapore Ministry of Health

### If there's an issue with a dataset, please provide a description of the problem

Not currently being reported

### Please provide the fields expected in this dataset:

date | new cases | % new cases unvaccinated status| % new cases one shot vaccinated status| % new cases 2 shots vaccinated status| % new cases 2 shots + booster vaccinated status

------|---------|-------------
2017-09|1000|77|3|18|2

### How frequently would you need this dataset to be updated?
Example: 
- [X] Daily

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Analysis and tracking of vaccine efficacy over time

**Comment by lennardl** [comment]
@HotSnapZ You're right it does not seem to be there, I do recall them releasing vaccination by age group. As MOH is the owner of the data, might be easier to approach them to request for the data to be added on Data.gov.sg as it would be more effective.

**Comment by HotSnapZ** [comment]
@lennardl Did you ever receive a response to your request?  I find it puzzling that most all other governmental agencies able to report this information,  around the world , are doing so for the exception of the Singapore MOH?  The question now begs......WHY?
