### ISSUE TITLE
Data request: Real Time weather readings in Singapore

### ISSUE THREAD

**Issue by lucasarea** [datagovsg/datagovsg-datasets#124]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Air temperature, rainfall and relative humidity

### Do you know which agency provides/can provide this data?
National Environment Agency

### If there's an issue with a dataset, please provide a description of the problem
On all three datasets I request all the for different dates
Air temperature 
- only provide me for 01-03-2018 13:55:00 with only two stations.
- if i request past data (ex.: 20-02-2018), I receive the same data as before ("current" data)

Rainfall
- I get what seems to be the whole data, but only for 01-03-2018 13:50:00
- I receive the same data when requesting for past data

Relative humidity
- Sometimes it gives the data I expect when requesting a whole day, but other times show the same problem as the others
- I receive only the "current" data of 13:55 when requesting past days data

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
date              | latitude | longitude | rainfall | humidity | air temperature
02-10-2018  |    1.3...  |  100.8...    |   0.1...  |    50...     |   30...

### How frequently would you need this dataset to be updated?
- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [x] Real-time

I also would like to get past data from the weather readings from the whole year of 2017

### Can you give a short explanation on how you're planning to use this dataset?
My research aims to find relation in traffic, public transport using DataMall datasets and a number of Environmental variables to explain its variance

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/realtime-weather-readings

**Comment by lennardl** [comment]
Historical data
https://data.gov.sg/dataset/relative-humidity-monthly-mean
https://data.gov.sg/dataset/surface-air-temperature-monthly-mean
https://data.gov.sg/dataset/rainfall-monthly-total
