### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by kienwei96** [datagovsg/datagovsg-datasets#1242]
### Please provide the name of the dataset or describe the dataset that you're requesting:
HDB Public Housing Building Under-Construction

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
HDB

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For university project purpose

**Comment by lennardl** [comment]
@kienwei96 Does this work https://data.gov.sg/dataset/number-of-units-of-hdb-developments-by-status ? Breakdown on specific blocks are not provided.
