### ISSUE TITLE
Dataset request: COVID-19 vaccinations

### ISSUE THREAD

**Issue by jlwj51** [datagovsg/datagovsg-datasets#1243]
### Please provide the name of the dataset or describe the dataset that you're requesting:
COVID-19 vaccinations

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Health

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

All the fields in the "Vaccination" section of the [daily updates](https://www.moh.gov.sg/covid-19/past-updates)

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Tracking the vaccination numbers

**Comment by lennardl** [comment]
@jlwj51 I've feedback to MOH and they responded that it would be added to the dataset in due time https://data.gov.sg/dataset/covid-19-case-numbers as of now we have other relevant vaccination numbers.
