### ISSUE TITLE
Dataset request: COVID-19 case numbers

### ISSUE THREAD

**Issue by jlwj51** [datagovsg/datagovsg-datasets#1244]
### Please provide the name of the dataset or describe the dataset that you're requesting:
COVID-19 case numbers (https://data.gov.sg/dataset/covid-19-case-numbers)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Health

### If there's an issue with a dataset, please provide a description of the problem
Only recent data is available, there is no data prior to these dates:
- Breakdown of Number of Active Cases in Hospital, COVID-19 Treatment Facilities, Community - 21/10/2021
- Number of Community Cases by Age - 30/9/2021
- Moving average of deaths & active cases in ICU or requiring O2, per 100k population - 14/10/2021
- Weekly Infection Growth Rate - 27/8/2021
- Patients Needing Oxygen Supplementation, ICU Care or Died, by Age Groups - 30/9/2021
- Proportion (%) of cases who died, by age and vaccination status - 1/5/2021
- Proportion (%) of cases ever in ICU care or died, by age and vaccination status - 1/5/2021
- Proportion of cases ever requiring O2, in ICU care or died, by age & vaccination status - 1/5/2021

**Comment by lennardl** [comment]
@jlwj51 I understand but it does not look like MOH will be backdating the data.
