### ISSUE TITLE
Dataset request: <Clinical Data for testing machine learning algorithm in predicting diabetes>

### ISSUE THREAD

**Issue by JayanthiKJ** [datagovsg/datagovsg-datasets#1257]
### Do you know which agency provides/can provide this data? No. I am not aware of the agency details
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
age as of 2021, height, weight, BMI, fasting blood glucose, cholestrol, BP, diabetes (Y/N)

 

### Can you give a short explanation on how you're planning to use this dataset?
I am currently pursuing my Masters in Data Science and AI with UOL, under Singapore Institute of Management's Global Education Programme.

**Comment by lennardl** [comment]
@JayanthiKJ For such data, you will need to approach MOH for it.

**Comment by JayanthiKJ** [comment]
Dear Lennard:Noted with thanks for the reply. I will reach out the MOH. Thanks.  Thanks & Regards,Jayanthi Sent from Mail for Windows From: lennardlSent: 15 November 2021 09:23To: datagovsg/datagovsg-datasetsCc: JayanthiKJ; MentionSubject: Re: [datagovsg/datagovsg-datasets] Dataset request: <Clinical Data for testing machine learning algorithm in predicting diabetes> (Issue ***@***.*** For such data, you will need to approach MOH for it.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
