### ISSUE TITLE
Dataset request: Junior College Admissions by Secondary Schools

### ISSUE THREAD

**Issue by fascin18** [datagovsg/datagovsg-datasets#1270]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Education
Would like to request for the following data:
number of admissions,
junior college name (admitted),
From secondary school name
Secondary school  streams (Express, Normal Academic NA, Normal Technical NE) and 
year.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
MOE Ministry of Education 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Year | Junior College Name | No. Students Admitted | From Secondary School Name | Stream (Express / Normal Academic / Normal Technical)

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

2021 | Raffles Junior College | 30 | Chung Cheng High (Yishun) | Express 

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To plan children Education journey and school admissions

**Comment by lennardl** [comment]
@fascin18 We have some of the data you need here https://data.gov.sg/search?q=enrollment but we may not have the detailed breakdown for the enrollment
