### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by siw-sgp** [datagovsg/datagovsg-datasets#1271]
### Please provide the name of the dataset or describe the dataset that you're requesting:
**### IPOS applications API**
The data provided via the 3 APIs for Trademark, Design and Patent data seems to have stopped updating from over a year ago. Please assist to rectify the backend data update of these APIs.
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Intellectual Property Office of Singapore

### If there's an issue with a dataset, please provide a description of the problem
update IPOS applications API current date 2021-12-02
your Last Updated | March 22, 2019, 13:57 (SGT)

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country |
------|---------|-------------
2021-12|Singapore|

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [X] Real-time

**Comment by lennardl** [comment]
@siw-sgp We have stopped support for those three APIs for any API support you will need to approach IPOS directly
