### ISSUE TITLE
Dataset request: <Sunshine hours In Pakistan for Karachi, DI khan, Lahore, Peshawar, Quetta and Islamabad>

### ISSUE THREAD

**Issue by abdulmoiz2020** [datagovsg/datagovsg-datasets#1275]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset: Monthly Data for mentioned cities in Pakistan (1980 to 2020)
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [x] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [x] Real-time

**Comment by lennardl** [comment]
@abdulmoiz2020 We can only provide data relevant to Singapore.
