### ISSUE TITLE
Dataset request: Schools in Singapore

### ISSUE THREAD

**Issue by Diasamanuly** [datagovsg/datagovsg-datasets#128]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Schools in Singapore

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Education 

### If there's an issue with a dataset, please provide a description of the problem

I need a data of number and type of schools (boys', girls', co-ed) from in period from 1991 to 2018. I only found the data from 2017. 
 
### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

year | country | schools / Boys' / Girls' / Co-ed
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I'm a teacher and educator. First of all I want to compare of increasing of decreasing the number os single-education schools worldwide and share it with experts. Depending on that information I want to share my knowledge to improve our education system in Kazakhstan. It's only for scientific purpose. 

Thank you in advance.

**Comment by iewil** [comment]
@Diasamanuly historical data for school listings are not available.
