### ISSUE TITLE
Taxi Availability API returning nothing

### ISSUE THREAD

**Issue by cheeaun** [datagovsg/datagovsg-datasets#1287]
The Taxi Availability API (https://data.gov.sg/dataset/taxi-availability) is currently returning no taxis. This has been happening since 26 Dec 2021.

**Steps to reproduce:**
1. Load the API URL: https://api.data.gov.sg/v1/transport/taxi-availability
2. See the response. It returns:
    ```json
    {
      "api_info": {
        "status": "healthy"
      },
      "message": "no results found"
    }
    ```

**Expected behavior**
A list of coordinates of available taxi locations.

**Screenshots**

1. Loading it in the browser 
    <img width="557" alt="Screenshot 2021-12-29 at 7 19 15 PM" src="https://user-images.githubusercontent.com/2296/147657140-c187dbd6-02d9-4628-adc9-1d8ed376c94c.png">
2. Loading it on data.gov site https://data.gov.sg/dataset/taxi-availability
    <img width="750" alt="Screenshot 2021-12-29 at 7 19 35 PM" src="https://user-images.githubusercontent.com/2296/147657168-ec51d3f5-078e-4db7-b738-371e635b6465.png">

**Additional context**

This is currently affecting my site (https://taxirouter.sg) which serves 1.2K monthly active users.

**Comment by lyqht** [comment]
Tried the API as well, no results found.

**Comment by cheeaun** [comment]
Weirdly enough, the LTA datamall API works (http://datamall2.mytransport.sg/ltaodataservice/Taxi-Availability) (with `AccountKey`)

**Comment by pranabdas** [comment]
Same problem with the traffic camera API (https://api.data.gov.sg/v1/transport/traffic-images). Not working at the moment. It only returns: 
```
{"items":[{}],"api_info":{"status":"healthy"}}
```

**Comment by cheeaun** [comment]
I can see that the API is up now https://api.data.gov.sg/v1/transport/taxi-availability

Thanks 🙇 🙇
