### ISSUE TITLE
Dataset request: MRT ridership

### ISSUE THREAD

**Issue by isaacngym** [datagovsg/datagovsg-datasets#129]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Public Transport Ridership 

A 10% sample of commuter routes sampled randomly from ticketing data (ez-link records) 
Data should not be a sampling of commuter transactions, whole routes need to be intact - not one half of a trip that involved transfers

### Do you know which agency provides/can provide this data?
Land Transport Authority

### Please provide the fields expected in this dataset:
Routes are either "MRT" for MRT data (as specific route cannot be inferred from ezlink data) or <bus route>-<direction>, following transitlink's standard for direction 1/2 (See: Transitlink's web service https://www.transitlink.com.sg/eservice/eguide/service_idx.php )
Serial corresponds to a hashed ezlink serial to find clusters of individuals with similar travel patterns which can be used to create crowdsourced bus or carpooling routes

Serial | MthNum | Mth | DayNum | Day | Route | SvcType |         StartStn |        EndStn | EntTime | ExTime | Transfer 
 3f2e2 |      9 | Sep |      6 | Fri | 105-1 |     Bus |      Catholic JC |     Lien Twrs |   1021h |  1055h |        N
 3f2e2 |      9 | Sep |      6 | Fri | 174-2 |     Bus |        Lien Twrs |        Blk 18 |   1059h |  1128h |        Y
 7b89b |     10 | Oct |      7 | Sat |   MRT |     MRT |        Woodlands | Raffles Place |   0753h |  0908h |        N
 7b89b |     10 | Oct |      7 | Sat | 107-1 |     Bus | One Raffles Quay |     Shaw Twrs |   0916h |  0928h |        Y
 d3a4c |      1 | Jan |      3 | Mon | 105-2 |     Bus |        Lien Twrs |   Catholic JC |   1826h |  1907h |        N

### How frequently would you need this dataset to be updated?
- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Create visualisations on transport flow through Bus/MRT network over course of a day
Spot seasonal trends (e.g. do more people take mrt during monsoon season?)
Spot temporal trends (e.g. do all public transport services get the same amount of increase in ridership during peak hours?)
Calculate ridership statistics (e.g. how long is an average commuter's time on the MRT? on the bus? what's the most common commuting time?) - similar to this https://blog.data.gov.sg/fingerprint-of-a-bus-route-73e5be53dcf0 but using GIS 
Identify potential carpooling/bus routes
Calculate mean/variance in commuting time at a time of day for a given route

**Comment by iewil** [comment]
@isaacngym this is a duplicated issue of #16. We'll take your inputs into consideration when reviewing the request. Further updates will be provided in issue #16
