### ISSUE TITLE
Dataset request: ERP rates

### ISSUE THREAD

**Issue by fterh** [datagovsg/datagovsg-datasets#133]
### Do you know which agency provides/can provide this data?
* LTA

### Please provide the fields expected in this dataset:
*Type of vehicle, weekday or weekend, time window, gantry identifier, rate

### How frequently would you need this dataset to be updated?
- [ ] Annually
- [X ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I'm incorporating it into an experimental transport-based chat bot.

**Comment by mauris** [comment]
yes please. the current data representation (in the individual PDF files) for ERP pricing is very messy and definitely not usable. even for most people, we have to cross reference and double check everywhere just to figure out if a particular gantry is working at a particular time.

**Comment by tyjtyj** [comment]
Another Vote from me. Including location of the gantry.

**Comment by lennardl** [comment]
We do not have the data
