### ISSUE TITLE
Dataset request: <Singapore Bus Stop Information>

### ISSUE THREAD

**Issue by nchlsf** [datagovsg/datagovsg-datasets#134]
### Please provide the name of the dataset or describe the dataset that you're requesting:

List of Singapore bus stops geolocations 

List of all bus stop numbers

Distance between each bus stop

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

Land Transport Authority

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Bus stop name | Bus stop number | Geocode 

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

Planning to calculate the shortest route between all bus stops in Singapore for a data analytics project using a travelling salesman problem.

**Comment by LoneRifle** [comment]
I'll defer to my colleagues to consider making this available in data.gov.sg, but in the meantime, this dataset can be found on [LTA's DataMall](https://www.mytransport.sg/content/mytransport/home/dataMall/dynamic-data.html) (check the API documentation PDF as well). 

An example of this in action can be found in a python script in [datagovsg/beeline-routing](https://github.com/datagovsg/beeline-routing/blob/master/fetch-bus-stops-with-headings/fetch_bus_stops_from_data_mall.py).
