### ISSUE TITLE
Dataset request: Historical Inflation Rates of Singapore

### ISSUE THREAD

**Issue by 19hours** [datagovsg/datagovsg-datasets#135]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Historical inflation rates of Singapore

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Monetary Authority of Singapore

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

year | inflation rate
------|---------
2017 | 2.5%

### How frequently would you need this dataset to be updated?
- [X ] Annually

### Can you give a short explanation on how you're planning to use this dataset?
I want to analyse data sets with nominal prices. With the yearly inflation rate I can calculate the real prices.

Thanks!

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/consumer-price-index-monthly
