### ISSUE TITLE
Dataset request: <PM2.5>

### ISSUE THREAD

**Issue by gryphonmonster** [datagovsg/datagovsg-datasets#141]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I am requesting for the PM2.5 dataset.

### Do you know which agency provides/can provide this data?
National Environment Agency

### If there's an issue with a dataset, please provide a description of the problem
I am trying to pull the information out. However, there isn't any link I can find that I can extract the data from. 

### Please provide the fields expected in this dataset:
*(e.g. Date | Region | pm2.5)*

2-4-2018 | Central | 50

### How frequently would you need this dataset to be updated?
- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
We are trying to explore to see how environmental parameters affect various health outcomes, in particular acute upper respiratory infections. The NEA website provides rainfall and temperature data but we would also like to include PM2.5 indices into the model. We would ideally require 3 years worth of daily data.

**Comment by peitingtan** [comment]
Hi, we would like to explore how is the haze period affect infant health outcomes. Hence we would appreciate if could have data from 1-Jan-2014 to 31-Dec-2016.

**Comment by lennardl** [comment]
@peitingtan Our data API only goes as far back as 2016 here https://data.gov.sg/dataset/pm2-5?view_id=8c9e6472-9b1f-42b3-b631-d2056848bf95&resource_id=fa0958a9-bade-419e-9475-cbf5ccf4f746

Data up till 2014 can be found here: https://data.gov.sg/dataset/air-pollutant-particulate-matter-pm2-5 

We have missing data in between.
