### ISSUE TITLE
Dataset request: HDB resale transaction data

### ISSUE THREAD

**Issue by Lucidity1** [datagovsg/datagovsg-datasets#142]
Hi, 

We are no longer able to find HDB resale flat prices dataset in data gov.
data.gov.sg/dataset/resale-flat-prices.

Is there any reason why is it removed and how can we acquire them?

Hope to hear from you soon. 

Thanks.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/resale-flat-prices
