### ISSUE TITLE
sengkang hdb transactions

### ISSUE THREAD

**Issue by vpho2707** [datagovsg/datagovsg-datasets#143]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
Full data here https://data.gov.sg/dataset/resale-flat-prices, can be filtered to district
