### ISSUE TITLE
Dataset request: Digitised Land Information (Building Outline)

### ISSUE THREAD

**Issue by jglim** [datagovsg/datagovsg-datasets#145]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Digitised Land Information (Building Outline)

### Do you know which agency provides/can provide this data?
[Singapore Land Authority](https://data.gov.sg/organization/singapore-land-authority)

[SLA Building Outline](https://www.sla.gov.sg/Services/Street-Map/Licensing-of-Digitised-Land-Information#5)

![lbbuilding1_thumb](https://user-images.githubusercontent.com/1116555/38300041-54a4aa2a-382e-11e8-8e63-4ac97fe3f486.png)

### If there's an issue with a dataset, please provide a description of the problem
N/A

### Please provide the fields expected in this dataset:

Building outline|Building height (where available)|House/ Block number|Road name|Building name
------|---------|-------|------|------
(KML polygon)|22|55|NEWTON ROAD|REVENUE HOUSE

### How frequently would you need this dataset to be updated?

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I built a [free tool](https://osm.sn.sg) to export 3D models of buildings in a region to assist researchers, architects, realtors and surveyors. Greater public access to this accurate data opens up many opportunities, such as determining wireless signal propagation, designing 3D-printed scale models, UAV flight planning and more. I am also hoping to be able to contribute this data upstream to OpenStreetMap.

This data already appears to readily available with SLA, furthermore some of the offerings in their "Digitized Land Information" [already exist](https://data.gov.sg/dataset/sla-cadastral-land-parcel?resource_id=60f3d2ca-e058-4a7a-9dbc-5b7df2d9cd19) in data.gov.sg.

**Comment by lennardl** [comment]
We do not have the 3D data
