### ISSUE TITLE
Dataset request: <Traffic light locations - Lat, Long>

### ISSUE THREAD

**Issue by vebitsai** [datagovsg/datagovsg-datasets#146]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Traffic light locations in Singapore. 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
LTA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [x ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
We are researching on how drivers behave near traffic junctions.

**Comment by lennardl** [comment]
We do not have the data
