### ISSUE TITLE
Dataset request: <List of child care>

### ISSUE THREAD

**Issue by AshleyHow** [datagovsg/datagovsg-datasets#147]
### Please provide the name of the dataset or describe the dataset that you're requesting:
List of child care regarding the location, price, operation hours, fees, etc

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
the data.gov initially had this data but was removed

### If there's an issue with a dataset, please provide a description of the problem
it has been removed

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
to create a platform for users to pick their childcare for their children conveniently

**Comment by Madeleinekohbc** [comment]
Can you please include the fees ? The name of the person in charge or the principal of the centres

The fees is readily available in Child care link.

Easier for comparison when download and export to Excel

Thanks !

Madeleine

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/list-of-childcare-centres
https://data.gov.sg/dataset/listing-of-childcare-centre-services
