### ISSUE TITLE
Dataset request: <HDB Remaining Leasehold>

### ISSUE THREAD

**Issue by hugegene** [datagovsg/datagovsg-datasets#148]
### Please provide the name of the dataset or describe the dataset that you're requesting:
HDB remaining leasehold by subzone

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
HDB

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
year| singapore| subzone| types of dwellings| average remaining leasehold 

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For NUS ISS school project.

**Comment by lennardl** [comment]
Data can be inferred from https://data.gov.sg/dataset/hdb-property-information but not segmented by sub zone
