### ISSUE TITLE
Dataset request: Historical Dengue and Zika outbreak cases

### ISSUE THREAD

**Issue by nakamura41** [datagovsg/datagovsg-datasets#149]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Historical Dengue and Zika outbreak cases

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
National Environment Agency

### If there's an issue with a dataset, please provide a description of the problem
We have collected and analysed Dengue Cases dataset from this link: https://data.gov.sg/dataset/dengue-cases
and found out that we also need time information for each case.

### Please provide the fields expected in this dataset:

This is the current format of Dengue Case dataset

JOIN_COUNT|AREANAME|DETAIL|INC_CRC|FMEL_UPD_D|POLYGON_COORDINATES
-----|---------|-------|----|-----|----
6|No. of Dengue Cases : 6|No. of Dengue Cases : 6|7F348F76B93DD662|20180319105341|103.910223160521,1.3318800762804,0.0 103.910223216615,1.33368880376895,0.0 103.912020329102,1.33368874661339,0.0 103.912020271696,1.33188001920238,0.0 103.910223160521,1.3318800762804,0.0
1|No. of Dengue Cases : 1|No. of Dengue Cases : 1|2A7651D54A9A2814|20180319105341|103.922802937052,1.33187964904273,0.0 103.922803002323,1.33368837595089,0.0 103.924600114227,1.33368830955228,0.0 103.924600047644,1.33187958273421,0.0 103.922802937052,1.33187964904273,0.0

What we need is something like this one:

TIME|NO_CASES|AREANAME|POSTALCODE|LATITUDE|LONGITUDE|INC_CRC|FMEL_UPD_D|POLYGON_COORDINATES
-----|-----|---------|-------|----|-----|----|----|----
2018-03-21|6|539 Bedok North Street 3 |460539|103.910223160521|1.3318800762804|7F348F76B93DD662|20180319105341|103.910223160521,1.3318800762804,0.0 103.910223216615,1.33368880376895,0.0 103.912020329102,1.33368874661339,0.0 103.912020271696,1.33188001920238,0.0 103.910223160521,1.3318800762804,0.0
2018-04-01|1|235 Tampines Street 21 |521235|103.922802937052|1.33187964904273|2A7651D54A9A2814|20180319105341|103.922802937052,1.33187964904273,0.0 103.922803002323,1.33368837595089,0.0 103.924600114227,1.33368830955228,0.0 103.924600047644,1.33187958273421,0.0 103.922802937052,1.33187964904273,0.0

Can you give us the past 3 years of dengue cases in Singapore?

### How frequently would you need this dataset to be updated?
One time request

### Can you give a short explanation on how you're planning to use this dataset?

We are a group of master students from Institute of Systems Science NUS which are currently working on Geospatial Analysis project. We need this dataset as part of our course project work.

**Comment by OlgaKolmykova** [comment]
Hi David, please let me know if you manage to get data.
