### ISSUE TITLE
Is this no longer updated? -- acra-information-on-corporate-entities

### ISSUE THREAD

**Issue by bjornlll** [datagovsg/datagovsg-datasets#1492]
### Please provide the name of the dataset or describe the dataset that you're requesting:
`acra-information-on-corporate-entities`

### Do you know which agency provides/can provide this data?
ACRA

### If there's an issue with a dataset, please provide a description of the problem
The dataset `acra-information-on-corporate-entities` has not been updated since February 23, 2022. According to data.gov.sg, this is supposed to be updated monthly. Since that hasn't happened, I have to ask: Is this deprecated? Should we still use this?

Thanks!

**Comment by bjornlll** [comment]
@lennardl I see you have been quite active here - do you know the right person to ask? Thanks!

**Comment by veager** [comment]
Seems the previous dataset has been removed from the datamall.

**Comment by bjornlll** [comment]
Yeah I noticed that yesterday. So they left it there, unattended for almost a year and then finally removed it. Wonder why? Is there any way to hear from ACRA as to why this dataset has now been made private?

Björn Lindfors
+65 8285 2594 | WhatsApp

**Comment by veager** [comment]
I found that ACRA provides APIs to query these information, but very expensive.

**Comment by bjornlll** [comment]
They probably prefer to charge SGD .30 a request instead of letting us access it for free. 👎 I guess someone in ACRA is trying to hit their KPIs.

For anyone else viewing this thread: [ACRA - Accounting And Corporate Regulatory Authority](https://www.apimall.acra.gov.sg/products/detail/7/2)'s APIs can be found using this link. Using this, you can get up-to-date information on what was previously found in the `acra-information-on-corporate-entities` dataset (and more!).

**Comment by arshadali172** [comment]
hi @bjornlll, the acra dataset on DataGov is up again. Thanks for bringing this up. 

We are in the midst of updating the dataset with the latest information

**Comment by veager** [comment]
> hi @bjornlll, the acra dataset on DataGov is up again. Thanks for bringing this up.
> 
> We are in the midst of updating the dataset with the latest information

Good news! Thank you!

**Comment by bjornlll** [comment]
> hi @bjornlll, the acra dataset on DataGov is up again. Thanks for bringing this up.
> 
> We are in the midst of updating the dataset with the latest information

That's amazing news - thanks for this! 

Any idea when it will be up-to-date with the latest information? Many thanks.

**Comment by arshadali172** [comment]
We are working towards updating the datasets under ACRA Information on Corporate Entities by the end of the week.
