### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by choonhian** [datagovsg/datagovsg-datasets#151]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Singapore Dollar monthly average currency Exchange rate from 1961 to 2017 per following countries:

Malaysia
Indonesia
Thailand
Philippines
Vietnam
China
Hong Kong
Japan
United Kingdom
France
Germany

### Please provide the fields expected in this dataset:

month | country | foreign currency | sgd_per_unit
------|---------|-------------
2017-09|US      | USD               | 1.2671
2017-09|MALAYSIA| MYR               | 0.3367

### How frequently would you need this dataset to be updated?

- [X] Test

### Can you give a short explanation on how you're planning to use this dataset?

I would like to use this datasets to look at the relationship between currency exchange rate with the number of air passenser arrivals.

**Comment by lennardl** [comment]
We do not have that data
