### ISSUE TITLE
Dataset request: <Betting/ Football/ Casino/ Private Lottery and Fruit Machine Duties>

### ISSUE THREAD

**Issue by hky8** [datagovsg/datagovsg-datasets#152]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Betting/ Private Lottery and Fruit Machine Duties

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
IRAS used to publish both Betting and Private Lotteries duties with further breakdowns into a line item for Football for the former and Fruit Machines for the latter.

With effect from Mar 2010, Betting and Sweepstakes duties include Casino Tax collected under s146 of Casino Control Act and has been lumped into one line item instead beginning FY10/11 .

### If there's an issue with a dataset, please provide a description of the problem
Requires the single line "Betting Taxes"

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000
Year|Duty Collected

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ x] Annually
- [x ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

Casino tax and Tote Board and Private Lotteries have very different revenue drivers... ie tourist entertainment budget, general population gaming budget and the social / entertainment type of fruit machines. They also have different cost structures, ie rent paying abilities... while the casinos are basically segmented into 2 operating locations.

**Comment by lennardl** [comment]
Data is not available
