### ISSUE TITLE
Dataset request: National library board

### ISSUE THREAD

**Issue by herzizza88** [datagovsg/datagovsg-datasets#153]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )* national library board

### Please provide the fields expected in this dataset: 
Dataset 1
month | year| footfall| number of borrows | geographical location

Dataset 2
For year 2016,2017
Month|unique identifier of borrower| number of items borrowed per person | categories of items borrowed| geographical location of borrowed items 

*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [x] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Im using it for a project in school.

**Comment by lennardl** [comment]
Data not available
