### ISSUE TITLE
Dataset request: School Directory for Institutes of Higher Learning and International Schools

### ISSUE THREAD

**Issue by goodaccoustics** [datagovsg/datagovsg-datasets#154]
### Please provide the name of the dataset or describe the dataset that you're requesting:
datagovsg already provides very good school information and locations for MOE Schools (e.g Pri, Sec, JC) and Pre-Schools. However, datagovsg does not seem to have data of schools under the Institutes of Higher Learning-IHL segment (e.g Public Universities and Private Universities such as NUS, NTU, SMU, Chicago etc etc) and the International Schools segment (e.g. American school, Japanese school, French school). 
Would be more complete if datagovsg/MOE can provide such information for IHLs and International Schools.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
MOE: http://sis.moe.gov.sg/

### If there's an issue with a dataset, please provide a description of the problem
The following dataset already exists but missing IHL and International Schools. It will be more complete to add IHLs and International Schools into this same dataset.
https://data.gov.sg/dataset/school-directory-and-information

### Please provide the fields expected in this dataset:
Similar to this dataset
https://data.gov.sg/dataset/school-directory-and-information

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Useful for people to have a broad base list to plan for their kids education in terms of proximity to home, the subjects, the focus of the school etc.

**Comment by lennardl** [comment]
We do not have the data, the data is limited to the schools under MOE
