### ISSUE TITLE
Dataset Issue: SDCP Park

### ISSUE THREAD

**Issue by jordanlys95** [datagovsg/datagovsg-datasets#156]
### Please provide the name of the dataset or describe the dataset that you're requesting:
**SDCP Park**
Indicative polygon of Park

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Urban Redevelopment Authority

### If there's an issue with a dataset, please provide a description of the problem
Spelling Error for 'DAIRY FARM NATURE PARK' spelt as 'DAI**S**Y FARM NATURE PARK'

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

name |
------|
DAIRY FARM NATURE PARK|

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/sdcp-park
