### ISSUE TITLE
Dataset request: Uniform Singapore Energy Price

### ISSUE THREAD

**Issue by wengkeong** [datagovsg/datagovsg-datasets#157]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Uniform Singapore Energy Price

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

https://www.ema.gov.sg/cmsmedia/Publications_and_Statistics/Publications/ses/2017/energy-prices/index.html

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

I will need the updated average monthly Uniform Singapore Energy Price. The one from EMA only has up to Mar 2017 figures
https://www.ema.gov.sg/statistic.aspx?sta_sid=201707106swQNahHjHnP

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I want to look at the trending in USEP price over the years

**Comment by lennardl** [comment]
Data not available
