### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by culture1998** [datagovsg/datagovsg-datasets#1571]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Rainfall - Monthly Total

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
NEA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

month | Singapore | rainfall

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

Correlation for an outdoor device breakdown rate

**Comment by christinaWEEKG** [comment]
Sorry. Pls close case.

Thank you
Christina

**Comment by culture1998** [comment]
Ok
