### ISSUE TITLE
Dataset request: Road Network

### ISSUE THREAD

**Issue by leeyenter** [datagovsg/datagovsg-datasets#159]
### Please provide the name of the dataset or describe the dataset that you're requesting:

List of roads in Singapore

### Do you know which agency provides/can provide this data?

LTA

### If there's an issue with a dataset, please provide a description of the problem

1. Data is not complete / dirty. For example:
    * Bedok North Road, near junction with PIE: does not show bend in road
    * Siglap Close - shows extended road, where Google Maps shows that there's no street there
2. Does not show direction of road
    * Not sure if this is a problem with how the data is exported, but there doesn't seem to be a fixed order of points (it can be going from start to end, or end to start. Particularly noticeable for one-way roads, such as Cheviot Hill)

If possible, would also be good if we can see which junctions lead to which other roads. I tried incorporating this with the Arrows dataset (from LTA as well) but it is also not complete. 

### Please provide the fields expected in this dataset:

id|road_name|start_lat|start_lng|end_lat|end_lng|leads_to
---|------|---------|-------------|------|------|------
1|Cheviot Hill|1.31574|103.923|1.316|103.924|[2]
2|Cheviot Hill|1.316|103.924|1.31606|103.924|[4,6]

### How frequently would you need this dataset to be updated?

- [x] Annually (or rather, ad-hoc)
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

Model traffic flow with taxi availability data

**Comment by ntalam** [comment]
@leeyenter Did you manage to successfully get this data? Can you share?

**Comment by leeyenter** [comment]
Apologies for the late reply. No afraid I haven't.
