### ISSUE TITLE
Dataset request: Abortion Rate Singapore

### ISSUE THREAD

**Issue by ongkowinoto** [datagovsg/datagovsg-datasets#160]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Abortion Rate.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Health, Ministry of Home Affairs

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
month | no. of abortion
----- | ---------------

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Fertility Rate vs. Abortion Rate

**Comment by lennardl** [comment]
We do not have abortion rates data
