### ISSUE TITLE
Dataset request: Crime Distribution in Singapore

### ISSUE THREAD

**Issue by samkai887** [datagovsg/datagovsg-datasets#161]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Crime Distribution in Singapore based on a district(Example: Serangoon, Kallang)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Home Affairs - Singapore Police Force

### If there's an issue with a dataset, please provide a description of the problem
N.A

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Month|District|Number of offenders|Type of Offence
January|Kallang|100|Housebreaking

Additional Requirements: Preferably the data to be presented in these formats: CSV, KML and SHP.

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To develop an application that displays the crimes in an area and warn Singaporeans of the potential dangers in the area.

**Comment by lennardl** [comment]
We do not have the data down to the district level just the overall numbers
