### ISSUE TITLE
CPF Interest rates

### ISSUE THREAD

**Issue by nataziaperez** [datagovsg/datagovsg-datasets#163]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Central provident Fund Interest Rates

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Central Provident Fund Board

### If there's an issue with a dataset, please provide a description of the problem
I cannot seem to find the file regarding the interest rates of CPF. Can you help me navigate where I can find it?

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/monthly-interest-for-cpf-members
