### ISSUE TITLE
Dataset request:  <Number of Dwelling Units in Pasir Panjang>

### ISSUE THREAD

**Issue by jontay76** [datagovsg/datagovsg-datasets#166]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Number of Residential Dwelling Units in Pasir Panjang

### Do you know which agency provides/can provide this data?
URA/SLA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For research purposes

**Comment by lennardl** [comment]
We do not have that data
