### ISSUE TITLE
Dataset request: hourly weather observations for past 1 year

### ISSUE THREAD

**Issue by cjgeorge77** [datagovsg/datagovsg-datasets#167]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I would like to request an bi-hourly dataset containing weather, rainfall, temperature, relative humidity, air pressure and wind speed for any of the weather station for the last two years

### Do you know which agency provides/can provide this data?
*national Environmental agency/meteorological service singapore

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month/day | hour | rainfall | temperature | relative humidity | air pressure | wind speed | weather classification

### How frequently would you need this dataset to be updated?
Example: 

- [X ] Daily
- [ X] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
i will use this dataset to predict the weather for the weather station, as a part of my final project for my data science course

**Comment by lennardl** [comment]
You can pass in the params to get historical data from here https://data.gov.sg/dataset/realtime-weather-readings
