### ISSUE TITLE
Dataset request: <UEN>

### ISSUE THREAD

**Issue by tohweihong** [datagovsg/datagovsg-datasets#168]
### Please provide the name of the dataset or describe the dataset that you're requesting:
UEN, Company status

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
ACRA

### If there's an issue with a dataset, please provide a description of the problem
It was supposed to be updated monthly, but the last data set is Nov 2017 - is there a problem with the monthly updating?

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*
Monthly

### Can you give a short explanation on how you're planning to use this dataset?
Internal company use for automatic UEN reconciliation + auto populate customer address; to know also if the company is still live or dead (and whether we should do business)

**Comment by LoneRifle** [comment]
Do the following help?
https://data.gov.sg/dataset/acra-information-on-corporate-entities
https://data.gov.sg/dataset/entities-with-unique-entity-number

**Comment by tohweihong** [comment]
No. Please read my original message. I am NOT asking where to find the
info. I am asking why the frequency of update is so far behind and if I can
get more up to date info through any other way. Hope that clarifies

**Comment by LoneRifle** [comment]
Okay, well, the second of the two datasets I provided list a last-updated timestamp of 2018-06-13, that is, today. I'm not entirely sure if this is what you want (you've asked for UEN and company status, but also imply you probably want the address), so in case it isn't, we'll have a look into keeping the first dataset fresh.

**Comment by tohweihong** [comment]
Thanks - the set that has been updated is the truncated set - comprising
only some key data elements. The more detailed version (
https://data.gov.sg/dataset/acra-information-on-corporate-entities) was
updated Nov 2017 and has since then not seen an update. It is this data set
that I am more interested in - this set contains paid up capital
information, as well as SSIC which is helpful to us in building sectoral
performance and correlation.

The update frequency is "adhoc". Is there a minimum update frequency? or
what factors trigger the update?
failing which, what is the update frequency of the less detailed set? the
latter seems helpful as a temp measure until the detailed dataset is
available. in which case, understanding the currency of the data also helps
us determine the reliability of the data.

WH
