### ISSUE TITLE
Dataset request: Road Accidents in 2017 

### ISSUE THREAD

**Issue by ljysarah** [datagovsg/datagovsg-datasets#170]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Monthly Number of Road Accidents in 2017

### Do you know which agency provides/can provide this data?

-Land Transport Authority 
-Ministry of Home Affairs - Singapore Police Force

### Please provide the fields expected in this dataset:

year | month | number of accidents 
------|---------|-------------

### How frequently would you need this dataset to be updated?
 
- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

I am a student from Singapore Polytechnic currently doing a statistical project, trying to prove a correlation between heavy weather and rate of road accidents. I would like the monthly number of road accidents in 2017 in order to compare it to the amount of rainfall recorded per month in the same year. 

Thank you.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/causes-of-road-accidents-causes-of-accidents-by-severity-of-injury-sustained
