### ISSUE TITLE
Dataset request: Market Rental Rates of HDB

### ISSUE THREAD

**Issue by atng** [datagovsg/datagovsg-datasets#174]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Market Rental Rates of HDB by Block.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

HDB, IRAS. This is already publicly available via a manual query here: https://services2.hdb.gov.sg/webapp/BR12AWRentalEnq/BR12PSearch.jsp

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

flat_type | floor_area_sqm | lease_commence_date | month | remaining_lease | storey_range | street_name | town | block

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [X] Monthly
- [X] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

I intend to construct a valuation model based on the data.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/key-stats-since-1960-demand-for-rental-and-sold-flats
