### ISSUE TITLE
Dataset request: resale-flat-prices

### ISSUE THREAD

**Issue by pischuu** [datagovsg/datagovsg-datasets#179]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### If there's an issue with a dataset, please provide a description of the problem
https://data.gov.sg/dataset/resale-flat-prices
This dataset is taken down it was still previously available a few days ago

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [] *Test*

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
using the dataset for an assignment

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/resale-flat-prices
