### ISSUE TITLE
Dataset request: Public Transport Dataset by Regional

### ISSUE THREAD

**Issue by skykian** [datagovsg/datagovsg-datasets#18]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I need the Dataset of these SubZones served by Public Transport for my BI GROUP Assignment which shown as following:
Ang Mo Kio- Total | 174,770
Ang Mo Kio Town Centre | 5,020
Cheng San | 29,770
Chong Boon | 27,900
Kebun Bahru | 23,910
Sembawang Hills | 6,890
Shangri-La | 18,510
Tagore | 8,350
Townsville | 23,770
Yio Chu Kang | 30
Yio Chu Kang East | 4,080
Yio Chu Kang North | -
Yio Chu Kang West | 26,550
Bedok- Total | 289,750
Bayshore | 7,480
Bedok North | 85,930
Bedok Reservoir | 25,400
Bedok South | 51,190
Frankel | 33,570
Kaki Bukit | 40,820
Kembangan | 38,440
Siglap | 6,930
Bishan- Total | 90,700
and all regions of Singapore

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Don't know. Cause i try to look for it through many Singapore government website. Still cannot get it.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Area | Subzone | passengers
------|---------|-------------
Ang Mo Kio | Ang Mo Kio Town Centre | 10,000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X ] Annually  * I just need 2015 Dataset Figures
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I will use it for my BI Group Assignment. Cause i currently studying at Kaplan Murdoch Uni and our group assignment need this dataset to answer the questions and diagram for the Group Assignment.

**Comment by iewil** [comment]
@skykian this has been answered to in another issue #31. Thanks.
