### ISSUE TITLE
Dataset request: Cyclists involved in road accidents

### ISSUE THREAD

**Issue by junjie** [datagovsg/datagovsg-datasets#180]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Cyclists involved in road accidents, classified by severity with cause of accident

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Home Affairs - Singapore Police Force

### If there's an issue with a dataset, please provide a description of the problem
NA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

year | accident_classification | causes_of_accident | number_of_accidents | 
2017 | Injury |Disobeying Traffic Light Signals Resulting in Accidents with Vehicle | 10
2017 | Fatal |Overtaking without Due Care | 3
2016 | Injury | Changing Lane without Due Care | 5
2016 | Fatal |Overtaking without Due Care | 1

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
The government wants to promote a car-lite society by encouraging more cycling and PMD use. The current shared paths and footpaths infrastructure seem insufficient to handle the needs of cyclists, PMD users and pedestrians.

Although most people believe that cycling on the road is more dangerous (for the cyclist) than on the foot and shared paths, I personally find myself taking a lot more evasive action when cycling on the foot and shared paths.

For one, pedestrians frequently walk on the cycling paths and are paying very little attention to their surroundings, and cyclists have to weave around them as a result. Two, with the proliferation of bike sharing and PMDs, we're seeing a lot of casual, young, or inexperienced cyclists/PMD users who ride along the paths with in an disorderly manner. Three, the condition of the footpaths in Yishun is not exactly well suited for cycling.

As such, I find myself riding on the roads more, which is generally a more pleasant experience without causing disturbance to pedestrians.

If we can encourage cyclists to move to the road instead of the footpaths, we can reduce the number of accidents that can happen between cyclists and pedestrians.

In order to do so though, we need to dispel the notion that cycling on the roads is dangerous.
And one way to do so is to publish data of accidents involving cyclists and other vehicles on the roads.

With the availability of these data, lawmakers can make better decisions on how to improve road safety for cyclists on the road. For instance, if there are many accidents due to dangerous overtaking, it may make sense to introduce a minimum passing law.

**Comment by lennardl** [comment]
We do not have the breakdown its grouped at a topline level https://data.gov.sg/dataset/causes-of-road-accidents-causes-of-accidents-by-severity-of-injury-sustained?view_id=e80588ff-310c-4199-93bf-e6479e160634&resource_id=d68321b6-c438-425d-b9f4-d5777eee9e77
