### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by Auburncat** [datagovsg/datagovsg-datasets#182]
### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

2018-06 | Singapore | 10000
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [x] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
The dataset will be used as part of my module's project in understanding medical waste management and as part of the requirement for my degree in Biomedical Science.

**Comment by lennardl** [comment]
The data is not available
