### ISSUE TITLE
Dataset request: <Number of people who cycle on a daily basis>

### ISSUE THREAD

**Issue by qwertyrul** [datagovsg/datagovsg-datasets#184]
### Please provide the name of the dataset or describe the dataset that you're requesting:Number of people who cycle on a daily basis

daily basis | singapore | NIL

### How frequently would you need this dataset to be updated?

- [ ] Annually
- [ ] Monthly
- [ x ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

Ill need it for my assignment regarding cycling

**Comment by lennardl** [comment]
We do not have that data
