### ISSUE TITLE
Dataset request: list of Singapore restaurants

### ISSUE THREAD

**Issue by eunkenlow** [datagovsg/datagovsg-datasets#187]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I was wondering if business name/ restaurant name can be added to the:
List of NEA Licensed Eating Establishments with Grades, Demerit Points and Suspension History

### Do you know which agency provides/can provide this data?
National Environment Agency

### Please provide the fields expected in this dataset:
(e.g. licensee_name | licence_number | premises_name | premises_address | grade)

licensee_name | licence_number | premises_name | premises_address | grade
------|---------|-------------|----------|----------
Mr Tan|12345|Restaurant Hello|123 Road|A

### How frequently would you need this dataset to be updated?
Example: 
- [X] Test

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Allow users to easily find restaurants in Singapore

**Comment by lennardl** [comment]
We do not have the data
