### ISSUE TITLE
Dataset request: ACRA Information on Corporate Entities

### ISSUE THREAD

**Issue by mckeix** [datagovsg/datagovsg-datasets#190]
Hi,

Would it be possible to request for updated version of the ACRA Information on Corporate Entities dataset?

I'm using it to know the ssic of new companies.

Thanks a lot.

**Comment by susanshtan** [comment]
Agreed, need to use it update my supplier database.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/acra-information-on-corporate-entities
