### ISSUE TITLE
Dataset request: <Number of foreigners over the past 5 years by nationality/country>

### ISSUE THREAD

**Issue by Valvetronic** [datagovsg/datagovsg-datasets#191]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Number of foreigners over the past 5 years by nationality/country

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Not sure?

### If there's an issue with a dataset, please provide a description of the problem
-Nil-

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

year | country | No. People 
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To use in our school project in Temasek Polytechnic Business School.

**Comment by lennardl** [comment]
We do not have the data
