### ISSUE TITLE
Dataset request: OFO Bike

### ISSUE THREAD

**Issue by daphwong18** [datagovsg/datagovsg-datasets#192]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I am interested to do an analytics project on bike sharing in Singapore as my final year school project. Therefore, I am requesting for a dataset from ofo bike consisting of at least 3000-5000 records for my study.

### Do you know which agency provides/can provide this data?
LTA

### If there's an issue with a dataset, please provide a description of the problem
NA.

### Please provide the fields expected in this dataset:
Country, Start and End Time, Duration, Cost, Start Location, End Location, Purpose, Promotion etc. anything that has been captured would be good.

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
This is a one-time request so 1 year's data should suffice.

### Can you give a short explanation on how you're planning to use this dataset?
For final year analytics school project

**Comment by iewil** [comment]
@daphwong18 this is not a government generated dataset. You'll have to approach Ofo bike for access to the data
