### ISSUE TITLE
Dataset request: NEA Licensed Eating Establishments with Grades, Demerit Points and Suspension History

### ISSUE THREAD

**Issue by jamesoks** [datagovsg/datagovsg-datasets#194]
### Please provide the name of the dataset or describe the dataset that you're requesting:
List of NEA Licensed Eating Establishments with Grades, Demerit Points and Suspension History

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
NEA

### If there's an issue with a dataset, please provide a description of the problem
It's missing Premises name info
E.g. Data.gov provides the premises data of licence number W99282J000 as
392 HAVELOCK ROAD (STAFF CANTEEN) GRAND COPTHORNE WATERFRONT HOTEL (LEVEL 3) SINGAPORE 169663
Whereas NEA provides the same record as
CAFÉ 392 
392 HAVELOCK ROAD (STAFF CANTEEN) GRAND COPTHORNE WATERFRONT HOTEL (LEVEL 3), SINGAPORE 169663
The premises name 'Cafe 392' is missing from the dataset

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Licence Number | Premise name | Premise address | Grade

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
- [X] Monthly

Example: 
- [X] *Test*
- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To determine which restaurant chains have higher grades and see if there's any geographical clustering (e.g. malls vs hawker centres)

**Comment by lennardl** [comment]
We do not have the data
