### ISSUE TITLE
Dataset request: Fingerprint of a bus route

### ISSUE THREAD

**Issue by aslambughari** [datagovsg/datagovsg-datasets#195]
### Please provide the name of the dataset or describe the dataset that you're requesting:
-Public Transport Journeys (Buses only)
-Public Transport Capacity (Buses only)
-Public Transport Utilisation(Buses only)
-Commuter Facilities (Buses only)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
LTA - Land Transport Authority

### If there's an issue with a dataset, please provide a description of the problem
N/A

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

1- Route ID I Start Place I Drop off Place | Passenger Count |      Date       | Start Time | End Time 
------------|------------|---------------|------------------|-------------|-----------|----------|
   2               | 99009        |         97049     |         666              | 01-12-2018 |       13:00   |    13:30   | 

2- BusID I Route ID | Bus Start Place | Bus End Place |
---------|----------|----------------|----------------|
   102      |     2         |     99009           |       10499         |

3- Please provide meta data of Route and Buses per Depot.

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
We are students from NIELIT (https://www.nielit.gov.in/) , Kerala, India doing Diploma in Artificial Intelligence. As part of course, we are interested to analyse and visualise public transportation data.

**Comment by lennardl** [comment]
We do not have the data
