### ISSUE TITLE
Dataset request: Car park availability

### ISSUE THREAD

**Issue by tnger8** [datagovsg/datagovsg-datasets#196]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Car park availability 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For Data visulisation for sch assignment

**Comment by iewil** [comment]
@tnger8 You can get this information from https://data.gov.sg/dataset/carpark-availability or https://www.mytransport.sg/content/dam/datamall/datasets/LTA_DataMall_API_User_Guide_v4.6.pdf
