### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by tikamody** [datagovsg/datagovsg-datasets#198]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Is there a dataset that tells me what is the working population in a particular area of Singapore (e.g. the number of employees working central business district)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
URA
LTA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Year, Month, Passenger/Employees, Area, Industry
month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*
Annually
- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
There is an effort to figure out the best places to put co-working places

**Comment by iewil** [comment]
@tikamody Sorry but this dataset is not available on data.gov.sg. There is however information on rentals and vacancies that you can find here: https://data.gov.sg/dataset/median-rentals-and-vacancy-of-office-space.
