### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by honeytta** [datagovsg/datagovsg-datasets#2]
### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### Do you know which agency can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by iewil** [comment]
@honeytta the form hasn't been filled up. Can you fill it up if you have a request? Thanks.

**Comment by iewil** [comment]
@honeytta closing issue. Please submit again if you have a request.
