### ISSUE TITLE
Dataset request: acra-information-on-corporate-entities

### ISSUE THREAD

**Issue by skenaja** [datagovsg/datagovsg-datasets#20]
### Please provide the name of the dataset or describe the dataset that you're requesting:
https://data.gov.sg/dataset/acra-information-on-corporate-entities

### Do you know which agency provides/can provide this data?
* ACRA

### If there's an issue with a dataset, please provide a description of the problem
The above dataset is returning a 404 error

### How frequently would you need this dataset to be updated?
- [ ] Annually
- [ ] Monthly
- [x] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by chrissng** [comment]
@skenaja could this be the dataset you are looking for? https://data.gov.sg/dataset/entities-with-unique-entity-number

**Comment by skenaja** [comment]
@chrissng ``entities-with-unique-entity-number`` is a cut-down dataset with very limited attributes - it's missing key fields like incorporation date, SSIC codes, normalised addresses, previous names, paid-up capital, etc which were in the ``acra-information-on-corporate-entities`` file.

Here's a saved copy of the metadata description file:
https://gist.github.com/skenaja/ae2b65fef7700c0287c0f7cd8c5def50

**Comment by jobchong** [comment]
Sorry for the duplicate, but I'm also wondering where `resource_id=bdb377b8-096f-4f86-9c4f-85bad80ef93c` has disappeared to

**Comment by iewil** [comment]
@jobchong @skenaja there's been a issue with getting the dataset updated. We're working on getting a fix up, and an updated version of the dataset should be available by the end of this week. Sorry about that.

**Comment by LoneRifle** [comment]
Hello all, I see that the above link no longer 404s. Can we consider the matter resolved?

**Comment by skenaja** [comment]
Many thanks! Closing ticket.
