### ISSUE TITLE
Commuter Start and End 

### ISSUE THREAD

**Issue by tikamody** [datagovsg/datagovsg-datasets#200]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Start and end of a commuter route (MRT or Bus Route) 
Average commuter ticket price for common routes 
Want to understand the most common commuter journeys (so where passengers start and end)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
LTA
URA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Month/Year, Start Location (can be dwelling), End location (can be dwelling), avg. ticket price 

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*
Annually 
- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Important to understand commuter routes for ride-sharing / pooling

**Comment by lennardl** [comment]
The data is not available
