### ISSUE TITLE
Dataset request: Air Pollutant - Ozone

### ISSUE THREAD

**Issue by pbancken** [datagovsg/datagovsg-datasets#201]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Air Pollutant - Ozone

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

National Environment Agency

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2018-06|Singapore

### How frequently would you need this dataset to be updated?
Example: 
- [ X] Daily

### Can you give a short explanation on how you're planning to use this dataset?

I'm looking into indoor air quality and I would like to get preferably all air pollutant info but certainly the ozone and PM2.5 
to be able to look for correlation between outdoor air quality and indoor air quality 

thank you very much for your help

best regards
pascal bancken

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/air-pollutant-ozone
