### ISSUE TITLE
Dataset request: <Vehicle information>

### ISSUE THREAD

**Issue by fausi** [datagovsg/datagovsg-datasets#204]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Vehicle information database. The database ideally should provide the general vehicle built information for corresponding vehicle registration number. 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Land Transport Authority

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

Vehicle No.| Vehicle Type: Wagon/Jeep etc. | Vehicle Scheme | Vehicle Make | Vehicle Model | Year of Manufacture | Engine Capacity | Engine Power | Fuel Type | Engine Cylinder | Tank Capacity | Vehicle Images(optional)

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
We would like to leverage vehicle details in Telematics app along with driver profiling.

**Comment by lennardl** [comment]
Data is not available
