### ISSUE TITLE
Dataset request: Tertiary school enrollment rates (F/M)

### ISSUE THREAD

**Issue by jinybery** [datagovsg/datagovsg-datasets#205]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Tertiary school enrollment rates (F/M) (gender segregated data (as % of gross)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of education
### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

Data from 1992 to 2016, Singapore "tertiary education enrolment rates: gender segregated data"

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am writing my dissertation on gender inequality for my PhD degree. One of the variables is for my research is "Tertiary education enrollment rates" of 34 countries.

**Comment by lennardl** [comment]
https://data.gov.sg/search?q=Tertiary+enrollment
