### ISSUE TITLE
Dataset request: Singapore MRT ridership

### ISSUE THREAD

**Issue by rwillianto** [datagovsg/datagovsg-datasets#206]
### Please provide the name of the dataset or describe the dataset that you're requesting:
MRT ridership by station

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
LTA, SMRT, SBS

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

date, time, # passengers, board, get off, ez-link/ one time ticket

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [x] Daily
- [x] Hourly
- [x] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To generate information about the movement of Singaporeans for retail planning

**Comment by lennardl** [comment]
MRT ridership numbers are not available
