### ISSUE TITLE
Dataset request: SkillsFuture

### ISSUE THREAD

**Issue by alcklow** [datagovsg/datagovsg-datasets#207]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Hi, My name is Alvin from ITE College West. My group of students will be participating in a Data Analytic Challenge and doing some research on SkillsFuture. As Singapore is going into Smart Nation and encouraged to upgrade in terms of skills based, or knowledge based. My team would like to analyze some of the following data (will only used for internal and not for distribution) :

1) Actual number of participants (based on age group), and area (North, South, East and West) started using Skillsfuture Credit.
2) Courses that has the highest sign up rate.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Skillsfuture, People Association, Institute of Technical Education

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Hi, My name is Alvin from ITE College West. My group of students will be participating in a Data Analytic Challenge and doing some research on SkillsFuture. As Singapore is going into Smart Nation and encouraged to upgrade in terms of skills based, or knowledge based. This would also help to encourage more Singaporean to sign up and upgrade themselves in near future.

**Comment by lennardl** [comment]
Data is not available
