### ISSUE TITLE
Dataset request: Number of Hospital Beds

### ISSUE THREAD

**Issue by LiuJun523** [datagovsg/datagovsg-datasets#208]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
https://data.gov.sg/dataset/number-of-hospital-beds

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

year | sector | no_of_hospital_beds
------|---------|-------------
1960|Public Sector|6537

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Do a dashboard for exercising

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/number-of-hospital-beds
