### ISSUE TITLE
Dataset request: realtime weather

### ISSUE THREAD

**Issue by ningmenghuang86** [datagovsg/datagovsg-datasets#209]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Realtime Weather Readings across Singapore

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
NEA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

timestamp | station_id | temperature
------|---------|-------------
2018-08-02T21:25:00+08:00|S44|28

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [X ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I would like to use the weather data to analyze its relationship with taxi availability.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/realtime-weather-readings
