### ISSUE TITLE
Dataset request: <Senior citizen friendly facilities by planning area/subzones>

### ISSUE THREAD

**Issue by CJ1228** [datagovsg/datagovsg-datasets#21]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I would like to get the amount of senior citizen friendly facilities by our planning areas and subzones etc.
We have the datasets for senior citizen population by planning areas and subzones but fail to find any datasets for senior citizen friendly facilities. Amount of Bus services that are senior citizen friendly, senior citizen corners, Care centers, Activity centers, Enhancement for Active Seniors flats etc. 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
LTA, URA, MSF, HDB

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Subzones | Amount of Bus Services | Senior Corner | Care Centers | Planning Area
##################################################
Yishun North | 15 | 10 | 5 | Yishun

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

1 time dataset for year 2015.

### Can you give a short explanation on how you're planning to use this dataset?

The data is actually for our university assignment trying to find out which planning areas and subzone  can actually have more improvements on such senior friendly facilities.

**Comment by iewil** [comment]
@CJ1228 this is a duplicated issue. Please refer issue #31 for more info.
