### ISSUE TITLE
Dataset request: <Orthopaedic cases>

### ISSUE THREAD

**Issue by rwillianto** [datagovsg/datagovsg-datasets#210]
### Please provide the name of the dataset or describe the dataset that you're requesting:
What is the number of orthopaedic cases reported in Singapore public and private medical institutions.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
MOH

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | private/ public | number of patients | treatment requested/ given

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
This dataset is used to analyse trends regarding orthopaedic health in Singapore and to help make business decisions in this industry.

**Comment by lennardl** [comment]
Data is not available
