### ISSUE TITLE
6 Digit Postal Data with Building Type Description

### ISSUE THREAD

**Issue by WongCKB** [datagovsg/datagovsg-datasets#212]
### Please provide the name of the dataset or describe the dataset that you're requesting:
6 Digit Postal Data with Building Type Description

### Do you know which agency provides/can provide this data?
*Currently the data can be purchased from Singapore Post.  Not sure if there is a government agency which has complete records?*

### If there's an issue with a dataset, please provide a description of the problem
*At present, quarterly data updates can be purchased from SingPost at a cost of S$8500 annual subscription fee, which is quite steep.*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

POSTCODE | BLDGNO | STREETNAME | BLDGNAME | FLOOR | UNIT | BLDGCODE | BLDGDESC
------|---------|----------|----------|----------|----------|----------|----------
POSTAL CODE|APT/BLK/BLDG NUMBER|STREET/ROAD NAME|BLDG/PROJECT NAME|LEVEL/STOREY/FLOOR NUMBER|UNIT/STACK NUMBER|BLDG TYPE CODE|BLDG TYPE DESCRIPTION

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Quarterly would be great!*
- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

To maintain an in-house I.T. system which is dependent on updated postal code and local address data.

**Comment by lennardl** [comment]
Postal Code data is not available on the site and can only be requested from Singapore Post
