### ISSUE TITLE
Dataset request: <LTA static dataset request>

### ISSUE THREAD

**Issue by wangnanxin** [datagovsg/datagovsg-datasets#213]
### Please provide the name of the dataset or describe the dataset that you're requesting:
1. Bus stop location
2. Covered linkway
3. Cycling path
4. Foot path
5. Pedestrian overhead bridge/underpass
6. Road crossing
7. Speed regulating strip
8. Traffic light
9. Road classification

### Do you know which agency provides/can provide this data?
Land Transport Authority

### If there's an issue with a dataset, please provide a description of the problem
We require the datasets to be entirely complete and will ensure the data is secure within our team.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

Data should be presented in GIS layers
1. Bus stop location (point data)
2. Covered linkway (line data)
3. Cycling path (line data)
4. Foot path (line data)
5. Pedestrian overhead bridge/underpass (line data)
6. Road crossings by type (point data)
7. Speed regulating strip (point data)
8. Traffic light (point data)
9. Road classification by number of lanes and classification type

### How frequently would you need this dataset to be updated?
We only require static datasets.

-[Past and current data set, once off request] *All data listed above*
Most recently updated. We only require this dataset once for this study.

### Can you give a short explanation on how you're planning to use this dataset?
The requested layers will be utilized for research which will assess associations between recreational, transport and other environments with physical activity, health and mental well-being in Singapore. This project is supported by the MND Research Fund and is collaboration between the National Parks Board and the Saw Swee Hock School of Public Health, National University of Singapore (NUS). The main objective of the project is to investigate the association between green spaces and health and wellbeing. 

The information which the LTA supply will be overlaid on GIS layers of Singapore to create a walkability and transport index following the International Physical Activity and the Environment Network (IPEN) methods. For all participants in the Saw Swee Hock School of Public Health’s Singapore Population Health Study cohorts, neighbourhood buffer zones will be created and statistical tests will be conducted to assess the association between environmental attributes, their physical activity levels and other health outcomes.

**Comment by lennardl** [comment]
We only have the cycling network
https://data.gov.sg/dataset/cycling-path-network
