### ISSUE TITLE
Dataset request: Driving License details

### ISSUE THREAD

**Issue by ManikBucha** [datagovsg/datagovsg-datasets#214]
### Please provide the name of the dataset or describe the dataset that you're requesting:
We would like to request for an API which allows to validate a driving license in Singapore along with the years of driving experience and no. of demerit points. API will be extremely useful to ensure that right parties are getting insurance on the road and just not based on declaration.

### Do you know which agency provides/can provide this data?
Singpaore police force?

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [x] Real-time

**Comment by ManikBucha** [comment]
API will be extremely useful to ensure that "credible" individuals are getting insurance on the road and just not based on declaration which has resulted in lot of customer conflicts resulting in non payment of car insurance claims.

**Comment by lennardl** [comment]
Data is not made available by SPF/Traffic Police
