### ISSUE TITLE
Dataset request: Details of an existing car 

### ISSUE THREAD

**Issue by ManikBucha** [datagovsg/datagovsg-datasets#215]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Request a real time API which takes car plate as an input and returns all the details needed to transact an insurance policy including:
Details of the owner (Name, NRIC)
Car Make
Car Model
Engine CC
Registration Year
Engine Number
Chassis number
Any declared modifications

### Do you know which agency provides/can provide this data?
LTA?

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Name of the owner
NRIC
Car Make
Car Model
Engine CC
Registration Year
Engine Number
Chassis number
Any declared modifications

Access should be real time

### Can you give a short explanation on how you're planning to use this dataset?
To provide real time customer centric car insurance quotes to customers just using their car plate details.

**Comment by lennardl** [comment]
The data is not made available to that level
