### ISSUE TITLE
Dataset request: Breast cancer mortality by age group

### ISSUE THREAD

**Issue by wsminmin** [datagovsg/datagovsg-datasets#216]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Breast cancer mortality in Singapore by age groups (10-14 yrs, 15-19 yrs, 20-24 yrs, 25-29 yrs, up to ≥85 yrs) and ethnicity

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

 Health Promotion Board or Ministry of Health

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Age group | Mortality (all) | Mortality (Chinese) | Mortality (Indian) | Mortality (Malay)

### How frequently would you need this dataset to be updated?
Example: 
- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To calculate lifetime and 10-year absolute risk of breast cancer in Singapore

**Comment by lennardl** [comment]
Data is not available
