### ISSUE TITLE
Dataset request: <Traumatic head injuries>

### ISSUE THREAD

**Issue by sianliu** [datagovsg/datagovsg-datasets#217]
### Please provide the name of the dataset or describe the dataset that you're requesting:
The number of people who are affected by traumatic brain injury that are not able to reintegrate back into society. The number of mild, moderate, or severe cases. 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Health Promotion Board
Ministry of Health

### If there's an issue with a dataset, please provide a description of the problem
Of the 52 datasets provided by MOH, no datasets on TBI cases could be found. 

### Please provide the fields expected in this dataset:
GCS score
Severity of injury 
Cause of injury
Age of patient
Year of occurrence 

### How frequently would you need this dataset to be updated?
(At minimum)
- [ x] Annually
- [ x] Monthly

### Can you give a short explanation on how you're planning to use this dataset?
Conduct analysis and find a solution to increase the chances for those affected by traumatic brain injuries (TBI) in reintegrating back into society and living a fulfilling life.

**Comment by lennardl** [comment]
Data is not available
