### ISSUE TITLE
Dataset request: Market Share of Food Delivery Services in Singapore

### ISSUE THREAD

**Issue by stephanietans** [datagovsg/datagovsg-datasets#218]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Market Share of Food Delivery Services in Singapore:
The dataset I am requesting for would be the market share of food delivery services in Singapore, preferably the yearly revenues of each of the companies (deliveroo, grabfood/ubereats, and foodpanda). 

### Do you know which agency provides/can provide this data?
Deliveroo, Grabfood, Foodpanda

### If there's an issue with a dataset, please provide a description of the problem
-

### Please provide the fields expected in this dataset:
month | country | passengers
------|---------|-------------
2017-01 to 2018-08|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [ ] Annually
- [ ] Monthly
- [X] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am planning to use this data set for my extended essay research for my International Baccalaureate examination. My research is regarding the market structure of the food delivery services in Singapore, and I require the yearly revenues so as to be able to calculate the market share of these delivery services for my research paper.

**Comment by lennardl** [comment]
Data is not available
