### ISSUE TITLE
Dataset request: <playgrounds>

### ISSUE THREAD

**Issue by BoonieTan** [datagovsg/datagovsg-datasets#220]
Hi,

I am looking for data on all the public playgrounds in Singapore.

I believe this data would be available from:

- Building and Construction Authority
- Early Childhood Development Agency
- Urban Redevelopment Authority
- National Parks Board
- Housing and Development Board

The fields expected would be  - Location, Type of Facilities/ Features, Unique Identifier, etc

With a weekly update expected.

This data will be used to potentially provide a free app service for parents looking for playgrounds based on their distance, age and safety preferences.

many thanks!
BC

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/nparks-playfitness-equipment
https://data.gov.sg/dataset/nparks-activity-area

We are requesting for the mapping of playgrounds within HDB areas
