### ISSUE TITLE
Dataset request: Applications for one-room and two-room HDB rentals

### ISSUE THREAD

**Issue by revathivalluvar** [datagovsg/datagovsg-datasets#221]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Number of one-room and two-room rental applications for the last 10 years

### Do you know which agency provides/can provide this data?
HDB

### Please provide the fields expected in this dataset:
years, number of applications

Years | number of one-room rental applications
Years | number of two-room rental applications

### How frequently would you need this dataset to be updated?
Example: 

- [X] Annually

### Can you give a short explanation on how you're planning to use this dataset?###
Possibly in a news article

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/key-stats-since-1960-demand-for-rental-and-sold-flats
https://data.gov.sg/dataset/number-of-applications-registered-for-resale-flats
