### ISSUE TITLE
Dataset request: air quality data

### ISSUE THREAD

**Issue by baongocthai** [datagovsg/datagovsg-datasets#227]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I'm doing a project in school on air pollution caused by PM2.5 and I need the data on PM2.5 produced by industries and vehicles in Singapore, and the data on PM2.5 24-hr mean, as long a period of time as possible

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
I think it can be from Ministry of Environment and Water Resources or NEA.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Day, Year, Industry, PM2.5 mean, Location
month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ x] Weekly
- [ x] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I'm going to use this for my Design Project in NUS regarding air pollution control strategies in Singapore.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/pm2-5
