### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by zhaozizhi** [datagovsg/datagovsg-datasets#228]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I would like to know the quantity of  Automated External Defibrillators for public use installed in Singapore.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [x] Real-time

**Comment by zhaozizhi** [comment]
we are planning to use this data in an research which is aimed to compare the utilization of AED in different  countries.

**Comment by lennardl** [comment]
Data is not available
