### ISSUE TITLE
Dataset request: Weather data

### ISSUE THREAD

**Issue by NgSiHan** [datagovsg/datagovsg-datasets#229]
### Please provide the name of the dataset or describe the dataset that you're requesting:

- Realtime Weather Readings across Singapore
- Ultra-violet Index (UVI)
- PM2.5
- Pollutant Standards Index (PSI)
- Weather Forecast

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
https://data.gov.sg/organization/national-environment-agency

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

All fields are required

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [X] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
School Computer Science project, to create a weather application in Java

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/pm2-5

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/realtime-weather-readings
