### ISSUE TITLE
Dataset request: Lightning Risk Forecast

### ISSUE THREAD

**Issue by LXSkyhawk** [datagovsg/datagovsg-datasets#231]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Lightning Risk Forecast, in particular, the data which SAF uses to determine weather status (i.e. Cat 1/2/3) sourced from Meteorological Services Division (i.e. http://wip.weather.gov.sg)

### Do you know which agency provides/can provide this data?

Meteorological Services Division
OR
National Environment Agency

### If there's an issue with a dataset, please provide a description of the problem

NIL

### Please provide the fields expected in this dataset:

start time | end time | region | forecast
----------|----------|-------|---------
1200|1400|Changi|Cat_1

### How frequently would you need this dataset to be updated?

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [X] Half-Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

Currently working on a Weather Notification Telegram Bot for Changi Air Base. My prototype sourced data from NEA’s existing weather forecast (2 hour nowcast) but it was not ideal since I need it to coincide with SAF’s official weather announcements of Cat 1/2, etc.
Was referred to wip.weather.gov.sg which is under Meteorological Services Division which provides the appropriate lightning forecast I need, but provides the data in an image format, which is hugely inconveniently and almost impractical to extract any data from.
Thus, having a proper API dataset for this would be extremely helpful to my project.

**Comment by lennardl** [comment]
We do not have any lightning data
