### ISSUE TITLE
Dataset request: Road Accident

### ISSUE THREAD

**Issue by W3ddl3Q5** [datagovsg/datagovsg-datasets#232]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Details of traffic accident with recorded  details  include weather,  time,  date  and location,  type,  location  and  maneuver  of  the vehicle, driver details, details of injury and injury severity 

### Do you know which agency provides/can provide this data?
Ministry of Home Affairs - Singapore Police Force

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Time | Date | Weather | Location | Accident Classification | Type of accident
------|---------|-------------
12:20:20 | 10/9/2018 | Wet | Woodlands Ave 5 | FATAL | Failing to Keep a Proper Lookout

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
We are planning to use this dataset to predict any potential accident and traffic condition recognition

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/causes-of-road-accidents-causes-of-accidents-by-severity-of-injury-sustained
