### ISSUE TITLE
Dataset request: weather data

### ISSUE THREAD

**Issue by xizhang00166** [datagovsg/datagovsg-datasets#233]
### Please provide the name of the dataset or describe the dataset that you're requesting:
- Data requested: Singapore PM2.5 Hourly&Daily Historical Data from 2016-01 to 2018-01.
- Following link only present annual mean values of PM2.5 in Singapore:
https://data.gov.sg/dataset/air-pollutant-particulate-matter-pm2-5 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
- National Environment Agency

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2016-01~2018-01|Singapore|NA

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X ] Daily
- [X ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
- Case study regarding air quality worldwide, including China, India and Singapore.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/pm2-5
