### ISSUE TITLE
Dataset request: <List of China Parented Companies in Singapore>

### ISSUE THREAD

**Issue by Selenewongyt** [datagovsg/datagovsg-datasets#234]
### Please provide the name of the dataset or describe the dataset that you're requesting:
List of China Parented Companies in Singapore

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Not sure 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)* Name of Chinese Company in Singapore, Estimated Revenue Range 

Name of Chinese Company in Singapore | Estimated Revenue Range 

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
The company is planning to search for new clients opportunities through seeing which China firms with Singapore subsidiary have we not targeted.

**Comment by lennardl** [comment]
We do not have the data
