### ISSUE TITLE
Dataset request: Shopping malls

### ISSUE THREAD

**Issue by DtCarrot** [datagovsg/datagovsg-datasets#236]
### Please provide the name of the dataset or describe the dataset that you're requesting:
The list of shopping malls in Singapore.

### Do you know which agency provides/can provide this data?
Urban Redevelopment Authority

### Please provide the fields expected in this dataset:
Name | Size (Square Feet) | Year built | Developer
Northpoint City | 1, 300, 000 | 1992  | Fraser Centrepoint

### How frequently would you need this dataset to be updated?
- [x] Annually

### Can you give a short explanation on how you're planning to use this dataset?
I'm using this dataset to identify what is the proximity from any given location in Singapore to shopping malls in Singapore. Shopping malls play a significant role in Singapore's urban landscape - It also contributes to the property price in the surrounding area. This dataset can potentially help people in their decision making before they rent or purchase any property (office, housing, retail).

**Comment by lennardl** [comment]
We do not have the data
