### ISSUE TITLE
Dataset request: <Rainfall: Daily Highest 30-min Rainfall Historical Records>

### ISSUE THREAD

**Issue by xiaosquare** [datagovsg/datagovsg-datasets#237]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Rainfall: Daily Highest 30-min Rainfall Historical Records

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
National Environmental Agency - Meteorological Service Singapore

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] Annually

### Can you give a short explanation on how you're planning to use this dataset?
Now we can actually find these data on the website at weather.gov.sg, but it's segregated by month. So it takes time and effort to download all the historical data for analysis. It's important that we pay more attention to the highest 30-min rainfall rather than daily rainfall because it is the intensity of the rain which causes flash flood in Singapore. Therefore, when designing for local drainage system, it's prudent that we make reference of such statistics rather than relying on the rainfall intensity chart published by PUB which reflects only data up till 2009.

**Comment by lennardl** [comment]
Our rainfall data is limited to https://data.gov.sg/search?q=rainfall
