### ISSUE TITLE
Dataset request: Fruits and Vegetable wasted everyday

### ISSUE THREAD

**Issue by RomilaMukherjee** [datagovsg/datagovsg-datasets#238]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [x] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by RomilaMukherjee** [comment]
We need this dataset for educational purpose .
We need to analyse the data set for educational project purpose.

**Comment by lennardl** [comment]
We do not have the data
