### ISSUE TITLE
Dataset request: Dengue Cases Data since 2013

### ISSUE THREAD

**Issue by whatforeveris** [datagovsg/datagovsg-datasets#239]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Dengue Cases (found at https://data.gov.sg/dataset/dengue-cases)
We would like to have all of the relevant data since 2013.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
National Environmental Agency (NEA)

### If there's an issue with a dataset, please provide a description of the problem
NIL

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

date | number of cases | latitude | longitude
------|---------|-------------|-------------
15/03/2017|2|1.375687|103.722478

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [x] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

For our ES2001 Computational Earth Systems Science assignment in Nanyang Technological University, my group and I are planning to map out any correlations between historical Singapore meteorological distribution and trends, and dengue cases using MATLAB and Google Earth. We, therefore,, kindly hope to be able to have access to this data, which would be really helpful for our project. We will definitely give due credit to NEA in our project.

**Comment by lennardl** [comment]
We do not keep the historical data going back that far, NEA might be able to assist with that
