### ISSUE TITLE
Dataset request: Temperature and Rainfall Hourly Record

### ISSUE THREAD

**Issue by Linerax** [datagovsg/datagovsg-datasets#24]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Temperature and rainfall hourly record in Singapore (preferably Clementi) for the month of October.

### Do you know which agency provides/can provide this data?
National Environmental Agency, NEA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
( temperature | rainfall )

day | hour | temperature | rainfall | humidity

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [X] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
School Project

**Comment by iewil** [comment]
@Linerax the real-time temperature and rainfall data can be found in our developers portal. You can query for historical data by filling up the datetime parameter. Links to the relevant datasets below:
https://developers.data.gov.sg/environment/air-temperature
https://developers.data.gov.sg/environment/rainfall
