### ISSUE TITLE
Data Request: Government procurement from July 2018 to Sep 2018

### ISSUE THREAD

**Issue by GlennTJR96** [datagovsg/datagovsg-datasets#240]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Hi, I'm requesting for Government procurement from july 2018 to september 2018.

### Do you know which agency provides/can provide this data?
The agency that provide this is: https://www.gebiz.gov.sg/ . 
I understand that data.gov.sg already has the information, but it is only from 2015 to 2017. The GEBiz official website has the data, but I am unable to find any means to import the data over to excel.

### If there's an issue with a dataset, please provide a description of the problem
Nil.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Same format  as the provided one.

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For me to do a quick observation on how are the procurement rates.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/government-procurement
