### ISSUE TITLE
ACRA Dataset: entities-with-unique-entity-number

### ISSUE THREAD

**Issue by RHTGOC** [datagovsg/datagovsg-datasets#242]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Dataset: entities-with-unique-entity-number;

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
ACRA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [] Daily
- [ ] Hourly
- [ X] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Inform users if the company name is already registered or available.

**Comment by lennardl** [comment]
Can I understand if there is something within the dataset that's missing or you need?

**Comment by RHTGOC** [comment]
Hi  Lennardl,


My name is Aparna and I am representing RHT Management Services Pte ltd.


Thanks for the response. We are implementing Company checkname functionality in our website. I was wondering Is there any API to incorporate this checkname functionality. I have already checked the data Gov website. But there is no public API for this.





I would appreciate your guidance for this matter.


Regards,

Aparna

Senior Developer

RHT Management Services Pte. Ltd.

DID    : +65 6381 6913

Email : aparna.pc@rhtgoc.com<mailto:aparna.pc@rhtgoc.com>  | Web : www.rhtgoc.com<https://www.rhtgoc.com/>


[cid:image001.png@01D42B47.79578C00]<https://www.facebook.com/RHTManagementServices/>[cid:image002.png@01D42B47.79578C00]<https://www.linkedin.com/company/rht-management-services> [cid:image003.png@01D42B47.79578C00] <https://twitter.com/rhtms>

 [cid:image005.png@01D46D21.41CBF160] <https://www.rhtmgtsvcs.com/> [cid:image007.png@01D46D21.41CBF160]

<http://www.rhtacademy.com/asean-summit-2018/>


________________________________

**Comment by lennardl** [comment]
Hi Aparna,
We do have a search function but would query based on all fields so the results might not be as accurate.

Example: https://data.gov.sg/api/action/datastore_search?resource_id=bdb377b8-096f-4f86-9c4f-85bad80ef93c&q=rht

**Comment by RHTGOC** [comment]
Understood. Thanks for the comments. Some of the other companies also using checkname functionality api through data gov sg portal. I believe they also using this api provided by the data gov SG website. Because  I found out result are not accurate.

Thanks so much Lennard.

Regards,
Aparna

**Comment by nicolasmarchand** [comment]
Hi @lennardl 
Thanks for managing this.
It looks like this dataset is supposed to be updated weekly, yet last update was August 23, 2018. 
Do you know when is the next estimated update?

**Comment by lennardl** [comment]
@nicolasmarchand Yes we are experiencing an issue with ARCA to update the dataset, we are trying to resolve this.

**Comment by RHTGOC** [comment]
@lennardl The api you have provided in the earlier message prompting login form. Is there any way we can bypass this option? Is it the public api?

I would appreciate your  help .

Thanks.
Aparna

**Comment by lennardl** [comment]
@RHTGOC can you try if this works: https://data.gov.sg/api/action/datastore_search?resource_id=50d498c3-5317-4fc5-95e2-a74e8908c7e7
