### ISSUE TITLE
Dataset request: <Singapore Sports Hub Concerts>

### ISSUE THREAD

**Issue by trohera2014** [datagovsg/datagovsg-datasets#243]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Singapore Sports Hub Concerts: 
I live near Stadium and everyday I see different people spending hours in front of the concerts hall. I'm not sure whether this data is publicly available, but I was hoping to do an analysis of the attendance numbers across years hopefully, genres, and time periods. This could be useful to the Sports Hub team as it'd help them to plan their events accordingly. 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Sports Singapore

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
month | year | event type | event attraction | number of attendees
month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ 1] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
It's just for analysis purposes. I'd like to use Tableau to visualize this dataset

**Comment by lennardl** [comment]
Data is not available
