### ISSUE TITLE
Dataset request: container volumes

### ISSUE THREAD

**Issue by chimp007** [datagovsg/datagovsg-datasets#245]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Container transhipment volumes

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
annual data 2008-2017
month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by chimp007** [comment]
Undertaking analysis of regional container market

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/container-throughput-monthly-total
