### ISSUE TITLE
Dataset request: Waiting times for Registration and for Consultation at Polyclinics 

### ISSUE THREAD

**Issue by stinko02** [datagovsg/datagovsg-datasets#247]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Waiting times for Registration and for Consultation at Polyclinics from February 2017 to April 2017.

### Do you know which agency provides/can provide this data?
Ministry of Health 

### Please provide the fields expected in this dataset:
February - March 2017, Singapore, waiting times for each patient

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am a masters student at NTU/NIE doing a statistics module. The data will be use for analysis for the completion of the assignment. The data will only be use for personal consumption.

**Comment by lennardl** [comment]
The data is not available
