### ISSUE TITLE
Dataset request: Total length of Tunnels

### ISSUE THREAD

**Issue by PerformanceRotors** [datagovsg/datagovsg-datasets#248]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Total length of Tunnels (Motorway Tunnels, Service Tunnels)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
LTA, JTC

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Market Research for Marketing Plan in Investor Deck and Operations Planning

**Comment by lennardl** [comment]
We do not have the data
