### ISSUE TITLE
Dataset request: Achieved bus arrival data

### ISSUE THREAD

**Issue by jeffgorithm** [datagovsg/datagovsg-datasets#249]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Archived Bus Arrival Data

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
LTA

### If there's an issue with a dataset, please provide a description of the problem
No issues with the existing APIs, just that I'll require an archived version of it for my research project

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

BusStopCode | ServiceNo | ArrivalTime 
------|---------|-------------

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [ ] Annually
- [ ] Monthly
- [X] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

As part of my research project from my degree program, BSc-Computing Science (SIT-UOG), I am researching on the possibility of using Machine Learning models to estimate bus arrival timings based on a statistical approach by learning from the history of the data. It would be great if I am able to retrieve a dataset like this for analysis and building of machine learning models

**Comment by lennardl** [comment]
We do not have the data
