### ISSUE TITLE
Dataset request: tourist by attraction dataset 

### ISSUE THREAD

**Issue by johnabil** [datagovsg/datagovsg-datasets#251]
### Please provide the name of the dataset or describe the dataset that you're requesting:
tourist by attraction dataset 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

2d images

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
Data is not available
