### ISSUE TITLE
Dataset request: Request of Data Relating to Petrol Stations

### ISSUE THREAD

**Issue by izzatariel** [datagovsg/datagovsg-datasets#252]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I would like to request four datasets:
1) The number of petrol stations in Singapore from 1990 to 2018.
2) Land information on whether the sale of land (tender) for petrol station is for a vacant land or if it is a continuation of lease for an existing petrol station. 
3) Identification of petrol stations which closed down. 
4) Identification of all petrol stations in Singapore (on a map) at present - not available in OneMap.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
HDB, URA, SLA, EMA

### If there's an issue with a dataset, please provide a description of the problem
N.A.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

1) Number of Petrol Stations and Year
2) List of sale sites (and identification of which petrol stations were built on vacant land and which are just a continuation of lease of an existing petrol station).
3) List of sites where petrol stations have closed down.
4) Identification of all the petrol stations in Singapore on a map.

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am doing a study on the impact of petrol stations on the surrounding HDB residential prices. I would like to find out the effect of a newly built petrol station (which was previously not a petrol station) on surrounding HDB prices. Land tender data for HDB does not show which sites were vacant or whether the sale is a continued lease of an already existing petrol station.

**Comment by lennardl** [comment]
Data is not available
