### ISSUE TITLE
Dataset request: <List of NEA L3 License Holders>

### ISSUE THREAD

**Issue by gohchoonhuat** [datagovsg/datagovsg-datasets#255]
### Please provide the name of the dataset or describe the dataset that you're requesting:
List of NEA L3 License Holders

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

NEA
### If there's an issue with a dataset, please provide a description of the problem
Can only see the total, not the breakdown.

### Please provide the fields expected in this dataset:
*(e.g. Radiation License Type| Security or Medical | Agency or Company | numbers)*

Radiation License Type| Security or Medical | Agency or Company | Numbers
------|---------|-------------
L3|Security|Agency1|2
L3|Medical|XXClinic|3

We need to know specifically L3 and L4 only.

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

We are a security and inspection system and services provider. We wish to know the above mentioned dataset so as to better understand who may require our system and services. This is because the x-ray security screening equipment we can sell to are niche and has limited customer base in Singapore. We wish to extend our solution to other customers, not known to us.

**Comment by lennardl** [comment]
We do not have the data
