### ISSUE TITLE
Dataset request: Designated Smoking Areas & Non-Designated Smoking Areas

### ISSUE THREAD

**Issue by char1estan** [datagovsg/datagovsg-datasets#257]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Designated Smoking Areas & Non-Designated Smoking Areas

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
NEA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

identifiable area | location on GPS | distance from identifiable area for smoking (M) | smoking radius (M)
------|---------|-------------
chua chu kang bus stop | location | 5 | 2

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Develop an app to map out the smoking and non-smoking areas for Android

**Comment by lennardl** [comment]
We have approached NEA and they have designated smoking and non-smoking areas in Orchard as it is the first geographical area where smoking is banned (https://data.gov.sg/dataset/designated-smoking-areas). 

As for the rest of Singapore, smoking is allowed outside Orchard as long as it does not happen within specified compounds (https://www.nea.gov.sg/our-services/smoking-prohibition/overview). NEA currently does not have it mapped out of Orchard.
