### ISSUE TITLE
Dataset request: Usual Mode of Transport to Work, Age Group and Sex

### ISSUE THREAD

**Issue by Libby555** [datagovsg/datagovsg-datasets#258]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Resident Working Persons Aged 15 Years and Over by Usual Mode of Transport to Work, Age Group and Sex, 2015

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Data.gov.sg

### If there's an issue with a dataset, please provide a description of the problem
The Mode of transport is missing

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Usual mode of transport | Age Group | Sex | Value (thousands)

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For a research

**Comment by lennardl** [comment]
Hi,
Isn't the mode of transport available on the graph? 
https://data.gov.sg/dataset/resident-working-persons-aged-15-yrs-over-by-usual-mode-of-transport-to-work-age-group-sex-2015?view_id=a4f51a2e-84fe-4f58-a935-3552c24a16e4&resource_id=34f4d6a6-a643-40b6-8b00-2528c7f95695
