### ISSUE TITLE
Dataset request: Carpark Availability

### ISSUE THREAD

**Issue by PikaRapier** [datagovsg/datagovsg-datasets#259]
### Please provide the name of the dataset or describe the dataset that you're requesting:

I'm requesting for Carpark Availability real-time data.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

Data is provided by HDB.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Expected fields are : 
Location of carpark, Total no. of lots, No. of lots available.

### How frequently would you need this dataset to be updated?

- [ ] *Test*
- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [X ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I'm attending a Python course by NUS-ISS. I intend to use the data to write a carpark availability program using Python.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/carpark-availability
