### ISSUE TITLE
Dataset request: taxi-availability

### ISSUE THREAD

**Issue by raywu** [datagovsg/datagovsg-datasets#26]
### Please provide the name of the dataset or describe the dataset that you're requesting:
taxi-availability should show taxi statuses

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
LTA or A*STAR

### If there's an issue with a dataset, please provide a description of the problem
The current API feed shows geolocation of all active taxis, but does not show statuses, such as the following:

| Status   | Description                                                               |
|----------|---------------------------------------------------------------------------|
| BUSY     | Taxi driver temporarily unavailable due to a personal reason              |
| STC      | Taxi soon to clear the current job and ready for new bookings             |
| FREE     | Taxi unoccupied and ready for taking new passengers or bookings           |
| BREAK    | Taxi on a break and driver logged on mobile data terminal (MDT)           |
| POWEROFF | MDT shut down and not working                                             |
| ARRIVED  | Taxi arrived at the booking pickup location and waiting for the passenger |
| ONCALL   | Taxi unoccupied, but accepted a new booking job                           |
| OFFLINE  | Taxi on a break and driver logged off from MDT                            |
| POB      | Passenger on board and taximeter running                                  |
| PAYMENT  | Passenger making payment and taximeter paused                             |
| NOSHOW   | No passenger showing up and the booking canceled soon                     |

### Please provide the fields expected in this dataset:
latitude | longitude | status

Latitude | Longitude | status
------|---------|-------------
1.39646|103.89945|'POB'
1.38482|103.74587|'ONCALL'
1.38481|103.74586|'ARRIVED'

### How frequently would you need this dataset to be updated?

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [X] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

This will allow MagicBus to simulate based on consumer demands for On Demand Bus System.

**Comment by lennardl** [comment]
Data on taxi availability is available and limited to the fields here https://data.gov.sg/dataset/taxi-availability
