### ISSUE TITLE
Dataset request: Demarcation of HDB precinct

### ISSUE THREAD

**Issue by jayshen84** [datagovsg/datagovsg-datasets#260]
### Please provide the name of the dataset or describe the dataset that you're requesting:

**Demarcation of HDB precincts for Punggol

Basically which building blocks belong to which precinct in each neighborhood in Punggol**

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

**HDB
URA
SLA**

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

**Block number | Precinct Name | Neighborhood Name**  

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [**X** ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

**I wish to study the facilities of each HDB precinct to analyse how difference precincts have difference facilities.**

**Comment by lennardl** [comment]
We do not have the demarcation data
