### ISSUE TITLE
Dataset request: <Sulfur Hexafluoride Usage>

### ISSUE THREAD

**Issue by kahsiong** [datagovsg/datagovsg-datasets#261]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Sulfur Hexafluoride Usage

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
custom.gov.sg

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Personal research

**Comment by lennardl** [comment]
Data is not available
