### ISSUE TITLE
Dataset request: <Number of claims made under madishield life by sector>

### ISSUE THREAD

**Issue by zhaowenong** [datagovsg/datagovsg-datasets#262]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Number of claims made under madishield life by sector

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

Ministry of Health

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Year | Sector | Number of Claim
------|---------|-------------
2006 | Public | 10000
2006 | Private | 10000

### How frequently would you need this dataset to be updated?
- [x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

I want to use the dataset to find out the trend of the medishield life claim.

**Comment by lennardl** [comment]
@zhaowenong we have approached the relevant agency and the data is not available at this point in time.
