### ISSUE TITLE
Dataset request: <dataset title>housing development broad

### ISSUE THREAD

**Issue by Fnlp11** [datagovsg/datagovsg-datasets#263]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
Could you provide more details on what HDB data you are looking for?
