### ISSUE TITLE
Dataset request: <Road Coordinates>

### ISSUE THREAD

**Issue by e0026527** [datagovsg/datagovsg-datasets#266]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Coordinates of all Singapore roads, can be in kml, shapefile or xml.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
LTA

### If there's an issue with a dataset, please provide a description of the problem
MP08 Mapsheet Minor Road Name and MP08 Mapsheet Major Road Name files are empty

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Road Name | Coordinates

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am currently doing a research on traffic congestion and would wish to map it out on ArcGis.

**Comment by lennardl** [comment]
We do not have that data
