### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by motoristsg** [datagovsg/datagovsg-datasets#267]
### Please provide the name of the dataset or describe the dataset that you're requesting:

weather-forecast

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

NEA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [X ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

We plan to show the weather forecast for bike riders before they start their journey

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/realtime-weather-readings
