### ISSUE TITLE
Dataset request: Linggiu Reservoir Volume data

### ISSUE THREAD

**Issue by jchanke** [datagovsg/datagovsg-datasets#268]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Volume of water of the Linggiu Reservoir in Johor, Malaysia - source of our imported water - over a time period

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

Public Utilities Board

### If there's an issue with a dataset, please provide a description of the problem

NIL. This isn't available on the site though.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

day | volume of water in litres / percentage of water filled
------|-------------
2017-09-10| 22%

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

Ideally daily would be great! Otherwise, as frequent as can be provided would be great.

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

I'm a JC student looking to conduct research on mathematically modelling the volume of water in Linggiu Reservoir, Johor using stochastic processes, and I need data to test my model. The data will be for private use.

**Comment by jchanke** [comment]
hi! were you able to find any updates on this? (:

**Comment by lennardl** [comment]
Hi @jchanke, we are not able to get the data from PUB as of now.

**Comment by jchanke** [comment]
Thank you!
