### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by Nick-Zeng** [datagovsg/datagovsg-datasets#269]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Geojson (geographic information) of district of Singapore

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
No

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

district | country |
------|---------|
28 districts | Singapore |

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I would like to request the geojson (geographic information) of district of Singapore to develope a WebGIS application.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/sla-land-survey-district
