### ISSUE TITLE
Dataset request: air pollutants 

### ISSUE THREAD

**Issue by tieso** [datagovsg/datagovsg-datasets#27]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Air Pollutant - Particulate Matter PM2.5
Frequency: Daily

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
National Environment Agency

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-10|Mexico|1

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
School project

**Comment by iewil** [comment]
@tieso this data is already available as both a [dataset on data.gov.sg](https://data.gov.sg/dataset/air-pollutant-particulate-matter-pm2-5), and as an api on our [developers portal](https://developers.data.gov.sg/environment/pm25)
