### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by KarlPeltzer** [datagovsg/datagovsg-datasets#274]
### Please provide the name of the dataset or describe the dataset that you're requesting:

National Behavioural Surveillance Survey

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
The last updated data can be found here: https://data.gov.sg/dataset/national-behavioural-surveillance-survey. HPB has discontinued the dataset.
