### ISSUE TITLE
Dataset request: National Behavioural surveillance dataset

### ISSUE THREAD

**Issue by KarlPeltzer** [datagovsg/datagovsg-datasets#276]
### Please provide the name of the dataset or describe the dataset that you're requesting:

2016 National Behavioural surveillance dataset
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@KarlPeltzer, the survey was not carried out in the following years. Data after 2016 is not available.

**Comment by KarlPeltzer** [comment]
Thank you, but I want it for the latest dataset
