### ISSUE TITLE
Dataset request:Carpark Availabilty

### ISSUE THREAD

**Issue by c170154** [datagovsg/datagovsg-datasets#277]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [x] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Create a mobile app that shows the carparks and the availability on google maps

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/carpark-availability
