### ISSUE TITLE
Dataset request: bus ridership data

### ISSUE THREAD

**Issue by marthaisaacs** [datagovsg/datagovsg-datasets#28]
### Please provide the name of the dataset or describe the dataset that you're requesting:
bus ridership data

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
LTA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

EZlink card ID | date entered | bus route | origin bus stop | enter time | destination bus stop | exit time | commuter type

### How frequently would you need this dataset to be updated?
Example: 
- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am a researcher for the Centre for Liveable Cities and I am working on a project on Orchard Road. I want to look at current bus ridership on Orchard Road. I would need the ID card numbers of EZlink cards, the bus routes of trips. starting location and ending location of the bus trips, and the times of trips. I could have this data for every day for the past year, or just have two months with daily data to sample. Data from a past year would also work.

**Comment by iewil** [comment]
@marthaisaacs this is a duplicated issue. Please look at issue #7. If you want to propose additional fields, please comment in that thread. Thank you.
