### ISSUE TITLE
Dataset request: <HDB property information>

### ISSUE THREAD

**Issue by ander122** [datagovsg/datagovsg-datasets#280]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
Can you provide more details on the type of HDB information you are looking for?

**Comment by ywnch** [comment]
Hi, I wonder if it is proper to add to this issue, assuming that this issue points to this [dataset](https://data.gov.sg/dataset/hdb-property-information). Is it possible to access/include previous versions of this dataset as well (i.e., past quarterly releases)? Thank you!

**Comment by lennardl** [comment]
Data is not available and is rolling
