### ISSUE TITLE
Dataset request: <Historical annual corruption crime data>

### ISSUE THREAD

**Issue by ghost** [datagovsg/datagovsg-datasets#283]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Historical annual data for corruption criminal cases/investigations in Singapore since the inception of Corrupt Practices Investigation Bureau (CPIB), 1952-2017.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

Corrupt Practices Investigation Bureau

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Example of similar data from the U.S.: https://www.irs.gov/compliance/criminal-investigation/statistical-data-public-corruption-investigations

year  | investigations | investigations brought to trial | investigations resulting in sentencing |
------|----------------|----------------------------------|-------------------------------------------|
1952 | 5,000             |          100                                  |   20                                                        |
1953 | 10,000           |          200                                  |   30                                                        |
1954 | 15,000           |          300                                  |   40                                                        |

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] **Annually**
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

Academic research about the role of the CPIB in fighting corruption in Singapore

**Comment by lennardl** [comment]
We do not have the data and SPF did not revert
