### ISSUE TITLE
Dataset request: Live Bus Locations

### ISSUE THREAD

**Issue by jarrettyeo** [datagovsg/datagovsg-datasets#284]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Live Bus Location

### Do you know which agency provides/can provide this data?

LTA

### If there's an issue with a dataset, please provide a description of the problem

NA

### Please provide the fields expected in this dataset:

bus_id | datetime | bus_service | crowdedness | lat | lon
------|---------|-------------
SBS1234X | 2018-12-15 01:21:05 | 179 | high | 1.298452 | 103.769685

### How frequently would you need this dataset to be updated?

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [X] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

Plot live locations of buses on map for commuters to easily track the buses

**Comment by lihweilihwei** [comment]
@jarrettyeo Real-time bus locations of the arriving buses are already available in the Bus Arrival API from LTA ([documentation](https://www.mytransport.sg/content/dam/datamall/datasets/LTA_DataMall_API_User_Guide.pdf)). Update frequency is 1 minute. You might need to do some extra processing to match the different arriving buses at different bus stops.

**Comment by jarrettyeo** [comment]
Sweet!
