### ISSUE TITLE
Dataset request: endoscopic surgeries in Singapore

### ISSUE THREAD

**Issue by goglobal123** [datagovsg/datagovsg-datasets#285]
Dear Sir or Madame,
	I hope that this e-mail finds you well. I am writing to you on behalf of the GoGlobal firm which is creating market analysis. My current client Vimex S.p.z.o.o. European leader in production of  endoscopic needles and equipment is planning to enter Singapore’s medical devices market. In order to make our analysis as complex as possible we need to fulfil it with accurate data. Therefore, I want to ask you if it is possible for you to share with us following data: 
-	Data concerning the number of the endoscopic surgeries and operations completed in 2017 in Singapore with division between arthroscopy, cystoscopy, hysteroscopy, laparoscopy etc. 
-	Prognosis concerning the number of the endoscopic surgeries in coming years.
I hope that my request will be accepted and you will provide me with those crucial information. Thank you for your time and assistance!
Kind Regards

**Comment by lennardl** [comment]
We do not have the data
