### ISSUE TITLE
Dataset request: Quarter-on-quarter annualised growth rate of Singapore

### ISSUE THREAD

**Issue by tessajw** [datagovsg/datagovsg-datasets#286]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Quarter-on-quarter annualised growth rate, seasonally-adjusted (2010 chained)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
https://www.singstat.gov.sg/-/media/files/news/advgdp3q2018.pdf

### If there's an issue with a dataset, please provide a description of the problem
n/a

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Quarter-on-quarter annualised growth rate, seasonally-adjusted, 2010 chained | Quarter and Year | Country

### How frequently would you need this dataset to be updated?
Example: 

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Using to calculate QoQ growth (non-annualised) as cannot find regular QoQ growth for Singapore

**Comment by lennardl** [comment]
Data not available
