### ISSUE TITLE
Singapore Property Data 

### ISSUE THREAD

**Issue by iateveggies** [datagovsg/datagovsg-datasets#287]
### Do you know which agency provides/can provide this data?
HDB and URA 

### Please provide the fields expected in this dataset:
Blk | Street | Max Floor | Year Completed| Type of Occupancy (Residential / Commercial) | Total Dwelling Unit |

### How frequently would you need this dataset to be updated?
- [X ] Monthly

### Can you give a short explanation on how you're planning to use this dataset?

Using this data to analyze current property marketing, better understanding of the property risk exposure in Singapore

**Comment by lennardl** [comment]
@iateveggies would this data work for you?
https://data.gov.sg/dataset/hdb-property-information

**Comment by iateveggies** [comment]
Unfortunately, that data don't include Private Properties like condo and landed properties.

**Comment by portergoh** [comment]
Hi any updates on condo dataset

**Comment by lennardl** [comment]
@portergoh We were not able to get the relevant dataset from the agencies as the data is not readily available.
