### ISSUE TITLE
Dataset request: <Undergraduate Enrollment & Graduating Cohort Time Series Data>

### ISSUE THREAD

**Issue by imwilfred** [datagovsg/datagovsg-datasets#288]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Time series data of undergraduate enrollment in local universities (NUS, NTU, SUTD, SIT, SMU, and UniSim) as well as the Graduating Cohort size (i.e. number of students graduating). For both data set, to be broken by broad categories such as Engineering, Infocomm Technology, Business etc.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
No, but I figure the Ministry of Education might have it.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Enrollment and Graduating Cohort will share the same format as follows:
Year | Engineering | Infocomm Technology | Business (and so on, one column for each category)
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I would like to analyse the trend in the enrollment vs. graduating numbers in broad disciplines

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/universities-intake-enrolment-and-graduates-by-course
