### ISSUE TITLE
Dataset request: <dataset title>Mobile Data Usage

### ISSUE THREAD

**Issue by georgino6** [datagovsg/datagovsg-datasets#289]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by georgino6** [comment]
To construct a telecommunication price index

**Comment by lennardl** [comment]
There's data here, we are getting IMDA to update the data. https://data.gov.sg/dataset/mobile-data-usage

**Comment by lennardl** [comment]
The data has been updated.
