### ISSUE TITLE
Dataset request: <Rain Radar>

### ISSUE THREAD

**Issue by RichardAtCT** [datagovsg/datagovsg-datasets#291]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I would like access to the rain area map (http://www.weather.gov.sg/weather-rain-area-50km) 

### Do you know which agency provides/can provide this data?
MSS/NEA

### Please provide the fields expected in this dataset:

time and date | location | rain intensity (0-20)
------|---------|-------------
YYYY-MM-DD[T]HH:mm:ss (SGT)|lat:long|20

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [x ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I would like to create a service that alerts users ~5 minutes before rain is due at their precise location.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/realtime-weather-readings?resource_id=8bd37e06-cdd7-4ca4-9ad8-5754eb70a33d
