### ISSUE TITLE
Dataset request: <stats on average daily car traffic >

### ISSUE THREAD

**Issue by Felichaa** [datagovsg/datagovsg-datasets#292]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [x] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
We do not have the data, we have it on an annual level available at LTADataMall
