### ISSUE TITLE
Dataset request: flood occurrence in singapore, rainfall index, ground and surface water level

### ISSUE THREAD

**Issue by liangzi101** [datagovsg/datagovsg-datasets#293]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

date.            | time       | surface water level reading|country.       | floor hotspot|
------------|---------|----------------------------|------------|
09-2017      |1715hrs  |1234ml                                     |Singapore  |orchard road |

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ x] Daily
- [ x] Hourly
- [ ] Real-time

I am doing a project for Temasek polytechnic for data analytic project for flood occurrences. hope you can help

**Comment by lennardl** [comment]
We do not have the data
