### ISSUE TITLE
Dataset request: NParks Tracks

### ISSUE THREAD

**Issue by audthenerd** [datagovsg/datagovsg-datasets#294]
### Do you know which agency provides/can provide this data? National Parks Board
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2018-11|Singapore|100

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [x ] Real-time

**Comment by lennardl** [comment]
Is this sufficient?
https://data.gov.sg/dataset/nparks-tracks
