### ISSUE TITLE
Dataset request: Polling Districts and number of Electors

### ISSUE THREAD

**Issue by lychee512** [datagovsg/datagovsg-datasets#295]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Vector map with polling districts and number of electors in each polling district

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Prime Minister's Office - Elections Department

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

year | polling district name / number | polling district polygon | number of electors

eg. 2015 | CCK 01 | geojson / kml | 12345

### How frequently would you need this dataset to be updated?
Example: 

- [X] Every election cycle
- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Study impact of electoral boundary changes

**Comment by lennardl** [comment]
@lychee512 , the data is not currently available. The relevant agencies will be working on making the data available but it would not be ready soon.
