### ISSUE TITLE
Dataset request:  kml_1647

### ISSUE THREAD

**Issue by takashimiyashiro** [datagovsg/datagovsg-datasets#296]
### Please provide the name of the dataset or describe the dataset that you're requesting: 
kml_1647

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

**Comment by lennardl** [comment]
Can you provide more details on what you are looking for?
