### ISSUE TITLE
Request data for multiple dates in 1 api call

### ISSUE THREAD

**Issue by zohebjamal** [datagovsg/datagovsg-datasets#298]
### Please provide the name of the dataset or describe the dataset that you're requesting:
temperature data by date

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
NEA

### If there's an issue with a dataset, please provide a description of the problem
The temperature dataset and the api allow us to query by specifying a date or a timestamp as the parameter. I would like to request an api extension to allow retrieving data for a set of dates in a single request

### Can you give a short explanation on how you're planning to use this dataset?
I intend to use temperature time series data to look at weather patterns across different regions of Singapore.

**Comment by lennardl** [comment]
@zohebjamal thanks for your feedback and suggestion. We'll place it on the backlog, as we have other items to develop and fix we will not be able to complete this request that quickly.

**Comment by zohebjamal** [comment]
Sure. It is not urgent
