### ISSUE TITLE
Dataset request: LTA taxi stop

### ISSUE THREAD

**Issue by Alvinwee** [datagovsg/datagovsg-datasets#299]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/lta-taxi-stop?resource_id=fb808253-852c-423d-9715-20404eda8c9e
