### ISSUE TITLE
Dataset request: <Informal Housing Settlements Singapore>

### ISSUE THREAD

**Issue by sybilt** [datagovsg/datagovsg-datasets#301]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Informal Housing Settlements in Singapore 1960s-present

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

2018-11|Singapore

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

Master's of Urban Planning research

**Comment by lennardl** [comment]
@sybilt we have approached the relevant agencies and they do not have the data available

**Comment by lennardl** [comment]
We do not have the data
