### ISSUE TITLE
Dataset request: ACRA Information on Corporate Entities

### ISSUE THREAD

**Issue by MDevie** [datagovsg/datagovsg-datasets#304]

**Comment by lennardl** [comment]
@MDevie Can I understand is there something missing in the dataset that you require?

**Comment by MDevie** [comment]
> @MDevie Can I understand is there something missing in the dataset that you require?

Hi @lennardl , sorry, i misunderstood. I thought i needed to file a request to get real-time data from ACRA. Saw the list of 14 real-time APIs and realised that ACRA data is not one of them. Please ignore request, thanks!
