### ISSUE TITLE
Dataset request: <Skin Care Industry Imports>

### ISSUE THREAD

**Issue by zachlim** [datagovsg/datagovsg-datasets#305]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Skincare industry imports

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Not sure

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | volume | sales
------|---------|-----------|-------------
2018 - 2016|Singapore|1000000|1000000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For industry analysis

**Comment by lihweilihwei** [comment]
@zachlim You might be able to get this data from Statlink by Enterprise Singapore. It has commodity trade data for Singapore (import, exports etc.).
