### ISSUE TITLE
Dataset request: <Channel estimation and Direction of Arrival estimation in massive MIMO>

### ISSUE THREAD

**Issue by sneha06081993** [datagovsg/datagovsg-datasets#306]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

output  | channel coefficients| input|arrival angle|noise
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am in need of channel estimation data and DOA data set for training my neural network. 

1. First, we need to identify a channel model and identify the equation to generate it. Use a path loss model to and calculate the gain (NOT in dB). Then generate random complex numbers with variance unity and multiply with the gain generated for each path to obtain the complex gain coefficients. Then generate theta from a uniform distribution (-90 to 90). generate channel. This can be done in two way. either fix complex gain coefficients and vary theta. or vary both. 
2. Then generate test  signal x (can be any bpsk (+1 or -1), ) better to choose unit test signal
3. Then find the output .
4.To be specific, every time, once a transmitted signal vector is added in the channel, the corresponding y is obtained in a special direction. Based on this manner, the received signals can be obtained in all direction.  Generate theta as in step-1 and calculate the output y for all theta. Then give y as the input to DNN and set original known theta as the target and train the DNN.

**Comment by lennardl** [comment]
@sneha06081993 Could you help us expand on the acronyms (MIMO and DOA) to help us better figure who we need to approach for the data?
