### ISSUE TITLE
Dataset request: Dengue cluster locations (historical)

### ISSUE THREAD

**Issue by prusswan** [datagovsg/datagovsg-datasets#307]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Dengue clusters by date (Historical data)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
NEA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Same as the existing dengue cluster dataset on NEA's site, but searchable by date

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Study historical trends of dengue clusters

**Comment by lennardl** [comment]
@prusswan We currently do not keep the historical records of the dengue clusters. We will have to approach NEA for this.
