### ISSUE TITLE
Dataset request: Addition of Postal Code to existing dataset (HDB Property Information)

### ISSUE THREAD

**Issue by morbidintel** [datagovsg/datagovsg-datasets#308]
### Please provide the name of the dataset or describe the dataset that you're requesting:
https://data.gov.sg/dataset/hdb-property-information

### Do you know which agency provides/can provide this data?
HDB, Singpost

### If there's an issue with a dataset, please provide a description of the problem
Data does not include postal code, therefore there are issues accurately dynamically positioning and overlaying blocks over a map.

### Please provide the fields expected in this dataset:
blk_no|street|postal_code
-|-|-
9A|BOON TIONG RD|162009
9B|BOON TIONG RD|163009
9C|BOON TIONG RD|164009

### How frequently would you need this dataset to be updated?
- [x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Show all the HDB blocks over a map (e.g. Google Maps, OneMap.sg). Having postal code as a search parameter would return more accurate results from aforementioned APIs.

**Comment by lennardl** [comment]
@morbidintel Unfortunately postal code information is owned by SingPost and we are not able to get and make the data available on data.gov.sg

**Comment by lennardl** [comment]
@morbidintel Thanks for sharing but we are not able to host the data on the postal codes. I would suggest sharing the code on your scraper so others might benefit.
