### ISSUE TITLE
Dataset request: General Transit Feed Specification (GTFS, GTFS-RT)

### ISSUE THREAD

**Issue by ywnch** [datagovsg/datagovsg-datasets#309]
### Please provide the name of the dataset or describe the dataset that you're requesting:

For bus and rail services:
- General Transit Feed Specification (GTFS)
- General Transit Feed Specification Realtime (GTFS-RT)

Thus, ideally, 4 sets of data. Most likely, requesting for bus GTFS at least.

### Do you know which agency provides/can provide this data?

LTA would most likely have these datasets, if they ever exist.

### If there's an issue with a dataset, please provide a description of the problem

n/a

### Please provide the fields expected in this dataset:

- [GTFS Data Specification](http://gtfs.org/reference)
- [GTFS Data Specification](http://gtfs.org/realtime)
- [GTFS Real-world Examples](http://transitfeeds.com/p/king-county-metro)

### How frequently would you need this dataset to be updated?

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time
- [x] Whenever there is a change (e.g., stop location, bus rerouting, frequency adjustment)

### Can you give a short explanation on how you're planning to use this dataset?

Analyze scheduled transportation services. GTFS has become a common open data across cities around the world. Providing this dataset officially would facilitate consistent and accurate application, research and analysis.

**Comment by lihweilihwei** [comment]
@ywnch While an official GTFS is unavailable for Singapore, @yinshanyang made one himself ([github repo](https://github.com/yinshanyang/singapore-gtfs)). Much respect for the effort!

**Comment by ywnch** [comment]
@lihweilihwei Thanks for the reply! Yes, I am aware of @yinshanyang 's work. Would also like to point the community in search of relevant data to the [busrouter repo](https://github.com/cheeaun/busrouter-sg) by @cheeaun. Though not in GTFS format, it contains relevant data that is updated periodically and may potentially be helpful. Hopefully, please keep us posted if an officially maintained version finally shows up!

**Comment by karrkh** [comment]
Interested in this dataset from the official agency.
Looking at possibility of using this dataset, and fusion with other situational traffic datasets for route optimization analysis.
Any possibility of this request to be accepted by the relevant agency? @lennardl

**Comment by lennardl** [comment]
@ywnch I've approached LTA to see if the data can be made available.
