### ISSUE TITLE
Dataset request: <Senior Citizen Transportation, Medical, Activities in 2015 to 2017>

### ISSUE THREAD

**Issue by ivanlow85** [datagovsg/datagovsg-datasets#31]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Statistic for Senior Citizen in 2015 to 2017 includes the Public Transportation, Medical Facilities and Activity centers.
1. Public transports are defined by the Public Buses and Public Trains. 
2. Medical Facilities will be refer to only the Government Hospitals and Polyclinic. 
3. Activity Centers will be the Community Centers, NParks and any Activity Corners.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
http://www.singstat.gov.sg
https://data.gov.sg

### If there's an issue with a dataset, please provide a description of the problem
I could not find dataset that are required mentioned above 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

year | country | male | female | subzone| zone
------|---------|-------------
2017|Singapore|11000|10200 |ang mo kio|north

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
This dataset is for my school assignment

**Comment by iewil** [comment]
@ivanlow85 the data that you are requesting for seems to be a combination of multiple datasets. For instance, historical information on population by geography can be found [here ](https://data.gov.sg/search?q=Singapore+Residents+by+Subzone+and+Type+of+Dwelling&res_format=KML). Other information such as medical facilities and activity centres can be retrieved from OneMap.

**Comment by ivanlow85** [comment]
Hi,

Thanks for the links provided. I have found Table 146 Resident Working
Persons Aged 15 Years and Over by Planning Area and Usual Mode of Transport
to Work. Currently im looking for the number of public transport within the
subzone instead of planning area. As for the subzone, i would want the
subzone to based Geographic Distribution/General Household Survey 2015/Table
7 Resident Population by Planning Area/Subzone, Age Group and Sex to define
the number for Mode of Ransport to work. Would you able to assist on this?
Thanks.

Regards,
Ivan

**Comment by iewil** [comment]
@ivanlow85 it looks like you're asking for a breakdown by age group and gender. These datasets seems to look like what you're asking for:
https://data.gov.sg/dataset/singapore-residents-by-subzone-age-group-and-sex-june-2016-male
https://data.gov.sg/dataset/singapore-residents-by-subzone-age-group-and-sex-june-2016-female

You can also download the full list of datasets [here](https://data.gov.sg/dataset/dataset-listing) to check what data is available on the site.

**Comment by ivanlow85** [comment]
Hi Liwei,

Sorry maybe i didnt describe to you clear.  I'm looking for the number of
public transport within the subzone,Planning Area/Subzone and the umber for
Mode of Transport to work. I will also need to be able to download as CVS
or XLSX format. I have the sample dataset format as attach above, i will
just need the values in the sample dataset. Pls have a look. Thank you

**Comment by ivanlow85** [comment]
Hi Liwei,

Sorry to add on, are you able to provide the longitude and latitude of the planning area and subzone? Thanks. 

Sent from Mail for Windows 10

**Comment by ivanlow85** [comment]
Hi Liwei,

Is there any updates? As i need the dataset urgently, do let me know
whether you are able to provide it. Thanks

**Comment by iewil** [comment]
@ivanlow85 We won't be able to provide you the final dataset as you've requested. 

The data you are requesting for is already available online, and you can merge them to form the final dataset that you have requested for. Due to the broad range of possible applications each dataset can take, we try to keep our datasets generic so that each file remains simple to understand for our users, while ensuring that it can be easily combined with other datasets should the use case requires. 

Data preparation is a big part of any analysis, and I hope that you will understand why our datasets are structured the way they are. Thank you for understanding.
