### ISSUE TITLE
Request for Daily Rainfall at Sentosa from 2016 to now

### ISSUE THREAD

**Issue by pamelalow** [datagovsg/datagovsg-datasets#310]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Daily Rainfall at Sentosa Island from 2016 to now

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

NEA or Meteorological Service Singapore (data incomplete on website)

### If there's an issue with a dataset, please provide a description of the problem

Data here http://www.weather.gov.sg/climate-historical-daily/ is incomplete 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

year | month | day | rainfalll

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [x ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

Analyse impact of rainfall on visitorship to Sentosa

**Comment by lennardl** [comment]
Hi @pamelalow, You can get the daily rainfall for Sentosa from this dataset https://data.gov.sg/dataset/realtime-weather-readings?resource_id=8bd37e06-cdd7-4ca4-9ad8-5754eb70a33d. We do not support querying date range querying at the moment.

**Comment by pamelalow** [comment]
Hey thank u! However, the data points are insufficient for my analysis. The data here is incomplete, else it would be ideal http://www.weather.gov.sg/climate-historical-daily/

**Comment by lennardl** [comment]
@pamelalow Our data comes from NEA and weather.gov.sg is owned by them. So our data points will likely be similar.

**Comment by pamelalow** [comment]
Thanks, hence the data is incomplete?
