### ISSUE TITLE
Dataset request: <CEA Salesperson Information>

### ISSUE THREAD

**Issue by ace108** [datagovsg/datagovsg-datasets#313]
### Please provide the name of the dataset or describe the dataset that you're requesting:
CEA Salesperson   

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
CEA

### If there's an issue with a dataset, please provide a description of the problem
Unable to access it.. Used to be able to do so at: https://data.gov.sg/dataset/cea-salesperson-info
--

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I was using it for a class assignment in Singapore Polytechnic for my Data Science class before and want to update the data.

**Comment by lennardl** [comment]
The data has been restored.
