### ISSUE TITLE
Dataset request: (Median/Mean) Graduate salaries from 1994-2017 

### ISSUE THREAD

**Issue by Eyerald** [datagovsg/datagovsg-datasets#314]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Education, Autonomous Universities

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To find out how graduates' ability to purchase assets (such as car, property), have changed over time

**Comment by lennardl** [comment]
We do not have that data broken down by graduates and non-graduates
