### ISSUE TITLE
Dataset request: Tourist and Singaporean information 

### ISSUE THREAD

**Issue by Jrzkai** [datagovsg/datagovsg-datasets#315]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [x ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ x] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I'm a student in Temasek Polytechnic. Currently, having a competition and wish to have the data. Of course if is free.

**Comment by lennardl** [comment]
@Jrzkai can you let us know what sort of data you would like to have?

**Comment by Jrzkai** [comment]
> @Jrzkai can you let us know what sort of data you would like to have?

Tourist information (gender, date of visit, days of the visit, the reason of visit, age group, status) and Singaporean information (gender, age group, status). Is it possible

**Comment by Jrzkai** [comment]
@lennardl 
hello???

**Comment by Jrzkai** [comment]
@lennardl
Do you have any idea to get the data.

**Comment by lennardl** [comment]
@Jrzkai The tourist information would be kept by ICA/STB and the Singapore information you are requesting would come from different government agencies like ICA and Department of Statistics. 

Some of the data fields being requested might not be released that quickly. I would recommend heading over to https://www.singstat.gov.sg/ to see if there's any readily available data which you could use.

**Comment by Jrzkai** [comment]
@lennardl 
thank u very much
