### ISSUE TITLE
Dataset request: Number of transactions per property agent

### ISSUE THREAD

**Issue by premhiru** [datagovsg/datagovsg-datasets#316]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Number of property transactions (bought/sold) each licensed property agent has conducted over past 10 years

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:

id | estate_agent_license_no | estate_agent_name | registration_end_date | registration_no | registration_start_date | salesperson_name|Transaction ID|Transaction Type|Address|Days on Market

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Developing model to determine if agents impact days on market

**Comment by lennardl** [comment]
We do not have that data
