### ISSUE TITLE
Dataset request: ARCA SSIC entities

### ISSUE THREAD

**Issue by freddieang** [datagovsg/datagovsg-datasets#318]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Entities SSIC Code

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
ACRA

### If there's an issue with a dataset, please provide a description of the problem
Nil

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

uen | entity name | Primary SSIC Code | Secondary SSIC Code
12345678A | 123 ABC Company | 46099 | 62099

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To complete the "entities-with-unique-entity-number" data set by including the industry type of each entity.

**Comment by freddieang** [comment]
Thanks in advance for the help.

**Comment by lennardl** [comment]
@freddieang the SSIC is available on the dataset https://data.gov.sg/dataset/acra-information-on-corporate-entities. We are in the process of getting an update to the data.

**Comment by johnqwerty1** [comment]
May I know when will the update happen as it has been more than a year and the more regularly updated subset has been removed. Thanks!

**Comment by freddieang** [comment]
Hi,

The output file for “Entities Registered with ACRA” in .CSV format has exceeded the number of rows in Excel spreadsheet.

May I ask could we have the output file in .txt format, or alternatively, have the ”uen_status” to show only “R = Registered”.

Thank you

Regards
Freddie Ang
________________________________
