### ISSUE TITLE
Requesting for ACRA's data for easy KYC on a professional dashboard.

### ISSUE THREAD

**Issue by cherilyntan** [datagovsg/datagovsg-datasets#32]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Registered Entities with Unique Entity Number

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Accounting and Corporate Regulatory Authority

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

uen | uen_status | entity_name | entity_type | uen_issue_date | reg_street_name | reg_postal_code

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [X] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
We are planning to help professional firms such as Accountants, Lawyers and Consultants do their due diligence faster to ensure better KYC.

**Comment by LoneRifle** [comment]
Hey @cherilyntan - is this what you're looking for?

https://data.gov.sg/dataset/entities-with-unique-entity-number

**Comment by iewil** [comment]
Thanks @LoneRifle. @cherilyntan I'm closing this case if there isn't anything else.

**Comment by cherilyntan** [comment]
Thank you! Very helpful!

**Comment by LoneRifle** [comment]
Closing after discussion through private channels.
