### ISSUE TITLE
Dataset request: Weather and temperature forecast-area based API

### ISSUE THREAD

**Issue by mahadeer2008** [datagovsg/datagovsg-datasets#320]
### Do you know which agency provides/can provide this data?
NEA
*( Refer to this link for a full list of agencies: https://data.gov.sg/dataset/weather-forecast?view_id=9bfd2345-62ed-491d-ba2c-940b3eaee39c&resource_id=571ef5fb-ed31-48b2-85c9-61677de42ca9 )*

### If there's an issue with a dataset, please provide a description of the problem
Under 2 hour weather forecast, district based weather data is available but not temperature data. I would need an API which displays both the weather and temperature based on districts.

### Please provide the fields expected in this dataset:

Weather| Temperature| District

### How frequently would you need this dataset to be updated?

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [X ] Hourly
- [X ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am an mobile developer. My current project requires an API for both weather and temperature forecast.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/realtime-weather-readings
