### ISSUE TITLE
Dataset request: dengue dataset

### ISSUE THREAD

**Issue by abhinit** [datagovsg/datagovsg-datasets#322]
### Please provide the name of the dataset or describe the dataset that you're requesting:

I need access to the dengue dataset

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

https://data.gov.sg/group/health

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

All the fields

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [X] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

I wish to analyze the irregularities in the data and see whether the usability of models across years is possible. Also, is it possible to carry out transfer learning using models which are trained on old data.

**Comment by lennardl** [comment]
@abhinit The dataset was recently updated, hopefully it helps.
