### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by Joelim3212** [datagovsg/datagovsg-datasets#325]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [x ] Annually
- [x] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
project

**Comment by lennardl** [comment]
@Joelim3212, we need more details on what data is required.
