### ISSUE TITLE
Listing of Registered Renovation Contractors

### ISSUE THREAD

**Issue by ace108** [datagovsg/datagovsg-datasets#326]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Listing of Registered Renovation Contractors

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
HDB
https://www20.hdb.gov.sg/bn25/isos118p.nsf/List+by+Company?OpenView&Count=15&Start=1&RestrictToCategory=A#

### If there's an issue with a dataset, please provide a description of the problem
Inconsistent data. For example in data.gov.sg https://data.gov.sg/dataset/listing-of-registered-renovation-contractors , the count is shown as 1,534 records. However, the CSV download from https://data.gov.sg/dataset/e6204ae2-a07f-4fbb-a09b-5149f23e9955/downloaded has 2034 rows.
In the HDB page, I could see company "LIAN KEH HUAT RENOVATION CONTRACTOR" but in the data.gov.sg page, this compamny is missing.

### How frequently would you need this dataset to be updated?
- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Looking for contractors and their location.

**Comment by lennardl** [comment]
We have approached the relevant organisations to update the data.
