### ISSUE TITLE
Dataset request: <Solid Waste Management - Total Waste Generated by Waste Type>

### ISSUE THREAD

**Issue by HuDaNiNja** [datagovsg/datagovsg-datasets#328]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Solid Waste Management - Total Waste Generated by Waste Type

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
I think it would be the National Environment Agency.

### If there's an issue with a dataset, please provide a description of the problem
Simply looking for a more detailed data set of the following: https://data.gov.sg/dataset/solid-waste-management-total-waste-generated

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
year | total waste generated (million tonnes) | waste type

------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
This is a one time request.

### Can you give a short explanation on how you're planning to use this dataset?
I am simply aiming to produce a clean visualization. The visualization would be used in a proposal for a potential business opportunity.

**Comment by lennardl** [comment]
Data is limited to what is available on the dataset
