### ISSUE TITLE
Dataset request: <weather dataset>

### ISSUE THREAD

**Issue by bhavanakannoju** [datagovsg/datagovsg-datasets#329]
### Please provide the name of the dataset or describe the dataset that you're requesting:
weather data like min max temperature,rain fall,humidity,precipitation,wind(dataset with all these attributes)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
2012-17|singapore|
month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
-[  ] weekly 
Example: 

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Im developing dengue prediction model as my mtech major project. So to develop that i need data set

**Comment by lennardl** [comment]
@bhavanakannoju would the following datasets be sufficient?
https://data.gov.sg/dataset/realtime-weather-readings
https://data.gov.sg/dataset/relative-humidity-monthly-mean
https://data.gov.sg/dataset/surface-air-temperature-monthly-mean
https://data.gov.sg/dataset/rainfall-monthly-total
https://data.gov.sg/dataset/relative-humidity-monthly-mean

**Comment by bhavanakannoju** [comment]
thanks a lot, i will check out
