### ISSUE TITLE
Dataset request: <dengue clusters file(shp or xml)>

### ISSUE THREAD

**Issue by lllena731** [datagovsg/datagovsg-datasets#33]
### Please provide the name of the dataset or describe the dataset that you're requesting:
dengue clusters datasets

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
NEA or Ministry of Health 

### If there's an issue with a dataset, please provide a description of the problem
only 14 latest dengue cluster data are online available.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
At least 1 year historic dataset starting from 2011.3 to present | Singapore

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [ ] Annually
- [x] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by iewil** [comment]
@lllena731 I've forwarded your request to our colleagues at NEA for their help.

**Comment by zhenyuan992** [comment]
Hi,
any updates on this dataset? i am also interested in the historical (since 2015) weekly dataset of dengue clusters and dengue cases.
