### ISSUE TITLE
Dataset request: longitude and latitude coordinate of singapore planning area/ region

### ISSUE THREAD

**Issue by aeiyuni** [datagovsg/datagovsg-datasets#331]
### Please provide the name of the dataset or describe the dataset that you're requesting:
longitude and latitude coordinate of singapore planning area/ region

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
similar to data.gov.sg but instead of X AND Y address, i need it in long and lat. 

### Please provide the fields expected in this dataset:
Singapore

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by aeiyuni** [comment]
yes it does!thank you. 

Does data.gov has a a list of postal code that corresponds to the 55 planning area in Singapore?
This is for geospatila analysis..

**Comment by lennardl** [comment]
@aeiyuni Unfortunately not, the postal code data belong to SingPost (private corporation).
