### ISSUE TITLE
Dataset request: Daily maximum temperature measurements from 2012 to 2017.

### ISSUE THREAD

**Issue by kokpingteo** [datagovsg/datagovsg-datasets#334]
### Please provide the name of the dataset or describe the dataset that you're requesting:
i would like to request for the daily maximum temperature measurement from 2012 to 2017.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
NEA?

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

date | day | week | max_temperature
------|---------|-------------|--------
2018-01-08|Tue|Week 2|30
2018-01-09|Wed|Week 2|32
2018-01-10|Thu|Week 2|35

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annualy
- [ ] Monthly
- [ ] Weekly
- [ x] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

i would like to study the relationship between temperature for a period and compare it to the infectious disease data.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/surface-air-temperature-mean-daily-maximum
