### ISSUE TITLE
Dataset request: Traffic data

### ISSUE THREAD

**Issue by ygjihye** [datagovsg/datagovsg-datasets#335]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Carpark Availability
Traffic News 
Traffic Cameras

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Land Transport Authority

### If there's an issue with a dataset, please provide a description of the problem
How do i use the dataset with Python 3.6?
Able to give codes to do display the codes in Python and on HTML?

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [X] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I'm planning to use it for my school project module, and I need it ASAP. Thank you!

**Comment by lennardl** [comment]
@ygjihye 
Carpark Availability: https://data.gov.sg/dataset/carpark-availability
Multiple feeds for the different traffic cameras: https://data.gov.sg/search?q=Traffic+Cameras

In terms of traffic news, could you give an example of the traffic news you are looking for?
