### ISSUE TITLE
Dataset request: Government Procurement via GeBiz

### ISSUE THREAD

**Issue by KelvinKoh95** [datagovsg/datagovsg-datasets#336]
### Please provide the name of the dataset or describe the dataset that you're requesting:
 
Government Procurement via Gebiz
https://data.gov.sg/dataset/government-procurement?resource_id=b9d8d509-5cb6-45dc-bb46-9508e670e3c2

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Finance

### If there's an issue with a dataset, please provide a description of the problem

Is it possible to add the GRA supply/workhead requirements for past listings?
Is it possible to include procurement info from before January 2015? 

Also the awarded amount for tender no. SPC000ETT17000021 seems to be erroneous. It says that 40 billion dollars has been awarded for supply and delivery of apparel for 24 months, which is the highest amount awarded in the list. 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [x ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

For research purposes.

**Comment by lennardl** [comment]
@KelvinKoh95 we have approached the relevant agency to request for the data. We will update the ticket again once we get a response.
