### ISSUE TITLE
Dataset request: Height and Weight Chart 0-6yrs old

### ISSUE THREAD

**Issue by jacphua** [datagovsg/datagovsg-datasets#337]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I would like to request for the data below to be provided as statistics instead of PDF format, if possible:
https://www.nhgp.com.sg/uploadedFiles/Our_Services/General_Medical_Services/HEIGHT%20CHART%20FOR%20GIRLS.pdf
https://www.nhgp.com.sg/uploadedFiles/Our_Services/General_Medical_Services/WEIGHT%20CHART%20FOR%20GIRLS.pdf
https://www.nhgp.com.sg/uploadedFiles/Our_Services/General_Medical_Services/WEIGHT%20CHART%20FOR%20BOYS.pdf
https://www.nhgp.com.sg/uploadedFiles/Our_Services/General_Medical_Services/HEIGHT%20CHART%20FOR%20BOYS.pdf

### Do you know which agency provides/can provide this data?
https://data.gov.sg/organization/health-promotion-board
https://data.gov.sg/organization/ministry-of-health

### If there's an issue with a dataset, please provide a description of the problem
N/A

### Please provide the fields expected in this dataset:

age (in mths) | gender | height (cm) | percentile
------|---------|-------------
6|boy|60|3

### How frequently would you need this dataset to be updated?
- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Planning to use this as a online tool for parents

**Comment by lennardl** [comment]
We do not have that data
