### ISSUE TITLE
Dataset request: <PUB Water Distribution Network Data >

### ISSUE THREAD

**Issue by crixus5678** [datagovsg/datagovsg-datasets#338]
### Please provide the name of the dataset or describe the dataset that you're requesting:
**I would like to request for the water distribution network data collected by PUB which include but not limited to pressure, waterflow, acoustic and etc. If possible all data collected would be great so that I can do my research on reliable water leakage detection** 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

**Month | Date | Time | Pressure | Water Flow
Jan| 22| 18:00| 12 | 132**

### How frequently would you need this dataset to be updated? **It would be great if I can have a year worth of data for testing of reliable leak detection**
Example: 
- [X] *Test*

- **[X] Annually**
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by crixus5678** [comment]
so now I just wait for PUB to make a reply?

**Comment by lennardl** [comment]
@crixus5678 We are asking PUB if the data is readily available. They may or may not have the data thats sharable.

**Comment by crixus5678** [comment]
@lennardl I'm wondering if there is any update for this?
