### ISSUE TITLE
Dataset request: <Fuel Consumption>

### ISSUE THREAD

**Issue by Prof-MohamedAtef** [datagovsg/datagovsg-datasets#339]
### Such dataset can be found in any organizations registering their consumed fuel rates per day, specially if they work on freight forwarding and shipment.
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )

### Fields expected in this dataset:

day| vehicle_type | number_of_trips | fixed_trips_distance | redundant_trips_distance | iterated_trips | daily_fuel_budget_in_US_Dollar
------|---------|-------------

### I recommend this dataset to be updated regularly on a daily basis?
Example: 

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] *Daily*
- [ ] Hourly
- [ ] Real-time

**Comment by lihweilihwei** [comment]
@Prof-MohamedAtef This is useful for my research too!

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/monthly-motor-vehicle-population-by-type-of-fuel-used
