### ISSUE TITLE
Missing companies from ACRA entities-with-unique-entity-number

### ISSUE THREAD

**Issue by skenaja** [datagovsg/datagovsg-datasets#340]
### Please provide the name of the dataset or describe the dataset that you're requesting:
https://data.gov.sg/dataset/entities-with-unique-entity-number

### Do you know which agency provides/can provide this data?
ACRA

### If there's an issue with a dataset, please provide a description of the problem

It appears as though there are companies missing from the latest 16 January 2019 dataset (which has resumed being updated on data.gov.sg after it stopped in August 2018). 

There is a significant decrease in the apparent number of new companies incorporated between Aug 2018 and Dec 2018 in comparison to previous months (average expected is [around 5,000 each month](https://data.gov.sg/dataset/formation-of-all-business-entities-by-type-monthly)).

```
2018-06 | 5134
2018-07 | 5558
2018-08 | 3980
2018-09 | 75
2018-10 | 71
2018-11 | 82
2018-12 | 1305
2019-01 | 1566
```

An example of a missing company from the file which can be found at https://www.uen.gov.sg is "BAR-BEQUE PTE. LTD" (UEN 201830828R). 

This link confirms that it's missing from [entities-with-unique-entity-number](https://data.gov.sg/api/action/datastore_search?resource_id=bdb377b8-096f-4f86-9c4f-85bad80ef93c&q=201830828R)

Is there a reason as to why this large gap has occurred?

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

n/a

### How frequently would you need this dataset to be updated?

n/a

### Can you give a short explanation on how you're planning to use this dataset?

n/a

**Comment by lennardl** [comment]
@skenaja We have an ongoing issue with ARCA in getting the data. We would ask if you cancan get the data from ARCA directly till the matter is resolved?

**Comment by skenaja** [comment]
@lennardl - Thanks for the update. For info, this was the reply from ACRA when I got in touch directly back in November (covering both `entities-with-unique-entity-number` and `acra-information-on-corporate-entities`):

> ACRA has provided the data to the team from data.gov.sg on monthly basis. However, we understood the team may have faced some issues on their end. We are trying to understand further from the team as well.
> In the mean time, you may wish to contact the support team directly at feedback@data.gov.sg

Are you able to provide the data by alternative means?

**Comment by jaspersorrio** [comment]
Hi all,

I'm Jasper from Eezee Pte Ltd and we too are relying on this set of data for our company name autocompleter.

Looks like all companies starting with the letter A and B are missing..

The previous dataset page now redirects to a 404 error.

https://data.gov.sg/dataset/acra-information-on-corporate-entities?resource_id=9458197b-4b46-480e-a596-34dbff26d8dc

**Comment by lennardl** [comment]
@jaspersorrio ACRA has changed the format of their dataset, it can be found here: https://data.gov.sg/dataset/acra-information-on-corporate-entities1

**Comment by xkawi** [comment]
hi guys, I am also currently looking into this dataset as well. Reading from the comments above, does that mean the data set won't be updated in real time? If it is not, is there a way to get this real time data? or we must talk to ACRA?

**Comment by lennardl** [comment]
@xkawi If you need it realtime it might be better to talk to ACRA directly if you need it urgently. We have recommended to ACRA that the data should be updated on a regular basis.

**Comment by xkawi** [comment]
@lennardl thanks for the reply. Contacted ACRA about it, they directed me to their API Mall - https://www.apimall.acra.gov.sg/#/api-products in case others find it useful.
