### ISSUE TITLE
Dataset request: Origin Destination passenger volume

### ISSUE THREAD

**Issue by Faelledparken** [datagovsg/datagovsg-datasets#341]
### Please provide the name of the dataset or describe the dataset that you're requesting:

- Passenger Volume by Origin Destination Bus Stops

- Passenger Volume by Origin Destination Train Stations

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

- Land Transport Authority

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

transport | month | country | passengers | origin | destination
------|---------|-----------|--------|--------|--------
MRT|2017-09|Singapore|10000|Orchard|Raffle's Place

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

For research purposes on how the first-mile/last-mile commuting could be improved through the evidence of current mass transit flows.

**Comment by Faelledparken** [comment]
Hi @lennardl any news on this one? :)

**Comment by lihweilihwei** [comment]
@Faelledparken This is already in the DataMall API by LTA ([documentation](https://www.mytransport.sg/content/dam/datamall/datasets/LTA_DataMall_API_User_Guide.pdf])). See Annex B in the document for an example of the data.
