### ISSUE TITLE
Dataset request: MP08 Mapsheet Minor Road Name

### ISSUE THREAD

**Issue by SoniaAgnihotri** [datagovsg/datagovsg-datasets#343]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Minor and Major Road Network

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Urban Redevelopment Authority

### If there's an issue with a dataset, please provide a description of the problem
The dataset available is empty.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To perform network analysis

**Comment by lennardl** [comment]
@SoniaAgnihotri We have approached URA before. The map is no longer supported by them. Do you need road names or just the road network shape?

**Comment by SoniaAgnihotri** [comment]
Actually, I need both road network shapes and names. But for now major and minor road network shapes will be sufficient. 
Thanks!

**Comment by lennardl** [comment]
The road line section here might help: https://www.mytransport.sg/content/dam/datamall/datasets/Geospatial/RoadSectionLine.zip
