### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by syahirsahtarry** [datagovsg/datagovsg-datasets#344]
### Please provide the name of the dataset or describe the dataset that you're requesting:
- number of JC students withdraw from school
- number of Poly students withdraw from school
- number of poly students admitted to local universities and graduated with first-class honor
- number of JC students admitted to local universities and graduated with first-class honor

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [x] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
for school projects

**Comment by lennardl** [comment]
@syahirsahtarry We have approached MOE to request for the data.

**Comment by syahirsahtarry** [comment]
Noted. Thanks

**Comment by lennardl** [comment]
The enrollment data can be found here but we do not have withdrawal data
https://data.gov.sg/search?q=enrollement
