### ISSUE TITLE
Dataset request: Spatial format for route to take between each bus stop for bus services in Singapore

### ISSUE THREAD

**Issue by weicong96** [datagovsg/datagovsg-datasets#345]
### Please provide the name of the dataset or describe the dataset that you're requesting:
- Coordinates for bus routes in Singapore snapped to road. In loop services, lines should not overlap

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
- Land Transport Authority

### If there's an issue with a dataset, please provide a description of the problem
- OneMap.sg provides this data but loop service coordinates overlaps across the same road

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

bus | stopIndex | geometry|
------|---------|-----------|
177| 1|(any geospatial format)|

### How frequently would you need this dataset to be updated?
- [ ] Annually
- [ ] Monthly
- [x] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For research into bus services in Singapore

**Comment by lennardl** [comment]
@weicong96 We have approached the relevant agency to request for the data

**Comment by lennardl** [comment]
We do not have the data
