### ISSUE TITLE
Statistics on Singapore nurses turnover (turnover intentions or actual turnover included)

### ISSUE THREAD

**Issue by WeenahA** [datagovsg/datagovsg-datasets#346]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Unsure

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For dissertation purposes

**Comment by lennardl** [comment]
We do not have the data
