### ISSUE TITLE
Dataset request: Postal Code Based on Constituencies 

### ISSUE THREAD

**Issue by veljanelle** [datagovsg/datagovsg-datasets#347]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Postal code range based on the individual GRCs & SMCs  

### Do you know which agency provides/can provide this data?
Prime Minister Office, Singpost, Elections Department

### Please provide the fields expected in this dataset:

Example of data required: 

Postal Code Range | Constituency  
680111-680666 | Chua Chu Kang Group Representation Constituency 
669237-669449 | East Coast Group Representation Constituency 

### How frequently would you need this dataset to be updated?

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Search for the respective GRC/SMC based on location. Require this data to know which postal code falls under which constituency in Singapore.

**Comment by lennardl** [comment]
@veljanelle Postal code data is owned by SingPost, you will need to approach them for the data.

**Comment by veljanelle** [comment]
Are they able to provide us based on the GRC/SMC

**Comment by lennardl** [comment]
@veljanelle We have the last election boundary https://data.gov.sg/dataset/electoral-boundary-2015. If you do have the postal code, you would have to map it over this layer.

I'm not certain if SingPost has the postal codes mapped by GRC/SMC.
