### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by zhuangyingmok** [datagovsg/datagovsg-datasets#348]
### Do you know which agency provides/can provide this data?
HDB

*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

Dissertation report studying on alternative uses of HDB CP in light of car lite movement

**Comment by lennardl** [comment]
@zhuangyingmok Would this work? https://data.gov.sg/dataset/carpark-availability if you map the availability over the location you would get how often car parks are being used?

**Comment by lennardl** [comment]
@zhuangyingmok Hi, unfortunately we do not have that data.
