### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by momoshiki-otsutsuki** [datagovsg/datagovsg-datasets#351]
### Please provide the name of the dataset or describe the dataset that you're requesting:
ACRA Information on Corporate Entities

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### If there's an issue with a dataset, please provide a description of the problem
It is not having company director details.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

issuance_agency_id | uen | entity_name | entity_type_description | business_constitution_description | company_type_description | paf_constitution_description | entity_status_description | registration_incorporation_date | uen_issue_date | address_type | block | street_name | level_no | unit_no | building_name | postal_code | other_address_line1 | other_address_line2 | account_due_date | annual_return_date | no_of_charges | primary_ssic_code | primary_ssic_description | primary_user_described_activity | secondary_ssic_code | secondary_ssic_description | secondary_user_described_activity | no_of_officers | former_entity_name1 | former_entity_name2 | former_entity_name3 | former_entity_name4 | former_entity_name5 | former_entity_name6 | former_entity_name7 | former_entity_name8 | former_entity_name9 | former_entity_name10 | former_entity_name11 | former_entity_name12 | former_entity_name13 | former_entity_name14 | former_entity_name15 | paid_up_capital1_currency | paid_up_capital1_ordinary | paid_up_capital1_preference | paid_up_capital1_others | paid_up_capital2_currency | paid_up_capital2_ordinary | paid_up_capital2_preference | paid_up_capital2_others | paid_up_capital3_currency | paid_up_capital3_ordinary | paid_up_capital3_preference | paid_up_capital3_others | paid_up_capital4_currency | paid_up_capital4_ordinary | paid_up_capital4_preference | paid_up_capital4_others | paid_up_capital5_currency | paid_up_capital5_ordinary | paid_up_capital5_preference | paid_up_capital5_others | paid_up_capital6_currency | paid_up_capital6_ordinary | paid_up_capital6_preference | paid_up_capital6_others | paid_up_capital7_currency | paid_up_capital7_ordinary | paid_up_capital7_preference | paid_up_capital7_others | paid_up_capital8_currency | paid_up_capital8_ordinary | paid_up_capital8_preference | paid_up_capital8_others | paid_up_capital9_currency | paid_up_capital9_ordinary | paid_up_capital9_preference | paid_up_capital9_others | paid_up_capital10_currency | paid_up_capital10_ordinary | paid_up_capital10_preference | paid_up_capital10_others | uen_of_audit_firm1 | name_of_audit_firm1 | uen_of_audit_firm2 | name_of_audit_firm2 | uen_of_audit_firm3 | name_of_audit_firm3 | uen_of_audit_firm4 | name_of_audit_firm4 | uen_of_audit_firm5 | name_of_audit_firm5

Along with this, the company director details.

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

For tracking progress of corporate entities

**Comment by lennardl** [comment]
@momoshiki-otsutsuki Please approach ARCA for this data as the data we have is outdated for now.
