### ISSUE TITLE
Dataset request: driving-licence-information-qualified-driving-licence-holders

### ISSUE THREAD

**Issue by Chewondis** [datagovsg/datagovsg-datasets#352]
Hi previous there was a data set available but it now shows a 404 error. Has this been removed? please let me know if there is an updated data set. Thank youu

https://data.gov.sg/dataset/driving-licence-information-qualified-driving-licence-holders?resource_id=2c9d02bb-d9c3-4659-a86c-ce6d94a208bd

**Comment by lennardl** [comment]
@Chewondis We will check with the relevant agencies and get back to you.
