### ISSUE TITLE
Dataset request: Newborns by Gender

### ISSUE THREAD

**Issue by LakshmanSG** [datagovsg/datagovsg-datasets#354]
Newborns by Gender from 1984 - 2016

https://data.gov.sg

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@LakshmanSG I've checked with the agency, the data for 2018 is not available yet. But we have the data up to Dec 2017 here https://data.gov.sg/dataset/live-births-by-birth-weight-age-group-of-mother-and-child-gender
