### ISSUE TITLE
Dataset request: List of registered Nursing Homes

### ISSUE THREAD

**Issue by inev** [datagovsg/datagovsg-datasets#356]
### Please provide the name of the dataset or describe the dataset that you're requesting:
List of registered Nursing Homes

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
AIC

### Please provide the fields expected in this dataset:

organization_name | locations (all branches) | capacity | private* | number_of_violations **

*If it is a private organization or if its a registered VWO
**If available

### How frequently would you need this dataset to be updated?
Example: 
- [ X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To make it easier for people to search nursing homes and their capacities, this data set can enable consumers to more easily select a suitable nursing home.

**Comment by lennardl** [comment]
@inev Does these datasets fit your requirements? 
https://data.gov.sg/search?q=nursing+homes

**Comment by inev** [comment]
@lennardl I had a look at that data and it does not have any details. Just has aggregate numbers

**Comment by lennardl** [comment]
We do not have breakdowns of the data
