### ISSUE TITLE
Dataset request: Median, 25th and 75th Percentiles of Monthly Basic and Gross Wages of Common Occupations by Industry

### ISSUE THREAD

**Issue by teohzyt** [datagovsg/datagovsg-datasets#357]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Median, 25th and 75th Percentiles of Monthly Basic and Gross Wages of Common Occupations by Industry (https://data.gov.sg/dataset/monthly-basic-and-gross-wages-of-common-occupations-in-all-industries?resource_id=e754e668-d555-4cc2-9830-c1218c087ce6)

The link provides data for 2017. I am looking for the same data ideally from 2000 onwards. So far I have only been able to access data for 2016 and 2017. 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

Ministry of Manpower

### If there's an issue with a dataset, please provide a description of the problem

I have tried to access previous years from the MoM website (https://stats.mom.gov.sg/Pages/Occupational-Wages-Tables2015.aspx) but encounter errors when trying to download the excel. 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Year | Occupation Description | Industry 1 | Monthly gross wage 75 percentile (dollars) | ... 50 percentile | ... 25 percentile | Monthly basic wage 75 percentile (dollars) | ... 50 percentile | ... 25 percentile 

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

I'm a masters student hoping to analyse some trends in changes of wages for my thesis.

**Comment by lennardl** [comment]
https://data.gov.sg/search?q=Monthly+Basic+and+Gross+Wages
