### ISSUE TITLE
Dataset request: <Graduates data by Universty by Course and Program level>

### ISSUE THREAD

**Issue by akritinautiyal** [datagovsg/datagovsg-datasets#359]
### Please provide the name of the dataset or describe the dataset that you're requesting:

We are looking at higher education statistics where we require Graduates data by individual University in Singapore. We are interested in detailed graduates data break up for each individual University/college by Male/Female, by Courses and by Award levels  ( doctorate, masters, bachelor etc).

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
No 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

Annual/Singapore/Graduate by university by course 

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

We are planning to use the data to analyse the graduate supply across Universities.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/universities-intake-enrolment-and-graduates-by-course
