### ISSUE TITLE
Dataset request: <List of companies incorporated under ACRA and its financial statements>

### ISSUE THREAD

**Issue by ivanersl** [datagovsg/datagovsg-datasets#36]
### How frequently would you need this dataset to be updated?
- [ ] Annually
- [ x] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by iewil** [comment]
@ivanersl to get past financial statements, you will have to purchase the data from [ACRA's bizfile](https://www.bizfile.gov.sg/ngbbizfileinternet/faces/oracle/webcenter/portalapp/pages/BizfileHomepage.jspx)
