### ISSUE TITLE
Dataset request: <MRT station>

### ISSUE THREAD

**Issue by yugispidey** [datagovsg/datagovsg-datasets#360]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Request for .shp file for future MRT lines, specifically Downtown Line 3 Extension, North East Line Extension, Circle Line 6, Jurong Region Line, Cross Island Line

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
URA / SMRT

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Shape (to be polygon) | Name of station | X address | Y address | shape length } shape area | type

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am creating a map using ArcGIS to illustrate households that are at least a 10 minute walk away from the nearest MRT / LRT station. In doing so, I can identify residential areas that fall outside this zone, and deduce the best way to increase connectivity island-wide.

**Comment by lennardl** [comment]
We do not have the updated shp files with the newest mrt stations
