### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by kithmik** [datagovsg/datagovsg-datasets#361]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [x] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by Kithmi1995** [comment]
create air pollution monitoring system

**Comment by lennardl** [comment]
@Kithmi1995 Does these datasets help? https://data.gov.sg/search?q=air+pollutant
