### ISSUE TITLE
Dataset request: Motor Vehicle Collision data

### ISSUE THREAD

**Issue by jeremysze** [datagovsg/datagovsg-datasets#363]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Motor Vehicle Collision Data.
This dataset should contain information like date, time, GPS coordinates, address, intersection street names, persons involved( pedestrians, cyclists, motorist, etc), injury severity, number of people injured or killed, vehicle types, and contributing factors.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Home Affairs - Singapore Police Force (Traffic police) 

### Please provide the fields expected in this dataset:
(ID|Date|Time|Address|Cross Street|On Street|GPS Coordinates|Neighbohood name|Number of collisions|Number of persons involved|Number of persons injured|Number of persons killed|Number of pedestrians injured|Number of pedestrians killed|Number of cyclist injured|Number of cyclist killed|Number of motorist injured|Number of motorist killed|Vehicle Types|Contributing Factors
)

### How frequently would you need this dataset to be updated?
- [ ] Annually
- [ X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I would like to examine the effect of introduction of bike sharing in Singapore on motor vehicle collisions. My hypothesis is that with the introduction of bike sharing there might be an increase in vehicle-cyclist collisions due to an increase in number of casual cyclist. Other areas that can be explored are the effect of the new cycling regulations, shared paths, and expansion in PCN.

**Comment by lennardl** [comment]
@jeremysze We have approached SPF, they are not able to share the data.

**Comment by jeremysze** [comment]
Thanks for helping!
