### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by hpliew25** [datagovsg/datagovsg-datasets#364]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I was looking at the data in M651281 - Road Traffic Accident Casualties, Annual.
(https://www.tablebuilder.singstat.gov.sg/publicfacing/createDataTable.action?refId=15159)

As a motorcyclist, I was wondering there are data about the injuries and fatalities where motorcycles are involved. I particular, I am curious about the level of experience of riders involved in the accidents (such as years of riding experience, class of license held), the capacity of the motorcycles, the time of day where accidents occur, and the type of vehicles motorcycle accidents also involved, etc.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

LTA and/or Traffic Police

### If there's an issue with a dataset, please provide a description of the problem
NA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

age of rider | license class (2, 2A, 2B) | riding experience at the time of accident | day or night or time of accident | weather | road condition | engine capacity of motorcycle involved in accident | type of vehicle involved in other accident | type of roads the accident took place (expressway/major thoroughfares / traffic junctions, etc.

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation of how you're planning to use this dataset?

The data would help us understand the various risk factors involved in accidents and would be useful for educational purposes.

**Comment by lennardl** [comment]
@hpliew25 Similar to https://github.com/datagovsg/datagovsg-datasets/issues/363. We have approached SPF for the data but its not available.
