### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by hpliew25** [datagovsg/datagovsg-datasets#365]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I am looking for the break down of the engine capacity and fuel type of each motor vehicle class described in Annual Mileage for Private Motor Vehicles (https://data.gov.sg/dataset/annual-mileage-for-private-motor-vehicles).

motor vehicle classes: Cars, Private Hire Buses, School Buses, Light Goods Vehicle, Heavy Goods Vehicle, Motorcycles

How are the various motor vehicle classes categorized/defined?

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
LTA

### If there's an issue with a dataset, please provide a description of the problem
NA

### Please provide the fields expected in this dataset:
*(e.g. month | country | 

median engine capacity for | maximum allowable pollutant emissions 

How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
This dataset would help us understand the major contributors of pollutants by vehicles, which could help in our efforts in combating climate change.

**Comment by hpliew25** [comment]
hi, in addition, can the number of vehicles in each category also be included in the data, this variable would allow the calculation of the total mileage by vehicles in each category.

**Comment by lennardl** [comment]
We do not have the data
