### ISSUE TITLE
Dataset request: worker training records & Factory Notification or Registration 

### ISSUE THREAD

**Issue by peonmodel** [datagovsg/datagovsg-datasets#368]
### Please provide the name of the dataset or describe the dataset that you're requesting:
worker training records
&
Factory Notification or Registration 

### Do you know which agency provides/can provide this data?
MOM
https://www.mom.gov.sg/workplace-safety-and-health/factory-notification-and-registration/apply-for-notification-or-registration
https://www.mom.gov.sg/eservices/services/check-worker-training-records
MOM already provides this information but under a different API

### Please provide the fields expected in this dataset:
see link provided

### How frequently would you need this dataset to be updated?
- [x] Monthly
MOM updates this with unknown frequency

### Can you give a short explanation on how you're planning to use this dataset?
to check workers record is aligned with the govt's

**Comment by lennardl** [comment]
We do not have the data
