### ISSUE TITLE
Dataset request: <Number of teacher in higher education>

### ISSUE THREAD

**Issue by Katssify** [datagovsg/datagovsg-datasets#369]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )* MOE

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Total number of teachers in higher education 2018/2017

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
https://data.gov.sg/search?q=teachers
