### ISSUE TITLE
Dataset request: List of entities listed with ACRA

### ISSUE THREAD

**Issue by jobchong** [datagovsg/datagovsg-datasets#37]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### If there's an issue with a dataset, please provide a description of the problem

Hi there! Sending a request with urllib2 with a header including an API token from an account registered at https://developers.data.gov.sg/user/register to [this resource](https://data.gov.sg/api/action/datastore_search?q={'entity_name': 'apple'}&resource_id=bdb377b8-096f-4f86-9c4f-85bad80ef93c) now returns a 403 Forbidden.

I have a few questions:
1. Is authentication required?
1b. If so, how should it be done?
2. Why is the requirement for authentication switching on and off every few days? Last week it was working, and the issue was even closed #20, but now instead of 404ing I get the abovementioned 403.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by jobchong** [comment]
When I log in, the datastore 404s now.

**Comment by iewil** [comment]
@jobchong the correct query should be https://data.gov.sg/api/action/datastore_search?resource_id=bdb377b8-096f-4f86-9c4f-85bad80ef93c. You do not need to login to make use of the datastore search.

**Comment by jobchong** [comment]
I used that link, and it still redirects me to the `came_from` link.

**Comment by jobchong** [comment]
It's back up now! I'm really not sure what to make of this intermittent availability. Have you guys figured it out?

**Comment by kllzn** [comment]
Hi. I'm trying to get entity information by requesting https://data.gov.sg/api/action/datastore_search?q=ARMSTRONG%20MOVER&resource_id=50d498c3-5317-4fc5-95e2-a74e8908c7e7
`50d498c3-5317-4fc5-95e2-a74e8908c7e7` - id of dataset `ACRA Information on Corporate Entities ('A')`
But response contains 0 found records. Is it a bug or I missing something?
In the same time I can get this company info by this request https://data.gov.sg/api/action/datastore_search?q=Armstrong&resource_id=bdb377b8-096f-4f86-9c4f-85bad80ef93c&limit=1

**Comment by iewil** [comment]
@kllzn Only endpoints found on developers.data.gov.sg require an API key for access. This is not applicable to datastore search.

There's a limit to the number of records the datastore can access on the file. My suggestion is to access the CSV file and retrieve the file from the storage URL.

You can programatically do this by:
1. Using the CKAN package show api: https://data.gov.sg/api/action/package_show?id=entities-with-unique-entity-number

2. For each object in the resources key, use the url provided in the "URL" field.
