### ISSUE TITLE
Dataset request: List of NEA Licensed Eating Establishments(Historical)

### ISSUE THREAD

**Issue by tsb123** [datagovsg/datagovsg-datasets#370]
### Please provide the name of the dataset or describe the dataset that you're requesting:
List of NEA Licensed Eating Establishments(Historical: from 2010 to 2017)

### Do you know which agency provides/can provide this data?
NEA

### Please provide the fields expected in this dataset:
Would it be possible to get a historical version of the following datasets
https://data.gov.sg/dataset/list-of-nea-licensed-eating-establishments-with-grades-demerit-points-and-suspension-history 

OR

https://data.gov.sg/dataset/eating-establishments

### How frequently would you need this dataset to be updated?

- [X ] Annually (i.e. I would like to have yearly snapshots of all licensed food establishments)

### Can you give a short explanation on how you're planning to use this dataset?
I would like to construct a dataset that describes changes in Singapore's food environment over time, and be able to use this in health/ food choice behavior studies, for research purposes

**Comment by lennardl** [comment]
We do not have the historical data for that
