### ISSUE TITLE
Dataset request: Public Holidays in SG

### ISSUE THREAD

**Issue by peonmodel** [datagovsg/datagovsg-datasets#371]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Public Holidays and other important days (e.g. cultural days typically celebrated in SG)

### Do you know which agency provides/can provide this data?
MOM: https://www.mom.gov.sg/employment-practices/public-holidays

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

date | isPH | event|Remarks
------|---------|-------------|-------------
YYYY-MM-DD|No|QingMing|Chinese festival
YYYY-MM-DD|Yes|Deepavali|

### How frequently would you need this dataset to be updated?
- [x] Annually

### Can you give a short explanation on how you're planning to use this dataset?
To auto-calculated leave taken based on dates

**Comment by peonmodel** [comment]
any updates on this?

i still prefer an official API to get the information i need

heres a workaround to retrieve the info from official MOM website if anyone needs

it uses a CORS bypass url service
```js
const URI = 'https://www.mom.gov.sg/-/media/mom/documents/employment-practices/public-holidays/public-holidays-sg-';
const bypass = '';  // CORS bypass service

// fetch(`https://${bypass}/${URI}`).then(r=>r.text()).then(console.log)

export default async function getPublicHolidays(year) {
	const ics = await fetch(`https://${bypass}/${URI}${year}.ics`).then(r=>r.text());
	return ics.split('\n').filter(str => str.startsWith('UID')).map(str => {
		const [match, date, name] = RegExp(/UID:(\d{8})-(.+)@/).exec(str);
		const year = date.substr(0, 4);
		const month = date.substr(4, 2);
		const day = date.substr(6, 2);
		return {
			date: new Date(year, month - 1, day),
			event: name.replace('-',' '),
		};
	});
}
```

**Comment by lennardl** [comment]
@peonmodel https://data.gov.sg/dataset/singapore-public-holidays-for-2020
