### ISSUE TITLE
Dataset request: Landed Housing Area

### ISSUE THREAD

**Issue by fxronaldo** [datagovsg/datagovsg-datasets#372]
### Please provide the name of the dataset or describe the dataset that you're requesting:
MP14 SDCP LHA PLAN - Landed Housing Area. In KML or Shapefile

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
URA

### If there's an issue with a dataset, please provide a description of the problem
The dataset currently available in data.gov.sg is outdated (published in 2011). 
URA Space v2.0 has the updated dataset that covers more areas in Singapore. 
Please make the updated dataset available to the public for download. 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To generate more accurate pickup location for on-demand public transport service

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/mp14-sdcp-lha-plan-landed-housing-area
