### ISSUE TITLE
Dataset request: <HDB BTO Launches>

### ISSUE THREAD

**Issue by hongchiong** [datagovsg/datagovsg-datasets#373]
### Please provide the name of the dataset or describe the dataset that you're requesting:
The real-time BTO data. Currently as seen on this site: https://services2.hdb.gov.sg/webapp/BP13AWFlatAvail/BP13SEstateSummary?sel=BTO

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
HDB

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

launch_dates | launch_projects | project_name | project_rooms | blks_in_project | units_in_blks | unit_price

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [X] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Trying to build a site to display BTO information with friendlier user interface.

**Comment by lennardl** [comment]
@hongchiong We have approached HDB for the data and will come back to you once we get a response.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/price-range-of-hdb-flats-offered
