### ISSUE TITLE
Dataset request: Location of Electric Vehicle Charging Points

### ISSUE THREAD

**Issue by teojcryan** [datagovsg/datagovsg-datasets#374]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Location of Electric Vehicle Charging Points

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
LTA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Planning to explore which areas are under-served in terms of availability of electric vehicle charging points

**Comment by lennardl** [comment]
We do not have the data on this
