### ISSUE TITLE
Dataset request: <Rare diseases>

### ISSUE THREAD

**Issue by erictaneric** [datagovsg/datagovsg-datasets#375]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Number of people with rare diseases in Singapore

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Health Promotion Board
Ministry of Health
Health Science Authority
Singapore Medical Council

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Year | country | no. of people
------|---------|-------------
2017|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Currently, there is hardly any research on rare diseases as most healthcare industry players find it wasteful to spend money and resources to do research as the number of people that are affected are so minimal that industry players can't reap profits from rare diseases. 

I will be using the data to showcase the importance and uprising of rare diseases. In the future, I might request for mortality rate due to rare diseases to raise awareness

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/weekly-infectious-disease-bulletin-cases
