### ISSUE TITLE
Dataset request: <Planned MRT Stations for the future>

### ISSUE THREAD

**Issue by Stephen-Jawahar** [datagovsg/datagovsg-datasets#376]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Planned MRT Stations for the future

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

1) Ministry of Transport
2) Public Transport Council

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Latitude Position | Longitude Position| Station Name | Line name | 

### How frequently would you need this dataset to be updated?
Example: 

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

I would like to use the data sheet to better inform my customer about the new MRT/LRT Station coming up in the area in which they would like to rent or purchase their property.

**Comment by lennardl** [comment]
We only have the masterplan but it does not include upcoming MRT stations
