### ISSUE TITLE
Dataset request: Bus registrations by length

### ISSUE THREAD

**Issue by PedroAlvarilhao** [datagovsg/datagovsg-datasets#377]
### Please provide the name of the dataset or describe the dataset that you're requesting:

I would like to obtain a dataset containing the number of bus registrations in the past year by length. This is, the number of bus registered up to 6m, from 7-9m from 9-12m and articulated or higher length.

### Do you know which agency provides/can provide this data?
*  Land Transport Authority I imagine

### If there's an issue with a dataset, please provide a description of the problem
It doesn't exist or I didn't found it

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Year
Lenght sizes. up to 6-, 7m-9m, 9-12m, articulated or >12m
Vehicle type (but I'm requesting for buses since it's a niche market)

### How frequently would you need this dataset to be updated?
Example: 
- [X] Annually

### Can you give a short explanation on how you're planning to use this dataset?

The objective is to understand the current demand for buses and past demand as well and be able to try to forecast bus demand by length in Singapore

**Comment by lennardl** [comment]
We do not have the data
