### ISSUE TITLE
Dataset request: <hand foot mouth>

### ISSUE THREAD

**Issue by Ghzhu** [datagovsg/datagovsg-datasets#378]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [x] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/weekly-infectious-disease-bulletin-cases
