### ISSUE TITLE
Dataset request: Islamic Prayer Times For Singapore

### ISSUE THREAD

**Issue by nurmuhammadsirat** [datagovsg/datagovsg-datasets#38]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Islamic Prayer Times for Singapore

### Do you know which agency provides/can provide this data?
Majlis Ugama Islam Singapura

### If there's an issue with a dataset, please provide a description of the problem
No issue. The dataset is not available.

### Please provide the fields expected in this dataset:
date|subuh|syuruk|zuhur|asar|maghrib|isyak
2017-11-14|5:27|6:48|12:51|4:13|6:51

### How frequently would you need this dataset to be updated?
- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I would like to create a Garmin ConnectIQ app for my watch. Currently, MUIS does publish this data on its website (https://www.muis.gov.sg/documents/Resource_Centre/Prayer%20Timetable%202017.pdf). However, it is in PDF format. It would be easier for apps to consume this dataset if it is in CSV or JSON format.

Another reason why I would use it is because other media outlets, like radio, uses these times as well. So it would be great if I could use the same set of timings, instead of trying to calculate it myself or try to parse the PDF file.

**Comment by abanghazrul** [comment]
Hi @iewil. I'm just wondering if our colleagues at MUIS have responded with a response?

**Comment by ashcoding** [comment]
+1 to this.

**Comment by hazrulazhar** [comment]
Hi @iewil . bumping this up again.

**Comment by nurmuhammadsirat** [comment]
@lennardl Is there any reason why this is closed?

**Comment by lennardl** [comment]
@nurmuhammadsirat We were clearing out old tickets that have been marked with data not available. I see there is a continued need for this. I'll reopen the ticket and follow up with MUIS on this.

**Comment by nurmuhammadsirat** [comment]
@lennardl Thanks! This has been in limbo for quite some time and I'm not sure of the status of the request. I've always assumed it's being looked into.

I don't mind it being closed but would like to have a reason for it. (Eg. will not implement due to time, etc)

**Comment by nurmuhammadsirat** [comment]
@hazrulazhar Not only MuslimSG, I'm using Muslim Pro app which has global prayer calculations. And one of them is specific to MUIS. So I agree with you that they probably do have an API.

Or maybe all these apps just parse the PDF! ;) 🤷‍♂️

**Comment by lennardl** [comment]
We have approached MUIS and getting the data from them. Will update this ticket again soon.

**Comment by hazrulazhar** [comment]
> @hazrulazhar Not only MuslimSG, I'm using Muslim Pro app which has global prayer calculations. And one of them is specific to MUIS. So I agree with you that they probably do have an API.
> 
> Or maybe all these apps just parse the PDF! ;) 🤷‍♂️

MuslimPro parses PDF and saves in their DB. 

For me, I used the calculation method. Included Adhan.js from Batoul apps, and added a new calculation method called MUIS and worked on the values that needed to be entered because MUIS values are not the same as Egypt, not the same as Jakim, and not totally complying with MABIMS standards as written by aslaaken (NUS) in his articles. I have managed to produce a 99.99% accurate timing from pure calculation alone through this method. However, until MUIS open sources their algorithm, or decides to adopt an open source method, we will have to resort to calling APIs. Until that API is made available, many apps had to resort to parsing that data from PDF.

**Comment by ashcoding** [comment]
@lennardl Thanks for your hard work! I definitely prefer if MUIS can just have an XML file somewhere or JSON formatted data that we can consume officially.

**Comment by lennardl** [comment]
Data from MUIS on the prayer timings have been made available: https://data.gov.sg/dataset/islamic-prayer-timing-for-singapore
They were not able to provide an API just a CSV, but you can use our API.

**Comment by hazrulazhar** [comment]
Hi @lennardl 

How do we access your API to pull data from this CSV?

**Comment by lennardl** [comment]
Its on the data API button next to the embed chart function on the page itself. Its not a full fledge API.

**Comment by hazrulazhar** [comment]
@lennardl ok great! would be sufficient for now. Except that the data is a bit stale. Its now November 2018, and this data is only for 2018. May we request for the 2019 data?

**Comment by hazrulazhar** [comment]
@lennardl Would the resource ID change if the data was updated?
