### ISSUE TITLE
New Registration of Motor Vehicles 

### ISSUE THREAD

**Issue by keeweitkw** [datagovsg/datagovsg-datasets#381]
Monthly New Registration of Motor Vehicles by Vehicle Quota Categories

### Do you know which agency provides/can provide this data?
Land transport authority 

The data provide is from 2013, i wish to request for data as old as from 2007. Thank you.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

Im a student from National University of Singapore and i will like to do a project with the relevant data.

**Comment by lennardl** [comment]
@keeweitkw We were not able to get data going that far back, we did update the dataset to Feb 2019.

**Comment by keeweitkw** [comment]
hi, @lennardl 

Is there anywhere to get it? What is the latest data available?
