### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by freeke** [datagovsg/datagovsg-datasets#382]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Key Indicators On Divorces, Annual

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Trade and Industry - Department of Statistics

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by freeke** [comment]
I'm an Standardization Engineer from China, I am just doing some research.

**Comment by lennardl** [comment]
@freeke We'll liaise with the relevant agency to update the data. In the meantime, you can retrieve the data from http://www.tablebuilder.singstat.gov.sg/publicfacing/createDataTable.action?refId=1700
