### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by louiscastlery** [datagovsg/datagovsg-datasets#383]
### Please provide the name of the dataset or describe the dataset that you're requesting:
New house sales / New house completion + future target

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Housing and Development Board

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month |number of HDB sold
------|---------|-------------
2017-09|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

Look at the trend of new HDB houses on a monthly level and future data to gather insights such as future housing price

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/price-range-of-hdb-flats-offered
