### ISSUE TITLE
Dataset request: Clinic Data/CHAS Clinic Data

### ISSUE THREAD

**Issue by evelynlsl** [datagovsg/datagovsg-datasets#384]
### Please provide the name of the dataset or describe the dataset that you're requesting:
GP Name and Postal Code in Singapore

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Health

### Please provide the fields expected in this dataset:
clinic name | address | postal code|chas clinic indicator

### How frequently would you need this dataset to be updated?
Monthly

### Can you give a short explanation on how you're planning to use this dataset?
To get the location of clinics in Singapore for a school project

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/chas-clinics
