### ISSUE TITLE
Household income by subzone

### ISSUE THREAD

**Issue by Mira217** [datagovsg/datagovsg-datasets#385]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Household income data by subzone

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Trade and Industry - Department of Statistics, The General Household Survey

### If there's an issue with a dataset, please provide a description of the problem
NA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
subzone | average household monthly income | household size
------|---------|-------------
Bukit Batok East| 15000 | 4

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
this is for a research project on the distribution of green space in neighborhood in Singapore. We have a map of green space already and would like to over lay that on the income map.

**Comment by lennardl** [comment]
@Mira217 The relevant agencies do not have the data available
