### ISSUE TITLE
Dataset request: <dataset title>Filipino Dragons

### ISSUE THREAD

**Issue by MARYE0322** [datagovsg/datagovsg-datasets#386]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@MARYE0322 Can you please provide more details on what information you require?

**Comment by MARYE0322** [comment]
> @MARYE0322 Can you please provide more details on what information you require?

I want to purchase a company profile of a certain society.
