### ISSUE TITLE
Dataset request: List of Licensed/Approved Food Establishment

### ISSUE THREAD

**Issue by susanshtan** [datagovsg/datagovsg-datasets#388]
List of all the food establishments licensed by AVA.

Currently AVA allows the public to search for a licensed food establishment at: 
https://www.ava.gov.sg/e-services/tools-and-resources/licensed-food-establishment-search 

However, I would like to have the full list of all licensed/approved food establishments.

### Please provide the fields expected in this dataset:

Manufacturer Name | Establishment Address | Grade | Trade Description
--------------------------------|--------------------------------|----------|-----------------------------
AALST CHOCOLATE PTE. LTD.|26 TUAS AVENUE 7 S639273|Grade A|MFG OF CHOCOLATE

### How frequently would you need this dataset to be updated?
- [ ] Annually
- [ ] Monthly
- [X] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
We will use this dataset to monitor and ensure that all our food suppliers are licensed by AVA. Besides, we also want to use this for reaching out to more suppliers.

**Comment by lennardl** [comment]
@susanshtan Does this work https://data.gov.sg/search?q=Licensed+Food+Establishments ?

**Comment by susanshtan** [comment]
@lennardl Thank you for your reply. The lists provided are mainly lists of Eating Establishment.

Maybe I should clarify, I need the list of food manufacturers that are licensed by AVA.

**Comment by lennardl** [comment]
@susanshtan Thanks for clarifying. I've reached out to AVA for the data.
