### ISSUE TITLE
Higher education enrollment

### ISSUE THREAD

**Issue by YaraMourad** [datagovsg/datagovsg-datasets#389]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [x] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by YaraMourad** [comment]
Dear Mr. 
I would like to obtain data about higher education in Singapore mainly Gross enrollment ratio, number of graduates, public expenditure on tertiary education as % of GDP and Expenditure on R&D  from 1990 till 2017. I need this data because I am an undergraduate and I am doing my dissertation in the topic of the impact of higher education on economic growth in East Asia and I  want to include Singapore in the range of countries that I will choose. This data will be used for research in the field of economic development. I thought I would find it on the World Bank website, but unfortunately I found the data for 2 years only and I cannot find a time-series data set. I am in a need for this data in order to be able to include Singapore in my analysis that will add value to my dissertation. So, I am writing to request the data, please

**Comment by lennardl** [comment]
Data available across multiple datasets here https://data.gov.sg/search?q=enrollement
