### ISSUE TITLE
Dataset request: Polytechnic Courses For Academic year 2019/2020

### ISSUE THREAD

**Issue by skiddattle** [datagovsg/datagovsg-datasets#391]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Polytechnic Courses For Academic year 2019/2020

Reference : http://www.polytechnic.edu.sg/introduction/available-courses

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
MOE

### If there's an issue with a dataset, please provide a description of the problem
dataset not available on the website

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

school|jae_course_cluster|course_title|jae_course_code|faculty|2019_jae_elr2b2|new_course

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For a university project

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/nanyang-polytechnic-full-time-diploma-courses
