### ISSUE TITLE
Dataset request: <child>

### ISSUE THREAD

**Issue by thiawang1** [datagovsg/datagovsg-datasets#392]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by thiawang1** [comment]
Dear lennardl, I would need a dataset of the services (inclusive of fees) provided by all the registered childcare centres in Singapore.

**Comment by lennardl** [comment]
Does this help? https://data.gov.sg/dataset/list-of-childcare-centres

**Comment by thiawang1** [comment]
This dataset does not include the fees column. Previously there was a dataset which includes the fees - https://data.gov.sg/api/action/datastore_search?resource_id=0c14ceec-da1b-43c6-92fc-e82d7219840b. But last night, I was not able to access it. Do you how I can access it?

**Comment by lennardl** [comment]
@thiawang1 The fees data field was removed by the Early Childhood Development Agency who maintains the dataset. The dataset I provided in the link was the updated dataset from the resource you provided in the link.
