### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by chmlifys** [datagovsg/datagovsg-datasets#393]
### Please provide the name of the dataset or describe the dataset that you're requesting:
PM2.5

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

https://api.data.gov.sg/v1/environment/pm25

### If there's an issue with a dataset, please provide a description of the problem

not applicable

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

2017|Singapore

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [/ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Research project

**Comment by lennardl** [comment]
@chmlifys We have data prior to 2015 here: https://data.gov.sg/dataset/air-pollutant-particulate-matter-pm2-5?view_id=5e24aca5-8a19-43e7-9c48-574686586397&resource_id=2e47ab6d-e327-4eb0-824f-e3ab6a5984db we have stopped receiving yearly average data from NEA.
