### ISSUE TITLE
Dataset request: <Traffic Light>

### ISSUE THREAD

**Issue by dian-natasha** [datagovsg/datagovsg-datasets#394]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )* LTA or ITS perhaps

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Latitude | longitude | height | Traffic light orientation | number of Faces

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For personal projects, for school project

**Comment by lennardl** [comment]
@dian-natasha We have limited data on that, what we do have is https://data.gov.sg/dataset/lta-traffic-signal-aspect

**Comment by dian-natasha** [comment]
Thanks! any idea if there are plans to gather more specific traffic light data in future?

**Comment by lennardl** [comment]
@dian-natasha We have not heard from LTA that specific traffic light data will be provided.
