### ISSUE TITLE
Dataset request: <https://data.gov.sg/dataset/dengue-cases> 2019Y Aedes mosquito breeding habitats central, east, west, south, north 2019Y (Jan to Apr)

### ISSUE THREAD

**Issue by OlgaKolmykova** [datagovsg/datagovsg-datasets#399]
### Do you know which agency provides/can provide this data?
https://www.nea.gov.sg/dengue-zika/dengue/dengue-cases

### If there's an issue with a dataset, please provide a description of the problem
I need data from jan to april 2019

### Please provide the fields expected in this dataset:

JOIN_COUNT | AREANAME | DETAIL | INC_CRC | FMEL_UPD_D | POLYGON_COORDINATES
-- | -- | -- | -- | -- | --

### How frequently would you need this dataset to be updated?
Example: 
- [ X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset? 

I am student in NUS and currently working under my project “Dengue Fever in Singapore visualization”
but unfortunately, I have data only for previous week, I would be very very appreciated if you can share with me data of 2019Y (in excel of any format you have):
-dengue clusters 2019Y (Jan to Apr)
- Aedes mosquito breeding habitats central, east, west, south, north 2019Y (Jan to Apr)
  
PS: I attached example what I have, but its only one week ☹ . 

Really Looking forward your reply.  

Best regards, 
Olga

**Comment by lennardl** [comment]
We do not store the historical data for these
