### ISSUE TITLE
Dataset request: Energy and nutrient composition of food

### ISSUE THREAD

**Issue by heyjared** [datagovsg/datagovsg-datasets#4]
### Please describe the dataset that you're requesting:
Energy and nutrient composition of food
Data is already available here: http://focos.hpb.gov.sg/eservices/ENCF/foodsearch.aspx

### Please provide the fields expected in this dataset:
Food name | Food Group | Food Sub Group | Nutrients per 100g Edible Portion

### Do you know which agency can provide this data?
Health Promotion Board

### How frequently would you need this dataset to be updated?
- [X] Annually

### Can you give a short explanation on how you're planning to use this dataset?
Compose different foods into meal plans for various diets based on nutritional info.

**Comment by awreccan** [comment]
Bump. Any updates?
✋ I'm also interested, for the same use case!

**Comment by lennardl** [comment]
@awreccan We have approached HPB for the data and gotten a response that they are in the mids of updating the database and will not be able to share it with us at this point in time.
