### ISSUE TITLE
Dataset request: Weather Forecast

### ISSUE THREAD

**Issue by Cre8tion** [datagovsg/datagovsg-datasets#402]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Weather Forecast

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
data.gov.sg
NEA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Weather, Location

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [X] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

Prototype for school project. Retrieval of real-time weather and future weather to advice users to close their windows.

**Comment by lennardl** [comment]
deos this work? 
https://data.gov.sg/dataset/realtime-weather-readings
https://data.gov.sg/dataset/weather-forecast

**Comment by Cre8tion** [comment]
Yes. Thank you!
