### ISSUE TITLE
ACRA Dataset missing:  `entities-with-unique-entity-number`

### ISSUE THREAD

**Issue by skenaja** [datagovsg/datagovsg-datasets#403]
### Please provide the name of the dataset or describe the dataset that you're requesting:

https://data.gov.sg/dataset/entities-with-unique-entity-number

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

ACRA

### If there's an issue with a dataset, please provide a description of the problem

The above link currently shows as 404 Not Found

**Comment by lennardl** [comment]
@skenaja the dataset has been made available again.
