### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by kaishengteh** [datagovsg/datagovsg-datasets#404]
### Please provide the name of the dataset or describe the dataset that you're requesting:
1. Passenger Volume by Train Stations
2. Passenger Volume by Origin Destination Train Stations

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Land Transport Authority (LTA)

### If there's an issue with a dataset, please provide a description of the problem
I was only able to query Jan & Feb 2019 dataset.
Unable to get data for previous years.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

1. YEAR_MONTH | DAY_TYPE | TIME_PER_HOUR | PT_TYPE | PT_CODE | TOTAL_TAP_IN_VOLUME | TOTAL_TAP_OUT_VOLUME
-- | -- | -- | -- | -- | -- | --
2019-01 | WEEKENDS/HOLIDAY | 11 | TRAIN | NS7 | 7997 | 10996
-- | -- | -- | -- | -- | -- | --

2. YEAR_MONTH | DAY_TYPE | TIME_PER_HOUR | PT_TYPE | ORIGIN_PT_CODE | DESTINATION_PT_CODE | TOTAL_TRIPS
-- | -- | -- | -- | -- | -- | --
2019-02 | WEEKDAY | 9 | TRAIN | EW32 | DT24 | 1

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*
- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Build a visualization showing the trend of passenger usage and also the O&D demand for different pairs for MRT stations.

**Comment by lennardl** [comment]
We do not have that data
