### ISSUE TITLE
Dataset request: Commercial Buildings in Singapore

### ISSUE THREAD

**Issue by SPDKay** [datagovsg/datagovsg-datasets#405]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Number and Type of Commercial Buildings in Singapore

### Do you know which agency provides/can provide this data?
Statistics Singapore, BCA and URA

### Please provide the fields expected in this dataset:
Building Name| Property Type | Property Owner | Tenure | Class Type | Number of Floor | Number of Tenants

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am requesting on behalf of SP Group. This request is will be use as part of our internal research to understand how Landlords are managing energy consumption with their tenants and what is the gap for them to become more sustainable and efficient

**Comment by lennardl** [comment]
We do not have the data
