### ISSUE TITLE
Requesting for Monthly Registration of New Cars by Make, Starting from Jan 2004 to Present Date

### ISSUE THREAD

**Issue by snowflakescity** [datagovsg/datagovsg-datasets#407]
Hi LTA,

On https://www.lta.gov.sg/content/dam/ltaweb/corp/PublicationsResearch/files/FactsandFigures/M03-Car_Regn_by_make.pdf, LTA provides monthly registration of new cars by make, but only for 1st 2 months of 2019.

I am requesting for monthly registration of new cars by make, starting from Jan 2004 to present date.

Would appreciate if this request is approved. I need the data to do a thesis and dissertation.

**Comment by snowflakescity** [comment]
Appreciate also a prompt reply, thanks.

**Comment by lennardl** [comment]
@snowflakescity Does this work for you?
https://data.gov.sg/dataset/monthly-new-registration-of-cars-by-make?view_id=ef816b31-f922-4562-81d2-4fcd3b372a54&resource_id=4d4e1688-fc99-48a0-b3e4-342ccbb6a543
