### ISSUE TITLE
Dataset request: <acute and community inpatient average length of stay

### ISSUE THREAD

**Issue by buns13** [datagovsg/datagovsg-datasets#409]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Acute restructured hospitals length of stay and community hospitals length of stay 

### Do you know which agency provides/can provide this data?

Ministry of Health

### Can you give a short explanation on how you're planning to use this dataset?

To provide comparison for efficacy of newer healthcare models

**Comment by lennardl** [comment]
We do not have that data
