### ISSUE TITLE
Dataset request: Monthly New Registration of Motorcycles by Make and Model

### ISSUE THREAD

**Issue by natznano** [datagovsg/datagovsg-datasets#411]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Monthly New Registration and Number of Motorcycles by Make and Model

### Do you know which agency provides/can provide this data?
https://data.gov.sg/
Land Transport Authority

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | make | model | new registration number | total number
------|---------|-------------|------|-------
2017-09|Yamaha|AEROX GDR155 CVT|100|4000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*
- [x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Personal use to analyse which make and model are performing best in the market.

**Comment by natznano** [comment]
Any help with this is much appreciated! Thanks!

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/monthly-new-registration-of-motorcycles-by-make?view_id=f2b73160-02fb-4fad-823a-144c8e5d0161&resource_id=94aba21d-b7b5-40ec-b6ab-2dde780b20e1

**Comment by natznano** [comment]
Thanks a lot @lennardl but this dataset does not have the model of the bike, just the make. It would be great to include the model as well. That gives a better idea of the type of bike Singaporean riders like. Thanks again!

**Comment by lennardl** [comment]
@natznano That would be more difficult as LTA does not provide that data.

**Comment by natznano** [comment]
Okay, they do provide that information for the OMV prices. Is it possible for me to make a request for that data? Thanks again @lennardl
