### ISSUE TITLE
Dataset request: Weekly Infectious Disease Bulletin - January 1, 1982 to March 16, 2019

### ISSUE THREAD

**Issue by xiaoketam** [datagovsg/datagovsg-datasets#412]
### Ministry of Health
*( Refer to this link for a full list of agencies: 
[https://data.gov.sg/dataset/weekly-infectious-disease-bulletin-cases?resource_id=ef7e44f1-9b14-4680-a60a-37d2c9dda390]
)*

### Description of the problem
Current datasets in data.gov.sg only coverage between January 1, 2012 to March 16, 2019.
Request datasets between January 1, 1982 to March 16, 2019.
-- | --

### The fields expected in this dataset:
Epidemiological Week--| Disease| No. of Cases
------|---------|-------------
2019-W11|Cholera|0
--

### How frequently would I need this dataset to be updated?
- [X] *Test*

### Can you give a short explanation on how you're planning to use this dataset?
A study on weather VS infectious disease in Singapore

**Comment by TamGS** [comment]
<img width="381" alt="Dengue_Singapore" src="https://user-images.githubusercontent.com/37769987/58006274-4811c100-7b1a-11e9-936e-b1ae9eebce67.PNG">

**Comment by lennardl** [comment]
@TamGS We do not have access to the datasets that go back to 1982

**Comment by TamGS** [comment]
![course2_assignment4](https://user-images.githubusercontent.com/37769987/58443183-f624f880-8122-11e9-9f90-80285186067d.png)
Ok. Thanks.
Just for sharing.
