### ISSUE TITLE
Dataset request: <Taxi Availability>

### ISSUE THREAD

**Issue by darkgt** [datagovsg/datagovsg-datasets#413]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Taxi Availability

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Land Transport Authority

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [X] Hourly
- [X] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

For data visualization and research study.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/taxi-availability
