### ISSUE TITLE
Dataset request: Average mileage by age of motorcycle

### ISSUE THREAD

**Issue by terilyl** [datagovsg/datagovsg-datasets#414]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Average mileage by age of motorcycle

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
National Environmental Agency
Land Transport Authority

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | age of motorcycle | average mileage

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I would like to study if the age of the motorcycle correlates with the average amount of mileage it covers per month.

**Comment by lennardl** [comment]
@terilyl The data is not available
