### ISSUE TITLE
ACRA Dataset missing: `entities-with-unique-entity-number`

### ISSUE THREAD

**Issue by skenaja** [datagovsg/datagovsg-datasets#415]
### Please provide the name of the dataset or describe the dataset that you're requesting:

https://data.gov.sg/dataset/entities-with-unique-entity-number

### Do you know which agency provides/can provide this data?

ACRA

### If there's an issue with a dataset, please provide a description of the problem

The above link currently shows as 404 Not Found (re-occurrence of issue #403 )

**Comment by lennardl** [comment]
@skenaja It's back up

**Comment by skenaja** [comment]
Thanks @lennardl !
