### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by swathikarri** [datagovsg/datagovsg-datasets#419]
Hi ,

This is Swathi,Application Specialist  for Australian international school Singapore.

We want API details of Haze(for PSI) to show on school website ,Currently we have"http://api.nea.gov.sg/api/WebAPI/?dataset=psi_update&keyref=781CF461BB6606ADE5BD65643F178174ED03118D98F5A12D" this.
 
![haze](https://user-images.githubusercontent.com/50317931/57213050-327ba200-7018-11e9-87db-6c20827bdc37.PNG)

Please provide latetst API details to update in our website.

Regards,
Swathi.K

**Comment by lennardl** [comment]
@swathikarri Is this what you are looking for?
https://data.gov.sg/dataset/pm2-5
