### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by GuoQi0901** [datagovsg/datagovsg-datasets#420]
### Please provide the name of the dataset or describe the dataset that you're requesting:

PM2.5
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
1999-01|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I m a student in Master of Data Science, I will apply statistical tools and machine learning to this dataset, aim to predict climate change// thank you!

**Comment by GuoQi0901** [comment]
https://data.gov.sg/dataset/pm2-5?view_id=8c9e6472-9b1f-42b3-b631-d2056848bf95&resource_id=fa0958a9-bade-419e-9475-cbf5ccf4f746

**Comment by lennardl** [comment]
@GuoQi0901 Is that dataset you mentioned sufficient?

**Comment by GuoQi0901** [comment]
@lennardl  what I am looking for is a Monthly (or Daily) PM2.5 historical data, better from 1990 to 2018/2019. I'm not sure which year you have..  Thanks!

**Comment by lennardl** [comment]
We have a yearly averaged number here: https://data.gov.sg/dataset/air-pollutant-particulate-matter-pm2-5?view_id=5e24aca5-8a19-43e7-9c48-574686586397&resource_id=2e47ab6d-e327-4eb0-824f-e3ab6a5984db

If you need monthly data, I would suggest using the API to call past dates.

**Comment by GuoQi0901** [comment]
@lennardl  Get it. Thank you very much!!!
