### ISSUE TITLE
Dataset request: Motorcycle ownership by make

### ISSUE THREAD

**Issue by natznano** [datagovsg/datagovsg-datasets#421]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Motorcycle ownership by make

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
LTA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | ownership | make
------|---------|-------------
2017-09 | Individual/corporate | Yamaha

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
This is better understand the number of rental motorcycles in Singapore as part of understanding motorcycle usage behaviour of Singaporeans.

**Comment by lennardl** [comment]
We do not have that data
