### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by shimeng813** [datagovsg/datagovsg-datasets#422]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Singapore zipcode list

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Transport

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

Region|Department|Zip code

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To find a place use the zipcode

**Comment by lennardl** [comment]
@shimeng813 We are unable to provide zipcode/postal codes as they are the property of Singapore Post. You would need to approach SingPost for it.
