### ISSUE TITLE
Dataset request: 

### ISSUE THREAD

**Issue by lcp3npedusg** [datagovsg/datagovsg-datasets#424]
### Please provide the name of the dataset or describe the dataset that you're requesting:
LTA

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
LTA

### If there's an issue with a dataset, please provide a description of the problem

LTA
### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
----05--|---A------|-------------2
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@lcp3npedusg Can you provide more details on the data you need?
