### ISSUE TITLE
Dataset request

### ISSUE THREAD

**Issue by raylooi** [datagovsg/datagovsg-datasets#425]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Causes of Road Accidents - Causes of Accidents by Severity of Injury Sustained

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
MHA - SPF

### If there's an issue with a dataset, please provide a description of the problem
no issue

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

1) accident_classification	
2) road_user_group
3) causes_of_accident
4) date and time of accident (if available)
5) location / GPS coordinates of accident (if available)

### How frequently would you need this dataset to be updated?
Example: 

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To see if there are any patterns on map/locations of where these accidents often occur.

**Comment by lennardl** [comment]
Data is limited to https://data.gov.sg/dataset/causes-of-road-accidents-causes-of-accidents-by-severity-of-injury-sustained
