### ISSUE TITLE
Dataset request: <Singapore Buildings Information Database>

### ISSUE THREAD

**Issue by sjpark1989** [datagovsg/datagovsg-datasets#426]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Singapore Buildings Information Database: This dataset will have a full list of buildings in Singapore with their location coordinates, year of completion, type of uses, and gross floor area.

### Do you know which agency provides/can provide this data?
URA, BCA

### If there's an issue with a dataset, please provide a description of the problem
N.A.

### Please provide the fields expected in this dataset:
id|Building Name|Full Address|Latitude|Longitude|Year of Completion|Type of Use|GFA
1|The Concourse|300 Beach Road, 199555|1.1231|103.1231|1990|Office: 80%, Retail: 3%, Hotel: 0%, Residential: 0%|15,000 sq.m

### How frequently would you need this dataset to be updated?
Example: 
- [x] Annually
- [x] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
This data will be useful for property developers and urban planning consultants in assessing current supply of floorspace by type of use. I will be using this data to provide recommendations on economically sustainable land use programme for new developments in Singapore.

**Comment by lennardl** [comment]
@sjpark1989 For that data, I would suggest using the URA masterplan as it contains most of the information you need with the exception of year of completion.

**Comment by sjpark1989** [comment]
@lennardl The issue with the URA Masterplan is that it only has information on what is permissible by the authorities. Developers do not always maximize what is allowed for various reasons, and the gross floor area mix also changes over the years with users applying for change of use. What will be useful is a database of existing buildings as built, and not according to what is allowed on the site.
