### ISSUE TITLE
Dataset request: <Request For Road Trafffic Accidents Involving Public Buses>

### ISSUE THREAD

**Issue by waltertoh** [datagovsg/datagovsg-datasets#428]
### Please provide the name of the dataset or describe the dataset that you're requesting:

I would like to request for a dataset either in MS Excel or CSV format 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

Ministry Of Home Affairs/Singapore Police Force/Traffic Police Department

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Year/Month/Date/Time/Road Condition/Weather/Visibility/Type Of Accident/Public Transport Operator/Vehicle Involved/Vehicle Manufacturer/Vehicle Model/Fatalities/Injuries/Conveyed To Hospital/Which Hospital/Accident Location/Red Light Camera/School Zone/Silver Zone/Other Specific Zones/Liability

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [X] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

It will be be mostly used for school project and may be used for providing preventive recommendation to PTOs.

**Comment by lennardl** [comment]
@waltertoh We do not have a dataset specific for bus accidents, we do have one covering moter vehicles in generals and the causes. Would this work for you?

https://data.gov.sg/dataset/causes-of-road-accidents-causes-of-accidents-by-severity-of-injury-sustained?view_id=e80588ff-310c-4199-93bf-e6479e160634&resource_id=d68321b6-c438-425d-b9f4-d5777eee9e77

**Comment by waltertoh** [comment]
@lennardl  thank you for your response. 

I have checked on the .csv file and found that the data is too general to derivate any conclusions. As I am currently learning MS Power BI, I hope that you can help to provide a more detailed dataset so that I can use the software to see whether there is any trend/relationship on the factors. 

At the same time, can you please provide the dataset nearer to present time?

**Comment by lennardl** [comment]
@waltertoh I've approached the data owners for an update to the dataset and the request to break it down. Will respond back once I hear from them.

**Comment by waltertoh** [comment]
@lennardl thank you very much for your assistance. looking forward for your positive response soon.

**Comment by waltertoh** [comment]
hi @lennardl, may I know whether there's any update to this request?

**Comment by lennardl** [comment]
@waltertoh Apologizes for the delayed response. SPF has reverted that they will update the dataset but would not be able to provide the breakdown.
