### ISSUE TITLE
Dataset request: List of registered TCM Clinic

### ISSUE THREAD

**Issue by jinyuan** [datagovsg/datagovsg-datasets#429]
### Please provide the name of the dataset or describe the dataset that you're requesting:
List of registered TCM Clinic

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

name | full_address | postal_code
------|---------|-------------
XXX TCM Clinic|19 XXX Road #01-01|100017

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Understanding the distribution of TCM clinics and general business analytics

**Comment by lennardl** [comment]
The data is not available
