### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by wrjanan** [datagovsg/datagovsg-datasets#43]
### Please provide the name of the dataset or describe the dataset that you're requesting:
list of registered acra companies

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
accounting-and-corporate-regulatory-authority (ACRA)

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

name| registered| date of registration|status|UEN
------|---------|-------------
hilton|live|2008-jun|PTE LTD|123ID

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [X] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Plan to use this dataset as a means to measure the trend of business setups in Singapore and hopefully be able to encourage more locals to set up businesses.

**Comment by LoneRifle** [comment]
Is this what you are looking for?
https://data.gov.sg/dataset/acra-information-on-corporate-entities
