### ISSUE TITLE
Dataset request: request Auth Token for PSI API

### ISSUE THREAD

**Issue by on3nx** [datagovsg/datagovsg-datasets#430]
### Please provide the name of the dataset or describe the dataset that you're requesting:
HI,
can I request authentication token to access this API?

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
National Environment Agency

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [x] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@on3nx The PSI API is open for public use and does not need an Auth Token. Do let me know if you are still experiencing issues accessing the data.
