### ISSUE TITLE
Dataset request: average hospital inpatient bill size

### ISSUE THREAD

**Issue by 2wnh** [datagovsg/datagovsg-datasets#431]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Average hospital inpatient bill size

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
MOH

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Average inpatient bill size per day, average total bill, total bill at 90th percentile, total bill at 95th percentile for all public hospitals (including CGH, KTPH, KKH, NIH, NTFGH, SGH, TTSH, NHC) for the year.

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Used to gauge amount of provision for pension to older employees.

**Comment by lennardl** [comment]
@2wnh We do not have the exact numbers, we do have the % of expenditure per household. Would that work? 
https://data.gov.sg/dataset/household-healthcare-expenditure?view_id=ff0a1c40-d22f-46db-ae9c-9e6a361879cb&resource_id=10882b91-504a-4b5a-8f69-801f7f3436c2
