### ISSUE TITLE
Dataset request: <Locations and Postal Codes of PUB Sewage Pumping stations>

### ISSUE THREAD

**Issue by SandraSajen** [datagovsg/datagovsg-datasets#432]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Postal Codes and Locations of the PUB Sewage/ DTSS pumping stations 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
PUB

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
PUB pumping station Name | Location | Postal code | block No.
------|---------|-------------

### How frequently would you need this dataset to be updated?
Example: 
- [x] *Test*

- [x ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [x] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Needed it urgently for the waste collection tender. The locations would help in route planning 
To start with it would be most helpful if you could provide the postal codes for the PUB pumping stations given below.
1. Chua Chu Kang Road - PUB
2. Jurong West Street 76 (PUB Sewerage Station)
3. Pandan Avenue (PUB Pumping Station)
4. Tanjong Penjuru Road (PUB Sewerage Pumping Station II)
5. West Coast Road (Pandan I - Pumping Station)
6. Yuan Ching Road (Jurong Pumping Station (PUB))

Thanks a lot!

**Comment by lennardl** [comment]
Postal code data is not available
