### ISSUE TITLE
Dataset request: Singapore Bunker Sales - Monthly Data

### ISSUE THREAD

**Issue by huabingyong** [datagovsg/datagovsg-datasets#433]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Singapore Bunker Sales - Monthly Data

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Maritime and Port Authority of Singapore - They only provide monthly data up to 2018.
Used to exist on data.gov but is now a broken link

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | Total | MGO | MDO | MFO 180 cst | MFO 380 cst | MFO 500 cst | LSMGO | LSFO 180 cst | LSFO 380 cst | LSFO 500 cst | Others
2019-01|4,199.4 | 79.1 | 0.0 | 27.0 | 2,971.3 | 795.5 | 229.5 | 29.0 | 3.6 | 0.0 | 64.3

### How frequently would you need this dataset to be updated?
Example: 
- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am trying to build a regression model between bunker sales and vessel calls for the purpose of predicting bunker sales in Singapore

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/bunker-sales-monthly
