### ISSUE TITLE
ACRA datasets disappeared

### ISSUE THREAD

**Issue by aroslov** [datagovsg/datagovsg-datasets#437]
The following 2 datasets are missing since a few days ago

https://data.gov.sg/dataset/entities-with-unique-entity-number?resource_id=bdb377b8-096f-4f86-9c4f-85bad80ef93c

https://data.gov.sg/dataset/entities-with-unique-entity-number?resource_id=5ab68aac-91f6-4f39-9b21-698610bdf3f7

Is there a technical issue with it?

**Comment by lennardl** [comment]
@aroslov Its back up now.
