### ISSUE TITLE
Dataset request: CPF balances (by account) and withdrawals by age

### ISSUE THREAD

**Issue by deborahohm** [datagovsg/datagovsg-datasets#438]
### Please provide the name of the dataset or describe the dataset that you're requesting:
CPF balances and withdrawals by CPF account and by age

### Do you know which agency provides/can provide this data?

CPF

### If there's an issue with a dataset, please provide a description of the problem
N/A

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
year  | age | total balance | ordinary account | special account | medisave | withdrawal |

### How frequently would you need this dataset to be updated?

- [X] Annually

### Can you give a short explanation on how you're planning to use this dataset?

Masters thesis on pension adequacy. Institution: United Nations University/ Maastricht University

**Comment by lennardl** [comment]
We do not have that detailed breakdown
