### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by Data-Star** [datagovsg/datagovsg-datasets#44]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [x] Annually
- [x] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by Data-Star** [comment]
for class project

**Comment by yongjun21** [comment]
@Data-Star I think you forgot to specify in your template which dataset you're requesting
