### ISSUE TITLE
Dataset request: <Request For Past Three Years Of IPO Price and Their Price Movement>

### ISSUE THREAD

**Issue by waltertoh** [datagovsg/datagovsg-datasets#441]
### Please provide the name of the dataset or describe the dataset that you're requesting:
 Dataset of SGX IPO Prices and their Price Movements after listed (2017-2019)

### Do you know which agency provides/can provide this data?
SGX, MAS

### If there's an issue with a dataset, please provide a description of the problem
NA

### Please provide the fields expected in this dataset:

Year/Month/Day of Listing/Time/Opening Price/Highest Price/Lowest Price/Closing Price/ 

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

For project purposes

**Comment by lennardl** [comment]
We do not have the data
