### ISSUE TITLE
Dataset request: Annual Mileage for Private Motor Vehicles

### ISSUE THREAD

**Issue by haitian-fang** [datagovsg/datagovsg-datasets#443]
### Please provide the name of the dataset or describe the dataset that you're requesting:

**Annual Mileage for Private Motor Vehicles**

### Do you know which agency provides/can provide this data?

Land Transport Authority 

### If there's an issue with a dataset, please provide a description of the problem

I would like to request for more updated values if available. 

### Please provide the fields expected in this dataset:

_(vehicle type | year | average annual mileage)_

average annual mileage can be replaced by monthly values if additional granularity is available. 

### How frequently would you need this dataset to be updated?

- [X] Annually. Up to latest Year (2018)
- [X] Monthly. If possible. 
- [ ] Weekly

### Can you give a short explanation on how you're planning to use this dataset?

This will be used by ExxonMobil to analyse the market conditions.

**Comment by lennardl** [comment]
@haitian-fang We have approached LTA to have the data updated

**Comment by haitian-fang** [comment]
Thanks. Could you also help to enquire if private hire car mileage is available (a new category under vehicle type)?  Thanks for the help!
