### ISSUE TITLE
Dataset request: <Average Hospital Inpatient Bill Size>

### ISSUE THREAD

**Issue by cherylwong** [datagovsg/datagovsg-datasets#444]
The data I am requesting for is Average Hospital Inpatient Bill Size

Do you know which agency provides/can provide this data?
MOH

If there's an issue with a dataset, please provide a description of the problem
I remember looking at it the last time when i was choosing my data for my project. I wrote the title of the data and the url too. But now when I click on the url, it says invalid. I am planning to use this data for excel project work.

**Comment by lennardl** [comment]
MOH would have the data we do not have the data
