### ISSUE TITLE
Dataset request: <Approved Pet Shops Location and Contact>

### ISSUE THREAD

**Issue by agoagoagoago** [datagovsg/datagovsg-datasets#446]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Approved Pet Shops Location and Contact

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

https://www.nparks.gov.sg/avs

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

Name, Location, Contact Person, Contact Number, Email

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [X ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

Easier to locate approved pet shops and also good for research on potential area for business opportunities.

**Comment by lennardl** [comment]
@agoagoagoago we have approached NParks for the data. Will update this issue again once we get a response.
