### ISSUE TITLE
Dataset request: Historic CEA Salesperson Information

### ISSUE THREAD

**Issue by chinchinnn** [datagovsg/datagovsg-datasets#447]
### Please provide the name of the dataset or describe the dataset that you're requesting:
CEA Salesperson Information

### Do you know which agency provides/can provide this data?
CEA, Data.gov.sg

### If there's an issue with a dataset, please provide a description of the problem
No issue.
Would like to request for past versions of this dataset, i.e. daily versions of the dataset over the past 3 years (e.g. 21st Dec 2016 data, 22nd Dec 2016 data ... up till 23rd Jun 2019 data) assuming the dataset is not overwritten each time it is updated.

### Please provide the fields expected in this dataset:
Current fields

### How frequently would you need this dataset to be updated?
Example: 

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To examine agent movement across agencies

**Comment by lennardl** [comment]
@chinchinnn Unfortunately only latest version of the data is made available
