### ISSUE TITLE
Dataset request: <Singapore contours (1m)>

### ISSUE THREAD

**Issue by aceaves** [datagovsg/datagovsg-datasets#449]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Singapore topographic contours at 1m elevations.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

data.gov.sg
### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Latest contour polylines with z values, preferably in an ArcGIS format.

### Can you give a short explanation on how you're planning to use this dataset?
This dataset is going to be used for an acoustic assessment by Golder Associates of refrigeration that is currently placed on the roof of a building.

**Comment by lennardl** [comment]
We do not have that data
