### ISSUE TITLE
Dataset request: Wholesale electricity price

### ISSUE THREAD

**Issue by kaihendry** [datagovsg/datagovsg-datasets#450]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Wholesale (spot) electricity price

### Do you know which agency provides/can provide this data?

https://www.emcsg.com/

### Please provide the fields expected in this dataset:

A [prometheus](https://prometheus.io/) end point that could be scraped that simply published price per kw/h would be great. For example:

```
curl https://www.emcsg.com/metrics
# HELP wholesale_kwh_SGD shows the current realtime electricity price in Singapore dollars per kilowatt hour
# TYPE wholesale_kwh_SGD gauge
wholesale_kwh_SGD 0.10
```
10 cents per kilowatt hour at the time of scraping.

### How frequently would you need this dataset to be updated?

- [X ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

Transparency to the cost of electricity.

Everyone consumes electricity in Singapore. I've chosen to purchase via the "Electricity Market's **SPgroup Wholesale Electricity Price**. However when on that spot price, their app is unable to tell me what price I'm paying for energy and they refer to https://www.emcsg.com/ which don't appear to have a public API I can find.

**Comment by lennardl** [comment]
We do not have the data as it belongs to a private entity
