### ISSUE TITLE
Dataset request: <Rain Radar>

### ISSUE THREAD

**Issue by sijie123** [datagovsg/datagovsg-datasets#453]
This is a clarification for #291 as I would also like to access the data.

### Please provide the name of the dataset or describe the dataset that you're requesting:
I would like access to the [meteorological *radar* data](http://www.weather.gov.sg/weather-rain-area-50km) - the one that provides data to generate this map: 
I believe this is not the same as the [rainfall map](http://www.weather.gov.sg/weather-currentobservations-rainfall/) or [rainfall API data](https://data.gov.sg/dataset/realtime-weather-readings?resource_id=8bd37e06-cdd7-4ca4-9ad8-5754eb70a33d) as the radar reflects the cloud / water droplets in the air, vs rainfall map that reflects the amount of rain water that is collected.

### Do you know which agency provides/can provide this data?
NEA

### If there's an issue with a dataset, please provide a description of the problem
N.A.

### Please provide the fields expected in this dataset:
Not sure, it'll be good if it can be represented as categorical data, similar to:

time-and-date | lat | long | intensity
------|---------|-------------|------
2017-09-01 12:00:00 | 1.234 | 103.1234 | 100

For all lat, long perhaps up to 3 d.p. precision?

Alternatively, since the radar would probably provide analog data, a map or something similar would do too.

### How frequently would you need this dataset to be updated?
Example: 
- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [x] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Create a now-cast for specific location. Historical + Realtime radar provides predictive capability as we can monitor incoming rain clouds, as compared to rainfall which is more reactive in nature (only after rainfall is collected can we observe the rain)

**Comment by lennardl** [comment]
We do not have the rain radar data only weather and rainfall
