### ISSUE TITLE
Dataset request: <missing API to access database>

### ISSUE THREAD

**Issue by JNYH** [datagovsg/datagovsg-datasets#454]
### Please provide the name of the dataset or describe the dataset that you're requesting:
CEA Salesperson Information

### Do you know which agency provides/can provide this data?
CEA

### If there's an issue with a dataset, please provide a description of the problem
unable to access the database anymore, the API below seems to be missing:
https://data.gov.sg/api/action/datastore_search?resource_id=a41ce851-728e-4d65-8dc5-e0515a01ff31&limit=5
For example, the salesperson license numbers R014095G or R028693E cannot be found in the database.
However, they are valid license holders according to CEA public register website: https://www.cea.gov.sg/public-register

### Please provide the fields expected in this dataset:
salesperson_name | registration_no | registration_start_date | registration_end_date | estate_agent_name | estate_agent_license_no
-- | -- | -- | -- | -- | --

### How frequently would you need this dataset to be updated?
- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [X] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To verify that Real Estate Salesperson has a valid CEA license to perform estate agency work

**Comment by lennardl** [comment]
An API key is not required
