### ISSUE TITLE
Dataset request: list of WSQ courses

### ISSUE THREAD

**Issue by bilogic** [datagovsg/datagovsg-datasets#456]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
skillsfuture.gov.sg?

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

provider | Total Training hours | Training days | Course Duration days | website | contact number | funding end date | Reference Number | competency code | full cost
-|-|-|-|-|-|-|-|-|-
abc school | 24 | 3 | 3 | abc.com | +65-1234-1234 | 2017-09-01 | CRS-Q-0027443-IT | LPM-RES-401C-0 | 2500 

### How frequently would you need this dataset to be updated?
Example: 
- [] *Test*

- [ ] Annually
- [x] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
the search on skillsfuture/skillsconnect/myskillsfuture is incredibly hard to use and find relevant courses. a dataset like this will make WSQ courses more visible and accessible by all.

**Comment by bilogic** [comment]
any idea?

**Comment by lennardl** [comment]
That data is not made available here and the list is on WSQ itself
