### ISSUE TITLE
Dataset request: <Enterprise Count by Industry by Revenue (bands)>

### ISSUE THREAD

**Issue by byeung79** [datagovsg/datagovsg-datasets#459]
### Please provide the name of the dataset or describe the dataset that you're requesting:

I am trying to find out the number of enterprises by industry and by revenue band, similar to the enterprise count at:
https://www.singstat.gov.sg/modules/infographics/economy

but I need more granularity to industry and revenue (bands)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

I would think it will be ACRA but I have difficulty balancing the ACRA UEN numbers against the figures shown in the singstat page above.

### Please provide the fields expected in this dataset:

Year|Industry|Revenue Band|Number of Enterprises.

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

Thank you

**Comment by lennardl** [comment]
We do not have the data
