### ISSUE TITLE
Dataset request: <SG Addresses with lat long>

### ISSUE THREAD

**Issue by ptpmashish** [datagovsg/datagovsg-datasets#46]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Point addressing data - All addresses in Singapore and their latitude and longitude. 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
I couldn't figure out. OneMap maybe. 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

Addresses or blocks |Street name| POSTAL CODE|NAME of Building(if available)|Latitude|Longitude
-------------|------|---

1 | Shenton way| 049587|Shenton tower|1.34564564| 103.56456341 

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ X ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

I'm trying to put all addresses and point of interests into Qgis and understand the location of population and other aspects. this will be helpful to understand the transportation needs of SG. and based on that thinking to create a transportation optimization model.

**Comment by yongjun21** [comment]
@ptpmashish 
Unfortunately, the only official source for this data for now is OneMap and you'll have to use their [geocoding API](https://docs.onemap.sg/#search).

But there are community generated work that might simplify your work. [Example](https://github.com/xkjyeah/singapore-postal-codes)

**Comment by ptpmashish** [comment]
Thank you bro! the data looks good. Will submit a new pull request for more
up to date data.

**Comment by ptpmashish** [comment]
Further one more concern, Can i use the data under the open data license.

thank you!

**Comment by xkjyeah** [comment]
Yes I believe so. OneMap data is released under the Open Data Licence
