### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by nooyan** [datagovsg/datagovsg-datasets#460]
### Please provide the name of the dataset or describe the dataset that you're requesting:
singapore crime rates, 1990 to present

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Singapore Police Force

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Crime rate per 100,000 | District (e.g. bukit timah, sembawang, pasir ris) | year
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I plan to collate the data onto a map for easier reference ofcrime rate and its location

**Comment by lennardl** [comment]
We only have data that goes back to 2005 and it is a generic number https://data.gov.sg/dataset/overall-crime-cases-crime-rate
