### ISSUE TITLE
Dataset request: Public Transport Utilisation - Average Daily Public Transport Ridership

### ISSUE THREAD

**Issue by paigewonggg** [datagovsg/datagovsg-datasets#463]
1) dataset requesting:
Public Transport Utilisation - Average Daily Public Transport Ridership from 2016 onwards

2) issue with the dataset, please provide a description of the problem:
the dataset is currently not updated after 2015 

3) fields expected in this dataset:

- yearly updates of Average Daily Public Transport Ridership In Singapore for LRT, MRT and public buses from 2016 to 2018

4) How frequently would you need this dataset to be updated?

- [ x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

5) A short explanation on how you're planning to use this dataset?
I am currently studying the international baccalaureate in the UK. As part of my coursework for the program, am required to write an extended essay. I have decided to write about the ERP system in Singapore. The data that is already available will not be able to aid me in my essay as they are more than 5 years old. As such I will require more recent data to help reach my conclusion in my essay. Thank you very much

**Comment by lennardl** [comment]
We do not have the daily numbers
