### ISSUE TITLE
Dataset request: <Farming Land Area>

### ISSUE THREAD

**Issue by eulabius** [datagovsg/datagovsg-datasets#466]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Farming Land Area

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

Singapore Land Authority
SFA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Year | country | Amount of Land (Hectare)
------|---------|-------------
2008 - 2018 | Singapore |10000

### How frequently would you need this dataset to be updated?
Example: 

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

To analyse allocation of land towards farming in Singapore

**Comment by lennardl** [comment]
https://data.gov.sg/search?q=farm
