### ISSUE TITLE
Dataset request: <Vision Care Related Course Graduates>

### ISSUE THREAD

**Issue by WhichIsBetter** [datagovsg/datagovsg-datasets#467]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Annual Graduates of Vision(Eye) Care The Following Eyecare Related Courses:
- Optometry Diploma/Advanced Diploma from SP/NP
- NITEC In Opticianry from ITE
- Advanced Certificate of Performance in Ophthalmic Dispensing (ACOPOD) from SP
- Advanced Certificate of Performance in Ophthalmic Dispensing and Refraction (ACOPOD+R) from SP
- Certificate in Basic Opticianry Practice (CBOP) from RP

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
- ITE/SP/NP/RP/MOE

### If there's an issue with a dataset, please provide a description of the problem
The following data sets does not specify the actual course figures but instead grouped by general areas of study
- https://www.data.gov.sg/dataset/ite-intake-enrolment-and-graduates-by-course
- https://www.data.gov.sg/dataset/polytechnics-intake-enrolment-and-graduates-by-course

The following data sets does not include any graduates of Optometry/Opticianry
- https://www.data.gov.sg/dataset/number-of-graduates-in-healthcare-specialisations-by-course

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Year | Course | Level | School | Graduates
------|----|-----|------|-------
2017|Diploma In Optometry|Diploma|SP|10000

### How frequently would you need this dataset to be updated?
- [x] Annually

### Can you give a short explanation on how you're planning to use this dataset?
After years of increase in Cohort for Such courses, the industry is still facing shortages in manpower, would like to find out the attrition rate of the graduates across various types of studies for better understanding of the possible issues.

**Comment by WhichIsBetter** [comment]
@lennardl pls

**Comment by lennardl** [comment]
Data is limited to the topline
https://data.gov.sg/dataset/ite-intake-enrolment-and-graduates-by-course
https://data.gov.sg/dataset/universities-intake-enrolment-and-graduates-by-course
https://data.gov.sg/dataset/polytechnics-intake-enrolment-and-graduates-by-course
