### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by MichelleQuak** [datagovsg/datagovsg-datasets#47]
### Please provide the name of the dataset or describe the dataset that you're requesting:
**Primary School Locations (shapefile)
Secondary School Locations (shapefile)**

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
**MOE / URA**

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

**Name|Address|Total Enrollment (if possible)|X coordinate|Y coordinate|**

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

**- [X] Annually**
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Proximity analysis to other schools and housing. While the OneMap School Query app allows the layman to use it, I need the locational data to run some island-wide analysis for my own project. I believe this data was offered previously through the old OneMap / data.gov website, but has now been omitted.
Thank you.

**Comment by yongjun21** [comment]
@MichelleQuak
For primary schools, the official location can be fetched from this API: https://developers.onemap.sg/publicapi/schooldataAPI/retrieveAllSchools?token={token}

Token can be fetched here: https://developers.onemap.sg/publicapi/publicsessionid

For secondary school locations, you may need to do some geocoding based on postal code. Alternatively, you may take the data from our [SchoolPicker](https://schoolpicker.sg) source code: https://github.com/datagovsg/school-picker/tree/master/public/data/schools. [See here](https://github.com/datagovsg/school-picker/blob/master/public/data/schools/0701.json#L1053)

The SchoolPicker source code also contains P1 registration data where you can find the number of vacancies. [Example](https://github.com/datagovsg/school-picker/blob/master/public/data/schools/1020.json#L376)

As SchoolPicker is open-sourced for public to build on, you may use these data freely as long it's for your private project.
