### ISSUE TITLE
Dataset request: places of interest in tourist attractions

### ISSUE THREAD

**Issue by junhua** [datagovsg/datagovsg-datasets#472]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Facilities / Places of Interest in the Zoos and Universal Studios Singapore

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

STB

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

#### Table 1

Owner|POI | lat | long |duration|capacity|ind-outd|rating|n_review
---|---|---|---|---|--|--|--|-------
USS|roller coaster|123.45| 543.21 | 100 |500|indoor|4.7|5000

#### Table 2

Owner|from|to|distance|walk_time
---|---|---|---|------
USS|roller coaster|some theater|500|10

### How frequently would you need this dataset to be updated?
- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

Develop an itinerary recommendation algorithm for improving tourists' experience.

**Comment by junhua** [comment]
@lennardl

**Comment by lennardl** [comment]
We do not have the data
