### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by frederick0202** [datagovsg/datagovsg-datasets#473]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Yearly total water usage/consumption in Singapore. 
Current Water production capacity. 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Perhaps PUB. 

### If there's an issue with a dataset, please provide a description of the problem
Nil.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Year | country | Total Water Usage/Consumption  
------|---------|-------------
As far back as possible, to 2018 | Singapore | Total Water Usage/Consumption 

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I'm currently a student at Nanyang Polytechnic and I require this data for one of my assignments in order to forecast current water usage by using past data and using it to suggest how we can improve current water production capacity.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/water-sales-annual
