### ISSUE TITLE
Dataset request: HDB Property Information

### ISSUE THREAD

**Issue by sscctan** [datagovsg/datagovsg-datasets#474]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
HDB

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

BLOCK|STREET NAME|TOP FLOOR

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am a fitness enthusiast. Looking to take on other taller HDB blocks as my estate has only 19 floors to the top.

**Comment by sscctan** [comment]
Add on the explanation - stairs climbing as an exercise.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/hdb-property-information
