### ISSUE TITLE
Dataset request: Details of doctors and MCR number

### ISSUE THREAD

**Issue by albincool7** [datagovsg/datagovsg-datasets#475]
refer to the url - 
https://prs.moh.gov.sg/prs/internet/profSearch/mgetSearchSummaryByName.action 

### Do you know which agency provides/can provide this data?
https://prs.moh.gov.sg/prs/internet/profSearch/mgetSearchSummaryByName.action 

*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:

Qualifications
BMBS (U of Southampton, United Kingdom) 2014 
Type of first registration / date
Conditional Registration (10/10/2016)
Type of current registration / date
Conditional Registration (10/10/2016)
Practising Certificate Start Date
01/01/2018
Practising Certificate End Date
31/12/2019

Type of Register: Medical Professional
Specialty / Entry date into the Register of Specialists
This doctor is not on the Register of Specialists

Entry date into Register of Family Physicians
This doctor is not on the Register of Family Physicians

Primary Place of Practice
Department / Name of Practice Place
Gastroenterology, SINGAPORE GENERAL HOSPITAL
Address of Place of Practice
- Outram Road
Singapore 169608 
Tel
62223322 

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [x] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
We do not have the data on our site
