### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by claydohman** [datagovsg/datagovsg-datasets#476]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Lightning information/ alert
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

National Environment Agency
### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Date | Time | Location | Duration

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [X ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

To alert construction workers on potential lightning strikes.

**Comment by lennardl** [comment]
We do not have lightning data
