### ISSUE TITLE
ACRA Dataset missing: `entities-with-unique-entity-number`

### ISSUE THREAD

**Issue by ShefnaB** [datagovsg/datagovsg-datasets#477]
### Please provide the name of the dataset or describe the dataset that you're requesting:

https://data.gov.sg/dataset/entities-with-unique-entity-number

### Do you know which agency provides/can provide this data?

ACRA

### If there's an issue with a dataset, please provide a description of the problem
The above link currently shows as 404 Not Found (re-occurrence of issues: [#403](https://github.com/datagovsg/datagovsg-datasets/issues/403) and [#415](https://github.com/datagovsg/datagovsg-datasets/issues/415) )

**Comment by lennardl** [comment]
@ShefnaB It's back up.

**Comment by ShefnaB** [comment]
Thanks for the update @lennardl !
