### ISSUE TITLE
Dataset request: Demolished HDB blocks

### ISSUE THREAD

**Issue by fbiljecki** [datagovsg/datagovsg-datasets#478]
### Please provide the name of the dataset or describe the dataset that you're requesting:

The [HDB Property Information](https://data.gov.sg/dataset/hdb-property-information) includes data on existing blocks. However, it doesn't include blocks that have been demolished, e.g. under the Selective En Bloc Redevelopment Scheme (SERS).

### Do you know which agency provides/can provide this data?

HDB

### If there's an issue with a dataset, please provide a description of the problem

Information on completed SERS projects is available at [this website](https://www.hdb.gov.sg/cs/infoweb/residential/living-in-an-hdb-flat/sers-and-upgrading-programmes/completed-sers-projects) of the Housing and Development Board. However, the provided information is limited, as it does not contain data included in the HDB Property Information, such as the number of storeys of demolished blocks and their year of construction.

### Please provide the fields expected in this dataset:

All fields available in HDB Property Information topped with specific data on demolished blocks, such as the year of demolition and the replacement site (if SERS). For example:

| blk_no | street | max_floor_lvl | year_completed | ... | year_demolished | replacement site |
| --- | --- | --- | --- | --- | --- | --- |
| 103 | DEPOT RD | 10 | 1964 | ... | 1995 | "103A,DEPOT RD,103B,DEPOT RD"

(Please note that the fields `max_floor_lvl`and `year_completed` in this example are filled randomly for exemplary reasons, due to the lack of actual data.)

### How frequently would you need this dataset to be updated?

- [x] Annually

### Can you give a short explanation on how you're planning to use this dataset?

For studying the historical evolution of HDB blocks, and for estimating the building stock in Singapore at any given point in time in the past.

**Comment by lennardl** [comment]
The data is not be provided by HDB
