### ISSUE TITLE
Dataset request: Singapore Pools Results(Lottery & Sports)

### ISSUE THREAD

**Issue by melvinphua** [datagovsg/datagovsg-datasets#479]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Singapore Pools Results for lottery and sports betting

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Singapore Pools under the Singapore Totalisator Board, a statutory board under the Ministry of Finance.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Sports:
Date & Time|Event|Halftime|Fulltime
1x2|1/2 Goal|Total Goals Over/Under|Halftime-Fulltime|Pick the score|Total Goals|Total Goals odd/even|Halftime Goals Over/Under 

Lottery(4D):
Draw Date|First|Second|Third|Starter|Consolation

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For academic purpose only.

**Comment by lennardl** [comment]
We do not have the data
