### ISSUE TITLE
Dataset request: <Master Plan 2014 Above Ground Line>

### ISSUE THREAD

**Issue by tay-yijun** [datagovsg/datagovsg-datasets#48]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Master Plan 2014 Above Ground Line.
Indicative line showing infrastructure and road lines. 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

Urban Redevelopment Authority

### If there's an issue with a dataset, please provide a description of the problem

The current dataset is incomplete. There are only 129 polylines. 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

FID	Shape *	OBJECTID	OID_1	INC_CRC	FMEL_UPD_D	X_ADDR	Y_ADDR	SHAPE_Leng
0	Polyline	1	0	DECD2174092A1AAA	6/23/2014	27337.1531	42650.2329	431.106391

### How frequently would you need this dataset to be updated?

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

Visualising the road network of Singapore.

**Comment by yongjun21** [comment]
@tay-yijun 
Maybe use this instead: https://www.mytransport.sg/content/dam/mytransport/DataMall_StaticData/LTA_DataMall_GIS_User_Guide.pdf. Check out section on Road Section Lines
