### ISSUE TITLE
Dataset request: <Sunshine Duration- daily >

### ISSUE THREAD

**Issue by kokhua90** [datagovsg/datagovsg-datasets#484]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Sunshine Duration -Daily

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

National Environment Agency
--

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Day| country | duration (hours) 
------|---------|-------------
2019-01-01|Singapore|2

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Academic purpose.

**Comment by lennardl** [comment]
We only have monthly data https://data.gov.sg/dataset/sunshine-duration-monthly-mean-daily-duration
