### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by Keithljx** [datagovsg/datagovsg-datasets#485]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Bus Services
The dataset should contain bus services in Singapore, current and in the past, active and discontinued.
Information on bus services including, routes, start of service, end of service, changes in routes. 
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
MInistry of Transport, SBS transit, SMRT Buses, Tower Transit, Go-Ahead Singapore

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
month and year of bus service starting| bus route current| bus route past and changes| Year of change

### How frequently would you need this dataset to be updated?
Example: 
- [x] *Test*

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Create a visualisation of bus services and their changes across the years

**Comment by lennardl** [comment]
We do not have the data
