### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by isabeltay** [datagovsg/datagovsg-datasets#488]
### Please provide the name of the dataset or describe the dataset that you're requesting:
"Age-standardised incidence rate of the top three cancers by gender and 5-year period" and "Top 5 Leading Cancers by Gender"

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Health Promotion Board / Ministry of Health

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

No. | Name | Title | Type | Unit of Measure | Description
-- | -- | -- | -- | -- | --
1 | period_starting | Period starting | Datetime (Year) "YYYY" | - | -
2 | period_ending | Period ending | Datetime (Year) "YYYY" | - | -
3 | site | Site | Text (General) | - | -
4 | gender | Gender | Text (General) | - | -
5 | asir | ASIR | Numeric (General) | per 100000 Singapore residents | Age standardized incidence rate

No. | Name | Title | Type | Unit of Measure | Description
-- | -- | -- | -- | -- | --
1 | start_of_period | Start of Period | Datetime (Year) "YYYY" | - | -
2 | end_of_period | End of Period | Datetime (Year) "YYYY" | - | -
3 | gender | Gender | Text (General) | - | -
4 | type_of_cancer | Type of Cancer | Text (General) | - | -
5 | incidence_rate | Incidence Rate | Numeric (General) | Per 100,000 per Year | Refers to age-standardised rate (ASR) per 100,000 per year. ASR derived by the direct method using the 'World Population'.
6 | rank | Rank | Text (General) | - | Rank by incidence rate.

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am currently doing a Field Service Project with the National University of Singapore Business School. Our project aims to landscape the current diagnostic market for oncology in Singapore. As such, we are hoping to obtain updated data on the most common types of cancer in Singapore so we can determine the focus of our project appropriately. Your help will be greatly appreciated.

**Comment by lennardl** [comment]
We do not have the data
