### ISSUE TITLE
HDB resale prices not updated on Data.gov

### ISSUE THREAD

**Issue by chang-h** [datagovsg/datagovsg-datasets#49]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
**HDB**

### If there's an issue with a dataset, please provide a description of the problem
**The current dataset runs up till July 2017 only. We are currently missing Q3 / Q4 2017 data.** 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

**month of sale | address | floor level | property type | HDB estate | size | sale price | lat long (if possible) **  

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
**- [X] Monthly**
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
**We are using it for housing research in Singapore, to look at the property market and to understand the movement of resale HDB flats.**

**Comment by iewil** [comment]
@chang-h duplicate issue https://github.com/datagovsg/datagovsg-datasets/issues/51. Closing issue
