### ISSUE TITLE
Dataset request: <air quality>

### ISSUE THREAD

**Issue by adel28-lab** [datagovsg/datagovsg-datasets#493]
### NEA Singapore
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### 

July-August | Singapore| 10000
2019-07|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [x ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am a student and i want to make a research about influence of Riau hotspot to regional area around Riau

**Comment by lennardl** [comment]
https://data.gov.sg/search?q=air+pollutant Its all the end of the list but there's a bunch of other datasets that could be useful.
