### ISSUE TITLE
Dataset request: <Singapore Public Holiday>

### ISSUE THREAD

**Issue by angiechng** [datagovsg/datagovsg-datasets#495]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Singapore Public Holiday 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
https://www.mom.gov.sg

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

Date | Day |Country | Public Holiday
------------ -|-------------|-----------|-----------------
01-Jan-2020|Wednesday|Singapore|New Year's Day
### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Incorporate into project

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/singapore-public-holidays-for-2020
