### ISSUE TITLE
Resale Housing Prices, Capital Appreciation and Household Income 

### ISSUE THREAD

**Issue by jedlagged** [datagovsg/datagovsg-datasets#496]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Resale flat prices, and the corresponding capital appreciation in relation to the initial buying price, and the household income of that particular seller

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Housing Development Board

### If there's an issue with a dataset, please provide a description of the problem
'The resale flat prices' dataset is what I need, but along with the original price that the flat was bought at and the income range of the household that sold it

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Month | Town | Flat Type | Block | Street Name | Storey Range | Floor Area | Flat Model | Lease Commence Date| Remaining Lease | Resale Price **| Bought Price | Income Range of Household |**

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [X ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am writing a dissertation on the distributional wealth effects of public housing in relation to the various income groups. This is to evaluate the 'equitability' of asset appreciation on the various income groups in Singapore.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/resale-flat-prices
