### ISSUE TITLE
child care

### ISSUE THREAD

**Issue by osziemay** [datagovsg/datagovsg-datasets#498]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by osziemay** [comment]
looking for child care for my son

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/child-care-services
