### ISSUE TITLE
Request for Nationwide Sheltered Walkway .shp

### ISSUE THREAD

**Issue by yugispidey** [datagovsg/datagovsg-datasets#501]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Shapefile for nationwide sheltered walkway

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
MND, URA, LTA, HDB

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Longitude | Latitude | Length (metres) | Installation Date | Shape 
103.1 | 1.15 | 100 | 2018-08-12 | Polygon

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
We do not have that data
