### ISSUE TITLE
Dataset request: <Weekly Infectious Disease Bulletin>

### ISSUE THREAD

**Issue by vasudhamanikandan** [datagovsg/datagovsg-datasets#502]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Weekly Infectious Disease Bulletin

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### If there's an issue with a dataset, please provide a description of the problem
not updated to present date. 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

2019-07 - 2019-09 | Singapore | dengue cases

### How frequently would you need this dataset to be updated?
Example: 
- [] *Test*

- [ ] Annually
- [ ] Monthly
- [ X] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

Track and trend dengue epidemic in Singapore.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/weekly-infectious-disease-bulletin-cases
