### ISSUE TITLE
Dataset request: <Singapore trademark publications data>

### ISSUE THREAD

**Issue by Peng-Gong** [datagovsg/datagovsg-datasets#504]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Dear Sir or Madam,
I'm writing from a company called TrademarkNow Inc., that provides online trademark search and watch services worldwide. Our clients include law firms and corporate legal departments, and they use our search engine to clear new trademarks and monitor their existing brands for new threats.

We'd like to inquire about a potential trademark data agreement with Singapore PTO.  In the past, we have collaborated with many country trademark offices on such agreements, and we are interested in acquiring future Singapore updates / publications, in electronic format.

Could you please let me know what our options might be?  (e.g., Would this be free of charge, or any fee for API, FTP or other bulk download for trademark applications and registrations?)

If you are not the correct party to help me with this need, could you please let me know who that party would be?  We'd be happy to provide our legitimated business license if needed.
Thank you very much from TrademarkNow (https://www.trademarknow.com/)!

Best Regards

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Partnership & Programme Department of SG PTO directed us to this place

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ x] Monthly
- [ x] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@Peng-Gong we have APIs available here which are free to use: https://data.gov.sg/dataset/ipos-apis

Do let me know if this works for you.

**Comment by Peng-Gong** [comment]
Hi, thank you very much for the information. We checked the data and found a few issues with it.

1.  Latest applications are 2 months old, so this is not update-to-dated as the official PTO website, https://www.ip2.sg/RPS/WP/CM/SearchSimpleP.aspx?SearchCategory=TM

2. No unpublished marks, PTO website has quite many unpublished marks, and our customers often request for the latest marks posted on PTO website. 

Therefore, we are hoping to have the same data feed as on SG PTO website, if this is possible?

Thank you so much!

**Comment by lennardl** [comment]
@Peng-Gong,
We'll have to check in again to see if we can get everything up to date.

**Comment by Peng-Gong** [comment]
Great, thanks a lot! Please let us know if you will have up-to-date data available.
