### ISSUE TITLE
Dataset request: Visitor International Arrival to Singapore

### ISSUE THREAD

**Issue by huiping-chia** [datagovsg/datagovsg-datasets#505]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Visitor International Arrival to Singapore

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Singapore Tourism Board

### If there's an issue with a dataset, please provide a description of the problem
The excel data only reflects up till 2015, but will need more recent data (ie till 2019).

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | Region | country | no of visitor arrivals

### How frequently would you need this dataset to be updated? *once*
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Planning to use for school project for data with programming as part of SMU masters of science in accounting coursework.

**Comment by lennardl** [comment]
We do not have the data
