### ISSUE TITLE
Dataset request: <Rainfall, CO, NO2, ozone, SO2, Pb, PM2.5, PM10, temperature, relative humidity>

### ISSUE THREAD

**Issue by noortitan** [datagovsg/datagovsg-datasets#506]
### Please provide the name of the dataset or describe the dataset that you're requesting: 
Daily Rainfall, CO, NO2, ozone, SO2, Pb, PM2.5, PM10, temperature, relative humidity January 2009-August 2019.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
National Environment Agency 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2009-01 until 2019-08|Singapore|N/A

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am planning to use the data for climate research on Southeast Asian haze.

**Comment by maxng07** [comment]
Hi Noortitan,

I'm a fellow consumer of the Air Quality/PSI datasets, I've created a relevant app that consume these data.
I just did a check, the current datasets are available from 2017-01-01 to Now. Any earlier datasets does not seems available. Thought this might help while you wait for a reply or make do with whatever is available first.

The API for the PSI data are here as an example, just change the date to what you need
https://api.data.gov.sg/v1/environment/psi?date="2016-01-01"
https://api.data.gov.sg/v1/environment/psi?date="2017-01-01"

There are relevant datasets for temperature and humidity too, you might want to probe how far back the datasets are currently available.
More info are available here https://data.gov.sg/group/environment

Hope this helps.

/Max
PS: I'm a fellow consumer of NEA/MSS datasets, I do not work for Govtech.
