### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by alexissinglaire** [datagovsg/datagovsg-datasets#507]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Pollutant Standards Index (PSI)
Ultra-violet Index (UVI)
PM2.5

### Do you know which agency provides/can provide this data?
National Environment Agency 

 ### Please provide the fields expected in this dataset:
month | country | passengers
------|---------|-------------
2019|Singapore|N.A

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [x] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To provide weather and air quality index of Singapore in my mobile app TakeWhatBus SG, so the users can also get information on singapore air quality. To provide quality information for SG users that using my mobile app.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/ultraviolet-index-uvi
https://data.gov.sg/dataset/pm2-5
https://data.gov.sg/dataset/psi
