### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by khoo0157** [datagovsg/datagovsg-datasets#508]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Foreign Workforce Numbers, Annual 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Manpower

### If there's an issue with a dataset, please provide a description of the problem
Data points from the past missing

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
(Year | Number of Employment Pass holders | Number of S Pass holders | Number of Work Permit Holders (FDW) | Number of Work Permit holders (Construction) | Other Work Passes )

From 2004 to 2019

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [x] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
My group is doing a presentation on the foreign worker numbers and how the government policies have a direct impact on these numbers, based on the government's focus on developing Singapore's industry (from focusing on cheap labour to increasing productivity)

**Comment by lennardl** [comment]
We do not have the data
