### ISSUE TITLE
Dataset request: Pollutant Standard Index Data (PSI 

### ISSUE THREAD

**Issue by pankajm83** [datagovsg/datagovsg-datasets#510]
### Please provide the name of the dataset or describe the dataset that you're requesting:

I am requesting PSI data set for Singapore link is :
https://data.gov.sg/dataset?q=PSI

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Currently I am learning Applied Plotting and Charting course from "Coursera". At the end of the assignment I have to submit my analysis on the independent data set "Becoming an Independent Data Scientist". I need dataset for my analysis.

**Comment by lennardl** [comment]
Data provided at the URL you mentioned
