### ISSUE TITLE
Dataset request: smoking rates in SG 

### ISSUE THREAD

**Issue by yeowxuan** [datagovsg/datagovsg-datasets#511]
Would like to acquire data regarding the number of people who smoke at least one cigarette a day. 
Monthly or quarterly data would be ideal, otherwise annually would work as well. 

Data will be used for an Economics Honours Thesis to assess the efficacy of introducing curbs on smoking in public areas. Ultimate goal is to evaluate whether Singapore will be able to achieve its projected smoking rate of less than 10% by 2020.  

Thank you

**Comment by lennardl** [comment]
We do not have that data
