### ISSUE TITLE
Dataset request: ERP Locations by zone

### ISSUE THREAD

**Issue by why-2004** [datagovsg/datagovsg-datasets#512]
### Please provide the name of the dataset or describe the dataset that you're requesting:
ERP Locations as coordinates/KML/GeoJSON sorted by zone

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
LTA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

coordinates | zone name 

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
use as visual markers on maps to show the distribution of ERP prices by zone

**Comment by lennardl** [comment]
We do not have that data
