### ISSUE TITLE
Dataset request: Food stalls at hawker centres

### ISSUE THREAD

**Issue by kevalshah90** [datagovsg/datagovsg-datasets#513]
### Please provide the name of the dataset or describe the dataset that you're requesting:

We would like a list of stalls - food in hawkers centres in singapore. 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

NEA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

food stall name, open date, address, geo coordinates, cuisine type. 

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

We are gathering information on hawker operations in singapore.

**Comment by lennardl** [comment]
We only have the topline numbers of total hawker stalls
