### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by LinXing1994** [datagovsg/datagovsg-datasets#514]
### Please provide the name of the dataset or describe the dataset that you're requesting:
List of Pre schools in Singapore for year 2008, 2014 and 2019 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

https://data.gov.sg/dataset/pre-schools-location
As I noticed, my school seniors has previously found this data set from data.gov.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

address, postal code,  student quantity, name of school, subzone 

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
It is a school project that was given by our prof. We need to analysis the changes from year 2008-2014-2019 in Singapore. Therefore, this data is extremely important for us, as it is one of our criteria.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/listing-of-centres we do not have historical data
