### ISSUE TITLE
smart trash sensor data in singapore

### ISSUE THREAD

**Issue by cher313** [datagovsg/datagovsg-datasets#515]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [x] Hourly
- [ ] Real-time

**Comment by cher313** [comment]
i am  currently working on my FYP about waste management in Singapore. so the smart trash sensor data is important for my research. i want to enquire their locations and real-time tracking data. Thankl you for your help!

**Comment by lennardl** [comment]
We do not have the data
