### ISSUE TITLE
Dataset request: <Population Distribution>

### ISSUE THREAD

**Issue by BeacherChen** [datagovsg/datagovsg-datasets#517]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Population spatial distribution data (by blocks)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
LTA, HDB

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | 
------|---------|-------------
2017-09|Singapore|

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Working on a school project that requires me to look at the aged population and their proximity to facilities. I really need population data (grouped by ages) and their spatial distribution.

**Comment by lennardl** [comment]
We do not have the data
