### ISSUE TITLE
Dataset request: sla-cadastral-land-parcel updates

### ISSUE THREAD

**Issue by bensonc** [datagovsg/datagovsg-datasets#52]
### Please provide the name of the dataset or describe the dataset that you're requesting:
[https://data.gov.sg/dataset/sla-cadastral-land-parcel](https://data.gov.sg/dataset/sla-cadastral-land-parcel)

### Do you know which agency provides/can provide this data?
SLA

### If there's an issue with a dataset, please provide a description of the problem
Information has not been updated since mid July 2017. Some changes are reflected on OneMap but are not in the data set. e.g 10B and 10C SALLIM ROAD SINGAPORE 387641 was subdivided recently into 2 separate land parcels.

### Please provide the fields expected in this dataset:
The existing fields are ok.

### How frequently would you need this dataset to be updated?
- [ ] Annually
- [ ] Monthly
- [X] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by iewil** [comment]
@bensonc an update for the datasets on data.gov.sg is in progress. Sorry for the inconvenience caused.

**Comment by justinelliotmeyers** [comment]
is there a link for this on the open data portal? Thanks!
