### ISSUE TITLE
Dataset request: HDB Property Information 

### ISSUE THREAD

**Issue by gloriatansl** [datagovsg/datagovsg-datasets#520]
### Please provide the name of the dataset or describe the dataset that you're requesting:
HDB Property Information 

### Do you know which agency provides/can provide this data? HDB
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset: All fields that was listed on website of dataset.gov.sg
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ v] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to u
Fundraising for charities

**Comment by lennardl** [comment]
Does this work for you: https://data.gov.sg/dataset/hdb-property-information
