### ISSUE TITLE
Dataset Request: LTA Car registration

### ISSUE THREAD

**Issue by IgnatiusJHTan** [datagovsg/datagovsg-datasets#524]
### Please provide the name of the dataset or describe the dataset that you're requesting:

LTA Car registration data 

### Do you know which agency provides/can provide this data?
Land Transport Authority

### If there's an issue with a dataset, please provide a description of the problem
Lack of information regarding OMV on cars

### Please provide the fields expected in this dataset:

|Make/Model | COE paid | Date | OMV |
eg. Toyota Camry | 35,000 | 2015 | 23,000|

### How frequently would you need this dataset to be updated?
Example: 

- [ ] Annually
- [x] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Planning on using this data to extrapolate the depreciation and expected prices of cars in the secondhand market for a project in Data modelling and Analytics in Singapore Management University.

**Comment by lennardl** [comment]
We do not have the car registration data, there are top line numbers that's available on LTADataMall
