### ISSUE TITLE
Dataset request: Most Common Cause of Death by Age Group Annually

### ISSUE THREAD

**Issue by dszs95** [datagovsg/datagovsg-datasets#525]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Most Common Cause of Death by Age Group Annually - What is the most common cause of death for each age group.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Health
Ministry of Home Affairs - Immigration & Checkpoints Authority

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

year | age group | most common cause of death 
------|---------|-------------
2016 | 40-60 | Cancer

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To analyse the relation between age group and cause of death

**Comment by lennardl** [comment]
@dszs95 Does this work for you?
https://data.gov.sg/dataset/deaths-by-cause-and-type-of-certification?view_id=09cd7268-797e-4698-93e8-cb71d11481e3&resource_id=646e62ac-54ae-4d5d-bc14-962cea854c61

**Comment by dszs95** [comment]
As mentioned, doesn't fit the 3rd criteria. We do not have age group.

**Comment by lennardl** [comment]
This dataset has the gender and age group breakdown. 
https://data.gov.sg/dataset/death-by-cause-and-age-group?view_id=5b598623-23fc-4e18-aa2f-54e117f22d4a&resource_id=04787aed-3c46-4854-839f-6c0755a2ffdc

**Comment by dszs95** [comment]
Oh, just saw it. Thanks! Is there a way to get different years of data from this set. So far, I can only see 2018, preferably I could get at least the past 3 to 5 years of data?

**Comment by lennardl** [comment]
@dszs95 Not at the moment, I need to approach the data owner for more historical data. It might take time.

**Comment by agentsimar** [comment]
@lennardl Hello, kindly approach the data owner as it would be extremely helpful.

**Comment by lennardl** [comment]
@agentsimar / @dszs95  I've approached ICA for the data, waiting on a response.
