### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by sterlingass** [datagovsg/datagovsg-datasets#526]
### Please provide the name of the dataset or describe the dataset that you're requesting:
List of companies registered from 1979 to present by postcode

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
ACRA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
01-1979 to present, Singapore
month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
No need for update, request based on historical records
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Research

**Comment by lennardl** [comment]
@sterlingass We do not have postal code data on data.gov. For data related to postal code you would have to approach SingPost.
