### ISSUE TITLE
Dataset request: age wise casue of death of Singapor in the year 2016

### ISSUE THREAD

**Issue by jrai81** [datagovsg/datagovsg-datasets#527]
### Please provide the name of the dataset or describe the dataset that you're requesting:
age wise casue of death of Singapor in the year 2016

### Do you know which agency provides/can provide this data?

*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

year |Age  | Cause of death
------|---------|-------------
2016|14-49|Cancer 

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [. ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Need to create a visualization for my assignment.

**Comment by lennardl** [comment]
@jrai81 Does this work for you?
https://data.gov.sg/dataset/death-by-cause-and-age-group?view_id=5b598623-23fc-4e18-aa2f-54e117f22d4a&resource_id=04787aed-3c46-4854-839f-6c0755a2ffdc

**Comment by lennardl** [comment]
We do not have the historical data
