### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by ptpmashish** [datagovsg/datagovsg-datasets#53]
### Please provide the name of the dataset or describe the dataset that you're requesting:
In fact i dont need a data set. I just need to know the number of buildings in singapore. all buildings. thats it. no need of any classification. 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
no. checked online couldnt find. property department should be able to

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

no of buildings = X 

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

once. 

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

I'm trying to understand how the population is fitting into the number of buildings we have. and how any more we would need to accommodate a specific increase in population.

**Comment by iewil** [comment]
@ptpmashish You'll have to aggregate existing datasets to get the figure that you're requesting for. We try to provide as much granularity for each of our datasets to make them more reusable, so we won't be able to provide it as is. Sorry for the inconvenience caused. 

To get building data, you can make use of the APIs provided by [OneMap](https://docs.onemap.sg/).
