### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by Dawnkoh** [datagovsg/datagovsg-datasets#530]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Annual number of births with Down Syndrome for the last 20 years

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Year | country | births with Down Syndrome
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To improve awareness and understanding of Down Syndrome in Singapore

**Comment by lennardl** [comment]
We do not have the data
