### ISSUE TITLE
Dataset request: Death by cause and age group and gender

### ISSUE THREAD

**Issue by mudrag** [datagovsg/datagovsg-datasets#531]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Death by cause and age group and gender (for 2016)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Home Affairs - Immigration & Checkpoints Authority

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Cause of death, age range and amount 

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Will be used for educational purposes to complete an assignment

**Comment by lennardl** [comment]
https://data.gov.sg/search?q=death
