### ISSUE TITLE
Internet users in Singapore by age and gender

### ISSUE THREAD

**Issue by Yatish84** [datagovsg/datagovsg-datasets#532]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I am looking for internet users by age, gender and region

### Do you know which agency provides/can provide this data?
Not sure

### Please provide the fields expected in this dataset:
Age | Gender | Region | Total Population

### How frequently would you need this dataset to be updated?
Real Time

### Can you give a short explanation on how you're planning to use this dataset?
We are running a survey for which the sample criteria is internet users. We will use this data to run RIM weighting on the sample collected.

**Comment by lennardl** [comment]
@Yatish84 We only have the internet users by age group. We do not have it defined by region or sex https://data.gov.sg/dataset/individual-internet-usage?resource_id=e81b1683-7d5f-4f35-a4d9-4240ae5002bb

**Comment by Yatish84** [comment]
Thanks for this. This works
