### ISSUE TITLE
Dataset request: <Personal Vehicle Details>

### ISSUE THREAD

**Issue by SeanDavidOng** [datagovsg/datagovsg-datasets#534]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Personal Vehicle Data/details

### Do you know which agency provides/can provide this data? LTA
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Hi, can we request API to access: 
personal vehicle chasis number, 
engine number and capacity, 
vehicle make/model, attachement (if any) and 
registration date?  

We have explicit vehicle owner consent before extracting data for car insurance purpose. thank you

### How frequently would you need this dataset to be updated?
 Real-time, as and when the vehicle changes ownership

### Can you give a short explanation on how you're planning to use this dataset?
we will use the data to enable auto filling of an online form to aid a quick generation of real time car insurance quotation.

**Comment by lennardl** [comment]
@SeanDavidOng We do not have that level of details on vehicle ownership. You would have to approach LTA to ask if such data can be made available.
