### ISSUE TITLE
Dataset request: Historical Air Pollution Data 2013-2019

### ISSUE THREAD

**Issue by plearnaroonchote** [datagovsg/datagovsg-datasets#535]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Historical air quality data from 2013 to the the present that includes hourly (preferred) or daily readings for nitrogen dioxide, sulfur dioxide, carbon monoxide, particulate matter PM 2.5, ozone.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

National Environmental Agency

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

date | hour |  PM 2.5 concentration | ozone | nitrogendioxide | sulfurdioxide | carbonmonoxide | monitor location | lat. long. |
------|---------|-------------| --------| -------| ----------------| --------------| -------------|
2017-09-01|18:00| 5| 2.3 | 5.7| 3.2 | singapore central | 

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

I'm not clear what the question is asking but once we receive the data, we don't need an update. But would like hourly or daily time series for the above pollutant concentrations.

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly 
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

I'm a third-year student researcher from Tufts University in Massachusetts, USA. I am doing a research project for my environmental health data lab class on how air pollution particles from open burning in Indonesia are transported across the region to cities like Singapore. I will use the data to do a statistical analysis of the historical air pollution plumes.

**Comment by maxng07** [comment]
Hi, 

I'm a fellow consumer of these datasets. What you need is in this API and it provides a daily readings.
See here
https://data.gov.sg/dataset/psi

I did a check, it currently has datasets from 2017-01-01 to now.
You might want to correlate Wind Speed and Wind Direction.

Hope this helps.
Please post your report on your analysis, it will be a huge dataset to analyse.
