### ISSUE TITLE
Dataset request: NEA study on food wastage by households

### ISSUE THREAD

**Issue by Sanjay1345** [datagovsg/datagovsg-datasets#536]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
National Environmental Agency (NEA) and SEC (Singapore Environment Council)

### If there's an issue with a dataset, please provide a description of the problem
NEA provides data on overall food wastage data on its official website. However, I would like to request further details about NEA, about the "NEA study on household waste showed that 54 percent of food waste generated by households would not have been binned if people adopted a more prudent approach towards managing their food."
Read more at https://www.todayonline.com/singapore/more-half-food-thrown-away-households-can-be-avoided-nea-study 
I would also like to ask for details regarding a joint study by the Singapore Environment Council (SEC) and consulting firm Deloitte published last month. 
As part of the study, about 1,000 respondents were surveyed online to determine Singaporeans’ food storage behavior, purchasing patterns and food handling habits.
Read more at https://www.todayonline.com/features/trash-talk-battle-food-waste-bulge-why-you-should-throw-away-less-food

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [X ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am requesting for these datasets for my Extended Essay Paper, so as to write on the economic impacts of food wastage in Singapore.

**Comment by lennardl** [comment]
Data is not available
