### ISSUE TITLE
Dataset request: <Master Plan 2014 Planning Area Boundary (Web)>

### ISSUE THREAD

**Issue by toutengya** [datagovsg/datagovsg-datasets#538]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Master Plan 2014 Planning Area Boundary (Web)

### Do you know which agency provides/can provide this data?
Urban Redevelopment Authority

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Annually*
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I want to use it in my research. I am an NTU student.

**Comment by lennardl** [comment]
The data can be downloaded here: https://data.gov.sg/dataset/master-plan-2014-planning-area-boundary-web
