### ISSUE TITLE
Dataset request: <Historical Dengue Clusters, Temperature and rainfall>

### ISSUE THREAD

**Issue by WilliamAung** [datagovsg/datagovsg-datasets#539]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Location| DateTime| Temperature
------|---------|-------------
Clementi|1200|32.5°C

Location| DateTime| Rainfall(mm)
------|---------|-------------
Clementi|1200| 0

Location| DateTime| Number of Dengue Cases
------|---------|-------------
Jurong West|1200| 4

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [✓ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
We are students from Ngee Ann Polytechnic, and are currently doing a project predicting future dengue clusters using trends in historical data. To achieve this, we would require past record of temperature, rainfall and if possible dengue cases over the past few years(5 if possible)

**Comment by lennardl** [comment]
@WilliamAung Does this work for you?
Rainfall: https://data.gov.sg/dataset/rainfall-monthly-total
Temperature: https://data.gov.sg/dataset/surface-air-temperature-monthly-mean
Dengue cases: https://data.gov.sg/dataset/weekly-number-of-dengue-and-dengue-haemorrhagic-fever-cases
