### ISSUE TITLE
Zip codes / Subzones / Postal Districts

### ISSUE THREAD

**Issue by shannonajw** [datagovsg/datagovsg-datasets#54]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Zip codes / Subzones / Postal Districts

### Do you know which agency provides/can provide this data?
URA, SingPost can definitely provide this data, if they are not trying to be secretive about it.

### Please provide the fields expected in this dataset:
Zipcodes; Subzone (according to URA Masterplan 2014, 2008), Postal District

zipcode | sub zone | planning area | postal district
---------|----------|---------------|--------------
012984  | Cheng San | Ang Mo Kio | Ang Mo Kio

### How frequently would you need this dataset to be updated?
Whenever the zipcode system changes, new URA Masterplan comes out, or Postal Districts change.

### Can you give a short explanation on how you're planning to use this dataset?
Having this will enable social surveys conducted in Singapore to be geocoded (without the worry for identification). This can help to bolster research on population health. E.g. Link noise pollution in a certain area to individual health outcomes.

**Comment by iewil** [comment]
@shannonajw Singpost is a private company so we won't be able to get their data on our site. To compile the dataset that you're asking for, you can make use of the following datasets:

1. Subzone boundary: https://data.gov.sg/dataset/master-plan-2014-subzone-boundary-web
2. Planning area boundary: https://data.gov.sg/dataset/master-plan-2014-planning-area-boundary-web
3. Postal code: [OneMap API query](https://docs.onemap.sg/)
