### ISSUE TITLE
Dataset request: Bus Arrival in HTTPS

### ISSUE THREAD

**Issue by ronnieong** [datagovsg/datagovsg-datasets#544]
http://datamall2.mytransport.sg/ltaodataservice/BusArrivalv2?BusStopCode=83139

Would like to request that the bus arrival API provided by LTA at Datamall be available in also HTTPS format.

Am requesting for this as I am writing an app for Garmin watches and they only work with HTTPS. Also understand that there is a shift towards HTTPS and disallowing HTTP in general.

**Comment by achrinza** [comment]
@random85 This is unfortunately an ever-going issue. Currently I've circumvented this issue by hosting an [API wrapper for LTA Datamall](https://github.com/apprexp/ltadatamall-wrapper).

Disclaimer: I'm the author
