### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by Louis5227** [datagovsg/datagovsg-datasets#546]
### Please provide the name of the dataset or describe the dataset that you're requesting:
The amount of parking lots in Singapore

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
NA

### If there's an issue with a dataset, please provide a description of the problem
NA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2018-12|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@Louis5227 We have information on public car park lots that can be found in the link below. We do not have information on parking lots in commercial or private buildings:
https://data.gov.sg/search?q=parking+lots
