### ISSUE TITLE
Dataset request: Update "Available and Vacant Private Residential Properties"

### ISSUE THREAD

**Issue by raoulalwani** [datagovsg/datagovsg-datasets#547]
### Please provide the name of the dataset or describe the dataset that you're requesting:

https://data.gov.sg/dataset/available-and-vacant-private-residential-properties?resource_id=51b4a66e-1f95-453e-9206-f6314e7cb1bc

The data is up until 2015 only, it would be good for it to be updated to 2019 figures, and also updated quarterly. 

### Do you know which agency provides/can provide this data?
*URA/SLA? Unclear, agency source is not listed on the data page.*

### If there's an issue with a dataset, please provide a description of the problem

The current data is up until 2015 only, it would be good for it to be updated to 2019 figures, and also updated quarterly. 

It would also be good to provide some basic definitions (ie, what is the difference between "Apartment" and "Condominium Unit"?)

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

quarter | type_of_property | availability | no_of_private_residential_properties
------|---------|-------------|-------
2019-Q3| Apartments | Vacant | 385

### How frequently would you need this dataset to be updated?
Example: 

- [x] Quarterly

### Can you give a short explanation on how you're planning to use this dataset?

Analysis of the property market

**Comment by raoulalwani** [comment]
@lennardl just bumping this, thanks

**Comment by lennardl** [comment]
@raoulalwani I've managed to update the quarterly numbers. Note there's a change in categories for the figures. Do not have the official annual figures.

**Comment by raoulalwani** [comment]
@lennardl thanks for the quick reply -- do you have the updated link to the dataset? My originally posted one seems to be broken now, and I couldn't find it via the Search feature on data.gov.sg

**Comment by lennardl** [comment]
@raoulalwani Can you try this https://data.gov.sg/dataset/available-and-vacant-private-residential-properties ?

**Comment by raoulalwani** [comment]
@lennardl it works, thanks! Was the URL previously broken temporarily? Or was it something on my browser? Both my original link and your newly posted link were throwing a 404 earlier this week, though both are working now.

In any case, appreciate the quick turnaround! Will see if the quarterly data is usable by the team. 

Any chance for the annual data getting updated in early 2020?
