### ISSUE TITLE
Dataset request: Postal Code to Town Council Mapping

### ISSUE THREAD

**Issue by LimBrianSG** [datagovsg/datagovsg-datasets#549]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Hi, 
I would like to request for a dataset of a list of Postal Code and the town council they belongs to.
Thanks in advance
Regards
Brian

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am exploring the feasibility of creating a feature in my website where result of the town council can be returned, as well as the svg map will be highlighted, when user keys in the postal code to perform search

**Comment by lennardl** [comment]
@LimBrianSG Postal code information belongs to SingPost. You will need to approach SingPost for postal code related information.
