### ISSUE TITLE
Dataset request: Central Provident Fund Interest Rates

### ISSUE THREAD

**Issue by nataziaperez** [datagovsg/datagovsg-datasets#55]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Central Provident Fund Interest Rates

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Central Provident Fund Board

### If there's an issue with a dataset, please provide a description of the problem
I would just like to confirm the frequency of this dataset. In the excel file provided, data is monthly however in the “About this dataset” section on your website, the frequency is quarterly. This is a bit confusing. 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
We are from Thomson Reuters and we are planning to distribute this data on our product with accordance to your policies and regulations.

**Comment by nataziaperez** [comment]
![cpf](https://user-images.githubusercontent.com/33511756/33532282-51306650-d8d3-11e7-969d-8014f077d8a4.jpg)

**Comment by iewil** [comment]
Reference: https://data.gov.sg/dataset/cpf-interest-rates

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/monthly-interest-for-cpf-members
