### ISSUE TITLE
Dataset request: KML file of Town council boundaries

### ISSUE THREAD

**Issue by LimBrianSG** [datagovsg/datagovsg-datasets#550]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Hi All,
I would like to request KML file of town council boundaries for Singapore

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am testing the feasibility of using the KML file with GeoJson to create a feature where user can locate a region (e.g. West Code Town Council) with the postal code entered.

**Comment by lennardl** [comment]
Does this work? https://data.gov.sg/dataset/master-plan-2014-subzone-boundary-web
