### ISSUE TITLE
Dataset request: high resolution traffic images

### ISSUE THREAD

**Issue by zzeniale** [datagovsg/datagovsg-datasets#551]
### Please provide the name of the dataset or describe the dataset that you're requesting:
high resolution traffic images (compared to existing images from https://data.gov.sg/dataset/traffic-images)

### Do you know which agency provides/can provide this data?
LTA

### If there's an issue with a dataset, please provide a description of the problem
N.A.

### Please provide the fields expected in this dataset:

|date | time | image
|------|---------|-------------
|2019-11-10|20:17| image.png

### How frequently would you need this dataset to be updated?

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [x] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am working on a project to use the checkpoint images to automatically identify traffic levels, and provide commuters with current and past information to help them make decisions on when to cross.

**Comment by lennardl** [comment]
@zzeniale We are not able to provide higher resolution images.
