### ISSUE TITLE
Dataset request: Singapore weather real time 

### ISSUE THREAD

**Issue by sherylsimi** [datagovsg/datagovsg-datasets#552]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Realtime weather data in Singapore 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
NEA 

### If there's an issue with a dataset, please provide a description of the problem
https://api.data.gov.sg/v1/environment/wind-speed
https://api.data.gov.sg/v1/environment/air-temperature

is not in real time
the most recent data is from 6 days ago. 
Could you help me check it?

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

-

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [x] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
NTU ADM Final Year Project research and exploration

**Comment by maxng07** [comment]
I have the same ask. I check in the last hour, the JSON schema returns empty field. Is the dataset still valid and maintain?

From the website, last update is on February 13, 2018, 14:51 (SGT).

**Comment by lennardl** [comment]
Hi,
We are aware of the issue and working with NEA to restore the service.

**Comment by maxng07** [comment]
Thanks Lennard for the update. Just a suggestion/feedback, I know there is no SLA to the API datasets. It would be nice to have some notice posted both on website(data.gov.sg) and within the JSON schema to indicate the availability of service. The current dataset has "api_info":{"status":"healthy"}, perhaps this can be updated so that we will know and be able to provide the right info to our downstream users of our apps to seek info from else where while GovTech/NEA restore the service.

**Comment by lennardl** [comment]
Hi @maxng07 ,
Thanks for the feedback we'll see what we can do about the messaging. In the meantime, we are still working with NEA to restore the service.

**Comment by maxng07** [comment]
@lennardl  - thanks. I just check, the 4 datasets for Realtime Weather Readings across Singapore
are now available.

**Comment by lennardl** [comment]
@maxng07 We restored the service with NEA and will be asking them to backfill the data lost over last weekend.
