### ISSUE TITLE
Dataset request: <Location of Recycling Bins in myNEV app>

### ISSUE THREAD

**Issue by sandra-teo** [datagovsg/datagovsg-datasets#553]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Location of Recycling Bins in myNEV mobile application.

### Do you know which agency provides/can provide this data?
National Environmental Agency

### Please provide the fields expected in this dataset:
Locations of the different recycling / waste bins in Singapore.

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am currently a student from NTU School of Electrical and Electronic Engineering, and I am currently doing my Final Year Project. 
My mobile application is on educating Singaporeans on recycling and I would like to input the location of the recycling bins in my mobile application. This is purely for testing purposes and for my Final Year Project.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/recycling-bins
