### ISSUE TITLE
Dataset request: <Criminal Records>

### ISSUE THREAD

**Issue by neowenshun** [datagovsg/datagovsg-datasets#554]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Criminal Records

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Home affairs , Singapore Police force

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | Name | Offence | Location of incident |
2017-09|John|Money Laundering| Bedok

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [x ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this data set?
I would like to create a automated background checking for employers to utilize when handling applicants. This data set will be one of many that will be cross referenced before coming up with a suggestion for the employers.

**Comment by lennardl** [comment]
We do not have that data broken down to the details you nedd
