### ISSUE TITLE
Taxi Availability API not working

### ISSUE THREAD

**Issue by tatatee** [datagovsg/datagovsg-datasets#555]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Taxi Availability API

### Do you know which agency provides/can provide this data?
LTA

### If there's an issue with a dataset, please provide a description of the problem
Data is not displaying on the map

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*
- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [X] *Real-time*

### Can you give a short explanation on how you're planning to use this dataset?
Product demo

**Comment by achrinza** [comment]
It seems to be working at my end.

![image](https://user-images.githubusercontent.com/25147899/69519211-6b6b6c00-0f94-11ea-89a9-ec9b015285a8.png)
