### ISSUE TITLE
Dataset request: <Medical Practitioner Information >

### ISSUE THREAD

**Issue by thsanti13** [datagovsg/datagovsg-datasets#556]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Medical Practitioner Information 

### Do you know which agency provides/can provide this data?
https://prs.moh.gov.sg/prs/internet/profSearch/main.action?hpe=SMC

### If there's an issue with a dataset, please provide a description of the problem
Currently there's no online api for particular dataset

### Please provide the fields expected in this dataset:
Please refer to attached ( i added yaml file inside)
[doctor.zip](https://github.com/datagovsg/datagovsg-datasets/files/3862124/doctor.zip)

### How frequently would you need this dataset to be updated?
Example: 
- [] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [X ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Upon assessing claims currently our claim assessor will manually retrieve the attending doctor information to SMC website. We want to automate this process by retrieving the information electronically through api.

**Comment by lennardl** [comment]
The data is on the site you mentioned and MOH is not porting the data over
