### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by rose160302** [datagovsg/datagovsg-datasets#557]
### Please provide the name of the dataset or describe the dataset that you're requesting:
total number of traffic accident in Singapore in 2018

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
Data can be inferred from https://data.gov.sg/dataset/causes-of-road-accidents-causes-of-accidents-by-severity-of-injury-sustained
