### ISSUE TITLE
Dataset request: shopping malls

### ISSUE THREAD

**Issue by yongwee** [datagovsg/datagovsg-datasets#558]
### Please provide the name of the dataset or describe the dataset that you're requesting:
List of shopping malls in Singapore

### Do you know which agency provides/can provide this data?
Urban Redevelopment Authority (probably?)

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

name | address | lat | lon
-----------------|------------------------------------|---|---
Ion Orchard Mall | 2 Orchard Turn, Singapore 238801 | 10 | 10

### How frequently would you need this dataset to be updated?
Example: 

- [ ] Annually
- [x] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Making a shopping directory app for people to conveniently find the stores they're looking for.

**Comment by lennardl** [comment]
We do not have that data
