### ISSUE TITLE
Dataset request: Security Agencies

### ISSUE THREAD

**Issue by mntserious** [datagovsg/datagovsg-datasets#559]
### Please provide the name of the dataset or describe the dataset that you're requesting:
List of Security Agencies approved by Singapore Police Force along with UEN

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Singapore Police Force

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

AgencyName | UEN | ApprovalDate | ExpiryDate
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
We do not have that data
