### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by pmtan666** [datagovsg/datagovsg-datasets#56]
### Please provide the name of the dataset or describe the dataset that you're requesting:
_A dataset for all the addresses in Singapore.
This dataset will help to identify whether it is a valid address in Singapore._ 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
_One of them might be HDB, more agencies might be involved to get a complete set of data._

### If there's an issue with a dataset, please provide a description of the problem
_Not available at this time._

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

_AddressID | Block | StreetName | BuildingName | Floor | Unit | PostalCode | BuildingType | UnitType

BuildingType refers to whether it is a HDB unit, private house, JTC, condo etc.
UnitType refers to whether it is a 2-room, 3-room units, used mainly by HDB units._

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [X] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
_With the dataset, we will be able to identify whether the address provided is a valid address._

**Comment by iewil** [comment]
@pmtan666 This is a duplicate issue #46

**Comment by pmtan666** [comment]
Liwei,

This is not a duplicate issue. The request type is to include up to the unit level.
Currently, the mentioned issue #46 does not include unit level.

Please reopen the issue.


Thanks
John

**Comment by yongjun21** [comment]
@pmtan666 As mentioned on https://github.com/datagovsg/datagovsg-datasets/issues/46#issuecomment-347145513, the ONLY official source for this data for now is OneMap and you'll have to use their [geocoding API](https://docs.onemap.sg/#search).
