### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by garywongwy** [datagovsg/datagovsg-datasets#562]
### Please provide the name of the dataset or describe the dataset that you're requesting:
National Survey of R&D 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
A*STAR 

### If there's an issue with a dataset, please provide a description of the problem
The data available on Research and Development pulled from the National Survey of R&D is that of aggregated data. e.g.) Total private R&D expenditure in Singapore. 

Referring to the National Survey of R&D report, the survey is conducted on different organisations such as Local SMEs, Local LEs and Foreign Company but the data produced is that of aggregated data, and not the individual responses for each different firms. 

Require the raw data before aggregation on each individual organisation e.g.) Research expenditure by 'Firm X' (SME) on R&D

### Please provide the fields expected in this dataset:

e.g.)
Organisation|Sector|Industry|R&D expenditure category|Private source of R&D funding|Public Source of R&D funding|Total R&D personnel employed| 
------------- |------|-------------
Firm X|SME|Bio-Medical Sciences|Land, Buildings and other structures|$XXX|$XXX|

### How frequently would you need this dataset to be updated?

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

I intend to conduct econometric analysis on the various R&D factors affecting firm level performance in Singapore

**Comment by lennardl** [comment]
@garywongwy We have approached A-Star for the data and will revert once we have gotten a response from them

**Comment by garywongwy** [comment]
@lennardl Thank you for responding. Look forward to hearing from you soon.
