### ISSUE TITLE
Dataset request: HDB Town Planning Areas

### ISSUE THREAD

**Issue by saimingliew** [datagovsg/datagovsg-datasets#563]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Planning area by HDB towns

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

SLA, HDB, URA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

HDB town boundaries

### How frequently would you need this dataset to be updated?
Example: 
- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

Map HDB resale and rental prices to different HDB towns

**Comment by lennardl** [comment]
@saimingliew The last data we have can be found here: https://data.gov.sg/dataset/master-plan-2014-planning-area-boundary-no-sea the next refreshed is not due yet.
