### ISSUE TITLE
Dataset request: Number of drivers by class by age by year

### ISSUE THREAD

**Issue by rockerbun** [datagovsg/datagovsg-datasets#564]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I want to know the number of drivers in Singapore
- By Age
- By Year
- By Class

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
No i dont

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Year | Age | Class | Drivers Count
-----|------|-------|---------------|
2018|18|Class 3|10000 
2018|55|Class 4|10880
2018|58|Class 4A|10087

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I want to know the drivers in Singapore for study purpose.

**Comment by lennardl** [comment]
We do not have the breakdown of the data in that manner only the top line numbers
