### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by ericalearn** [datagovsg/datagovsg-datasets#565]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Singapore Police Force Fixed Speed Cameras

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Home Affairs - Singapore Police Force

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time
- [X] *Test*
### Can you give a short explanation on how you're planning to use this dataset?
to train and code ML detection

**Comment by lennardl** [comment]
https://data.gov.sg/search?q=speed+camera
