### ISSUE TITLE
Dataset request: <HDB BTO Price from year 2005 based on township>

### ISSUE THREAD

**Issue by LOUISEXIA888** [datagovsg/datagovsg-datasets#568]
### Please provide the name of the dataset or describe the dataset that you're requesting:
HDB BTO Price from year 2005 based on township

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Housing and Development Board

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

quarter | town | flat-type | median_price
------|---------|-------------
2005-Q2 | Ang MO KIO | 1-RM | 250000
--
### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Quarterly from year 2005

### Can you give a short explanation on how you're planning to use this dataset?
This is for my assignment for Specialist Diploma in Data Science

**Comment by lennardl** [comment]
We do not have historical data only the current BTO prices
