### ISSUE TITLE
NEA Datasets not updated

### ISSUE THREAD

**Issue by karrkh** [datagovsg/datagovsg-datasets#569]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Dengue, mosquito and zika related datasets. See below.

### Do you know which agency provides/can provide this data?
National Environment Agency

### If there's an issue with a dataset, please provide a description of the problem
1. "dengue-cases-central"  - Not updated for at least 1 month despite frequency stated to be daily
2. "dengue-cases-north-east" - Not updated for at least 1 month despite frequency stated to be daily
3. "dengue-cases-south-east" - Not updated for at least 1 month despite frequency stated to be daily
4. "dengue-cases-south-west" - Not updated for at least 1 month despite frequency stated to be daily
5. "dengue-clusters" - Not updated for at least 1 month despite frequency stated to be daily
6. "aedes-mosquito-breeding-habitats-central" - Not updated for at least 1 month despite frequency stated to be daily
7. "aedes-mosquito-breeding-habitats-north-east" - Not updated for at least 1 month despite frequency stated to be daily
8. "aedes-mosquito-breeding-habitats-north-west" - Not updated for at least 1 month despite frequency stated to be daily
9. "aedes-mosquito-breeding-habitats-south-east" - Not updated for at least 1 month despite frequency stated to be daily
10. "aedes-mosquito-breeding-habitats-south-west" - Not updated for at least 1 month despite frequency stated to be daily
11. "zika-cluster" - Not updated for at least 1 month despite frequency stated to be daily
12. There is no dataset for "dengue-cases-north-west" while other regions have datasets. Is this intended?

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

### How frequently would you need this dataset to be updated?
- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Visualization of dengue clusters over Singapore

**Comment by lennardl** [comment]
@karrkh We have alerted investigated and alerted NEA on this. They are looking into this. I will update this issue again once we have gotten an update.
