### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by michanky** [datagovsg/datagovsg-datasets#573]
### Do you know which agency provides/can provide this data?
Sport Singapore

### If there's an issue with a dataset, please provide a description of the problem
The current gym tracker is not updated. It is found here https://gym-tracker.data.gov.sg/

### Please provide the fields expected in this dataset:
Location | Hour | Capacity 
Bedok ActiveSG gym | 7 am | 21% full

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [X] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To update https://gym-tracker.data.gov.sg/

**Comment by lennardl** [comment]
The data is no longer provided by Sports Singapore
