### ISSUE TITLE
Dataset request: <Occupancy of ActiveSG gyms in different day and time of the week>

### ISSUE THREAD

**Issue by chongkai95** [datagovsg/datagovsg-datasets#574]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Occupancy of ActiveSG gyms in different day and time of the week

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )* 
Sport Singapore

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Day | Hourly interval | Occupancy in percentage | Location |
-----|------------------|-----------------------------|-----------|
Monday|07:00                 |20                                       |Bishan

### How frequently would you need this dataset to be updated?
- [X] *Test*

### Can you give a short explanation on how you're planning to use this dataset?
Final year university project. Using machine learning to predict the occupancy of any ActiveSG gym in any time within the opening hours of the gym.

**Comment by chongkai95** [comment]
Hourly interval (AM/PM)*****

**Comment by lennardl** [comment]
The data is not available
