### ISSUE TITLE
Dataset request: <hourly air temperature and rain fall>

### ISSUE THREAD

**Issue by ecsliuhm** [datagovsg/datagovsg-datasets#575]
### Please provide the name of the dataset or describe the dataset that you're requesting:
We would like to have hourly level temperature and perception of all (or most) weather stations in the period of 2015-2016. Currently, the information is only available since late 2016 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
meteorological-services-division or NEA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

### How frequently would you need this dataset to be updated?
- [ ] Hourly

### Can you give a short explanation on how you're planning to use this dataset?
We are working on a project that analyzes how changes in temperature affect people's daily activities.

**Comment by lennardl** [comment]
@ecsliuhm We do not have the data before 2016. If you need the historical data, you would need to approach NEA to see if they have it.
