### ISSUE TITLE
Missing wind-speed data from real-time weather API

### ISSUE THREAD

**Issue by MichaelChirico** [datagovsg/datagovsg-datasets#576]
https://api.data.gov.sg/v1/environment/wind-speed?date=2019-12-22

```
{"metadata":{"stations":[]},"items":[],"api_info":{"status":"healthy"}}
```

status is `healthy` but I'm not seeing any records; has this API been deprecated?

**Comment by lennardl** [comment]
@MichaelChirico We have checked and there's an issue on the data coming through from the source. We have alerted NEA on this.
