### ISSUE TITLE
Dataset request: .SHP Files for Master Plan 2019 Building, Land Use and Planning Area

### ISSUE THREAD

**Issue by yr360** [datagovsg/datagovsg-datasets#577]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Given that Master Plan 2019 has been gazetted, may you kindly provide the .shp files for Master Plan 2019 Building, Land Use and Planning Area please?

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
URA

### If there's an issue with a dataset, please provide a description of the problem
Master Plan 2014 is outdated.

### Please provide the fields expected in this dataset:
.shp files

*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Not applicable.

Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To have an accurate GIS depiction.

**Comment by lennardl** [comment]
@yr360 We have approached URA for this and am waiting on their response

**Comment by yr360** [comment]
@lennardl Thank you very much for your reply. Hope to hear from you soon when the authority has replied. Many thanks again!

**Comment by Venessang** [comment]
@yr360 I am also looking for these files. Are there any updates from URA?

**Comment by yr360** [comment]
@Venessang Have yet to receive any reply from the authority.

**Comment by Nonoeelle** [comment]
Is there any update in this case? I am also looking for this shapefile for my research. Many thanks.
