### ISSUE TITLE
Dataset request: <Weekly Infectious Diseases Bulletin>

### ISSUE THREAD

**Issue by Ian-Woo** [datagovsg/datagovsg-datasets#578]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Weekly Infectious Diseases Bulletin for HFMD weekly cases from 2009 to 2019

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Health

### If there's an issue with a dataset, please provide a description of the problem
Nil

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Epidemiological Week | No. of Cases
-------------------------|--------------
2019-W52 to 2009-W01 | Units

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am a Year 6 student at St. Joseph's Institution and I am doing an Biology Internal Assessment, IA, for my final year and I am studying the trends of HFMD against temperature.

**Comment by lennardl** [comment]
We do not have the historical data to that dataset
