### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by lulili1234567** [datagovsg/datagovsg-datasets#58]
### Please provide the name of the dataset or describe the dataset that you're requesting:

health
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lulili1234567** [comment]
nice

**Comment by iewil** [comment]
@lulili1234567 closing the request due to lack of detaisl? please reopen if you can provide more info. Thanks.
