### ISSUE TITLE
Dataset request: <Rainfall 2015 and 2016>

### ISSUE THREAD

**Issue by rsimsp** [datagovsg/datagovsg-datasets#581]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Singapore Rainfall 2015 and 2016
Singapore Temperature 2015

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
NEA/ MSS

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2015-01to12|Singapore|NA
2016-01to12|Singapore|NA

### How frequently would you need this dataset to be updated?
Example: 
- [] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [X] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
research purpose. I intend to use the data to analyze the variation of rainfall and temperature  in Singapore on an hourly basis.

**Comment by lennardl** [comment]
@rsimsp We do not have the data prior to 2016

**Comment by rsimsp** [comment]
@lennardl  Thank you for the information. Will you be so kind as to point me the data for 2016 then? Thank you.

**Comment by lennardl** [comment]
@rsimsp These two datasets might fit your criteria but they are monthly numbers:
https://data.gov.sg/dataset/surface-air-temperature-monthly-mean?view_id=23448019-64b0-4548-afef-ad41c73bd6ae&resource_id=07654ce7-f97f-49c9-81c6-bd41beba4e96
https://data.gov.sg/dataset/rainfall-monthly-total?view_id=be92ce92-d02e-4920-9479-ff6da87b45e8&resource_id=778814b8-1b96-404b-9ac9-68d6c00e637b
