### ISSUE TITLE
Dataset request: <Income of Companies by Income Type, Annual>

### ISSUE THREAD

**Issue by rlgnszzz** [datagovsg/datagovsg-datasets#583]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Income of Companies by Income Type, Annual

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
https://data.gov.sg/dataset/income-of-companies-by-income-type-annual?view_id=01809982-a089-4a39-8af6-231bcc89564d&resource_id=83b36d2e-6d2a-47d0-8042-415db84442e9

### If there's an issue with a dataset, please provide a description of the problem
only provided until 2017, 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [V ] Annually
- [V ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I will use data analysis and prediction on my projects

**Comment by lennardl** [comment]
The data will be updated by IRAS
