### ISSUE TITLE
Dataset request: <Income of Individuals by Income Type, Annual>

### ISSUE THREAD

**Issue by rlgnszzz** [datagovsg/datagovsg-datasets#584]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Income of Individuals by Income Type, Annual

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
https://data.gov.sg/dataset/income-of-individuals-by-income-type-annual?view_id=8a17dde2-7c8d-4a1e-978b-71e36b02677a&resource_id=a1ce0bec-7745-4c4f-9fb4-3f4d0600fcbb

### If there's an issue with a dataset, please provide a description of the problem
only provided until 2018.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

same as above of link, please. 

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [V ] Annually
- [V ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I will use data analysis and prediction on my projects.

**Comment by lennardl** [comment]
@rlgnszzz We have approached IRAS for the latest data. Once we get a response we will let you know.

**Comment by lennardl** [comment]
@rlgnszzz We have gotten a response from IRAS, the data for 2019 will only be made available in Q3 2020
