### ISSUE TITLE
Dataset request: death-by-cause-and-age-group

### ISSUE THREAD

**Issue by kosetin** [datagovsg/datagovsg-datasets#585]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Death by cause and age group and gender

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Home Affairs - Immigration & Checkpoints Authority

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
year | icd_main_category | icd_detail_category | gender | death_age | death_count

### How frequently would you need this dataset to be updated?
Example: 
- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Showing mortality statistics during the SPH5410 Developing health proposals course at NUS

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/death-by-cause-and-age-group?view_id=5b598623-23fc-4e18-aa2f-54e117f22d4a&resource_id=04787aed-3c46-4854-839f-6c0755a2ffdc
