### ISSUE TITLE
Dataset request: <Household Expenditure survey>

### ISSUE THREAD

**Issue by Vickychann5** [datagovsg/datagovsg-datasets#586]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
2000|Singapore|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am going to do an econometric dissertation using difference in differences approach in individual household data.

**Comment by lennardl** [comment]
We do not have that data available
