### ISSUE TITLE
Dataset request: Singapore Postal Data that can be grouped by Zone, Sub Zone, and Bldg Type

### ISSUE THREAD

**Issue by jericolayugan** [datagovsg/datagovsg-datasets#587]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Data with Singapore Postal codes that can be grouped by Region,Zone, Sub Zone, and Bldg Type

### Do you know which agency provides/can provide this data? No
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Region|Zone|SubZone|PostalCode|BldgType

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
We are Hope Singapore Church, a not for profit organization.  The data will help leadership team to have an overview/visualization of geographical location where small group is located, and location that can start a life group with.

**Comment by lennardl** [comment]
@jericolayugan For postal code data you would need to approach SingPost as it is privately owned

**Comment by jericolayugan** [comment]
thanks @lennardl Yes, Singpost has the postal code.
unfortunately, they don't have Zone and Sub Zone.

**Comment by b5r7a5d** [comment]
Able to share the postal code data file?
