### ISSUE TITLE
Dataset request: <GRCs, SMCs and Town Councils>

### ISSUE THREAD

**Issue by lihweilihwei** [datagovsg/datagovsg-datasets#59]
### Please provide the name of the dataset or describe the dataset that you're requesting:
A Shapefile of the GRCs, SMCs, and Town Councils in Singapore (Updated to the current arrangements)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of National Development

### Please provide the fields expected in this dataset:

Town Council|Constituencies within Town
--------------|--------------
Aljunied-Hougang Town Council|Aljunied GRC
Aljunied-Hougang Town Council|Hougang SMC
Ang Mo Kio Town Council|Ang Mo Kio GRC
Ang Mo Kio Town Council|Sengkang West SMC
Bishan-Toa Payoh Town Council|Bishan-Toa Payoh GRC
Chua Chu Kang Town Council|Chua Chu Kang GRC
Chua Chu Kang Town Council|Hong Kah North SMC
...|...

### How frequently would you need this dataset to be updated?
- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Find out which Town Council to report to based on your address.
Find out which GRC/SMC you belong to based on your address.

**Comment by justinelliotmeyers** [comment]
any update on this?

**Comment by iewil** [comment]
@justinelliotmeyers @lihweilihwei we'll forward this request to the partnering agencies for their follow-up. We'll post updates here as and when we get them. Thanks.
