### ISSUE TITLE
Dataset request: <Sentosa daily entry by cars>

### ISSUE THREAD

**Issue by 21leare** [datagovsg/datagovsg-datasets#590]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I am requesting a dataset for the amount of cars what enter Sentosa daily. the name for the data will be named: "Car entering Sentosa per hour" but there could be an option to see months and years

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
I'm not sure who would have the data

### If there's an issue with a dataset, please provide a description of the problem
I don't think they would be a problem. 

### Please provide the fields expected in this dataset:
*Amount of people
*The amount of cars
*At a specific time the cars enter (hourly)
*The amount in month

### How frequently would you need this dataset to be updated?
Example: 

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [X] Hourly
- [X] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am planning to use this for my EE (extended easy). I need to know how many cars enter Sentosa daily and see if there are any correlation between the amount of car enter to the amount of entry fee.

Thank you for your understanding.

**Comment by lennardl** [comment]
We do not have the data
