### ISSUE TITLE
Missing rainfall data

### ISSUE THREAD

**Issue by romainMiralles** [datagovsg/datagovsg-datasets#591]
Hi,

I don't get anything when I query the rainfall API.

https://api.data.gov.sg/v1/environment/rainfall?date=2020-10-14

{
  "metadata": {
    "stations": []
  },
  "items": [],
  "api_info": {
    "status": "healthy"
  }
}

is it still working?

**Comment by lennardl** [comment]
@romainMiralles I noticed your query is for 14 Oct 2020. The data for the future is not in the system.

**Comment by romainMiralles** [comment]
Sorry, I meant January 14th 2020

**Comment by lennardl** [comment]
@romainMiralles It seems there's missing data from NEA. We will contact them to see if we can backfill the data.
