### ISSUE TITLE
Dataset request: Postal Code,Location and Coordinates in Singapore

### ISSUE THREAD

**Issue by Blake888** [datagovsg/datagovsg-datasets#593]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Singpost? 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
PostalCode | Location | Latitude | Longtitude | Country 
------|---------|-------------
307987 | Novena | 1.3195° N | 103.8421° E | Singapore

### How frequently would you need this dataset to be updated?
Example: 

- [ ] Annually
- [X ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Working in infectious disease (dengue, food bone disease, influenza and etc) surveillance and analytics.

**Comment by lennardl** [comment]
@Blake888 The postal code data resides with SingPost (private entity) and we are unable to provide the data

**Comment by Blake888** [comment]
Thanks and no problem.

________________________________
