### ISSUE TITLE
Dataset request: <dataset title> Enrolment for public universities course-wise

### ISSUE THREAD

**Issue by jainamushah** [datagovsg/datagovsg-datasets#594]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Enrolment/intake per course for public universities

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
MoE

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

Students

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/enrolment-preu-by-age
