### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by chionghien** [datagovsg/datagovsg-datasets#595]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Doctors Per 10,000 Total Population
https://data.gov.sg/dataset/doctors-per-10-000-total-population
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
MOH

### If there's an issue with a dataset, please provide a description of the problem
This dataset is a duplicate with "Healthcare Professional to Population Ratio" which also provides the same data, but more updated than "Doctors Per 10,000 Total Population". Suggest to remove "Doctors Per 10,000 Total Population" dataset to minimise duplication.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Expected to remove this dataset to minimise duplication.

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@chionghien The dataset has been updated up till 2018. The numbers for 2019 have not been released
https://data.gov.sg/dataset/doctors-per-10-000-total-population?view_id=a55df2aa-22fc-4462-9148-6b1356c34e27&resource_id=d5488c4a-886c-4174-b139-b85718cf162a
