### ISSUE TITLE
CHAS Clinics 

### ISSUE THREAD

**Issue by b5r7a5d** [datagovsg/datagovsg-datasets#597]
### Please provide the name of the dataset or describe the dataset that you're requesting:
CHAS Clinics 

### Do you know which agency provides/can provide this data?
Ministry of Health 

### If there's an issue with a dataset, please provide a description of the problem
Dataset incomplete. 958 clinics listed against 1800+ as listed on AIC / CHAS / Healthhub websites. 

### Please provide the fields expected in this dataset:
All fields. Will be great to provide the operating hours as well (available on Healthhub). 

### How frequently would you need this dataset to be updated?
Example: 
- Monthly or Weekly

### Can you give a short explanation on how you're planning to use this dataset?
Locate CHAS clinics that's open at a given time.

**Comment by b5r7a5d** [comment]
Dataset still incomplete

**Comment by lennardl** [comment]
@b5r7a5d Thanks for the feedback, we have informed MOH to verify and update where necessary.

**Comment by b5r7a5d** [comment]
@lennardl any updates?

**Comment by lennardl** [comment]
@b5r7a5d We have not received any updates and have sent them a follow up email on this
