### ISSUE TITLE
HDB Resale Flat Prices Data Issue

### ISSUE THREAD

**Issue by superlu19601** [datagovsg/datagovsg-datasets#598]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Resale Flat Prices (resource_id = 42ff9cfe-abe5-4b54-beda-c88f9bb438ee)

### Do you know which agency provides/can provide this data?
Housing and Development Board

### If there's an issue with a dataset, please provide a description of the problem
When the parameter "filters" is used to filter the field "month", e.g. {"month": "2019-10"}, there are duplicate records returned. The "total" field in the returned json shows 6624 but there are duplicate records. The data downloaded from https://data.gov.sg/dataset/7a339d20-3c57-4b11-a695-9348adfd7614/download also confirms that the transactions in 2019-10 should be 2208 instead of 6624. Each transaction has 3 duplicates in the result returned by API.

Example API usage:
https://data.gov.sg/api/action/datastore_search?resource_id=42ff9cfe-abe5-4b54-beda-c88f9bb438ee&limit=100&filters=%7B%22month%22%3A%20%222019-10%22%7D

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*
- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Make some analysis of the sale transactions.

**Comment by lennardl** [comment]
@superlu19601 Can you try again the duplicate entries should be resolved.

**Comment by superlu19601** [comment]
@lennardl Confirm that the duplicates are gone. Thanks!
