### ISSUE TITLE
Listing of Licensed Healthcare Institutions

### ISSUE THREAD

**Issue by b5r7a5d** [datagovsg/datagovsg-datasets#599]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Listing of Licensed Healthcare Institutions. All healthcare institutions that are licensed under the Private Hospitals & Medical Clinics (PHMC) Act.

### Do you know which agency provides/can provide this data?
Ministry of Health

### If there's an issue with a dataset, please provide a description of the problem
N.A.

### Please provide the fields expected in this dataset:
Clinic name | Clinic address | Clinic contact | X coordinate | Y coordinate | Operating Hours | Licensee name | Licensee period | HCI code | Programmes

### How frequently would you need this dataset to be updated?
- [X] Monthly
- [X ] Weekly

### Can you give a short explanation on how you're planning to use this dataset?
Use of HCI dataset and overlay with other information

**Comment by lennardl** [comment]
We currently do not have the data and in contact with MOH for the data.

**Comment by b5r7a5d** [comment]
@lennardl any updates?

**Comment by lennardl** [comment]
@b5r7a5d We have not received any updates and have sent them a follow up email on this
