### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by StephanyAPT** [datagovsg/datagovsg-datasets#6]
### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### Do you know which agency can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### How frequently would you need this dataset to be updated?
Example: 
- [x] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [x] Real-time

**Comment by iewil** [comment]
@StephanyAPT is there something that you would like to request for? If there isn't we'll proceed to close this issue. Thanks!

**Comment by iewil** [comment]
@StephanyAPT closing this issue. Please submit another issue if you have a dataset request. Thank you.
