### ISSUE TITLE
Dataset request: Carpark Capacity (Max Lots) for HDB & LTA car parks

### ISSUE THREAD

**Issue by Tkaixiang** [datagovsg/datagovsg-datasets#603]
### Please provide the name of the dataset or describe the dataset that you're requesting:
A dataset containing the carpark capacity of car parks managed by HDB & LTA (currently only the carpark capacity of URA is provided).

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
1. Housing and Development Board (HDB)
2. Land Transport Authority (LTA)

### If there's an issue with a dataset, please provide a description of the problem
N/A

### Please provide the fields expected in this dataset:
*(e.g. carparkID | maxCapacity*

carparkID | maxCapacity
------|---------
A0001|350

### How frequently would you need this dataset to be updated?
Example: 
- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
We are planning on using this dataset to make a student web application displaying information on live availability of car parks around Singapore. Information on the max capacity of a car park can help to indicate how full a car park is relative to the current number of available lots.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/hdb-carpark-information

**Comment by Tkaixiang** [comment]
That data-set does not contain the max capacity of the car parks?

**Comment by lennardl** [comment]
Does this work for you: https://data.gov.sg/dataset/ura-carpark-information ?
