### ISSUE TITLE
Dataset request: Carpark rates for HDB, LTA & URA carparks

### ISSUE THREAD

**Issue by Tkaixiang** [datagovsg/datagovsg-datasets#604]
### Please provide the name of the dataset or describe the dataset that you're requesting:
A dataset comprising of the carpark rates of car parks managed by HDB, LTA & URA combined

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
1. Land Transport Authority (LTA)
2. Housing Development Board (HDB)
3. Urban Redevelopment Authority (URA)

### If there's an issue with a dataset, please provide a description of the problem
N/A

### Please provide the fields expected in this dataset:

Carpark | CarparkID | Weekdays Rate 1 | Weekdays Rate 2 | Saturday Rate | Sunday and Public Holiday Rate
------|---------|-------------|-------------|-------------|-------------
Suntec City|1|12am-11.59pm:$1.30 for 1st hr, $0.65 for sub. 30 mins or part thereof.|$1.30 for 1st hr, $0.65 for sub. 30 mins or part thereof.| Sat & PH: Same as wkdays | Sun:12am-11.59pm: $2.14 for 1st hr, $1.07 for sub. 30 mins or part thereof.

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Annually*
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
We are planning on integrating these carpark rates into a web application displaying carpark information around Singapore

**Comment by lennardl** [comment]
We only have the price information for this: https://data.gov.sg/dataset/carpark-rates

**Comment by Tkaixiang** [comment]
Oh, is there anyway to obtain the car park rates for other car parks?

**Comment by lennardl** [comment]
The HDB rates are listed here: https://www.hdb.gov.sg/cs/infoweb/car-parks/short-term-parking/short-term-parking-charges
