### ISSUE TITLE
Dataset request: Public Holidays / School holidays API 

### ISSUE THREAD

**Issue by teddyywj** [datagovsg/datagovsg-datasets#606]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Singapore Public Holidays / School Holidays 

### Do you know which agency provides/can provide this data?
Ministry of Manpower / Ministry of Education

### If there's an issue with a dataset, please provide a description of the problem
No issue

### Please provide the fields expected in this dataset:

Public Holidays for year 2020
holiday_name|date|day_of_week|
---------------|-----|--------------|
Hari Raya Puasa|24 May 2020|Sunday|
Hari Raya Puasa (Observed)|25 May 2020|Monday|

School Vacation for year 2020
group|date-start|date-end|
Primary|14 Mar 2020|22 Mar 2020|

### How frequently would you need this dataset to be updated?

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For an app which prefably can get latest holiday occurences from an API call

**Comment by lennardl** [comment]
@teddyywj We do not have the data in an API format. Would suggest grabbing it off here
https://www.moe.gov.sg/education/school-terms-and-important-dates#pri-sec-sch-hols-2020
https://www.mom.gov.sg/newsroom/press-releases/2019/0408-public-holidays-for-2020

As the dates do not change throughout the year.

**Comment by peonmodel** [comment]
https://github.com/datagovsg/datagovsg-datasets/issues/371#issuecomment-591889121

heres a workaround
