### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by KianCheeSMRT** [datagovsg/datagovsg-datasets#607]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Taxi Availability. It provides the number of taxis available for hire at each location in Singapore at a certain time.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
LTA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Date|Time|Location|Number of available taxis
2020-01-30|13:00:00|Bishan|20

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ X ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
We plan to use it to reverse engineer the probability of overcrowding of taxis at a certain location at a certain time. The objective is to help space taxi drivers into areas of lesser crowding of supplies so as to better meet demand.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/taxi-availability?view_id=7534780c-e99f-4713-9d87-870071919734&resource_id=9d217820-1350-4032-a7a3-3cd83e222eb7
