### ISSUE TITLE
Dataset request: <Past Taxi and Carpark Availability Records>

### ISSUE THREAD

**Issue by Teo-KJ** [datagovsg/datagovsg-datasets#609]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Carpark Availability
Taxi Availability

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Land Transport Authority

### Please provide the fields expected in this dataset:
We are requesting for past records of real time dataset of the taxi and carpark availability. We understand that the data provided in data.gov.sg is real time, hence we are hoping that we can get the past records of these real time data, and at least data from 2019. 

*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [X] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am an undergraduate student at the Nanyang Technological University. We are planning to use the data for a school project, and this data is for creating an application that can predict taxi and carpark availability based on a defined date and time. Hence, if we have the past records of the availability data, we can train on it with machine learning to make future predictions.

Thanks and Regards,
KJ

**Comment by lennardl** [comment]
@Teo-KJ Unfortunately we do not have the historical data.
