### ISSUE TITLE
Population Density - Geographic Distribution

### ISSUE THREAD

**Issue by LoneRifle** [datagovsg/datagovsg-datasets#61]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Indicators on Population, Annual

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Trade and Industry - Department of Statistics

### If there's an issue with a dataset, please provide a description of the problem
This dataset provides population density at the national level. Breaking the numbers down to finer-grained areas will be helpful in seeing exactly how the population is distributed

### Please provide the fields expected in this dataset:
Per existing dataset, with one extra column indicating the geographic area to which the entry is relevant to. How Singapore is broken up by geographic area can be discussed

### How frequently would you need this dataset to be updated?
Annually or more frequent

### Can you give a short explanation on how you're planning to use this dataset?
Beeline currently relies on suggestion data to determine how viable a route will be. While we can make educated guesses as to where residential populations are, having fine-grained residential population density will help us and possibly others better tailor our operations and offerings, especially in discovering population clusters that we currently do not know about

**Comment by iewil** [comment]
@LoneRifle you can find it here 
https://data.gov.sg/dataset/singapore-residents-by-subzone-and-type-of-dwelling-june-2016
