### ISSUE TITLE
Dataset request: Information about HDB carparks such as operating hours, car park location (in SVY21), type of parking system, etc. 

### ISSUE THREAD

**Issue by etchan** [datagovsg/datagovsg-datasets#610]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Information about HDB carparks such as operating hours, car park location (in SVY21), type of parking system, etc.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
HDB, URA, Wilson parking

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

For analysis of hdb/ura carpark with free parking on sunday and PH. As an academia, potentially the data is non-sensitive and can be used for final year projects dataset, for academic purposes.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/hdb-carpark-information?view_id=398e65ae-e2cb-4312-8651-6e65d6f19ed1&resource_id=139a3035-e624-4f56-b63f-89ae28d4ae4c
