### ISSUE TITLE
Dataset request: Disease Outbreak Data

### ISSUE THREAD

**Issue by sausagee90** [datagovsg/datagovsg-datasets#611]
### Please provide the name of the dataset or describe the dataset that you're requesting:
- Data on the number of people infected during disease outbreaks in Singapore / region / world (e.g. SARS / Ebola / Wuhan Coronavirus).

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
- Not sure, but my best guess would be MOH.

### If there's an issue with a dataset, please provide a description of the problem
- N.A.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

year-week | country | number of new cases | total number of people infected | disease | mode of transmission
------|---------|-------------
2020-04 | Singapore | 3 | 10 | Wuhan Coronavirus | Air 

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [ ] Annually
- [ ] Monthly
- [X] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am planning to use this dataset to understand how fast disease outbreaks in Singapore are spread by comparing the trend of infections for different diseases.

**Comment by lennardl** [comment]
You can find the dataset here: https://data.gov.sg/dataset/weekly-infectious-disease-bulletin-cases
We have approach MOH to update the dataset

**Comment by lennardl** [comment]
The dataset has been updated

**Comment by derekang** [comment]
Hi, the dataset URL seems to hit a 404 error. thanks!

**Comment by lennardl** [comment]
@derekang Can you please try again now, should be working.

**Comment by derekang** [comment]
hmm! still got the same.

**Comment by lennardl** [comment]
@derekang I just verified its working. Can you try clearing your browser cache?
