### ISSUE TITLE
Dataset request: singapore monthly bunker sales data

### ISSUE THREAD

**Issue by whitesynergy** [datagovsg/datagovsg-datasets#612]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Request for monthly singapore bunker sales data/breakdown by fuel type.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Maritime Port Authority

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [ ] Annually
- [x] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/bunker-sales-annual

**Comment by whitesynergy** [comment]
Thanks but i am looking for a monthly breakdown of bunker sales in
Singapore. Not annual.
Thank you.

**Comment by lennardl** [comment]
Can you see if this file helps? 
https://www.mpa.gov.sg/web/wcm/connect/www/8dbd15fc-c803-48f8-bf7c-553f83a3fc23/bunker-sales.xls?MOD=AJPERES&CONVERT_TO=url&CACHEID=8dbd15fc-c803-48f8-bf7c-553f83a3fc23

**Comment by whitesynergy** [comment]
i am actually looking for monthly bunker sales data breakdown from year
2000 onward.

**Comment by lennardl** [comment]
@whitesynergy We do not have data from that far back.
