### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by shadowchin** [datagovsg/datagovsg-datasets#615]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Wet Bulb Globe Temperature (WBGT) past years reading for May-Jul period at Nanyang Avenue. 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
NEA 

### If there's an issue with a dataset, please provide a description of the problem
No issue. I just want to request for it.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

hour | day | date | location | temperature
------|---------|-------------
10:00 | Tuesday | 01052019 | Nanyang Avenue | 30
11:00 | Tuesday | 01052019 | Nanyang Avenue | 32
12:00 | Tuesday | 01052019 | Nanyang Avenue | 34
...
17:00 | Monday | 01072019 | Nanyang Avenue | 30
18:00 | Monday | 01072019 | Nanyang Avenue | 30
19:00 | Monday | 01072019 | Nanyang Avenue | 30

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [X ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I'm planning the SAF day parade temperature monitoring to help soldiers monitor the WBGT to prevent heat exhaustion. There will be training during May to Jul each year that will be quite hot. The hourly temperature will help them to decide on the activities to do or take rest stops. I also want to use the data to give them a sense of what time period within the day they can exercise caution on the tasks under higher temperature.

**Comment by lennardl** [comment]
The data we have is at the topline level and not specific to locations https://data.gov.sg/dataset/wet-bulb-temperature-hourly
