### ISSUE TITLE
Dataset request: Business UEN GST list

### ISSUE THREAD

**Issue by archie29** [datagovsg/datagovsg-datasets#616]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Need a dataset that has UEN and GST details of a business
Something from https://mytax.iras.gov.sg/ESVWeb/default.aspx?target=GSTListingSearch

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
https://data.gov.sg/organization/inland-revenue-authority-of-singapore
https://data.gov.sg/organization/accounting-and-corporate-regulatory-authority
### Please provide the fields expected in this dataset:
Result similar to https://mytax.iras.gov.sg/ESVWeb/default.aspx?target=GSTListingSearch

GST Reg No.|UEN|Name|Status|Registered From|Registered To
--------------|----|-------|-------|------------------|-----------------
M200501853 | 198300096H | ACCESS SYSTEMS TECHNOLOGY PTE LTD | Registered | 01 Apr 1994 |

### How frequently would you need this dataset to be updated?
Example: 
- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
There are various datasets available worldwide about company information based on UEN and GST.
We need a dataset to join those by using UEN and GST relationship provided by a reliable agency instead of Fuzzy matching on Name.

**Comment by lennardl** [comment]
@archie29 We only have a dataset with the UEN details which is pending ACRA to update the data.

**Comment by archie29** [comment]
> @archie29 We only have a dataset with the UEN details which is pending ACRA to update the data.

Thanks for responding @lennardl . Will ACRA update this with GST? And is there an expected timeline when this would be done?

**Comment by lennardl** [comment]
@archie29 I'm not certain on the GST details. The dataset should be updated by this month.

**Comment by archie29** [comment]
> @archie29 I'm not certain on the GST details. The dataset should be updated by this month.

So how can I request a dataset? As I have shared a link to a website of the IRAS that lets me lookup the information per UEN or GST.
Is there a way to request the agency to have this data available as a dataset in this repository?

**Comment by lennardl** [comment]
@archie29 All request here only go to data.gov.sg. You could approach the agency to upload the data on data.gov.sg but its on their own accord to do so.
