### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by deltayoung** [datagovsg/datagovsg-datasets#617]
### Please provide the name of the dataset or describe the dataset that you're requesting:
LiDAR point cloud data of Singapore urban area with many street trees, measuring around 5x5 km.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Singapore Land Authority (SLA)

### If there's an issue with a dataset, please provide a description of the problem
N.A.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time
- [X] One-time

### Can you give a short explanation on how you're planning to use this dataset?
To experiment to automatically detect tree species and measurements by machine learning techniques for R&D purpose.

**Comment by lennardl** [comment]
@deltayoung We do not have that data. You would need to approach SLA for this specific data.
