### ISSUE TITLE
Dataset request: Singapore Waste Data by Constituency 

### ISSUE THREAD

**Issue by LyleLiewZJ** [datagovsg/datagovsg-datasets#620]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Hello GitHub Community, I am looking for Singapore Waste Data by Constituency 

Preferably I would like the dataset to contain historical data from 2010 to 2020, and localised in the different Singapore Constituencies for easy normalisation. 

### Can you give a short explanation on how you're planning to use this dataset?
Machine Learning Model to predict future waste trends.

**Comment by lennardl** [comment]
@LyleLiewZJ We have approached NEA to see if such a dataset is available.

**Comment by LyleLiewZJ** [comment]
Thanks for responding @lennardl , any idea when will NEA get back to you?

**Comment by lennardl** [comment]
@LyleLiewZJ Have gotten a response from NEA, they have responded that such a dataset is not available.
