### ISSUE TITLE
Dataset request: Government Procurement

### ISSUE THREAD

**Issue by apache088** [datagovsg/datagovsg-datasets#621]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Government Procurement

### Do you know which agency provides/can provide this data?
Ministry of Finance

### If there's an issue with a dataset, please provide a description of the problem
No issue with current dataset, but I would like to request for additional fields (i.e. supply head for tender).

### Please provide the fields expected in this dataset:
tender_no. | tender_description | agency | award_date | tender_detail_status | supplier_name | awarded_amt | tender_supply_head
-- | -- | -- | -- | -- | -- | -- | --
AGC000ETT14000011 | Invitation To Tender for The Supply, Delivery, Support of E-Discovery Software with an option for maintenance of software | Attorney-General's Chambers | 28/1/15 | Awarded to Suppliers | NCS PTE. LTD. | 243000 | EPU/CMP/10 - Computer Related Hardware, Software, and Services

### How frequently would you need this dataset to be updated?
Example: 
- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Analyse the key players bidding for government contracts

**Comment by lennardl** [comment]
The data can be found here: https://data.gov.sg/dataset/government-procurement
We have approached MOF to update the dataset.
