### ISSUE TITLE
Dataset request: <Traffic signal plan & Vehicle detector data from LTA >

### ISSUE THREAD

**Issue by fredricmokshifu** [datagovsg/datagovsg-datasets#624]
### Please provide the name of the dataset or describe the dataset that you're requesting:

I would like to request for a set of Traffic signal plan & Vehicle detector data, from LTA. Preferably for the area between Corporation Road and Boon Lay Way. Else, any set of data available in Singapore suitable for the traffic optimization and implementation of BALANCE an adaptive traffic control method. Therefore improving the traffic flow and evaluate the effectiveness of BALANCE, an Optimization-Based Adaptive Signal Control System.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

LTA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

signal group, signal sequence, signal timing, cycle length, intergreen stages, and Phase Sequence Timing, Phase length, offset etc
Time data for vehicle traffic “red-green-amber” 
Time data for pedestrian traffic “red-green flashing-green”. 
Vehicle detector data: Vehicle flow direction, location coordinates.
For Weekday & Weekend, peak & non-peak hours. (Recent for either of the years 2017/2018/2019)

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ /] Annually
- [ /] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
The main purpose of the project aims to implement BALANCE, an adaptive traffic control method on a specific network model through VISSIM, a Microscopic traffic simulation software. To efficiently direct traffic across networks to ease congestion and provide an improved traffic flow. In addition, to resolve major issues such as long vehicle waiting time, the number of vehicles stops and extended queue-lengths. Therefore, based on the final results generated, analyse the effectiveness of BALANCE, an Optimization-Based Adaptive Signal Control System.

**Comment by lennardl** [comment]
@fredricmokshifu we do not have that data you might need to approach LTA via their LTADataMall website to request for such data
