### ISSUE TITLE
Dataset request: EV charging infrastructure, updated EV statistics, and geospatial info

### ISSUE THREAD

**Issue by wchanwy** [datagovsg/datagovsg-datasets#629]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I am looking for data on current locations of electric vehicle (EV) charging stations in Singapore. Ideally, the data should include this information:
- geographical location of charging stations (using longitude and latitude or equivalent)
- how many chargers are available at each site
- type of charger (charging capacity, speed)
- optional: provider (e.g. BlueSG, Greenlots)
- anything else that is related and available

In addition, I would also be very thankful to retrieve updated data on historical EV ownership/uptake rates in Singapore. There is relevant information in the "Monthly Motor Vehicle Population Statistics by Type of Fuel Used" file on data.gov.sg, but it only covers 4 months in the period between Dec 2016 and Feb 2018. Is there any new data available?

Lastly, I am wondering if URA has data on land use and geospatial population densities that is recorded in a csv format (or any other format more amenable to data analysis than the KML and SHP formats, which I am entirely unfamiliar with).  At the very least, is there a dataset on the approximate longitudes, latitudes, and approximate parking capacities of public carparks?

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
- Land Transport Authority
- Energy Market Authority (under Ministry of Trade and Industry)
- Urban Redevelopment Authority

### If there's an issue with a dataset, please provide a description of the problem
N/A

### How frequently would you need this dataset to be updated?
Example: 

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
With the recent Budget announcement by DPM Heng concerning the aggressive promotion of EVs, I finally feel bold enough to ask for relevant datasets which can help me carry out optimisation studies on how best to site EV charging sites around the country. My work involves computational modelling, which will need to be built on robust datasets that accurately reflect the physical realities of current EV infrastructure, potential sites, and zones of demand and supply.

I've also noted that a similar request asking for the location of EV charging points was submitted about a year ago. Hopefully, this new request will be successfully processed this time.
Thank you very much for your help!

**Comment by lennardl** [comment]
@wchanwy We do not have this dataset. We have approached EMA before and they were in the process of collating this data from all the providers but its not available as of now.

**Comment by wchanwy** [comment]
Do you know if the other requested datasets are available?

**Comment by lennardl** [comment]
@wchanwy We have gotten an update for this: https://data.gov.sg/dataset/monthly-motor-vehicle-population-by-type-of-fuel-used?view_id=4e96af52-04ea-4d1c-9d43-95d41f970ec1&resource_id=56c8d9af-5bf5-49a1-91ce-1ed4b4b191f3

On the carparks we have
- https://data.gov.sg/dataset/hdb-carpark-information
- https://data.gov.sg/dataset/ura-carpark-information

**Comment by wchanwy** [comment]
Wow, this is great. Thank you!

**Comment by edwinksl** [comment]
Would be great to have the information on EV chargers (both existing and planned) as @wchanwy has requested.

@lennardl Any estimated timeline for when we can expect to hear from EMA? Thanks!
