### ISSUE TITLE
Dataset request: <Personal Mobility Devices, Aids and Mobility Bicycles>

### ISSUE THREAD

**Issue by sywong0411** [datagovsg/datagovsg-datasets#630]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Personal Mobility Devices, Aids and Mobility Bicycles

### Do you know which agency provides/can provide this data? 
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Transport, Land Transport Authority

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I won't be using it because my project will be due soon.

**Comment by lennardl** [comment]
@sywong0411 Can I understand are you looking for the number of known devices that's on Singapore roads?

**Comment by sywong0411** [comment]
Yes the number of known devices that's on Singapore roads, and if possible by the different areas in Singapore (Kovan, Pasir ris, Boon Lay, Jurong, Clementi, etc).
I understand the devices are knew at the moment, so there may not be data yet.

**Comment by lennardl** [comment]
@sywong0411 We do not have data split by the different areas in Singapore
