### ISSUE TITLE
Dataset request: PM2.5 real time data

### ISSUE THREAD

**Issue by RebeccaNUS** [datagovsg/datagovsg-datasets#631]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Weather data, mainly both air temperature and PM2.5 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization 
NEA

### If there's an issue with a dataset, please provide a description of the problem
I would like to have the api key for this extraction of data

### Please provide the fields expected in this dataset:
2016 - 01 -01 Singapore 

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X ] Monthly
- [ X] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am doing a research on air pollutants and air temperature in relation to building energy usage

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/pm2-5
