### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by koito19960406** [datagovsg/datagovsg-datasets#632]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Master Plan 2019 Symbol Text layer

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
URA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000
2020-03|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I will use this for my work at school.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/master-plan-2019-symbol-text-layer
