### ISSUE TITLE
Dataset request: District demarcation in Singapore

### ISSUE THREAD

**Issue by arina1986** [datagovsg/datagovsg-datasets#633]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Urban Redevelopment Authority

### Please provide the fields expected in this dataset:
District demarcation in Singapore, require coordinates in KML file

### How frequently would you need this dataset to be updated?
Monthly/ bi monthly

### Can you give a short explanation on how you're planning to use this dataset?
 To display property launch sites and the district they fall in for better relativity and representation.
Corporate website : https://www.edgeprop.sg/new-launches

**Comment by lennardl** [comment]
@arina1986 We do not have that data at the moment
