### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by Yuxuan1999** [datagovsg/datagovsg-datasets#634]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Taxi Availability API
https://api.data.gov.sg/v1/transport/taxi-availability

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Land Transport Authority

### If there's an issue with a dataset, please provide a description of the problem
None

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Latitude, Longtitude, total number of taxis

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [X] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I hope to create a taxi availability tracker using Javascript and HTML as part of my final project with Hackwagon.

**Comment by lennardl** [comment]
@Yuxuan1999 You are free to use the dataset, there is no API key required
