### ISSUE TITLE
Dataset request: <Workfare Transport Concession Card Usage and Travel Patterns>

### ISSUE THREAD

**Issue by brandonchen1986** [datagovsg/datagovsg-datasets#637]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Public Transport Usage Patterns for users of Workfare Transport Concession Card. 

### Do you know which agency provides/can provide this data?

Public Transport Council, or Land Transport Authority

### If there's an issue with a dataset, please provide a description of the problem

This dataset does not seem be to currently available, the only dataset related to this is the travel fares for the Workfare Transport Concession Card. 

### Please provide the fields expected in this dataset:

card identifier (anonymised) | weekday/weekend travel | time of travel | mode of transport (bus or MRT) | origin station/stop | destination station/stop | distance traveled | fare charged

### How frequently would you need this dataset to be updated?

This should be a once-off extraction for the purpose of academic research, and the latest available dataset should be sufficient for the purposes of this study. 

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

I am a Masters student at SUTD, and I wish to study the public transport usage patterns for low wage workers as part of my thesis. Besides the Public Transport Vouchers, I note that the Workfare Transport Concession Card is an option for low wage workers to travel on the public transport network at subsidised rates. I wish to study their transport patterns to see if their amount of travel is affected by distance-based charging, as compared to commuters who use the regular Adult Monthly Travel Card.

**Comment by brandonchen1986** [comment]
Bumping this request up for attention by relevant authorities. A nil response (i.e. no dataset available, or no intention to release) would be appreciated.

**Comment by lennardl** [comment]
@brandonchen1986 We do not have that data.

**Comment by brandonchen1986** [comment]
> @brandonchen1986 We do not have that data.

Thanks for confirmation.
