### ISSUE TITLE
https://data.gov.sg/dataset/resale-flat-prices

### ISSUE THREAD

**Issue by abhijitrri** [datagovsg/datagovsg-datasets#64]
### Please provide the name of the dataset or describe the dataset that you're requesting:
resale-flat-prices

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Cannot specify

### If there's an issue with a dataset, please provide a description of the problem
Unable to access the download link

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Understand the driving factors for housing prices

**Comment by abhijitrri** [comment]
Unable to access the above dataset, please advise. I need the same quite urgently

**Comment by yongjun21** [comment]
Closing as [link](https://data.gov.sg/dataset/resale-flat-prices) has been restored
