### ISSUE TITLE
Dataset request: Singapore National Corpus

### ISSUE THREAD

**Issue by greg1232** [datagovsg/datagovsg-datasets#640]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Singapore National Corpus

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
https://www.imda.gov.sg/programme-listing/digital-services-lab/national-speech-corpus

### If there's an issue with a dataset, please provide a description of the problem
No issues

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

We plan to use it to train research speech recognition systems.

**Comment by lennardl** [comment]
@greg1232 You would need to request for it from www.imda.gov.sg/nationalspeechcorpus
