### ISSUE TITLE
Dataset (*feature*) request: ACRA Information on Corporate Entities

### ISSUE THREAD

**Issue by danielnjoo** [datagovsg/datagovsg-datasets#641]
### Please provide the name of the dataset or describe the dataset that you're requesting *improvements to*: 
ACRA Information on Corporate Entities

### If there's an issue with a dataset, please provide a description of the problem
Would like to know if there are additional query options, from the example, only seems like there is word matching (q=, which matches across all fields) and result limiting (limit=). Additionally, there's a different endpoint for entities starting with different letters xyz for "A-", abc for "B-"... ideally they'd all be accessible from one endpoint.

### Can you give a short explanation on how you're planning to use this dataset?
For example, I'd like to query for *all* entities registered after a certain date. This isn't possible at the moment because results are limited to 100 total PER letter, and dates are stored as text objects.

**Comment by lennardl** [comment]
@danielnjoo Currently our API is limited and can't do what you're requesting for. We are looking to upgrade our system but it would take time.
