### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by SAFABAHRI** [datagovsg/datagovsg-datasets#642]
Hello, I'm a PhD student at the national school of engineering of Tunis. I would like to download a dataset related to dengue fever virus outbreak in order to develop a prediction model based on machine learning algorithms. Can you help me please?

**Comment by lennardl** [comment]
@SAFABAHRI Datasets are under the open data license and can be downloaded freely. Are you experiencing issues downloading the dataset?
