### ISSUE TITLE
Dataset Request: Rentals of Non-Landed Residential Buildings, Quarterly

### ISSUE THREAD

**Issue by matthewchay** [datagovsg/datagovsg-datasets#645]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Rentals of Non-Landed Residential Buildings, Quarterly

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
URA
https://data.gov.sg/dataset/rentals-of-non-landed-residential-buildings-with-at-least-10-rental-contracts-signed-in-1q2016?resource_id=4384e22c-234f-4196-9df8-1941cd41c667

### If there's an issue with a dataset, please provide a description of the problem
Currently it is updated on a quarterly basis and only the last quarter is available for download and not the historical quarters. Would like to be able to access historical quarters as well. Is it possible to share the resource id code for each quarter or the data dictionary?

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

To be able to access historical quarters as well

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

Monthly or Quarterly is fine

### Can you give a short explanation on how you're planning to use this dataset?

This is being used to track the number of rental contracts and the rental levels in Singapore; and to be able to forecast and derive analysis on this

**Comment by lennardl** [comment]
@matthewchay For the historical data, you would need to approach URA for it as we do not store the historical data
