### ISSUE TITLE
Dataset request: Number of covid 19 cases

### ISSUE THREAD

**Issue by ultraflame4** [datagovsg/datagovsg-datasets#646]
### Please provide the name of the dataset or describe the dataset that you're requesting:
number of covid19 cases

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

Ministry of health

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

json

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [x ] Daily
- [ ] Hourly
- [x] Real-time(preferably)

### Can you give a short explanation on how you're planning to use this dataset?

using it in a program to show the latest number of cases.

Please turn this into an api so i dont have to web scraps for it

**Comment by lennardl** [comment]
@ultraflame4 For Covid-19 details please head to https://www.moh.gov.sg/covid-19, a dashboard is also made available by MOH here: https://experience.arcgis.com/experience/7e30edc490a5441a874f9efe67bd8b89

**Comment by ultraflame4** [comment]
> @ultraflame4 For Covid-19 details please head to https://www.moh.gov.sg/covid-19, a dashboard is also made available by MOH here: https://experience.arcgis.com/experience/7e30edc490a5441a874f9efe67bd8b89

is it possible to get a json response from the website(s) instead?

**Comment by lennardl** [comment]
@ultraflame4 We have another follow up with MOH on whether they can share the data and if they can at least make their data available in JSON format.
