### ISSUE TITLE
Dataset request: <supermarket products transactions/prices/logistics/quantities>

### ISSUE THREAD

**Issue by domchanjl** [datagovsg/datagovsg-datasets#649]
### Please provide the name of the dataset or describe the dataset that you're requesting:
supermarket transactions

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
perhaps trade or NEA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
month/year/singapore

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
predicting types of products bought due to irrational consumer behaviour

**Comment by lennardl** [comment]
@domchanjl We do not have that data as the aggregated product transactions would come from multiple non-government entities.
