### ISSUE TITLE
Dataset request: Number of dwelling units completed(by block) annually

### ISSUE THREAD

**Issue by bryyanw** [datagovsg/datagovsg-datasets#650]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I would like a dataset to visualise the number of blocks completed each year as a comparison against the total number of dwelling units completed each year

### Do you know which agency provides/can provide this data?
HDB

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
year|blocks-completed|dwelling_units_completed

### How frequently would you need this dataset to be updated?
- [x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Examine the trend of population psm

**Comment by bryyanw** [comment]
My company would like to find out the trend of number of units a typical letterbox nest serves over the years

**Comment by lennardl** [comment]
@bryyanw We do not have that detailed data, for that you would need to approach HDB to break it down by block.
