### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by xiejinshan** [datagovsg/datagovsg-datasets#653]
### Please provide the name of the dataset or describe the dataset that you're requesting:
1. Singapore Daily Public Transport (Train/Bus) Rideship
2. Singapore number of companies with work from home business continuity plan for the COVID 19
3. Number of COVID-19 test performed and number of positive test each day
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
1. SMRT, Ministry of Transport
2. Ministry of Manpower
3. Ministry of Health

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
1.Date | Number of passengers
2. Date | Number of companies
3. Date | Number of tests
month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [X] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Using it to observe the implementation effectiveness of social distancing and number of business are ready.

**Comment by lennardl** [comment]
We do not have the data
