### ISSUE TITLE
Dataset request: COVID-19 cases in Singapore

### ISSUE THREAD

**Issue by Davianlols6** [datagovsg/datagovsg-datasets#654]
### Please provide the name of the dataset or describe the dataset that you're requesting:
COVID-19 cases in Singapore

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
MOH

### If there's an issue with a dataset, please provide a description of the problem
nil

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

date|total infected|recovered|critical condition
20/3/2020|345|124|15

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am planning to use it to make a chart

**Comment by lennardl** [comment]
@Davianlols6 For Covid-19 related data please go to https://www.moh.gov.sg/covid-19
