### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by Conefourthrees** [datagovsg/datagovsg-datasets#655]
### Please provide the name of the dataset or describe the dataset that you're requesting:

I'd like to request for dengue cases by location (e.g. Changi, Bedok, etc) or by region.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

(Date | Region/Location | Number of Cases)

Date | Region/Location | passengers
------|---------|-------------
2017-09|Changi|23

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [X] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I'd be using it for a school project and we are aiming to write a programme that uses machine learning to predict the number of dengue cases by location one month before so that measures or supplies can be prepared in response to the cases.

**Comment by lennardl** [comment]
Hi,
The data is limited to the last 2 weeks. We have a dataset that visualizes the locations here: https://data.gov.sg/dataset/dengue-clusters.

For a more details breakdown of the locations you can refer to here: https://www.nea.gov.sg/dengue-zika/dengue/dengue-clusters
