### ISSUE TITLE
Dataset request: <same day arrivals and departures of total singapore total arrivals>

### ISSUE THREAD

**Issue by mrjohnchen** [datagovsg/datagovsg-datasets#656]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
CAAS

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
date | no of passenger arrivals | no of passenger departure

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
person learning

**Comment by lennardl** [comment]
That data has not been made available to us
