### ISSUE TITLE
Dataset request: Width of roads in different areas

### ISSUE THREAD

**Issue by bruhbigcroissants** [datagovsg/datagovsg-datasets#659]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Width of roads in different areas: school zones, silver zones, estates, major intersections, expressways, highways

### Do you know which agency provides/can provide this data?
Land Transport Authority

### Please provide the fields expected in this dataset:
type of road/area | width of road
--------|---------

### How frequently would you need this dataset to be updated?
- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
School project to find out traffic light timings based on width of roads

**Comment by lennardl** [comment]
@bruhbigcroissants We do not have the data but have reached out to SLA/LTA to understand if they have it.

**Comment by lennardl** [comment]
@bruhbigcroissants We have heard back and the data you requested for is not available
