### ISSUE TITLE
Dataset request: Census Microdata

### ISSUE THREAD

**Issue by thelmapfaff** [datagovsg/datagovsg-datasets#661]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I am hoping to get a small, representative sample of your most recent census data for a marketing demographics study. I have not seen that specific data listed.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
Age, Gender, Ethnicity, Language, Highest Education, Region/Area/City, Income Level (if available)

### How frequently would you need this dataset to be updated?
Example: Once may be enough, we may request annually if we select this market.

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
An exploratory demographic study for marketing purposes.

**Comment by lennardl** [comment]
@thelmapfaff I believe the department of statistics is still running the latest 2020 census (https://www.singstat.gov.sg/census2020/census-2020) so the data is not available?

**Comment by thelmapfaff** [comment]
Yes, I was hoping for this microdata from the 2010 Census.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by lennardl** [comment]
@thelmapfaff Can I confirm if any of the following are helpful: https://data.gov.sg/dataset?q=Singapore+Census+of+Population+2010

Otherwise does this help: https://www.singstat.gov.sg/-/media/files/publications/cop2010/census_2010_admin/cop2010admin.pdf

**Comment by thelmapfaff** [comment]
Hello,

The links you sent show only totals of categories by region. This is not very helpful for identifying marketing audiences. The data I need is an anonymous sample of the individual level data, where each respondent or household's answers are.

As an example, South Africa, another potential market we are studying, offers a 10% nationally representative sample with all answers to the census for each resident which is usually called "microdata". This is what I am hoping to get from Singapore.

Thank you,
Thelma Pfaff

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by lennardl** [comment]
@thelmapfaff For the detailed data, you would need to approach the SingStat for the data.

**Comment by thelmapfaff** [comment]
Excellent, I am happy to do that. Can you send me some information or protocols on how to complete this and who to contact? I am confused by your website and who else I can contact as this seems to be the one source they offer.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by lennardl** [comment]
@thelmapfaff You can approach them at https://www.singstat.gov.sg/contact-us via the data request form that can be found here https://www.singstat.gov.sg/our-services-and-tools/statistical-enquiries/data-request-form
