### ISSUE TITLE
Dataset request: Covid 19 Real Time Data

### ISSUE THREAD

**Issue by justcodejs** [datagovsg/datagovsg-datasets#662]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Covid 19 dataset

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
MOH

### Please provide the fields expected in this dataset:
The data should consist of:

Total cases
Suspected Cases
Confirmed Cases
Recovered Cases
Imported Cases
Critical Cases
Death Cases
Locations of cases (Where the patient infected, and area of staying)
Dates of the cases - Infected date, recovered date, decreased date, etc
Linkage between cases
Infection clusters information
Announcements from Gov

### How frequently would you need this dataset to be updated?
Example: 
- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ X] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Build a free mobile app to let Singaporean to a better view of Covid 19 situation, get lastest update on Covid 19 stats and Gov announcement. Let Singaporean know which area should avoid or take extra precaution if the area have a high density of Covid 19 infection cases.

**Comment by lennardl** [comment]
@justcodejs For Covid-19 related data please go to https://www.moh.gov.sg/covid-19, a dashboard is also available at https://experience.arcgis.com/experience/7e30edc490a5441a874f9efe67bd8b89 to use

**Comment by justcodejs** [comment]
I know about both the websites you mentioned and I had visited both websites, but both are the web user interface. What I need is the API that my App can call and return the reliable data. I can use web crawling to the website you mentioned but that is not reliable whenever there is a change in UI and it is not efficient. If both the website you mentioned provide API call for application to get data, do let me know the API details. Thanks.

**Comment by lennardl** [comment]
@justcodejs I understand they do not have an API. MOH would like to have a single source of truth for Covid-19 data hence we are not able to provide the data.

**Comment by mengwong** [comment]
How about the fields already present in the daily press releases and annexes?

https://www.moh.gov.sg/docs/librariesprovider5/pressroom/press-releases/annex---summary-of-confirmed-cases-(30-march-2020).pdf

// data already published in the Annex table
Case Number
Date of Confirmation
Hospital admitted
Age (years)
Gender
Nationality/Citizenship
Travel History
Exposure
Links
Cluster

// optional additional data which seems to appear in the press releases
Date of Symptom Onset
Dates of GP/polyclinic visits
Current Location
Resolution Status

**Comment by lennardl** [comment]
@mengwong We normally work with agencies to have them publish their data on Data.gov.sg but should they choose not to we are unable to make them comply. In this case the reason from MOH is as stated to have a single point of information on Covid-19

**Comment by wentjun** [comment]
@lennardl Based on what you have mentioned, are you implying that MOH is choosing not to release the data as they prefer to be the single source of information?

**Comment by lennardl** [comment]
Yes, it is preferred to have a single source of information as information there would be the latest and most accurate.

**Comment by wentjun** [comment]
@lennardl I see. Thanks for the clarification!

However, if we were to put up a formal request with the backing of Govtech, do you think they will compromise the position?

There are multiple reasons why we would like data to be available:
1) Covid-19 data should be transparent, and made accessible to all.
2) There have been multiple inconsistencies (in the cluster counts) from MOH's daily report releases, thus we would be to have access to the information so that we know the reason behind the inconsistencies.
3) It will be mutually beneficial for both govtech and other developers (such as me and others on this thread), as we will have open access to the information, which facilitates the building of applications for public good.

**Comment by lennardl** [comment]
@wentjun I can put up the request to MOH again to see if they are willing to accede. However the data will still be updated by MOH themselves hence point 2 might not be resolved.

**Comment by wentjun** [comment]
@lennardl Thanks. Do let me know if there is anything else I can help with regards to this.
