### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by trixiexin** [datagovsg/datagovsg-datasets#663]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Singapore Well-being index report

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
https://data.gov.sg/group/economy

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2008-2018|Singapore|All

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
This dataset is used to apply in my assignment purpose for Macroeconomic subject.

**Comment by lennardl** [comment]
The data is not made available to us
