### ISSUE TITLE
Dataset request: Resale Flat Prices from January 2017 Onwards

### ISSUE THREAD

**Issue by dhanumun** [datagovsg/datagovsg-datasets#664]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Resale Flat Prices from January 2017 Onwards

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Housing and Development Board

### Please provide the fields expected in this dataset:
month | town | flat type | block | street name | storey range | floor area | flat model | remaining lease | resale price

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [x] Annually
- [ X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To do some personal research before investing on a flat.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/resale-flat-prices
