### ISSUE TITLE
Singapore Postal Sector Data

### ISSUE THREAD

**Issue by fillingthemoon** [datagovsg/datagovsg-datasets#666]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Singapore Postal Sector Vector Polygon Data

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
SLA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

postal sector |
--------------|
01
02
03

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Map postal sectors to determine green space coverage within

**Comment by lennardl** [comment]
@PhilBob1 Postal code data is owned by SingPost. You will need to approach them for this data.
