### ISSUE TITLE
Dataset request: Car Park Availability

### ISSUE THREAD

**Issue by cktang1985** [datagovsg/datagovsg-datasets#667]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I am writing in to request for car park availability data provided here (https://data.gov.sg/dataset/carpark-availability). I need additional data on top of what is provided here. In particular,
1. Historical data from 2016 onwards. I would like to see how the change in the parking rates affected 
2. Data on existing number of vehicles within parking facility 
3. Dates on parking charge increase

### Do you know which agency provides/can provide this data?
HDB

### Please provide the fields expected in this dataset:
A hypothetical example:

datetime| carpark id | total lots |lots available|Number of Cars in carpark|
------|---------|-------------|-------|------|
2017-09: 18:00:00| H2 | 100 | 0 | 105|

### How frequently would you need this dataset to be updated?
Example: 
- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [X] Real-time

**Comment by lennardl** [comment]
@cktang1985 
For point 1, you will have to call our API and specify the date and time. Our data only goes back as far as Sept 2017

For point 2, you can take the total lots minus the availability to get the number of vehicles 

For point 3, we do not have the data

**Comment by cktang1985** [comment]
I was aware of the data limits because i already called all the data from the api. Hence, i am checking in if there is data that predates this date.

Availability is truncated at zero. I want to know instances when there are more cars than the parking capacity.

Could you direct me to the data holders who can release more data?

Thanks


Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lennardl** [comment]
For more data you would need to approach HDB/LTA
