### ISSUE TITLE
Dataset request: Singapore Citizens By Age Group, Ethnic Group And Sex, End June, Annual

### ISSUE THREAD

**Issue by JovinLeong** [datagovsg/datagovsg-datasets#668]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Singapore Citizens By Age Group, Ethnic Group And Sex, End June, Annual

### Do you know which agency provides/can provide this data?
Ministry of Trade and Industry - Department of Statistics

### If there's an issue with a dataset, please provide a description of the problem
The dataset is available online and everything about it is perfect from my research, but the issue is that the age buckets are different from what I need. Namely, I need the population from 21-29; right now, with the existing data, I can get the number for 20-29 but I can't exclude the 20-year-olds.

I also need this data to be split according to gender and ethnicity; that's presently how the data is split (which is perfect) but the only issue is that I can't segregate out the 20-year-olds.

### Please provide the fields expected in this dataset:

Variables | 2019
------|---------
Age 21 | 1000

### How frequently would you need this dataset to be updated?
Annually, it's part of an ongoing research project and the population of Singaporeans at least 21-years-old is important for research since 21 is that legal age for voting and tends to be a universally significant age that's used in analyses.

### Can you give a short explanation on how you're planning to use this dataset?
I'm trying to figure out the total voting population and how the voter population is distributed along gender lines.

**Comment by lennardl** [comment]
@JovinLeong For that split you would need to approach SingStat for it as they are the owners of the data.
