### ISSUE TITLE
Singapore's Monthly Population 

### ISSUE THREAD

**Issue by Conefourthrees** [datagovsg/datagovsg-datasets#670]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Singapore's Monthly Population from 2010
or
Singapore's Monthly Population by location/area from 2010

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | population
------|---------|-------------
2017-09|Singapore|10000

or

month| country | area | population
2017-09 | Singapore | North | 10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X] Monthly
- [X] Weekly (preferable)
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I'll be using it for a group project on Machine Learning in NUS.

**Comment by lennardl** [comment]
We only have the population numbers by years: https://data.gov.sg/search?q=population+by+month
If you need it by month you might have to approach SingStat to see if a breakdown is available.
