### ISSUE TITLE
Dataset request: Condo property data

### ISSUE THREAD

**Issue by derekchong79** [datagovsg/datagovsg-datasets#673]
### Please provide the name of the dataset or describe the dataset that you're requesting:

All condo property data with the following information
1. Name of condo
2. Block number
3. Floor number
4. Unit number
5. Size in square feet
6. Number of rooms

Each home unit is to be listed in a single row in excel. 

This data request is for a study purpose. 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

URA

### If there's an issue with a dataset, please provide a description of the problem

NA.

### Please provide the fields expected in this dataset:

1. Name of condo
2. Block number
3. Floor number
4. Unit number
5. Size in square feet
6. Number of rooms

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

Just run once.

### Can you give a short explanation on how you're planning to use this dataset?

To study Singapore property prices using data science. I am not a Property Agent.

**Comment by lennardl** [comment]
@derekchong79 We do not have that data broken down to the detail that you're requesting for.
