### ISSUE TITLE
"HDB Property Information" Data Issue

### ISSUE THREAD

**Issue by superlu19601** [datagovsg/datagovsg-datasets#674]
### Please provide the name of the dataset or describe the dataset that you're requesting:

[HDB Property Information](https://data.gov.sg/dataset/hdb-property-information)

### Do you know which agency provides/can provide this data?
HDB

### If there's an issue with a dataset, please provide a description of the problem
There are duplicates returned from the API.

Example:
_id = 12 from https://data.gov.sg//api/action/datastore_search?&resource_id=482bfa14-2977-4035-9c61-c85f871daf4e and _id = 715 from https://data.gov.sg//api/action/datastore_search?offset=700&resource_id=482bfa14-2977-4035-9c61-c85f871daf4e are the same HDB block (105 BIDADARI PK DR)

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@superlu19601  Can you please confirm its still the same on your end now?

**Comment by superlu19601** [comment]
Confirm that the issue is resolved. Thanks.
