### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by dingz26** [datagovsg/datagovsg-datasets#675]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Hi, I am looking for numbers on the spending of Singaporeans on specific products such as

Running Shoes
Toothpaste
Sunscreen
Eyewear

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

No
### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Dec | Singapore | Singaporeans
month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

I am planning to use this data set for my programme on Channel News Asia that is exploring consumer behaviour when it comes to choosing certain products.

**Comment by lennardl** [comment]
@dingz26 We don't have the breakdown of data to that level, SingStat might be able to help with that

**Comment by dingz26** [comment]
Thanks!

Regards,
DJ

Mobile: 97626819
