### ISSUE TITLE
Dataset request: news headline

### ISSUE THREAD

**Issue by lionelcrottaz** [datagovsg/datagovsg-datasets#676]
### Please provide the name of the dataset or describe the dataset that you're requesting:
news topics

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
MDA, SPH, Mediacorp, others

### If there's an issue with a dataset, please provide a description of the problem
N/A

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

newsheadline | date | source
COVID-19 | 08/04/2020 | channelnewsasia.com

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [] Hourly
- [x] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Having the topics of all news headlines discussed in any media in Singapore.
The goal is to understand what is trending in the population in terms of topic of conversation.

**Comment by lennardl** [comment]
@lionelcrottaz You will need to get the data from the individual sites as we do not compile non-government data

**Comment by lionelcrottaz** [comment]
Ok, thanks anyway. Stay safe.
