### ISSUE TITLE
Dataset request: SHP Files for Master Plan 2003 Land Use

### ISSUE THREAD

**Issue by ghost** [datagovsg/datagovsg-datasets#677]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Shapefile (.shp) of the "Master Plan 2003 Land Use". The Master Plans from 2008 and 2014 are available, however the one for 2003 does not contain a file (https://data.gov.sg/dataset/master-plan-2003-land-use)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Urban Redevelopment Authority (URA)

### If there's an issue with a dataset, please provide a description of the problem
No data available. 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

Shapefile or KML file

### How frequently would you need this dataset to be updated?
N/A

Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Needed for my research which also covers land use change.

**Comment by lennardl** [comment]
@Nonoeelle We are aware of the issue and getting help from URA to update this.
