### ISSUE TITLE
Historical Carpark Availability Data

### ISSUE THREAD

**Issue by lhuasheng** [datagovsg/datagovsg-datasets#678]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Historical Daily Carpark Availability Data

### Do you know which agency provides/can provide this data?
LTA
Govtech

### If there's an issue with a dataset, please provide a description of the problem
Current LTA datamall api only provides real-time data. I would like to get historical daily or hourly data to do carpark modelling and visualisation.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Timestamp|CarParkID|Area |Development |Location |Total number of lots|AvailableLots |LotType |Agency

or a subset of this data

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [X ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

To use for carpark modelling and visualisation for geospatial insights.

**Comment by lennardl** [comment]
You can pass in the data param as stated in the API reference to retrieve pass data

**Comment by lhuasheng** [comment]
![image](https://user-images.githubusercontent.com/32332135/79210770-e962dd80-7e77-11ea-8582-b7a82ecbba35.png)

Sorry, can you please show me an example? Eg, how can we retrieve the carpark past availability on 
 2019 Jan 02 at 13.15pm. Pai seh, pai seh.

**Comment by lennardl** [comment]
Use this: https://data.gov.sg/dataset/carpark-availability

**Comment by lhuasheng** [comment]
Thank you! Do you know if the dataset  includes LTA and URA carparks?

**Comment by lennardl** [comment]
It only covers HDB owned carparks. The details of the carparks can be found here: https://data.gov.sg/dataset/hdb-carpark-information
