### ISSUE TITLE
Property Home Sales in Singapore for past 10 years

### ISSUE THREAD

**Issue by derekchong79** [datagovsg/datagovsg-datasets#679]
### Please provide the name of the dataset or describe the dataset that you're requesting:

I would like to get the information of past home sales of properties from HDB, condominiums and landed properties in Singapore for the past 10 years.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

URA

### If there's an issue with a dataset, please provide a description of the problem

new data request

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

1. Project Name
2. Street Name
3. Type
4. Postal District
5. Postal Code
6. Market Segment
7. Tenure (freehold, xx years lease from year yyyy)
8. Type of Sale (new sale, resale, subsale)
9. Number of units
10. Price
11. Net Price
12. Area in Square Feet
13. Type of Area
14. Floor Level
15. Unit Price
16. Date of Sale (mm-yyyy)

### How frequently would you need this dataset to be updated?

monthly

### Can you give a short explanation on how you're planning to use this dataset?

I am using the data for data science analysis purposes.

**Comment by lennardl** [comment]
@derekchong79 We do not have that breakdown for the private property, you would need to approach URA for that specific breakdown.
