### ISSUE TITLE
Dataset request: <PM2.5 data request>

### ISSUE THREAD

**Issue by MSaiful94** [datagovsg/datagovsg-datasets#68]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [X] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
This data will be use in my study for comparing the PM2.5 in Singapore and Johor Bahru, Malaysia

**Comment by iewil** [comment]
@MSaiful94 our developers portal has the historical PM2.5 levels for the past year or so, and this can be queried in intervals of 2-3 minutes. NEA also has historical records on [their site ](http://www.nea.gov.sg/weather-climate/climate/historical-daily-records), but this only provides you with daily averages. Their records span all the way back to 1980s, and we're working to get this on data.gov.sg in a machine readable format.

**Comment by MSaiful94** [comment]
@iewil Hi Mr/Sir. Thanks for the response. As a newbie in here, I'm not familiar with this system. How am I going to get/retrieve the data as you stated that your developers portal do have the historical data of PM2.5?

**Comment by MSaiful94** [comment]
Hi Mr @iewil . How am I going to retrieve the data?
I'll be very appreciate upon your help on getting me the data.
Thanks.
