### ISSUE TITLE
Dataset request: COVID-19 Case Summary

### ISSUE THREAD

**Issue by ervintwj** [datagovsg/datagovsg-datasets#680]
### Please provide the name of the dataset or describe the dataset that you're requesting:
COVID-19 Case Summary

### Do you know which agency provides/can provide this data?

Ministry Of Health

### If there's an issue with a dataset, please provide a description of the problem
n/a

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

date | imported cases | linked to cluster | linked to other cases | pending tracing | daily total |
------|----------------|-----------------|----------------------|-----------------|----------|
11-04 |             0           |       98                  |                 29                |           71              |    198

date | active cases | stable | critical | isolated | discharged | death
------|-------------|-------|--------|---------|------------|-----|
11-04 |      875         |   843  |    32     |     734    |       493       |   7

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Enable the research community to apply recent advances in natural language processing and other AI techniques to generate new insights in support of the ongoing fight against the infectious disease. 

To produce forecasts, and potentially identify factors that appear to impact the transmission rate of COVID-19

**Comment by lennardl** [comment]
@ervintwj For Covid-19 related information and data you would need to get it from MOH on their Covid-19 page

**Comment by ervintwj** [comment]
> @ervintwj For Covid-19 related information and data you would need to get it from MOH on their Covid-19 page

True, nonetheless it's good to have a. a readily available structured dataset, and b. it be available from a single repo (i.e. data.gov.sg).

**Comment by lennardl** [comment]
@ervintwj Understood but for now all data on Covid-19 would need to be reference back to MOH
