### ISSUE TITLE
Dataset request: <dataset title> Electric Vehicles and EV Charging Points/Stations

### ISSUE THREAD

**Issue by Oohpierre** [datagovsg/datagovsg-datasets#681]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I am trying to understand the trends of electric vehicle adoption, as well as the evolution of EV charging points/stations in Singapore. It would also be ideal if the dataset is cut by type (EV car make, EV charging point capacity/speed, etc.) as well as a measure of the carbon emission by EVs in Singapore.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
I am not very sure... Would a combination of LTA and URA have this information?

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I want to understand the trend of EV adoption in Singapore as well as existing EV charging infrastructure so that I can derive intelligence/opportunity when it comes to the provision of additional EV charging stations in Singapore (where, how many, what type, etc.)

**Comment by lennardl** [comment]
@Oohpierre We currently do not have the data, we have informed EMA on this and they replied that they are in the process of aggregating that data.
