### ISSUE TITLE
Dataset request: ACRA

### ISSUE THREAD

**Issue by turingvangogh** [datagovsg/datagovsg-datasets#682]
### Please provide the name of the dataset or describe the dataset that you're requesting:
ACRA business information
- Basic Entity Information (Business name, UEN, Date of incorporation/registration, Status, Entity type, etc.)
- Singapore Standard Industrial Classification (SSIC) (Primary, Secondary, User Prescribed Activity)

### Do you know which agency provides/can provide this data?
ACRA

### If there's an issue with a dataset, please provide a description of the problem
NA
### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

name | uen | status| industry|address| date_incorporated|ssic|entity_type
### How frequently would you need this dataset to be updated?
- [X] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To plot a map of new companies formed

**Comment by lennardl** [comment]
The data is available but pending an update from ACRA:
https://data.gov.sg/dataset/acra-information-on-corporate-entities
https://data.gov.sg/dataset/entities-with-unique-entity-number
