### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by Xiao-Congchen** [datagovsg/datagovsg-datasets#683]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Number of Student Care Centres, Capacity and Enrollment

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Possibly the Ministry of Education

### If there's an issue with a dataset, please provide a description of the problem
The current one available only has data till 2014, which really requires updating

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

Total number of Student Care Centres, by Region | Total Capacity of Student Care Centres, by region | Enrollment Rate of the Student Care Centres, by Region

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
A research project which involves looking into current Student Care Centres' enrollment rate.

**Comment by lennardl** [comment]
@Xiao-Congchen We will approach MSF to update this dataset

**Comment by lennardl** [comment]
Only location data is available https://data.gov.sg/dataset/student-care-services
