### ISSUE TITLE
Dataset request: Compensation Of Employees By Industry At Current Prices, Annual

### ISSUE THREAD

**Issue by limyunqian** [datagovsg/datagovsg-datasets#686]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Compensation Of Employees By Industry At Current Prices, Annual

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:  
*(e.g. month | country | passengers)*

month | industry| role| rank|salary
------|---------|-------------
2017-09|banking| finance advisor| executive|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] Test

### Can you give a short explanation on how you're planning to use this dataset?
For my short course project for prog r.

**Comment by lennardl** [comment]
@limyunqian We do not have that data
