### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by zhouyanyijie** [datagovsg/datagovsg-datasets#688]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Number & Amount of Claims Made under MediShield/MediShield Life

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

Central Provident Fund Board

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@zhouyanyijie The data can be found here https://data.gov.sg/dataset/amount-of-claims-made-under-medishield-medishield-life-annual the data is outdated and I've approached CPF to help update this.
