### ISSUE TITLE
Dataset request: ACRA Information on Corporate Entities (Frequent Update Request)

### ISSUE THREAD

**Issue by daveanonuevo** [datagovsg/datagovsg-datasets#689]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Requesting for real-time/frequently updated information on ACRA Information on Corporate Entities.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
ACRA

### If there's an issue with a dataset, please provide a description of the problem
[Entities registered with ACRA](https://data.gov.sg/dataset/entities-with-unique-entity-number?resource_id=bdb377b8-096f-4f86-9c4f-85bad80ef93c) is outdated
[ACRA Information on Corporate Entities](https://data.gov.sg/dataset/acra-information-on-corporate-entities) is not updated frequently.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

uen_issue_date | entity name | UEN
-----------------|--------------|-------------
1992-03-28|SINGAPORE TELECOMMUNICATIONS LIMITED|199201624D

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [X] Hourly
- [X] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Dataset does not have any missing fields; however, it's not updated as frequently as it can be.
Goal would be to create a service whereby marketers/sales are able to reach out to newly formed companies to offer packages, support , help, etc.
This would open up newly formed corporations to being discovered.

**Comment by lennardl** [comment]
@daveanonuevo We are aware that the data is outdated and have reached out to ACRA to update the dataset.

**Comment by daveanonuevo** [comment]
@lennardl would it be possible for ACRA to automate the update process?

**Comment by lennardl** [comment]
@daveanonuevo We have a process in place, ACRA has not provided the latest data
