### ISSUE TITLE
Dataset request: Bicycle sharing data

### ISSUE THREAD

**Issue by vivipazos** [datagovsg/datagovsg-datasets#69]
### Please provide the name of the dataset or describe the dataset that you're requesting:
We would like to know if it's possible to get access to geolocated, time-stamped data of bike sharing usage in Singapore. In this [article](http://www.straitstimes.com/asia/the-king-of-bike-sharing) by The Straits Times, it says the data is provided to LTA by MoBike This information will be great for the public.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
LTA (http://www.straitstimes.com/asia/the-king-of-bike-sharing)

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

time-start | time-end | location-start | location-end | total-km
------|---------|-------------
2017-09-01 0800|2017-09-01 0810| 1.342616, 103.848418 | 1.342677, 103.845169 | 0.5

### How frequently would you need this dataset to be updated?
Just once is ok but then of course, if it can be updated after this: 
- [x] Monthly
- [x] Weekly

### Can you give a short explanation on how you're planning to use this dataset?
For a news story looking at bike sharing usage in Singapore. The most popular routes, most popular areas, peak vs non-peak usage, unusual bike usage.

**Comment by iewil** [comment]
@vivipazos I've forwarded your request to our colleagues at LTA. I'll post the updates here when i've heard back from them.
