### ISSUE TITLE
Dataset request: <Road accident related to HAZMAT vehicle>

### ISSUE THREAD

**Issue by evonnechng** [datagovsg/datagovsg-datasets#690]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Road accident related to HAZMAT vehicle

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
MOT/LTA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2019|Singapore|
2019|Australia|
2019|United Kingdom|
2019|United States|

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To do a study on the road accident with HAZMAT vehicle

**Comment by lennardl** [comment]
@evonnechng We have general road accident statistics not specifics related to HAZMAT vehicles
https://data.gov.sg/dataset/causes-of-road-accidents-causes-of-accidents-by-severity-of-injury-sustained

**Comment by evonnechng** [comment]
@lennardl: Thanks for your prompt response. We really appreciate it. How about data on the road accident statistics based on the vehicle type?

**Comment by lennardl** [comment]
@evonnechng the type of vehicle is recorded but not made available by SPF
