### ISSUE TITLE
DATA Requesting 

### ISSUE THREAD

**Issue by Praveenraj55** [datagovsg/datagovsg-datasets#691]
### Please provide the name of the dataset or describe the dataset that you're requesting:
- Singapore Contractors Associates 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
https://www.scal.com.sg/

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Singapore
Full data

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [1 ] Annually
- [ 1] Monthly
- [ 1] Weekly
- [ 1] Daily
- [1 ] Hourly
- [1 ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
we are going to use this date for the job opportunity and marketings
![building-construction-1575375068-5186367](https://user-images.githubusercontent.com/63828211/79523706-62894d00-8091-11ea-836a-f1a704e5da57.jpg)

**Comment by lennardl** [comment]
@Praveenraj55 The Singapore Contractors Associates is not a government entity. We are not able to host non-government entity data
