### ISSUE TITLE
Dataset request: Hawker Stores and Restaurant

### ISSUE THREAD

**Issue by anythinksg** [datagovsg/datagovsg-datasets#693]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Hawker Centers, Malls;
Hawker Stores, Restaurant;
Geo-coordinates - Latitude and Longitude.
Status

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
NEA (for info on hawker stores / license)
ACRA (for status of business)

### If there's an issue with a dataset, please provide a description of the problem
For existing APIs for ACRA information on Corporate Entities, as located in the below link, APIs resource ids are not provided for the following alphabets:
> F, G, J, L, M, P, W, X, Y, Z

[site](https://data.gov.sg/dataset/acra-information-on-corporate-entities?resource_id=6b5cbfa7-b502-4ce6-875d-dafff7ff04f2)

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Hawker Center / Mall | Hawker Store / Restaurant | Cuisine | Address | Postal Code | Latitude | Longitude | Status
------|---------|-------------
Maxwell Food Gentre | Tian Tian Hainanese Chicken Rice | Asian / Chinese | 1 Kadayanallur St | 069184 | 1.2805 | 103.8445 | Live

### How frequently would you need this dataset to be updated?
Example: 

- [ ] Annually
- [ ] Monthly
- [ X ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To suggest local hawker food and/or restaurant to users (both local and foreigners) and to promote our local hawker heritage and food-indulge culture.
Need to ensure that the data base is up to date.

**Comment by lennardl** [comment]
@anythinksg We have the location of hawker centres here https://data.gov.sg/dataset/hawker-centres we do not have the restaurant listing. I would not recommend using the ACRA dataset as it is not updated frequently.

**Comment by anythinksg** [comment]
Hi @lennardl, thanks for the comments and the suggestion. Was hoping to get the listings of the registered hawkers (stores) as well.

**Comment by wentjun** [comment]
+1 to @anythinksg 's request

@lennardl Is there anything you can do to make this data available? If not, do you know which organisation is in charge of this?

**Comment by lennardl** [comment]
Let me approach NEA to see if they are able to provide the full list
