### ISSUE TITLE
Request to update LTA carpark rates

### ISSUE THREAD

**Issue by MarkFull** [datagovsg/datagovsg-datasets#694]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Carpark Rates (Major Shopping Malls, Attractions and Hotels)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

LTA

### If there's an issue with a dataset, please provide a description of the problem

Last update time is Nov 2018. Some data have been out of date.

### Please provide the fields expected in this dataset:
Same as before

### How frequently would you need this dataset to be updated?
- [x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Building a tool to show nearby carpark realtime prices and availability.
http://sgparking.firebaseapp.com

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/carpark-rates

**Comment by MarkFull** [comment]
@lennardl Yes, this is the dataset I was mentioning. You can see the last update time is Nov 2018. It would be really great to have the latest data. 

Let me know if this is not clear. Thank you in advance! 

<img width="935" alt="image" src="https://user-images.githubusercontent.com/498866/81080962-f37e7600-8f23-11ea-820a-1c3a5a020360.png">

**Comment by lennardl** [comment]
@MarkFull We have approached LTA for assistance. Will update again once we hear from them.

**Comment by MarkFull** [comment]
@lennardl Thanks a lot!
