### ISSUE TITLE
Dataset request: HDB BTO price and application rates

### ISSUE THREAD

**Issue by ernesthan** [datagovsg/datagovsg-datasets#696]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I would to request for HDB BTO price and the application rates.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Housing Development Board

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
BTO Price:

Year of booking | BTO Project Name| Flat Type | Address | | Floor area | Floor level | Lease Commence | BTO price

Application Rate: 
BTO project name | Number of Units | Flat Type | Ethnicity | Applicants Type | Number of applicants

### How frequently would you need this dataset to be updated?
Example: 
- [X] Quarterly (As per BTO launch)

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

For personal interest, to plan for when and where to apply for BTO. The data is already public information but there are third-party selling this information for interested parties.

**Comment by lennardl** [comment]
We only have BTO prices and not application rates https://data.gov.sg/dataset/price-range-of-hdb-flats-offered
