### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by huichiang** [datagovsg/datagovsg-datasets#697]
### Please provide the name of the dataset or describe the dataset that you're requesting:
COVID-19 Cases in Singapore

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Health

### If there's an issue with a dataset, please provide a description of the problem
Does not exist

### Please provide the fields expected in this dataset:
*(e.g.date | country | number of cases | number of deaths)*
date | country | number of cases | number of deaths
------|---------|-------------|----
2017-09-01|Singapore|10000|0

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For projects of personal interest. Data is already being released by MOH daily, but would be convenient for many people if it could be aggregated.

**Comment by lennardl** [comment]
@huichiang The Covid-19 is limited to MOH hence we are not hosting it on Data.gov.sg
