### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by upkar29** [datagovsg/datagovsg-datasets#698]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Household loans outstanding and Non-performing loans out of them

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
https://www.hdb.gov.sg/cs/infoweb/homepage

### If there's an issue with a dataset, please provide a description of the problem
Currently data either limited or not available

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Year|Bridge and Housing Loans|Non-performing loans
month | country | House and Bridging loans | Non-performing loans linked to them |
------|---------|-------------
2018-00|Singapore|xxxx|xxxx|

2018-00|Singapore

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [x] Annually- want this
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For my internship project

**Comment by lennardl** [comment]
@upkar29 We do not have that data available. You would need to approach HDB for that.

**Comment by ckksteven** [comment]
Dear Lennard,
May I check how to cancel my account, so I will no longer receive any below email.
I have been receiving these emails almost 10 emails/day.
Yet, when I go to github, try many times trying to unsubscribe, trying to even delete or cancel my own account, still the email keep coming.
I must have press some buttons accidentally, please enlighten me.

Kindly advise.

Thanks,
Best regards,
Steven

**Comment by lennardl** [comment]
@ckksteven I believe its because you are watching the following page https://github.com/datagovsg/datagovsg-datasets

**Comment by ckksteven** [comment]
Thanks Lennard.
I realized the button could not be push at all because of browser issues. After changing to Edge, everything is fine, managed to unwatch it finally.  THANK YOU.
