### ISSUE TITLE
Dataset request: Covid-19 outbreak data in Singapore

### ISSUE THREAD

**Issue by jxwhat** [datagovsg/datagovsg-datasets#699]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Covid-19 outbreak data

### Do you know which agency provides/can provide this data?

MOH
 
Actually, I'm looking at [this data](https://www.moh.gov.sg/docs/librariesprovider5/default-document-library/annex-b5b793d89fa65418ca2cc232a47b12dfa.pdf) but in .csv format.

### Please provide the fields expected in this dataset:

Case number | Date of confirmation | Hospital admitted | Age (years) | Gender | Nationality | Nationality-2 | Exposure | Links | Cluster 
------|---------|--------|-----|------|-------|-------|--------|---------|-------------|
6130 | 18 Apr | NTFGH | 31 | M | China | Work permit holder | Local linked | N.A. | S11 Dormitory

### How frequently would you need this dataset to be updated?
Example: 

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Analysis on the Covid outbreak in Singapore

**Comment by lennardl** [comment]
@jxwhat For Covid-19 related data you would need to refer to MOH's Covid-19 page it will be the single source of accurate Covid-19 data

**Comment by wentjun** [comment]
@jxwhat I have a copy of what you are looking for, but it is in JSON format. However, it is incomplete as MOH no longer release most of the data since 2 weeks ago.
