### ISSUE TITLE
Dataset request: MRT Arrival Time

### ISSUE THREAD

**Issue by why-2004** [datagovsg/datagovsg-datasets#700]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Arrival times for MRT trains at various stations

### Do you know which agency provides/can provide this data?
LTA
(note: SMRT already has such a website, which proves that exposing this API is feasible)

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

platform | destination | time

### How frequently would you need this dataset to be updated?
Example: 

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [X] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Real-time MRT app to forecast ideal departure time

**Comment by lennardl** [comment]
We do not have the data
