### ISSUE TITLE
HDB Resale Price Update Time

### ISSUE THREAD

**Issue by superlu19601** [datagovsg/datagovsg-datasets#702]
### Please provide the name of the dataset or describe the dataset that you're requesting:
[HDB Resale Price](https://data.gov.sg/dataset/resale-flat-prices?resource_id=42ff9cfe-abe5-4b54-beda-c88f9bb438ee)

### Do you know which agency provides/can provide this data?
HDB

### If there's an issue with a dataset, please provide a description of the problem
The data has been updated at the above link for March 2020 but the api retrieves no results. May I know usually how much delay should be expected for the update?

**Comment by lennardl** [comment]
Can you check the APIs again, as for the latest data HDB responded that the data will be delayed.

**Comment by superlu19601** [comment]
Thanks. I got the data now. Is it a one-time issue or I should expect such delay in general?

**Comment by lennardl** [comment]
@superlu19601 The issue with the API would be one off as for the delay in data it would be expected to remain till Covid-19 gets less serious
