### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by LMDlifers** [datagovsg/datagovsg-datasets#703]
### Please provide the name of the dataset or describe the dataset that you're requesting:

supermarket sales

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

2020-2000|Singapore|nil

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [ ] Annually
- [X ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For a project, researching on how supermarket sales are affected each time during a financial meltdown.

**Comment by lennardl** [comment]
@LMDlifers We do not have the data on supermarket sales as they are private entities
