### ISSUE TITLE
Dataset request: Individual CPF data

### ISSUE THREAD

**Issue by marcusfwu** [datagovsg/datagovsg-datasets#705]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Individual CPF statement

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Central Provident Fund Board

### If there's an issue with a dataset, please provide a description of the problem
No issue with the data

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Ordinary Account | Special Account |Medisave Account
------|---------|-------------
$xxx|$xxx|$xxx

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Looking to build a mobile app for manage management so as to plan for retirement. The app will have direct linkage to CPF amount so that individual knows how much more saving he/she needs for retirement and we may also look into how we can use app to utilise CPF OA amount for investment. The retrieval of CPF data should be secured and authenticated only via myInfo-data.

**Comment by lennardl** [comment]
Individual CPF data cannot be retrieved on Data.gov.sg. To get the data you need to approach CPF.
