### ISSUE TITLE
Dataset request: <Estimated distance and time between MRT stations>

### ISSUE THREAD

**Issue by Jiaaa-yang** [datagovsg/datagovsg-datasets#706]
### Please provide the name of the dataset or describe the dataset that you're requesting:
The estimated distance and time between each MRT stations and its neighbouring one

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
LTA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

station | neighbour | distance(km) | time(mins)
------|---------|-------------|-------
Yishun|Khatib|1.4|2

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For use in creating an app to find optimal path from one MRT station to another, using the dataset in search algorithm.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/master-plan-2019-rail-station-layer?resource_id=5e5a3637-bee6-4ca4-8d5e-2a6936d93965
