### ISSUE TITLE
Missing Values

### ISSUE THREAD

**Issue by daveanonuevo** [datagovsg/datagovsg-datasets#707]
### Please provide the name of the dataset or describe the dataset that you're requesting:
ACRA Information on Corporate Entities

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
ACRA

### If there's an issue with a dataset, please provide a description of the problem

Dataset has missing values

e.g. CYBER YOUTH SINGAPORE PTE. LTD (UEN NO:  201929046R) does not appear in the dataset. However, they incorporated in 07 September 2019.

I believe that this means that it's missing because the latest incorporation date is February 8 2020.

**Comment by lennardl** [comment]
@daveanonuevo Can you flag this to ACRA as they are the owners of the dataset and we do not have the ability to add entries into the data
