### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by tjsmith2** [datagovsg/datagovsg-datasets#708]
### Please provide the name of the dataset or describe the dataset that you're requesting:

List of Telecommunication Dealer's in Singapore

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

Infocomm Media Development Agency

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

entity name | primary_ssic_description | secondary_ssic_description | street name | uen |

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

Searching for possible distributors for clients who manufacture telecomm equipment.

**Comment by lennardl** [comment]
We are checking with IMDA on this

**Comment by tjsmith2** [comment]
Any update?

Regards,

Tom Smith, P.Eng 

Principal Engineer
TJS Technical Services Inc.

Tel: +1 403-612-6664 

Email:  <mailto:tsmith@tjstechnical.com> tsmith@tjstechnical.com 
 <http://tjstechnical.com/> http://tjstechnical.com 

Follow us on Twitter: TJS_Technical

**Comment by lennardl** [comment]
@tjsmith2 We have not heard back from IMDA on this. You might need to approach them directly

**Comment by lennardl** [comment]
@tjsmith2 IMDA responded and the list is found here https://eservice.imda.gov.sg/tls

**Comment by tjsmith2** [comment]
Thanks!

Regards,

Tom Smith, P.Eng 

Principal Engineer
TJS Technical Services Inc.

Tel: +1 403-612-6664 

Email:  <mailto:tsmith@tjstechnical.com> tsmith@tjstechnical.com 
 <http://tjstechnical.com/> http://tjstechnical.com 

Follow us on Twitter: TJS_Technical
