### ISSUE TITLE
Dataset request: Public Holidays

### ISSUE THREAD

**Issue by cyau73** [datagovsg/datagovsg-datasets#709]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Singapore's public holidays for the past 50 years

### Do you know which agency provides/can provide this data?
Ministry of Manpower or GovTech

### If there's an issue with a dataset, please provide a description of the problem
If the public holiday falls on a Sunday, the following Monday is a public holiday but is not in the list.

### Please provide the fields expected in this dataset:
date | holiday 
----------|--------------
2020-01-01|New Year's Day

### How frequently would you need this dataset to be updated?
- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Used in conjunction with other data

**Comment by lennardl** [comment]
@cyau73 We do not have data that goes that far back into the past, you might have to approach the Ministry of Manpower for this.
