### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by yoonghm** [datagovsg/datagovsg-datasets#71]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I need three datasets:

+ Bus stop
      + Bus stop ID
      + GPS location

+ Bus service from one starting bus stop/station to its ending bus stop/station
      + Bus service number
      + Bus stops (in array) served by the bus service 
      + Distance between each bus stops (in array) served by the bus service

+ MRT/LRT
      + MRT station ID
      + GPS location

+ MRT/LRT service
      + MRT/LRT service number
      + MRT/LRT stations (in array) served by the MRT/LRT service
      + Distance between each MRT/LRT stations (in array) served by the MRT/LRT service

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
+ SMRT
+ SBS

### If there's an issue with a dataset, please provide a description of the problem
 
NA

### Please provide the fields expected in this dataset:

Please see my comments above about the required fields.

### How frequently would you need this dataset to be updated?
Example: 
- [x] As and when it is updated by SMRT and SBS.  The datasets are static.

### Can you give a short explanation on how you're planning to use this dataset?
Google map sometimes gives long paths, without knowing the existence of short walking distance, etc.

**Comment by iewil** [comment]
@yoonghm most of what you're looking for is already available on LTA's datamall (https://www.mytransport.sg/content/mytransport/home/dataMall.html). Can you have a look at what they have and let us know if there's anything else that has not already been provided? thanks.
