### ISSUE TITLE
Dataset request: Hourly Tidal Height Predictions 

### ISSUE THREAD

**Issue by teddyywj** [datagovsg/datagovsg-datasets#710]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Hourly Tidal Height Predictions

### Do you know which agency provides/can provide this data?
MPA

### If there's an issue with a dataset, please provide a description of the problem
It is available as a print book, however probably good to have it online so that more people can have access to it. 
https://www.mpa.gov.sg/web/portal/home/media-centre/publications/singapore-tide-tables

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

datetime | predicted_tidal_height 
----------------------|---------
2020-05-01 09:00:00|1.0
2020-05-01 10:00:00|1.2
2020-05-01 11:00:00|1.3

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To get the predicted tidal height through an online interface, instead of referring to a book.

**Comment by lennardl** [comment]
@teddyywj We have approached MPA to help with this. Waiting on their response.

**Comment by teddyywj** [comment]
@lennardl Any update from MHA? Thanks.

**Comment by lennardl** [comment]
@teddyywj Nope they are not able to provide it in a format for Data.gov.sg

**Comment by teddyywj** [comment]
@lennardl  ah okay, thanks anyway!!
