### ISSUE TITLE
Dataset request: Historical Daily PSI (pre-2014)

### ISSUE THREAD

**Issue by Karykatura** [datagovsg/datagovsg-datasets#715]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Historical Daily PSI between 2008-2014. The only available dataset spans from 2014 to end of 2018.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
National Environment Agency

### If there's an issue with a dataset, please provide a description of the problem
Current dataset only goes as far back as 2014, API requests goes back only to 2016. From the following study: 
[https://www.mdpi.com/2073-4433/11/1/9/html](url)
That prior data did exist until as far as in 2019.

### Please provide the fields expected in this dataset:

YYYY-MM-DD | West | North | Central | East
------|---------|-------------
2017-09-02|23|30|25|27

### How frequently would you need this dataset to be updated?

- [ ] Annually
- [] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I'm conducting a research into how tourism impacts pollution in developed nations, working for King's College London.

**Comment by lennardl** [comment]
@Karykatura We do not have data from that far back, you would need to approach NEA for historical data before 2014
