### ISSUE TITLE
Dataset request: Sunrise and sunset api

### ISSUE THREAD

**Issue by Davianlols6** [datagovsg/datagovsg-datasets#716]
### Please provide the name of the dataset or describe the dataset that you're requesting:
An API which has sunrise and sunset data for SG

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
NEA

### If there's an issue with a dataset, please provide a description of the problem
nil

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

Date|Time of sunrise|Time of sunset

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [x ] Annually
- [x ] Monthly
- [x ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I'm planning to use it to make a telegram bot

**Comment by lennardl** [comment]
@Davianlols6 We do not have that data, you would need to approach NEA for this.
