### ISSUE TITLE
Dataset request: <number of sales of MNCs in Q1 of 2019 and 2020>

### ISSUE THREAD

**Issue by EliseGina** [datagovsg/datagovsg-datasets#718]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@EliseGina We do not have that data available
