### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by delnyx** [datagovsg/datagovsg-datasets#722]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Master Plan 2019 Building layer

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Urban Redevelopment Agency

### If there's an issue with a dataset, please provide a description of the problem
No dataset provided for download

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

Building name, polygon boundary

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [x] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For my graduate thesis in GIS

**Comment by lennardl** [comment]
@delnyx The dataset was not sent to Data.gov.sg we have approached URA to assist on the matter.

**Comment by delnyx** [comment]
@lennardl Thank you. When may I expect it to be made available?

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/master-plan-2019-building-layer
