### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by abcng** [datagovsg/datagovsg-datasets#723]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Number of cases of Credit-for-Sex Scams in Singapore in the last 5 years.

### Do you know which agency provides/can provide this data?

Ministry of Home Affairs - Singapore Police Force

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Year | Month | Number of cases
------|---------|-------------
2017|09|10000

### How frequently would you need this dataset to be updated?
- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Would like to use the data as part of reaserch for 2020 H1 Project Work Assessment

**Comment by lennardl** [comment]
@abcng We have approached SPF to ask if they can make the data available on Data.gov.sg

**Comment by lennardl** [comment]
@abcng SPF has responded and that the data is available here https://www.police.gov.sg/Media-Room/Statistics

**Comment by abcng** [comment]
@lennardl Thank you very much!
