### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by yelreveb** [datagovsg/datagovsg-datasets#724]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
HPB
Ministry of Health
HSA?

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
FY2019|Singapore|population

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For research purposes and development

**Comment by lennardl** [comment]
@yelreveb I'm not certain what data you are requesting for?

**Comment by yelreveb** [comment]
Hi Lennard,

I’m actually looking for data regarding Myopia / Cataract / Eye disease prevalence rate in Singapore. Is there data available on that?

 

 

 

Thank You

 

Best Regards,

Beverley
Optometrist

Business Development
Eagle Eye Centre


159 Sin Ming Road
#05-07 Amtech Building
Singapore 575625
 ☎ Tel: 64960583
http://www.eagleeyecentre.com.sg/

**Comment by lennardl** [comment]
@yelreveb We do not have that dataset
