### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by Dolomites** [datagovsg/datagovsg-datasets#728]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Government Procurement via GeBiz, Requesting for 2019 dataset. (website currently up till 2018

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Finance

### If there's an issue with a dataset, please provide a description of the problem
N/A

### Please provide the fields expected in this dataset:

tender_no. | tender_description | agency | award_date | tender_detail_status | supplier_name | awarded_amt

------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Business case for supplying to government tenders.

**Comment by lennardl** [comment]
@Dolomites We have informed MOF of this but they are currently pre-occupied with matters regarding Covid-19 to update the data.
