### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by raouln97** [datagovsg/datagovsg-datasets#729]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Super market inventory with expiration dates of food products

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
NTUC,Giant,Cold Storage

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month/Branch
------|---------|-------------
2017-09|Marine Parade|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ X ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
With this unexpected and unusual times, we want to use this data to let the Singaporeans know when to go down to supermarkets to get offers on food products.This would help Singaporeans save money as well as reduce food wastage that when food products are expired and the above organisations throw it out.

**Comment by lennardl** [comment]
@raouln97 We do not have that data as it falls under the individual supermarkets inventory.
