### ISSUE TITLE
Dataset request: HDB price range offered

### ISSUE THREAD

**Issue by fire9flyer** [datagovsg/datagovsg-datasets#73]
### Please provide the name of the dataset or describe the dataset that you're requesting:
price-range-of-hdb-flats-offered
( price-range-of-hdb-flats-offered.csv )

### Do you know which agency provides/can provide this data?

HDB

### If there's an issue with a dataset, please provide a description of the problem
There seem to be missing data:
    . Choa Chu Kang, 2010
    . Jurong West, 2011, 2012, 2013, 2014, 2015
    . Sembawang, 2012
    . Woodlands, 2011, 2015
    . Yishun, 2015

### Please provide the fields expected in this dataset:
    financial_year,
    town,
    room_type,
    min_selling_price,
    max_selling_price,
    min_selling_price_less_ahg_shg,
    max_selling_price_less_ahg_shg

### How frequently would you need this dataset to be updated?
- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For a study on Singapore Housing

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/price-range-of-hdb-flats-offered
