### ISSUE TITLE
Dataset request: Real time weather warning and advisory API

### ISSUE THREAD

**Issue by Davianlols6** [datagovsg/datagovsg-datasets#730]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Real time Weather warning and advisory API

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
NEA

### If there's an issue with a dataset, please provide a description of the problem
nil

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

|start|end|message
------|---------|-------------
|2020-05-20T05:00:00+08:00|2020-05-20T06:00:00+08:00|Moderate to heavy thundery showers  with gusty wind are expected over many areas of Singapore between 8.15pm and 9.15pm.

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [x] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For a telegram bot

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/realtime-weather-readings

**Comment by Davianlols6** [comment]
> https://data.gov.sg/dataset/realtime-weather-readings

I don't see it though

**Comment by lennardl** [comment]
@Davianlols6 We do not have the alerts just the weather readings itself
