### ISSUE TITLE
Dataset request: SHP files for Master Plan 2019 Land Use

### ISSUE THREAD

**Issue by mavh123** [datagovsg/datagovsg-datasets#731]
### Please provide the name of the dataset or describe the dataset that you're requesting:
The link on data.gov.sg for the "Master Plan 2019 Land Use" does not contain an available Shapefile (.shp) or KML file for download. (https://data.gov.sg/dataset/master-plan-2019-land-use-layer)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Urban Redevelopment Authority (URA)

### If there's an issue with a dataset, please provide a description of the problem
Dataset is unavailable on data.gov.sg

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Land Use| Region Name| Planning Area Name
------|---------|-------------
Residential|East Region|Paya Lebar

### How frequently would you need this dataset to be updated?

N/A

### Can you give a short explanation on how you're planning to use this dataset?
Needed for analysis of land use change

**Comment by lennardl** [comment]
You can download the file from the page. The KML file is contained within a zip
