### ISSUE TITLE
Dataset request: <Air Pollutant - Nitrogen Dioxide>

### ISSUE THREAD

**Issue by ilsuarez** [datagovsg/datagovsg-datasets#732]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Air Pollutant - Nitrogen Dioxide

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
National Environment Agency of Singapore

### If there's an issue with a dataset, please provide a description of the problem
Data provided on the website is only until 2018

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

time range | country |
------|---------|------------
2010 (as far back as possible) - 2020 | Singapore | 

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [x] Annually
- [X] Monthly
- [X] Weekly
- [X] Daily
- [x] Hourly
- [X] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Will use the dataset for 2 things:
- Cross reference modelling of NO2 conversion from satellite data
- Visualizing the change in ground-level NO2 year-on-year, month-on-month, and if possibly - day on day.

**Comment by lennardl** [comment]
@ilsuarez We have approached NEA and requested for an updated to the dataset
