### ISSUE TITLE
Dataset request: Listing of Registered Medical Devices

### ISSUE THREAD

**Issue by omnomnom123** [datagovsg/datagovsg-datasets#733]
### Do you know which agency provides/can provide this data?
HSA

### If there's an issue with a dataset, please provide a description of the problem
Request for a more updated version of Listing of Registered Medical Devices

### Please provide the fields expected in this dataset:
As per current version of Listing of Registered Medical Devices

device_name | description | medical_speciality_area | hs_code | hsa_product_code | medical_device_class | device_registration_no | registration_date | expiry_date | product_owner_name | product_owner_short_name | product_owner_address | registrant_name | registrant_address
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Understanding the changing regulatory landscape.

**Comment by lennardl** [comment]
@omnomnom123 We have approached HSA to request for an update to the dataset

**Comment by omnomnom123** [comment]
Thank you very much for your help in this!

**Comment by lennardl** [comment]
@omnomnom123 HSA responded they update the dataset once every 6 months so the next update is due by end June.

**Comment by omnomnom123** [comment]
Thank you very much! Appreciate your help in this!
