### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by Funx156** [datagovsg/datagovsg-datasets#734]
### Please provide the name of the dataset or describe the dataset that you're requesting:
The rainfall of each month in the year 2019

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
2019|Singapore|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For a school project

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/rainfall-monthly-total?view_id=be92ce92-d02e-4920-9479-ff6da87b45e8&resource_id=778814b8-1b96-404b-9ac9-68d6c00e637b
