### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by gilbertmak** [datagovsg/datagovsg-datasets#736]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Visitor International Arrivals to Singapore

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### If there's an issue with a dataset, please provide a description of the problem
https://data.gov.sg/dataset/total-visitor-international-arrivals-to-singapore?resource_id=83063203-ff81-4764-a9dc-c4e209921fe7
dataset does not include full breakdown on ASEAN countries, specifically cambodia

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For school project

**Comment by lennardl** [comment]
We do not have the data on international visitors to Singapore
