### ISSUE TITLE
Dataset request: Hourly precipitation total at stations "Upper Changi Road North S24" and "Choa Chu Kang Road S11" in 2019.

### ISSUE THREAD

**Issue by jas9303** [datagovsg/datagovsg-datasets#737]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Hourly precipitation total at stations "Upper Changi Road North" and "Choa Chu Kang Road" in 2019.

### Do you know which agency provides/can provide this data?
National Environmental Agency

### If there's an issue with a dataset, please provide a description of the problem
The API to retrieve realtime weather rainfall readings is not working. There is no recorded rainfall even though there was a rainfall event. 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

year | month | day | hour | weather station name/ID number | hourly precipitation total in mm
-----|-------|----|-----|------------------------|----------------------|
2019 | 01 | 01 | 0 | Upper Chang Road North / S24 | 0.5

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am a teacher and I will use the data to analyse the time of rainfall in Singapore. In geography, the timing of the rainfall corresponds to the type of rain experienced in Singapore. I will use this in class to teach them about the types of rainfall in Singapore.

**Comment by lennardl** [comment]
@jas9303 Thanks for the feedback as it is a realtime data we are getting from NEA we are not able to retrieve the data point for 2019
