### ISSUE TITLE
Dataset request: Master Plan 2019 SDCP Building Height Control layer

### ISSUE THREAD

**Issue by WawanSolihin** [datagovsg/datagovsg-datasets#739]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Master Plan 2019 SDCP Building Height Control layer

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Urban Redevelopment Authority

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For viewing

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/master-plan-2019-building-layer
