### ISSUE TITLE
Dataset issue: 2-hour weather forecast

### ISSUE THREAD

**Issue by iewil** [datagovsg/datagovsg-datasets#74]
### Please provide the name of the dataset or describe the dataset that you're requesting:
This is an existing API on developers.data.gov.sg

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
NEA

### If there's an issue with a dataset, please provide a description of the problem
Possible values for forecast not provided

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by nickwwh** [comment]
Similar issue with the rainfall API. Fields are empty

**Comment by lennardl** [comment]
Forecast provided: https://data.gov.sg/dataset/weather-forecast
