### ISSUE TITLE
Dataset request: Updated Local Universities Statistics (2020)

### ISSUE THREAD

**Issue by wentjun** [datagovsg/datagovsg-datasets#741]
### Please provide the name of the dataset or describe the dataset that you're requesting:

This is in reference to the existing datasets on data.gov.sg:

1) [Graduate Employment Survey - NTU, NUS, SIT, SMU, SUSS & SUTD](https://data.gov.sg/dataset/graduate-employment-survey-ntu-nus-sit-smu-suss-sutd)
2) [Universities - Intake, Enrolment and Graduates by Course](https://data.gov.sg/dataset/universities-intake-enrolment-and-graduates-by-course)

I have noticed that the data is only updated till the year of 2018. However, the data for 2019 is actually already available from official sources such as the [following](https://beta.moe.gov.sg/uploads/Web-Publication-NUS-GES-2019.pdf) [two](http://www.nus.edu.sg/registrar/docs/info/student-statistics/enrolment-statistics/undergraduate-studies/ug-enrol-20192020.pdf) links.

May I know if the datasets could be updated anytime soon? Thanks!

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

Personal projects.

**Comment by lennardl** [comment]
@wentjun I've reached out to the relevant people to request for an update to the data.

**Comment by lennardl** [comment]
I've been informed by the data owner that the 2019 data for Universities - Intake, Enrolment and Graduates by Course will only be made available in Oct 2020

**Comment by wentjun** [comment]
Thanks @lennardl !! By any chance, do you think it will be possible to include more varieties of data within this dataset? Such as proportion of students from JC/polytechnics/IB/etc, international/local/exchange students, race, and other public data from MOE that may be part of this dataset yet?

**Comment by lennardl** [comment]
I can ask MOE to see if such data can be made available.

**Comment by wentjun** [comment]
Cool! Anyways, for figures such as proportion of students coming from JC/poly, I believe it is already available in the yearly prospectus.

**Comment by lennardl** [comment]
@wentjun 
The polytechnic graduate data can be found here: https://data.gov.sg/dataset/polytechnics-intake-enrolment-and-graduates-by-course

The JC student enrolment data is available here: https://data.gov.sg/dataset/enrolment-pre-university-by-level

The data on international and exchange students is not available similar to the breakdown
