### ISSUE TITLE
Data set request MELS details for household appliances

### ISSUE THREAD

**Issue by felixsusanto** [datagovsg/datagovsg-datasets#742]
### Please provide the name of the dataset or describe the dataset that you're requesting:
MELS details for household appliances

### Do you know which agency provides/can provide this data?
*NEA*

### Please provide the fields expected in this dataset:
```typescript
type MELS = {
  annualEnergyConsumptionUnit: string;
  annualEnergyConsumptionValue: number;
  annualEnergyCost: number;
  applianceCapacityUnit: "kW"|"kg"|"L"|"inches";
  applianceCapacityValue: number;
  brand: string;
  category: "Air-Conditioner"|	"Refrigerator"|	"Clothes Dryer" | "Television"
  energyRating: "low"|"fair"|"good"|"very good"|"excellent";
  maxTicks: number;
  model: string;
  testStandardMethod: string;
  ticks: number;
  typeOfAppliance: string;
}[];
```
example of dataset: 
```javascript
[
  {
    annualEnergyConsumptionUnit: "kWh",
    annualEnergyConsumptionValue: 2295,
    annualEnergyCost: 620,
    applianceCapacityUnit: "kW",
    applianceCapacityValue: 6.52,
    brand: "Mitsubishi Electric",
    category: "Air-Conditioner",
    energyRating: "excellent",
    maxTicks: 4,
    model: "AC-ABCD123",
    testStandardMethod: "ISO-ABCD",
    ticks: 4,
    typeOfAppliance: "Split type (inverter) Air-conditioner"
  }
]
```

### How frequently would you need this dataset to be updated?
Example: 
- [ ] Annually
- [X] *Monthly*
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

This will help many people makes a buying decision of energy efficient household items.
Will create a website that make a comparison of items based on category, brands, models, efficiency rating, and price. Preferably data can be accessed through REST API

**Comment by lennardl** [comment]
@felixsusanto I have approached NEA to see if the data can be made available

**Comment by felixsusanto** [comment]
Hi is there any update on this? thank you

**Comment by lennardl** [comment]
@felixsusanto We are not able to get the data from them.

**Comment by felixsusanto** [comment]
Ok, thank you @lennardl
