### ISSUE TITLE
Dataset request: labour market in sports industry

### ISSUE THREAD

**Issue by damienlkh** [datagovsg/datagovsg-datasets#743]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Jobs available or labour market data related to sports industry (coaches, sportsman, sports event organisers, executives, fitness gyms, sports venue operators and executives, camp facilitators, PE Teachers, National sports association employees) 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Sports SG, MOM, EDB Spring

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?

Annually
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Assess employability and relevance of sports program diploma holders

**Comment by lennardl** [comment]
@damienlkh We only have the topline numbers here https://data.gov.sg/dataset/job-vacancy-by-industry-and-occupational-group-annual?resource_id=5d429272-3383-442e-b20b-5306daf55229
