### ISSUE TITLE
Dataset request: SARS cases, deaths and recoveries over time

### ISSUE THREAD

**Issue by ajlee2006** [datagovsg/datagovsg-datasets#745]
### Please provide the name of the dataset or describe the dataset that you're requesting:
SARS cases, deaths and recoveries over time

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
MOH?

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

date | new cases | total cases | new deaths | total deaths | new recoveries | total recoveries

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X?? (never, actually) ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Compare it with COVID-19, possibly

**Comment by lennardl** [comment]
@ajlee2006 I've approached MOH to see if the data exists and can be made available.

**Comment by lennardl** [comment]
@ajlee2006 We only have the topline numbers here https://data.gov.sg/dataset/job-vacancy-by-industry-and-occupational-group-annual?resource_id=5d429272-3383-442e-b20b-5306daf55229

**Comment by lennardl** [comment]
MOH does not have the details to share
