### ISSUE TITLE
Dataset request: <NTUC finest / online breakdown, lazada breakdown, redmart breakdown>

### ISSUE THREAD

**Issue by melvin-ng** [datagovsg/datagovsg-datasets#746]
Hi.

I would like to request for NTUC finest / online breakdown, lazada breakdown, redmart breakdown.

Do you know which agency provides/can provide this data?

### Please provide the fields expected in this dataset:
*(e.g. year | profit | revenue | sales | costs)*

month | country | passengers
------|---------|-------------
2010-2020|Singapore|

### How frequently would you need this dataset to be updated?
Example: 
- [ ] Annually
- [ ] Monthly

### Can you give a short explanation on how you're planning to use this dataset?
I would be using this to compare for online vs offline grocery shopping for NUS MBA program

**Comment by lennardl** [comment]
@melvin-ng The data you are seeking would belong to the individual companies and we do not have that data. You would have to approach the companies individually for it.
