### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by Muzzing** [datagovsg/datagovsg-datasets#748]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Diet consumption of people living in Singapore (calories, macronutrient, fruits, etc)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
MOH, HPB

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

*any*

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Project on data analysis, we are looking at the the diets of the people living in Singapore

**Comment by lennardl** [comment]
@JunweiPng We have reached out to HPB for the data.

**Comment by lennardl** [comment]
@JunweiPng the data is refreshed once every 2years (last updated in 2018). HPB is looking to get the data for 2020 but it will take a while. They have mentioned if you need the raw data quicker you will need to write in to HPB.
