### ISSUE TITLE
Dataset request: MRT smart card data or AFC data

### ISSUE THREAD

**Issue by SoohyunKimKr** [datagovsg/datagovsg-datasets#75]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Smart Card Data (for at least one week)
e.g. Card ID; Transaction Date; Transaction Start Time; Transaction End-time; Transaction ID; The number of Transfer; Type of transport; Line ID; Car/Train ID; Fare...

Or, AFC data
Transaction ID; Date; Start Time; End Time; Start Station ID; End Station ID; Duration; Fare type;

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
https://data.gov.sg/group/transport
https://data.gov.sg/dataset/public-transport-utilisation-average-public-transport-ridership

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
2017-09|Singapore|10000

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [X] Real-time
Historical data would be also appreciated.

### Can you give a short explanation on how you're planning to use this dataset?
It will be used for a master thesis, which studies IoT analytics opportunities in railway stations

**Comment by lennardl** [comment]
MRT data is not available
