### ISSUE TITLE
Dataset request: Past Crowd Levels of Buses

### ISSUE THREAD

**Issue by TrollersHere** [datagovsg/datagovsg-datasets#753]
Please provide the name of the dataset or describe the dataset that you're requesting:

Bus passenger load by bus service.

Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Land Transport Authority
If there's an issue with a dataset, please provide a description of the problem

Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Hourly | Bus Service | Number of times bus load is 'Limited Standing'
28-5-2020, 18:00 | 62 | 10

How frequently would you need this dataset to be updated?
Example: 

- [ ] Annually
- [X] *Test*
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

Can you give a short explanation on how you're planning to use this dataset?
I am a student from Nanyang Polytechnic, me and my group are trying to analyse which bus service is usually crowded during peak periods.

**Comment by lennardl** [comment]
@TrollersHere We do not have that data
