### ISSUE TITLE
Dataset request: <list of supermarket license>

### ISSUE THREAD

**Issue by gummydelxue** [datagovsg/datagovsg-datasets#758]
### Please provide the name of the dataset or describe the dataset that you're requesting:
List of supermarket license

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
SFA or NEA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
licence_num | licensee_name	| building_name | block_house_num | level_num | unit_num | street_name | postal_code		

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Personal Project

**Comment by lennardl** [comment]
@gummydelxue We have approached the relevant government agency to request for the data.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/listing-of-licensed-supermarkets?resource_id=df586152-d00f-4b15-b667-9e268f1b60df
