### ISSUE TITLE
Data request: park data at 2011

### ISSUE THREAD

**Issue by fanfmy** [datagovsg/datagovsg-datasets#76]
### Please provide the name of the dataset or describe the dataset that you're requesting:

I would like to have the dataset of a list of all parks in Singapore with name of the park and longitude and latitude of the address as of 2011.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

National Parks Board

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Park name | latitude | longitude
------|---------|-------------
Sembawang Park|1.461502967|103.8368454

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/parks
