### ISSUE TITLE
Dataset request: PM2.5 and PSI

### ISSUE THREAD

**Issue by zjllee** [datagovsg/datagovsg-datasets#760]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Historical 1-hr PM2.5
Historical 24-hr PSI

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
NEA

### If there's an issue with a dataset, please provide a description of the problem
Both datasets seem to have stopped being updated in 2019 but post-2019 data can be viewed here:
https://www.haze.gov.sg/resources/historical-readings (just not easily retrievable)

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Time	Readings for 2 Jun 2020
24-hr PSI
North	South	East	West	Central	Overall  Singapore

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Time-series comparison of air-quality in Singapore especially during special cases like the haze season and pandemics.

**Comment by lennardl** [comment]
You can use this can parse in a time/date to get the historical data
