### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by biondin** [datagovsg/datagovsg-datasets#761]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Number of hospital beds in acute hospitals, psychiatric hospitals and community hospitals from 2000 to 2019
Population data from 2000 to 2019
Hospital beds density from 2000 to 2019
Annual figures

I would like to update WHO database on hospital beds density

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
Some of the historical data may not be available
https://data.gov.sg/dataset/health-facilities
