### ISSUE TITLE
Dataset request: Smart Card Data

### ISSUE THREAD

**Issue by TrollersHere** [datagovsg/datagovsg-datasets#762]
### Please provide the name of the dataset or describe the dataset that you're requesting:
EZ-Link data of the busorigincode, busdestinationcode, boarding time, alighting time, bus service and busnumberplate. Need data from 2010-2019

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Land Transport Authority

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

card_id | type | origin | boardtime | destination | alighttime | bus service no. | busnumberplate |
02***5F | adult | 65191 | 2020-06-05 12:00 | 65161 | 2020-06-05 12:07 | 3 | SG1720L |

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am a student from Nanyang Polytechnic, me and my group are trying to analyse which bus service is usually crowded during peak periods.

**Comment by lennardl** [comment]
@TrollersHere That data is not available
