### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by solateks** [datagovsg/datagovsg-datasets#765]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Monthly Motor Vehicle Population Statistics by Type of Fuel Used

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
    Land Transport Authority 

### If there's an issue with a dataset, please provide a description of the problem
Dataset is showing different result from its dataset name. Currently showing the dataset for vehicle model type not by its intended vehicle by fuel type.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Month | Year | Quantity | Fuel Type |

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [x] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To create an estimated growth of modern fuel type of vehicle (electric /hybrid ) to understand what will be the future demand for infrastructure to support new fuel type vehicles.

**Comment by lennardl** [comment]
The data for 2019 has not been made available by LTA https://data.gov.sg/dataset/annual-motor-vehicle-population-by-type-of-fuel-used?resource_id=39e17d4c-3bd3-4814-9ae7-bf9df39a2f5d
