### ISSUE TITLE
Dengue death count

### ISSUE THREAD

**Issue by kaihendry** [datagovsg/datagovsg-datasets#766]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Deaths caused by Dengue

### Do you know which agency provides/can provide this data?
NEA/MOH

### If there's an issue with a dataset, please provide a description of the problem

Cases are reported, but not deaths AFAICT
https://www.nea.gov.sg/dengue-zika/dengue/dengue-clusters

Ideally the way cases are reported are in a machine readable format and **consistent** to the way covid19 cases are reported https://github.com/datagovsg/datagovsg-datasets/issues/646

### Please provide the fields expected in this dataset:
```
date|death to due dengue
2020-06-01 | 1
```

### How frequently would you need this dataset to be updated?
- [ X] Daily

### Can you give a short explanation on how you're planning to use this dataset?

Compare to https://www.moh.gov.sg/covid-19

**Comment by lennardl** [comment]
We only have the weekly numbers and do not have the deaths resulting from Dengue
