### ISSUE TITLE
Dataset request: Realtime Weather Readings across Singapore

### ISSUE THREAD

**Issue by cloudi32003** [datagovsg/datagovsg-datasets#768]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Realtime Weather Readings across Singapore

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Republic Polytechnic

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2020-09|Singapore|10

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [X] Hourly
- [X] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Doing IoT project on weather forecasting which need to retrieve data using API and JSON to project on my project using http request on node-red.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/realtime-weather-readings

**Comment by cloudi32003** [comment]
Hi there,

i'm not able to retrieve the data through API and this link above, it shows
gateway timed out.

Best Regards,
Johnny Lee
