### ISSUE TITLE
Dataset request: <Temperature and Rainfall> not coming in since 2020-06-09

### ISSUE THREAD

**Issue by tanthiamhuat** [datagovsg/datagovsg-datasets#769]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Rainfall and Temperature

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
NEA

### If there's an issue with a dataset, please provide a description of the problem
https://api.data.gov.sg/v1/environment/rainfall?date=2020-06-08   gives correct data
https://api.data.gov.sg/v1/environment/air-temperature?date=2020-06-08 gives correct data

https://api.data.gov.sg/v1/environment/rainfall?date=2020-06-09  gives NO data
https://api.data.gov.sg/v1/environment/air-temperature?date=2020-06-09  gives NO data
from 2020-06-09 onwards, there is issue with the API data for both rainfall and temperature.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [X] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Monitoring of Rainfall and Temperature for Update on website for testing purposes.

**Comment by Davianlols6** [comment]
The API for the UV Index also doesn't give any data

**Comment by tanthiamhuat** [comment]
if someone is fixing the API, please refill those past data which is not recorded, thanks.

**Comment by tanthiamhuat** [comment]
can someone put back those temperature and rainfall data for dates 2020-06-09 and 2020-06-10, please?

**Comment by lennardl** [comment]
We have informed NEA of the issue and they are looking at it on their end.
