### ISSUE TITLE
Data request: hawker center data at 2011

### ISSUE THREAD

**Issue by fanfmy** [datagovsg/datagovsg-datasets#77]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I would like to have the dataset of a list of all hawker centers in Singapore with the address of the hawker center and longitude and latitude of the address as of 2011.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
National Environment Agency

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Hawker Center address | latitude | longitude
------|---------|-------------
Blk 16 Bedok South Road|1.320552165|103.9355391

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by iewil** [comment]
@fanfmy the dataset is available [here](https://data.gov.sg/dataset/hawker-centres)

**Comment by fanfmy** [comment]
Sorry, it seems that the link above only has the latest list of hawker centers. However, I am looking for historical data as of 2011. Do you have that? Thank you.
