### ISSUE TITLE
Dataset request: ARCA Business entities with UEN and SSIC Industry Codes

### ISSUE THREAD

**Issue by ethiangdy** [datagovsg/datagovsg-datasets#770]
### Please provide the name of the dataset or describe the dataset that you're requesting:
ACRA Registered Company with:
1) Basic Entity Information (Business name, UEN, Date of incorporation/registration, Status, Entity type, etc.)
2) Registered office address
3) Singapore Standard Industrial Classification (SSIC) (Primary, Secondary, User Prescribed Activity)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
ACRA 

### If there's an issue with a dataset, please provide a description of the problem
The current dataset at https://data.gov.sg/dataset/entities-with-unique-entity-number does not include a column for SSIC codes to indicate industry of business activity.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

Fields Required: uen | entity name | Primary SSIC Code | Secondary SSIC Code
Example: 12345678A | 123 ABC Company | 46099 | 62099

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To complete the "entities-with-unique-entity-number" data set by including the industry type of each entity and thereafter use the dataset to research on the development of singapore's retail industry landscape over time.

**Comment by lennardl** [comment]
@ethiangdy For the ACRA dataset, ACRA is providing the data as is so they will not be adding the SSIC

**Comment by ethiangdy** [comment]
Okay! Thanks for the clarification!
