### ISSUE TITLE
Dataset request: <Observed Daily Relative humidity data from 1980 until now>

### ISSUE THREAD

**Issue by Queensura123** [datagovsg/datagovsg-datasets#772]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Observed Daily Relative humidity data 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

http://www.weather.gov.sg/climate-historical-daily/

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Jan 1988 to Dec 2019

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I would to simulate future climate scenarios for Singapore

**Comment by lennardl** [comment]
We have a few datasets that match your request
https://data.gov.sg/search?q=humidity

**Comment by Queensura123** [comment]
Thank you very much. I checked that before. The frequency of the data is monthly and annually. May I know if you have daily temperature and relative humidity data?

Thank you again.

**Comment by lennardl** [comment]
@Queensura123 You can use this and parse in a date/time to get historical data https://data.gov.sg/dataset/realtime-weather-readings?resource_id=59eb2883-2ceb-4d16-85f0-7e3a3176ef46

**Comment by Queensura123** [comment]
Thank you for your kind reply. I still couldn't access the data using API. This data available from 2016. May I know some example on how to retrieve the data? I am getting error which says the data time string is not correct.

I would like to have the following data in daily resolution instead of monthly resolution from 1982 to 2020.

https://data.gov.sg/dataset/relative-humidity-monthly-mean 

https://data.gov.sg/dataset/surface-air-temperature-mean-daily-minimum?view_id=77e8bc16-c8a0-423a-b359-f031af5bfbc9&resource_id=ad0d8a97-9321-42e9-ac6f-46bf12845d44

https://data.gov.sg/dataset/surface-air-temperature-mean-daily-maximum?view_id=8455af74-1c39-486c-8768-3c0b1c54d3be&resource_id=c7a7d2fd-9d32-4508-92ef-d1019e030a2f

Thank you very much for your patience!

**Comment by lennardl** [comment]
@Queensura123 
You can pass in the date or date/time in the following format
https://api.data.gov.sg/v1/environment/relative-humidity?date=2020-06-16
https://api.data.gov.sg/v1/environment/relative-humidity?date_time=2020-06-16T10:00:00
You will need to encode : %3A

Our data typically does not go that far back. If you need historical data that spans that far back you might need to approach NEA for it
