### ISSUE TITLE
Dataset request: Realtime Weather Readings across Singapore (NEA)

### ISSUE THREAD

**Issue by powlook** [datagovsg/datagovsg-datasets#776]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Rainfall across Singapore

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
NEA

### If there's an issue with a dataset, please provide a description of the problem
I am getting historical data of 2019 rainfall. However I noted that data for some of the dates are missing as the API returns an error. The following are the dates 👍 

2019-04 - 21 to 30
2019-07- 21 to 31
2019-11- 08 to 30

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

datetime | station_id | rainfall_amount

### How frequently would you need this dataset to be updated?
Example: 
- [X] Once (historical)

### Can you give a short explanation on how you're planning to use this dataset?
I am from Ai Singapore working on a project to provide ETA for buses and will need the weather data as part of my training for the model.

**Comment by lennardl** [comment]
@powlook We are aware and have informed NEA on this, we are waiting on them to respond and provide the missing data.

**Comment by powlook** [comment]
Tks!

Looking forward to the missing dataset.
