### ISSUE TITLE
Dataset request: COVID-19 updates

### ISSUE THREAD

**Issue by samueljxlow** [datagovsg/datagovsg-datasets#778]
### Please provide the name of the dataset or describe the dataset that you're requesting:
COVID-19: Updates and announcements

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### If there's an issue with a dataset, please provide a description of the problem
No issues

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Date | Title

(All of the Dates in https://www.gov.sg/article/covid-19-updates-and-announcements)

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [X] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Creating a mobile application to store and read temperature readings as well as have a news feed regarding COVID-19 situations

**Comment by lennardl** [comment]
@samueljxlow For Covid-19 data we are currently directly everyone to the MOH Covid-19 site

**Comment by kaihendry** [comment]
The "MOH Covid-19 site" is unusable as a data source though... https://s.natalian.org/2020-08-21/sg-xls.mp4
