### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by ace108** [datagovsg/datagovsg-datasets#78]
### Please provide the name of the dataset or describe the dataset that you're requesting:
CEA Salesperson Information

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Council For Estate Agencies / 10 Jan 2018

### If there's an issue with a dataset, please provide a description of the problem
There is a duplicate in the display at 
https://data.gov.sg/dataset/cea-salesperson-info
although the downloaded looks OK. 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
No issue with the fields. 

### How frequently would you need this dataset to be updated?
NA

### Can you give a short explanation on how you're planning to use this dataset?
Just exploring.

**Comment by iewil** [comment]
@ace108 closing this issue. Please submit another issue if you have a dataset request.
