### ISSUE TITLE
Dataset request: Historical Electricity Tariff

### ISSUE THREAD

**Issue by tanykiat** [datagovsg/datagovsg-datasets#780]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Electricity Tariffs in Singapore

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Not in the list. It is SP Group
Currently the data is provided here: [](https://www.spgroup.com.sg/what-we-do/billing) 
It is provided as an Excel file: https://www.spgroup.com.sg/wcm/connect/spgrp/e0b9800a-c39b-4f41-8664-2bbe8e2ca826/Historical%2BElectricity%2BTariff_Oct+18%28w+GST%29.xls?MOD=AJPERES 
### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Per the Excel file provided in the link^

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X] Quarterly (that is how SP provides it)
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To obtain latest tariff rates.

**Comment by lennardl** [comment]
@tankevan The data belongs to SP Group which is not a government entity so their data would not be hosted here.
