### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by Rithvik29** [datagovsg/datagovsg-datasets#781]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2019-06|Singapore|1

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [X] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

In a learning project using python.

**Comment by lennardl** [comment]
@Rithvik29 Can you provide more details on the data you are looking for?
