### ISSUE TITLE
Dataset request: <Road Category and Historical Traffic data>

### ISSUE THREAD

**Issue by mathewgankl** [datagovsg/datagovsg-datasets#782]
### Please provide the name of the dataset or describe the dataset that you're requesting:
1. Road names with category (1-5), ideally packaged with segment geometric data.
2. Historical traffic speeds for each road, 85th percentile.
3. Historical average traffic volumes for each road.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
1. URA or LTA
2. LTA
3. LTA

### If there's an issue with a dataset, please provide a description of the problem
Road Section Line on LTA's Datamall does not contain road code information despite its description. Neither does it seem the most up to date as there are discrepancies between it and kerb line and lane marking geometries: https://www.dropbox.com/s/hm0kdcjpaeze3y8/RoadSectionLineDiscrepancy.png?dl=0

There are also no other available datasets that provide information on Singapore roads despite listings on data.gov.sg (cf MP08 Mapsheet Road Name datasets with zips that do not contain any data and no download link for Master Plan 2019 Road Graphic layer and Master Plan 2019 Road Name layer). 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
1. Road Name | Road Category | Geometry
2. Road Name | Traffic Speed, 85th percentile (kph)
3. Road Name | Average Daily Volume

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Calculation of a Bicycle Level of Service score (specifically the Bicycle Compatibility Index) for Singapore's roads, to be presented in a Bachelor's thesis for the fulfilment of degree requirements towards the National University of Singapore Real Estate programme.

**Comment by mathewgankl** [comment]
@lennardl Hi, may I know if this data may be made available? Speeds are not as important, but if I could obtain the traffic counts that would help a lot. Thanks!

**Comment by lennardl** [comment]
@mathewgankl I'll request and see if I can get the Master Plan 2019 Road Graphic layer and Master Plan 2019 Road Name layer updated

**Comment by lennardl** [comment]
@mathewgankl The two layers have been updated.
