### ISSUE TITLE
Dataset request: <Digital Surface Model of Singapore>

### ISSUE THREAD

**Issue by BigusD** [datagovsg/datagovsg-datasets#783]
Digital Surface Model of Singapore
- .tiff/.tif Format. 
- Height (m) values of each pixel in raster.

### Do you know which agency provides/can provide this data?
Singapore Land Authority

### Please provide the fields expected in this dataset:
- .tif metadata should contain CRS.

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Play around with data.

**Comment by lennardl** [comment]
@BigusD We do not have the data, you will need to approach URA for this
