### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by coralsg** [datagovsg/datagovsg-datasets#784]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Ministry of Law; with tags "money lending"

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Law

### If there's an issue with a dataset, please provide a description of the problem
The last update was in 2015, can it be updated to 2019?

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

1) use existing field data dictionary, but updated to 2019
2) breakdown into loan type (secured, unsecured)

Year | Amount of loans (S$ in millions) | loan type

### How frequently would you need this dataset to be updated?
Example: 

- [ ] Annually
- [x] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For market research, and for fine tuning my company strategy.  My business in in licensed money lending.

**Comment by lennardl** [comment]
@coralsg We have approached the Ministry of Law to see if the data can be updated and provide more breakdown.

**Comment by lennardl** [comment]
We are not able to get the data
