### ISSUE TITLE
Dataset request: <Annual Age Distribution of Cars on Transfer of Ownership>

### ISSUE THREAD

**Issue by danielyaps** [datagovsg/datagovsg-datasets#786]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Annual Age Distribution of Cars on Transfer of Ownership

### Do you know which agency provides/can provide this data?
Land Transport Authority

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Transfer Count | Age | Number of Cars
------|---------|-------------
1 | 5 years |10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by danielyaps** [comment]
Would like to understand how often Singaporean change their vehicle to study purchase patterns of Singaporean for both new and used vehicle cycles. Many studies have been done on new vehicle but used vehicles seem to be lacking in research. Would like to better understand the pre-owned vehicle economy.

**Comment by lennardl** [comment]
@danielyaps I have reached out to LTA to see if they can make the data available and update the data on the ownership transfer

**Comment by danielyaps** [comment]
Thanks! Appreciate it! :)

**Comment by lennardl** [comment]
We are not able to obtain the data
