### ISSUE TITLE
Dataset request: Train Disruption

### ISSUE THREAD

**Issue by TeckLoong** [datagovsg/datagovsg-datasets#787]
### Please provide the name of the dataset or describe the dataset that you're requesting:
May I have access to the data set for the minor frequent disruptions in public transport?

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
LTA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Day, Month, Year, Time when it occurred, Station Name, Frequency of the Train Arrival, Estimated Train Arrival and Duration of Disruption 

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [x] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by TeckLoong** [comment]
I am going to use this data set to find out the proportion in the percentage increase or decrease of the disruption by comparing before, during and after the peak hours. In return, using this data analysis to further enhance Singapore’s title of “World-class transportation”, as we discover from the public responses in the train and bus disruptions.

**Comment by lennardl** [comment]
@TeckLoong We have approached LTA for the data. Waiting on a response.

**Comment by TeckLoong** [comment]
Thank you so much!

**Comment by TeckLoong** [comment]
Hi sir or madam, is there still not a reply yet for the data sources requested? Thanks and have a nice day (:

**Comment by lennardl** [comment]
@TeckLoong Sorry, we have not heard back from LTA.

**Comment by TeckLoong** [comment]
Oh thanks!

**Comment by lennardl** [comment]
LTA will not be providing the data
