### ISSUE TITLE
Dataset request: management-corporation-strata-title

### ISSUE THREAD

**Issue by Aswathimohan-lefong** [datagovsg/datagovsg-datasets#788]
### Please provide the name of the dataset or describe the dataset that you're requesting:
management-corporation-strata-title

### Do you know which agency provides/can provide this data?
Not sure
### If there's an issue with a dataset, please provide a description of the problem
we are looking for email ids of the organisations and it is missing from the datasheet downloaded (management-corporation-strata-title).

### Please provide the fields expected in this dataset:
usr_devtname | devt_location | managementname | management_tel_no | emailid

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
to collect the email ids for promotion

**Comment by lennardl** [comment]
@Aswathimohan-lefong Emails are not provided by the data owner (BCA)
