### ISSUE TITLE
Dataset request: Space Out

### ISSUE THREAD

**Issue by choikwunyu** [datagovsg/datagovsg-datasets#789]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Space Out

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Urban Redevelopment Authority
### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Date | Hour | Location | Occupancy
------|---------|---------|------
28-06-2020|05|Vivocity|10000

### How frequently would you need this dataset to be updated?
- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [X] Hourly
- [X] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am representing SPOT Parking, a startup which is bringing variable pricing prices to commercial locations to help boost occupancy/revenue. Given the current circumstances, we want to use to show consumers the real-time Space Out occupancy data together with parking prices on our app to help consumers make an informed decision on which mall to go to.

**Comment by lennardl** [comment]
@choikwunyu I have approached URA asking if the data can be shared

**Comment by choikwunyu** [comment]
@lennardl is there any update on this? Thanks!

**Comment by lennardl** [comment]
@choikwunyu The data owners did not respond. For now, data on spaceout will need to be taken from their site.
