### ISSUE TITLE
Dataset request: <Pollutant Standards Index>

### ISSUE THREAD

**Issue by app3ko3** [datagovsg/datagovsg-datasets#790]
### Please provide the name of the dataset or describe the dataset that you're requesting:
5 years historical PSI at North, South, East and West Region of Singapore

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
National Environment Agency

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|PSI

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ X] Daily
- [ X] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To do projection on indoor and outdoor quality based on equipment installed indoor.

**Comment by lennardl** [comment]
You can use this API to retrieve the historical data. Our data does not go all the way back 5 years. 
https://data.gov.sg/dataset/psi?view_id=496c77eb-6add-4e9b-9883-17864cedfe9f&resource_id=82776919-0de1-4faf-bd9e-9c997f9a729d
