### ISSUE TITLE
Dataset issue: Blank API response for 2 hour weather forecast API

### ISSUE THREAD

**Issue by Davianlols6** [datagovsg/datagovsg-datasets#792]
### Please provide the name of the dataset or describe the dataset that you're requesting:
2 hour weather forecast API

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
nil

### If there's an issue with a dataset, please provide a description of the problem
The API is blank
`{"items":[{}],"area_metadata":[],"api_info":{"status":"healthy"}}`

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@Davianlols6 We are aware that the 2 Hr forecast has issues can you use the 4 or 24hr forecast for the moment? We are trying to resolve the issue with NEA.
