### ISSUE TITLE
lightning

### ISSUE THREAD

**Issue by simplicity94** [datagovsg/datagovsg-datasets#793]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@simplicity94 Can I confirm the data you are looking for?

**Comment by simplicity94** [comment]
Hi lennardl,

Is there any API for lightning alert? 

Thanks & Regards
Jin Ren

**Comment by lennardl** [comment]
@simplicity94 We do not have the data on lightning alerts. However, you should be able to access it on NEA here http://www.weather.gov.sg/lightning/lightning/lightningalertinformationsystem.jsp
