### ISSUE TITLE
Data Request: Rainfall radar area image

### ISSUE THREAD

**Issue by KhwaNyo** [datagovsg/datagovsg-datasets#797]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Rainfall radar area image.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
https://www.nea.gov.sg/weather/rain-areas
http://www.weather.gov.sg/weather-rain-area-50km

### If there's an issue with a dataset, please provide a description of the problem
is there any API to download rainfall radar realtime image?

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

DateTime| Rainfall radar image
------|---------|-------------
7.45 am Wed 8 Jul|image file

### How frequently would you need this dataset to be updated?
Example: 
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

**Comment by lennardl** [comment]
@KhwaNyo We do not have that data on Data.gov.sg you will need to refer back to NEA's site for that data.

**Comment by KhwaNyo** [comment]
@lennardl , thank you for your prompt reply. noted with thanks.
