### ISSUE TITLE
Dataset request: Government Procurement

### ISSUE THREAD

**Issue by dennisgoh82** [datagovsg/datagovsg-datasets#798]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Government Procurement

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

Managed By | Ministry of Finance
Last updated: March 28, 2019, 09:27 (SGT)

### If there's an issue with a dataset, please provide a description of the problem
This is an existing dataset and is described to be updated on a monthly basis on the data.gov.sg website.

However, it seems like the last updated date is in march 2019 and the data seems to only stretch till Dec 2018.

is this dataset no longer maintained or is there a newer dataset that supersedes this one?

**Comment by lennardl** [comment]
@dennisgoh82 We approached MOF they update it twice a year
