### ISSUE TITLE
Dataset request: <Electoral Boundary 2020>

### ISSUE THREAD

**Issue by adikoldskool** [datagovsg/datagovsg-datasets#799]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Electoral boundary 2020 consist of the updated 2020 postal code and the constituency

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

www.eld.gov.sg
www.sla.gov.sg
www.pa.gov.sg

### If there's an issue with a dataset, please provide a description of the problem
NA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Address | Postal Code | Constituency
------|---------|-------------
503 Tampines Central 1 | 520503 | Tampines GRC

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ✔️] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

To populate the statistic working for my organisation and is for internal usage within own branch and not to disseminate to external parties.

**Comment by lennardl** [comment]
@adikoldskool The electoral boundary 2020 can be found here https://data.gov.sg/dataset/electoral-boundary_2020
Postal code is not available as the data belongs to Singapore Post

**Comment by lennardl** [comment]
We only have the boundary https://data.gov.sg/dataset/electoral-boundary_2020
We do not have postal code data
