### ISSUE TITLE
2017-09|Singapore|10000

### ISSUE THREAD

**Issue by eric7yang** [datagovsg/datagovsg-datasets#80]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by iewil** [comment]
@eric7yang closing this request due to incomplete submission. Please submit another issue if you have a dataset request.
