### ISSUE TITLE
Data Request: HDB Rental Rates

### ISSUE THREAD

**Issue by superlu19601** [datagovsg/datagovsg-datasets#800]
### Please provide the name of the dataset or describe the dataset that you're requesting:
HDB rental rates

### Do you know which agency provides/can provide this data?
HDB

### How frequently would you need this dataset to be updated?

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Currently there is only dataset on median rent by town. To give the home seekers more transparency to market, would HDB consider to provide the detailed rent transactions just like the disclosed HDB resale prices?

**Comment by lennardl** [comment]
@superlu19601 We will approach HDB with the request.

**Comment by superlu19601** [comment]
Thank you very much!

**Comment by lennardl** [comment]
@superlu19601 HDB has responded that the data can be found here: https://services2.hdb.gov.sg/webapp/BR12AWRentalEnq/BR12PSearch.jsp they are still going through the internal process of whether it can be made available on Data.gov.sg. In the meantime, I would advise getting the data from there for now.

**Comment by superlu19601** [comment]
@lennardl Thank you for the help. It would be great if they can make it available on data.gov.sg because the page mentioned only allows limited query on a few blocks each time and up to one year, which makes analysis difficult.

**Comment by lennardl** [comment]
@superlu19601 Understood, if they respond and are willing to put the data.gov.sg I will reply this thread to let you know.

**Comment by lennardl** [comment]
Closing as they are directing the general population to the URL
