### ISSUE TITLE
Dataset request: Government Procurement via GeBiz

### ISSUE THREAD

**Issue by azharafn** [datagovsg/datagovsg-datasets#806]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Government Procurement via GeBiz from 2015 - 2019

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

GeBiz, BCA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Tender No. | Tender Description | Awarding Agency | Workhead/s and Grade required | Date Awarded | Respondents | Respondent Bids (S$) | Awarded Respondent

### How frequently would you need this dataset to be updated?
Example: 

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

To understand growth in certain types of government projects and the winning suppliers

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/government-procurement

**Comment by azharafn** [comment]
Hi is it possible to get further information on those contracts? (e.g. workheads and grades required, respondents, etc)

**Comment by lennardl** [comment]
@azharafn No, as this is what MOF releases to us.
