### ISSUE TITLE
Dataset request: Government Procurement via GeBIZ

### ISSUE THREAD

**Issue by alvinpang** [datagovsg/datagovsg-datasets#807]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )* MOF

### If there's an issue with a dataset, please provide a description of the problem
Dataset is not updated with 2019 data.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
We have approached MOF to update the data but they have not responsed
