### ISSUE TITLE
Dataset request: <dataset title>Singapore Residents By Age Group, Ethnic Group And Gender, End June, Annual

### ISSUE THREAD

**Issue by VisualizeKD** [datagovsg/datagovsg-datasets#808]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@VisualizeKD https://data.gov.sg/dataset/resident-population-by-ethnicity-gender-and-age-group?resource_id=d5d35678-cd15-4f43-b347-d671d1870655 please download the data to get the data up to 2019
