### ISSUE TITLE
Dataset request: Water prices and water sales, annual

### ISSUE THREAD

**Issue by darkytoothpaste** [datagovsg/datagovsg-datasets#809]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Water prices and water sales data for 2019

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
MEWR

### If there's an issue with a dataset, please provide a description of the problem
The current dataset runs from 2009 to 2018. However, as of 17 Jul 20 (today), the data is only up to 2018.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

Water   Prices, Annual **
--
Potable Water   Price For Domestic Users, 0-40 Cubic Metres (Dollar Per Cubic Metre)
Tariff (Dollar   Per Cubic Metre)
Water   Conservation Tax (Dollar)
Waterborne Fee   * (Dollar)
Sanitary   Appliance Fee * (Dollar Per Fitting)
Potable Water   Price For Domestic Users, > 40 Cubic Metres (Dollar Per Cubic Metre)
Tariff (Dollar   Per Cubic Metre)
Water   Conservation Tax (Dollar)
Waterborne Fee   * (Dollar)
Sanitary   Appliance Fee * (Dollar Per Fitting)
Potable Water   Price For Non-domestic Users (Dollar Per Cubic Metre)
Tariff (Dollar   Per Cubic Metre)
Water   Conservation Tax (Dollar)
Waterborne Fee   * (Dollar)
Sanitary   Appliance Fee * (Dollar Per Fitting)
Potable Water   Price For Shipping Customers (Dollar Per Cubic Metre)
Tariff (Dollar   Per Cubic Metre)
Water   Conservation Tax (Dollar)
Waterborne Fee   (Dollar)
Newater Price   (Dollar Per Cubic Metre)
Tariff (Dollar   Per Cubic Metre)
Water   Conservation Tax * (Dollar)
Waterborne Fee   (Dollar)
Industrial   Water Price (Dollar Per Cubic Metre)
Tariff (Dollar   Per Cubic Metre)
Waterborne Fee   (Dollar)
Water Sales, Annual **
Sales Of   Potable Water (Million Cubic Metres Per Year)
Domestic   (Million Cubic Metres Per Year)
Non-domestic   (Million Cubic Metres Per Year)
Sales Of   Newater (Million Cubic Metres Per Year)
Sales Of   Industrial Water (Million Cubic Metres Per Year)

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

Study on price elasticity for water and consumer behavior towards water tariffs

**Comment by lennardl** [comment]
@darkytoothpaste I've approached the relevant agency to ask if the data can be made available on the platform.

**Comment by darkytoothpaste** [comment]
Thank you very much for your help.

**Comment by lennardl** [comment]
@darkytoothpaste Data will be limited to those found on the site https://data.gov.sg/dataset/sale-of-potable-water
