### ISSUE TITLE
Dataset request: List of Singapore gyms

### ISSUE THREAD

**Issue by JemimaKoh** [datagovsg/datagovsg-datasets#81]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Public and private gyms in Singapore

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
No

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Name of gym | Address of gym 

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [x] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I want to see the list of gyms available in Singapore, both public and private because I realised the one in this website (Gyms@SG) is not updated, with a lot of gyms missing. I want to use it to analyse if locations of gyms will affect one's health status.

**Comment by iewil** [comment]
@JemimaKoh Data.gov.sg is the online repository for government open data, so private data will not be provided in the site. We've reached out to our colleagues at SportSG for help with the listings of public gyms, and we'll post updates here when we hear back from them. Thanks.
