### ISSUE TITLE
Dataset request: <price of construction materials>

### ISSUE THREAD

**Issue by deankong** [datagovsg/datagovsg-datasets#811]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [x] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by deankong** [comment]
i am analysing the risk of project delay and cost overrun due to material shortage and cost increase.

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/construction-material-market-prices-monthly
