### ISSUE TITLE
Dataset request: <Gebiz>

### ISSUE THREAD

**Issue by nicholas-cyber** [datagovsg/datagovsg-datasets#813]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Gebiz Awarded contracts and pe

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

Awarded: tender info | tender description| agency|award date|tender detail status|supplier name|awarded amount
Awarded: tender info | tender description| agency|respondent 1|respondent 2|respondent 3|respondent 4|respondent 5 (so on so for)

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [X] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
This is to have an overview of Gebiz platform

**Comment by nicholas-cyber** [comment]
please, someone help a dying soul here

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/government-procurement 
MOF updates this twice a year. The next update is due.
