### ISSUE TITLE
PSI API

### ISSUE THREAD

**Issue by jiongkass** [datagovsg/datagovsg-datasets#816]
### Please provide the name of the dataset or describe the dataset that you're requesting:
PSI API (with all pollutants sub-index readings)

### Do you know which agency provides/can provide this data?
National Environment Agency (NEA)

### If there's an issue with a dataset, please provide a description of the problem
Historical reading provided in the website are from 2016-02-07 onward. Would like to request historical readings from 2005-04-01, if possible. 

Also, would it be feasible to add in extra parameter for date range for example, 'from=2016-02-07&to=2020-07-23' to load all data from PSI API (https://data.gov.sg/dataset/psi) instead of choosing only one date at a time?

### Please provide the fields expected in this dataset:
Date Range | Country 
2005-04-01 to 2016-02-06 | Singapore

### How frequently would you need this dataset to be updated?
- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [X] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
- Prediction modelling of all pollutants with meteorological data
- Visualizing the change of dispersion pollutants based on available data (hourly, daily, monthly, yearly)

**Comment by lennardl** [comment]
The sub-index pollutants are available here: https://data.gov.sg/search?q=Air+Pollutant I've sent in a request to NEA to update the data.

We are currently not upgrading the platform hence the request for a date range is not possible.
