### ISSUE TITLE
Dataset request: <Number of 2 dimensional real time transoesophageal ultrasound (TTE or echocardiogram) of heart performed>

### ISSUE THREAD

**Issue by BoraBarbora** [datagovsg/datagovsg-datasets#819]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

------|---------|-------------
2017 | Singapore |

### How frequently would you need this dataset to be updated?
Example: 

- [ ] Annually

### Can you give a short explanation on how you're planning to use this dataset?

I need to know the scope of TTE performed in Singapore as I am trying to analyse how how much of additional value could be created by integrating an AI to this procedure. 

I am attaching a perfect dataset of Australia, something like this could be very useful.
[Procedures_data_cube_2017-18.xlsx](https://github.com/datagovsg/datagovsg-datasets/files/4972540/Procedures_data_cube_2017-18.xlsx)

**Comment by lennardl** [comment]
@BoraBarbora I've approached the Ministry of Health to see if the data can be made available.

**Comment by lennardl** [comment]
The data is not available
