### ISSUE TITLE
Dataset request: <dengue fever>

### ISSUE THREAD

**Issue by Guru-Purushothaman** [datagovsg/datagovsg-datasets#820]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Hi Officer,

Good Morning!

My name is Muthuvaithiligam Gopalakrishnan Purushothaman.

**I am a CET student of SUSS, pursuing SAS programming language and CET Student of Republic Polytechnic, pursuing Specialist diploma in Business Analytics.**

For my education, purpose, I am practicing data analytics, predictive analytics, data visualization, with a current important topic like COVID -19.

I am interested in creating data-driven analytical with dengue cases.

I tried to explore data regarding dengue cases, but I couldn't able to find the historical and updated data related to the dengue case in region wise.

Though the region-wise dengue data are available in KPM file, which I'm not familiar with this, 

May I request you to provide dengue-related data. In CSV format, if possible.. For my educational purpose.

**Dengue Mosquito Breeding Habitats
Dengue Clusters
Dengue Cases ( Central, Northeast, Southeast, and Southwest.**

**Below is my linked profile, for your reference to view my past data-driven predictive and visual analytics related to Covid-19 and Singapore general election.**

**https://www.linkedin.com/in/purushoth-aman-20039276/**
Thank you, 

Best regards, 
Purushoth
96137459
purushoth_dominos@hotmail.com

### Do you know which agency provides/can provide this data?
*( NEA: https://data.gov.sg/organization )*

### If there's an issue with a dataset, please describe the problem
The file is in KML format

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X] Monthly
- [X] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@Guru-Purushothaman We do not have the data in CSV format and its not provided to us in raw numbers by NEA.
Apart you might want to remove your NRIC from this Git Issue.

**Comment by Guru-Purushothaman** [comment]
ok. Thank you for the update.
