### ISSUE TITLE
Dataset request: Changes to Electronic Road Pricing rates

### ISSUE THREAD

**Issue by elltph** [datagovsg/datagovsg-datasets#823]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Changes to Electronic Road Pricing rates.

Currently, changes can only be cobbled together from news releases: https://www.lta.gov.sg/content/ltagov/en/newsroom.html?keyword=ERP%20rates#year-filter:path=default|mth-filter:path=default|road-filter:value=ERP%20rates|paging:currentPage=0|paging:number=7

### Do you know which agency provides/can provide this data?

Land Transport Authority

### If there's an issue with a dataset, please provide a description of the problem

No dataset exists for this information.

### Please provide the fields expected in this dataset:

announcement date (2018-05-23)
effective date of new rate (2018-05-26)
location of ERP gantry (AYE – After North Buona Vista Road towards Tuas
start time of new rate (07:00)
end time of new rate (07:30)
new rate (1)
amount of change (-1)

### How frequently would you need this dataset to be updated?
- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

I work for a company which employs drivers. Our drivers manually enter their ERP expenses into our database. I want to validate these expenses against official ERP rates.

**Comment by lennardl** [comment]
@elltph I've asked LTA to see if the data can be made available

**Comment by lennardl** [comment]
The data is not available from LTA
