### ISSUE TITLE
Dataset request: <Government Procurement>

### ISSUE THREAD

**Issue by brohs** [datagovsg/datagovsg-datasets#825]
### Do you know which agency provides/can provide this data? **MOF**
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
**tender_no.	tender_description	agency	award_date	tender_detail_status	supplier_name	 awarded_amt** 

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

**Understand Government procurement behaviours**

**Comment by lennardl** [comment]
@brohs the data is available here https://data.gov.sg/dataset/government-procurement but pending an update from MOF
