### ISSUE TITLE
Dataset request: Number of Polytechnic students sucessfully admitted into local university (Singapore)

### ISSUE THREAD

**Issue by hhylalala** [datagovsg/datagovsg-datasets#827]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Name:  Number of Polytechnic students sucessfully admitted into local university (Singapore)
Description: The dataset is about the number of polytechnic's graduates from different polytechnics that has successfully admitted into different local university for the past 10 years (Singapore).

### Do you know which agency provides/can provide this data?
https://data.gov.sg/organization/ministry-of-education

### Please provide the fields expected in this dataset: ( Polytechnics | No. of Polytechnic Graduates | University | Year )
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------

2017-09|Singapore|10000

Polytechnic | No. of Polytechnic Graduates | University | Year
-----------|--------------------------------|----------|----
Ngee Ann Polytechnic (Np)| 500 | National University of Singapore | 2019
Ngee Ann Polytechnic (Np)| 300 | Nanyang Technological University | 2019

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am planning to use this dataset for my assignment. I am going to show the increases of polytechnic graduates in terms of percentage the have been successfully admitted in different local university in Singapore throughout the past 5 or 10 years.

**Comment by lennardl** [comment]
We do not have specifics on polytechnic to University only the overall enrolment numbers
https://data.gov.sg/dataset/universities-intake-enrolment-and-graduates-by-course
