### ISSUE TITLE
Dataset request: Singapore Residents by Planning Area and Type of Dwelling, Jun 2018

### ISSUE THREAD

**Issue by leongchanhoong** [datagovsg/datagovsg-datasets#828]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Singapore Residents by Planning Area and Type of Dwelling, Jun 2018

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

MTI

### If there's an issue with a dataset, please provide a description of the problem

NA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

Population of Singapore Residents by Planning Area and Type of Dwelling, Jun 2018

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

To study usage of public amenities and experience by residential area, and housing type

**Comment by lennardl** [comment]
@leongchanhoong Can you retrieve the data from here first https://www.singstat.gov.sg/find-data/search-by-theme/population/geographic-distribution/latest-data while we try to resolve the missing data.
