### ISSUE TITLE
Dataset request: Diesel oil consumption in Singapore

### ISSUE THREAD

**Issue by geraldlowc** [datagovsg/datagovsg-datasets#829]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Diesel oil consumption in Singapore

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
EMA, ESG, CAAS, MPA, NEA, DOS

### If there's an issue with a dataset, please provide a description of the problem
no issue. new dataset request.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | volume
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For the planning of setting up green diesel oil production in Singapore

**Comment by lennardl** [comment]
@geraldlowc Does this work https://data.gov.sg/dataset/annual-motor-vehicle-population-by-type-of-fuel-used

**Comment by lennardl** [comment]
We do not have fuel type consumption by other means

**Comment by geraldlowc** [comment]
Thanks very much! These figures are very helpful! I noticed that its updated to 2018, and if there are new figures 2019, please help update too.
