### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by jonathanlpw87** [datagovsg/datagovsg-datasets#830]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Master Plan 2019 Symbol Text layer.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Urban Redevelopment Authority.

### If there's an issue with a dataset, please provide a description of the problem
No issue, but would like to download a copy of this file.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Location (long/ lat/ polygon area?) | Gross Plot Ratio|

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Would like to analyze Gross Plot Ratios statistically and visual map is not adequate.

**Comment by lennardl** [comment]
The data is updated here https://data.gov.sg/dataset/master-plan-2019-symbol-text-layer
