### ISSUE TITLE
Dataset request: Public Health Preparedness Clinics (PHPCs)

### ISSUE THREAD

**Issue by GermaVinsmoke** [datagovsg/datagovsg-datasets#831]
### Do you know which agency provides/can provide this data?

[Flu Go Where](https://www.flugowhere.gov.sg/)
[Govtech Singapore](https://www.tech.gov.sg/)
[Ministry of Health Singapore](https://www.moh.gov.sg/)
[Public Health Preparedness Clinic](https://www.primarycarepages.sg/practice-management/moh-national-schemes/public-health-preparedness-clinic-(phpc))

### Please provide the fields expected in this dataset:

```
{
  "HCICode": "19M0105",
  "clinicName": "1 MEDICAL TECK GHEE",
  "type": "GP",
  "openingHours": "Eve of Chinese New Year (24/01/2020) : 07:00 am to 01:00 pmChinese New Year (25/01/2020) : 07:00 am to 
  01:00 pmChinese New Year (26/01/2020) : 07:00 am to 01:00 pmChinese New Year (27/01/2020) : 07:00 am to 01:00 pm, 06:00 
  pm to 12:00 am",
  "address": "410 Ang Mo Kio Avenue 10, #01-837, Teck Ghee Square, S560410",
  "postalCode": "560410",
  "clinicTelephoneNo": "62517030",
  "lat": 1.36271542,
  "long": 103.854645,
  "oneMapLink": "https://www.onemap.sg/main/v2/?lat=1.36271542&lng=103.854644999999"
}
```

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

For creating a dashboard having better UI/UX for Clinics which provides swabbing, the time during which swabbing is available

**Comment by lennardl** [comment]
@GermaVinsmoke I've approached MOH to ask if they can make the data available on Data.gov.sg

**Comment by GermaVinsmoke** [comment]
Thanks @lennardl

**Comment by lennardl** [comment]
The data will be limited to the individual MOH sites.
