### ISSUE TITLE
Dataset request: <Singapore Coastal Habitats Map from High Resolution Satellite Imagery (2010/2011)>

### ISSUE THREAD

**Issue by Shuhwee24** [datagovsg/datagovsg-datasets#834]
Singapore Coastal Habitats Map from High Resolution Satellite Imagery (2010/2011)

Nparks

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

2010/2011 | Singapore | nil
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To study the coastal habitats of Singapore for a thesis at NUS.
![3-s2 0-B9780081008539000312-f24-03-9780081008539](https://user-images.githubusercontent.com/69471725/89801329-97e70880-db62-11ea-938b-d98a8f8f679c.jpg)

**Comment by lennardl** [comment]
We do not have this. You might need to approach URA for this
