### ISSUE TITLE
Dataset request: Singapore Traffic Accidents with Location Tagged

### ISSUE THREAD

**Issue by lionel-koh** [datagovsg/datagovsg-datasets#836]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Road accident data which includes:
1. Date of Accident
2. Road user group
3. Cause of accident
4. Location of accident

It would be desirable to have the data recorded in a per accident basis

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

Land Transport Authority

### If there's an issue with a dataset, please provide a description of the problem

https://data.gov.sg/dataset/causes-of-road-accidents-causes-of-accidents-by-severity-of-injury-sustained

The available one groups the accidents and does not have location data tagged to each accident

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Date | Road User Group | Cause of Accident | Location of Accident
------|---------|-------------
01-02-2015|Car|Lost control due to speeding|1.366092, 103.779642

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [ ] Annually
- [x] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

I'm a student working on a project on data visualisation on Geospatial Systems. I would like to have a plot of traffic accident localities. From there, hope to draw some insights such as 1) see if there are roads which may possibly have design flaws e.g. sharp bends, blind spots etc., 2) predict future accidents given the traffic density of a given time

**Comment by lennardl** [comment]
@lionel-koh SPF does not provide the exact location of the accidents and data is only given on the aggregated level in the dataset you found on our site.
