### ISSUE TITLE
Dataset request: <Violence: Applications Of Personal Protection Order (PPO)/Expedited Order (EO)/Domestic Exclusion Order (DEO)>

### ISSUE THREAD

**Issue by cyh002** [datagovsg/datagovsg-datasets#838]
### Please provide the name of the dataset or describe the dataset that you're requesting:

https://www.msf.gov.sg/research-and-data/Research-and-Statistics/Pages/Violence-Applications-of-Personal-Protection-Order-(PPO)Expedited-Order-(EO)Domestic-Exclusion-Order-(DEO).aspx

Violence: Applications Of Personal Protection Order (PPO)/Expedited Order (EO)/Domestic Exclusion Order (DEO)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

https://www.msf.gov.sg/research-and-data/Research-and-Statistics/Pages/Violence-Applications-of-Personal-Protection-Order-(PPO)Expedited-Order-(EO)Domestic-Exclusion-Order-(DEO).aspx

I wish to have access to the dataset used above ^.

### If there's an issue with a dataset, please provide a description of the problem
NIL

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Year|Month| | Number of Personal Protection Orders cases | Number of Domestic Violence cases reported
------|---------|-------------
2020|1|50|100

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [ ] Annually
- [ ] Monthly
- [x] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
The Dataset will be used to study the social effects of COVID19 and in general unemployment rates in relation to domestic violence cases for the Singapore Institute of Management SIM Economics Society Newsletter.

**Comment by lennardl** [comment]
The PPO numbers are here https://data.gov.sg/dataset/number-and-proportion-of-ppo-applications-filed-by-gender?resource_id=2ddefb03-17f6-41cb-aec2-b69e18106257

I'm asking MSF if there is a difference for the EO and DEO numbers
