### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by tommyruen** [datagovsg/datagovsg-datasets#839]
### Please provide the name of the dataset or describe the dataset that you're requesting: 
Air Passenger Arrival - Total by Region and Selected Country of Embarkation

### Do you know which agency provides/can provide this data?
Civil Aviation Authority of Singapore

### If there's an issue with a dataset, please provide a description of the problem
-NIL-

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2019-09 to 2020-06|Singapore|10000

### How frequently would you need this dataset to be updated?

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Using it for University assignment

**Comment by lennardl** [comment]
We do not have the data
