### ISSUE TITLE
ACRA - dissolution date 

### ISSUE THREAD

**Issue by skenaja** [datagovsg/datagovsg-datasets#84]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Addition of new fields to https://data.gov.sg/dataset/acra-information-on-corporate-entities

### Do you know which agency provides/can provide this data?

* ACRA

### If there's an issue with a dataset, please provide a description of the problem

* Dataset also requires updating - last update date = November 2, 2017, file is meant to be refreshed monthly

### Please provide the fields expected in this dataset:

Please provide some additional information to this existing dataset:

* dissolution date
* expiry date
* striking off date

### How frequently would you need this dataset to be updated?
 
- [ ] Annually
- [x] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by skenaja** [comment]
@lennardl - This ticket was closed without further comment - was any response received from ACRA?

**Comment by lennardl** [comment]
We were closing up past tickets that were marked as data no available. Will reopen this and have approached ACRA. Will update this ticket again.
