### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by tommyruen** [datagovsg/datagovsg-datasets#840]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Air Passenger Departures - Total by Region and Selected Country of Disembarkation

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Civil Aviation Authority of Singapore

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2020-03 to 2020- 06|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Using for University assignment

**Comment by lennardl** [comment]
We do not have the data
