### ISSUE TITLE
Dataset request: <Daily PSI and the six key air pollutants dataset>

### ISSUE THREAD

**Issue by James-Soh** [datagovsg/datagovsg-datasets#843]
### Please provide the name of the dataset or describe the dataset that you're requesting:
PSI and the six key air pollutants

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
NEA

### If there's an issue with a dataset, please provide a description of the problem
Available dataset on air pollutant are on a yearly basis.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

year-month-day | PSI | O3 | SO2 | NO3 | CO | PM2.5 | PM10 
---------------|-----|----|-----|-----|----|-------|------|
YYYY-MM-DD|x|x|x|x|x|x|x|

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

The data will be used for a data visualisation project to visualise the emission for the first 6 months of each year.
The aim is visually see if COVID-19 has a statistical impact on the reduction of greenhouse gas emission in 2020 compared to the previous years.

**Comment by lennardl** [comment]
We do not have the daily data on the pollutants just the PSI: 
https://data.gov.sg/dataset/historical-24-hr-psi
https://data.gov.sg/search?q=air+pollutant
