### ISSUE TITLE
Dataset request: No of EP holders in SG

### ISSUE THREAD

**Issue by waynefan369** [datagovsg/datagovsg-datasets#845]
### Please provide the name of the dataset or describe the dataset that you're requesting:

I would like to request for data on the  No. of employment pass holders since 2000.
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of manpower

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

Year | EP holders

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

I am doing a study on the number of foreign workers in Singapore

**Comment by lennardl** [comment]
We only have topline numbers https://data.gov.sg/dataset/foreign-workforce-numbers-annual
