### ISSUE TITLE
Dataset request: total number of deaths from any cause YTD 2020

### ISSUE THREAD

**Issue by dotnetspec** [datagovsg/datagovsg-datasets#846]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Singapore : total number of deaths from any cause YTD 2020

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
No

### Please provide the fields expected in this dataset:
e.g.:
month | country | number of deaths from any cause
------|---------|-------------
2017-09|Singapore|1000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Personal insight, perspective and understanding

**Comment by lennardl** [comment]
@dotnetspec We have a few related to your request https://data.gov.sg/search?q=cause+of+death

**Comment by dotnetspec** [comment]
Sorted by 'Last Modified' the most recent datasets relating to death figures start with 'Death by cause and age group and gender
Ministry of Home Affairs - Immigration & Checkpoints Authority / 03 Sep 2019'
i.e. almost a year old.
Do you have a more recent dataset i.e. YTD (up to Aug 2020) for death rates from all causes?

**Comment by lennardl** [comment]
@dotnetspec I've approached MHA to ask if the dataset can be updated

**Comment by dotnetspec** [comment]
Hi,
Can you please give me a confirmation on whether this can be
achieved within the next week?
Thanks,
Regards,
Philip

**Comment by lennardl** [comment]
@dotnetspec The death numbers are only updated till 2019 the numbers for 2020 are published annually and will not be updated until next year
