### ISSUE TITLE
Dataset request: Public Places Visited by Cases in Community during Infectious Period

### ISSUE THREAD

**Issue by tws4793** [datagovsg/datagovsg-datasets#848]
### Please provide the name of the dataset or describe the dataset that you're requesting:
MOH currently publishes an **Annex C3 - Public Places Visited by Cases in Community during Infectious Period** as part of their daily circulars on Covid-19 updates. However, it is currently only available in PDF form and therefore we will need to write code to extract such information from the PDFs. Would appreciate if such a dataset in csv or through an API is made available, which ideally should date back to when MOH started releasing this annex from 24 May 2020.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
MOH

### If there's an issue with a dataset, please provide a description of the problem
None

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

**Note**
- Both formats presented below are acceptable, depends on what is feasible
- *lat/lon* are optional if not feasible, we can use other APIs such as that of OneMap search address API to obtain the lat/lon from the address.
- Ideally the dataset should be compiled from when MOH started releasing annex C3, which was from 24 May 2020.

#### `CSV` format
date | time_start | time_end | location | sub_location | address | lat | lon
-|-|-|-|-|-|-|-
16/08/2020 | 1200 | 1300 | Block 4A Jalan Batu Hawker Centre | | 4A Jalan Batu | 103.85 | 1.29
16/08/2020 | 1700 | 1800 | Trivex | Zero1 Pte Ltd | 8 Burn Road | 103.85 | 1.29
19/08/2020 | 0745 | 0905 | Elias Mall | 623 F&B Pte Ltd | 623 Elias Road | 103.85 | 1.29
19/08/2020 | 0745 | 0905 | Elias Mall | Sheng Siong Supermarket | 623 Elias Road | 103.85 | 1.29

#### `JSON` format
```json
[
    {
        "date": "16/08/2020",
        "time_start": "1200",
        "time_end": "1300",
        "location": "Block 4A Jalan Batu Hawker Centre",
        "sub_location": [],
        "address": "4A Jalan Batu",
        "lat": 103.85,
        "lon": 1.29
    },
    {
        "date": "19/08/2020",
        "time_start": "0745",
        "time_end": "0905",
        "location": "Elias Mall",
        "sub_location": [
            "623 F&B Pte Ltd",
            "Sheng Siong Supermarket"
        ],
        "address": "623 Elias Road",
        "lat": 103.85,
        "lon": 1.29
    }
]
```

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [X] Real-time

**Real-time** means update the list at the same time as when the evening press release by MOH is made available

### Can you give a short explanation on how you're planning to use this dataset?
- Quickly identify new places added to list instead of having to manually eyeball differences between two sets of press releases.
- Develop visualisation in the form of a map to show public places visited in the last 14 days, and places more frequently visited by infected, which will help the public have better decision making on places to be more cautious of when visiting such places.

**Comment by lennardl** [comment]
@tws4793 We understand that the data is not in a readable format on MOH's site but for all Covid-19 data we were informed to direct request back to MOH's site.

**Comment by tws4793** [comment]
Ahh okay looks like I have to go back to the traditional way of scraping from the PDFs since I don't think MOH will want to release such data in the raw form. Thanks anyway!
