### ISSUE TITLE
Dataset request: Amount of recycled waste collected in Singapore by sector

### ISSUE THREAD

**Issue by okayryn** [datagovsg/datagovsg-datasets#849]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Amount of recycled waste collected in Singapore by sector. Sectors refer to the 7 regions that Singapore's public waste collection is categorised into.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
MEWR, NEA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am a student undertaking the International Baccalaureate Diploma Programme. Part of this educational course is an investigative report. My research topic is the scale of the National Recycling Programme, so the data on the amount of recycled waste collected by geographical sector will aid my understanding of the scheme's effectiveness.

**Comment by lennardl** [comment]
@okayryn We have approached NEA asking if the data is available

**Comment by okayryn** [comment]
Hi, just wondering if NEA has responded - is this data available? Thank you
