### ISSUE TITLE
Dataset request: Vehicle Transfer Fee Api

### ISSUE THREAD

**Issue by jaspersorrio** [datagovsg/datagovsg-datasets#85]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Transfer Fee Api. Something that https://vrl.lta.gov.sg/lta/vrl/action/enquireTransferFeeDetailsProxy?FUNCTION_ID=F0501015ET might be using.

Given {car_plate}, {roc/nric} and {transfer_date} as inputs, it will give back data on the vehicle + the transfer fee.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Land Transport Authority

### If there's an issue with a dataset, please provide a description of the problem
No Issue.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Key|Value
---|---
Vehicle No. |GQ5623Y
Vehicle Type |A50 - Goods (Closed) Van/Van Panel (Delivery)
Vehicle Attachment 1 |No Attachment
Vehicle Scheme |Normal
Vehicle Make |TOYOTA
Vehicle Model |LITEACE 5 DR
Chassis No. |KR420024884
Propellant |Petrol
Engine No. |7K0228557
Engine Capacity |1781 cc
Maximum Power Output |-
Maximum Laden Weight |2150  kg
Unladen Weight |1180  kg
Year Of Manufacture |1998
Original Registration Date |29 Dec 1998
Lifespan Expiry Date |28 Dec 2018
COE Category |C - Goods Vehicle & Bus
PQP Paid |$11,877.00
COE Expiry Date |28 Dec 2018
Road Tax Expiry Date |27 Jun 2018
Inspection Due Date |27 Jun 2018
Intended Transfer Date |31 Jan 2018
CO2 Emission |-
CO Emission |-
HC Emission |-
NOx Emission |-
PM Emission |-
Transfer Fee |-

### How frequently would you need this dataset to be updated?
Example: 
- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [x] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
[https://eezee.sg](https://eezee.sg) (Eezee Pte Ltd) is launching a new feature and are looking to provide our users a functionality where they only have to input  {car_plate} and {roc/nric} and get back info on the vehicle. Similar to  https://vrl.lta.gov.sg/lta/vrl/action/pubfunc?ID=EnquireTransferFee

This way our users don't have to manually key in data from the lta tool mentioned above.

**Comment by jaspersorrio** [comment]
Or can anybody point me in the right direction as to how we can apply to get such data? Can't seem to find any information on where to apply to get access this data.

Seems like http://www.sgcarmart.com/main/index.php and https://carro.sg/ are using such an api.

**Comment by iewil** [comment]
@jaspersorrio this service is provided by LTA, and you can approach them to assist you with your request. You can contact them using this [link](https://www.lta.gov.sg/feedback/). Thank you.

**Comment by roslanlogan** [comment]
Hi @jaspersorrio , i am planning to do such feature as well,  may i know if u manage to get this working or its a request to made to LTA ?

**Comment by jaspersorrio** [comment]
Hi @roslanlogan, in the end we did not go ahead
