### ISSUE TITLE
Maintainence of this repository - Too many opened issues

### ISSUE THREAD

**Issue by zackteo** [datagovsg/datagovsg-datasets#850]
Hello! 

I don't mean to offend anyone with this, but would like to ask about the maintenance of this repo and datagovsg as a whole.

Just got sent to this repo from clicking "Request a Dataset" and from an outsider's perspective, this current 581 open issues, looks like an unruly mess. A kind of non-technical technical debt I would say. 

I understand the difficulties of helping people to get data from the various government agencies - especially to get them to open source the data. But at this point, it looks like too much of a mess to work with - not sure how y'all preserve through psychologically to be honest.

Am thinking that perhaps it might be a good idea to do certain things like ...

1. Close Issues and Pull Requests
- Maybe bump old issues and say you will be closing them in 2 weeks?

2. Simple things like helping to rename the various "Dataset request: <dataset title>" to what they are asking for

3. Understand that this is not where y'all update the datasets list but perhaps y'all should? Last update was Aug 31, 2018
- Maybe have an automated CI/CD workflow to bump this repo (and a date somewhere) and say a sorted by category list (datasets.md) of the current dataset available?

Sorry I understand that this might be additional painful work that y'all are taking on, but do think little steps will go a long way!

**Comment by zackteo** [comment]
@lennardl think this might have been buried under the swamp of issues ... :x

**Comment by lennardl** [comment]
@zackteo Thanks for the feedback

1. We wanted the requester to close it when its fulfilled or can't be fulfilled which isn't happening and isn't working out so we will clean it up
2. Will look into it
3. We have a dataset listing here https://data.gov.sg/dataset/dataset-listing which is updated

That being said we understand the state that the data request and platform is at and are planning a tech refresh next year.

**Comment by lennardl** [comment]
Closing this as we are progressively closing up older issues
