### ISSUE TITLE
Dataset request: distribution of annual leave

### ISSUE THREAD

**Issue by EileenYap** [datagovsg/datagovsg-datasets#851]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@EileenYap Can I ask more on the details on the annual leave data you are requesting for?

**Comment by EileenYap** [comment]
Hi there

There is a sheet on distribution of annual leaves across all sectors for year 2018.

Just wondering if you have one for 2019?

Regards
Eileen

**Comment by lennardl** [comment]
@EileenYap I've approached MOM to ask if they can update the data.

**Comment by lennardl** [comment]
@EileenYap MOM has reverted that as the data is available biennially, there is no data for 2019
