### ISSUE TITLE
Dataset request: Weather data of Jurong (Singapore) for 2018-2019

### ISSUE THREAD

**Issue by zulhairi06** [datagovsg/datagovsg-datasets#852]
Weather data for Jurong (Singapore) for year 2018-2019

 Meteorological Services Division

### Please provide the fields expected in this dataset:
Year 2018-2019 | Singapore

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am using it for research purposes.

**Comment by lennardl** [comment]
@zulhairi06 We do not have the weather-specific for Jurong but for the west of the island which you can retrieve from here https://data.gov.sg/dataset/weather-forecast?resource_id=9a8bd97e-0e38-46b7-bc39-9a2cb4a53a62

**Comment by zulhairi06** [comment]
Hi,

Can I request the data in .csv/Xls format?

Regards,
Zul

Sent from my iPhone

On 3 Sep 2020, at 6:19 PM, lennardl <notifications@github.com> wrote:

﻿

@zulhairi06<https://github.com/zulhairi06> We do not have the weather-specific for Jurong but for the west of the island which you can retrieve from here https://data.gov.sg/dataset/weather-forecast?resource_id=9a8bd97e-0e38-46b7-bc39-9a2cb4a53a62

**Comment by lennardl** [comment]
@zulhairi06 We do not have that real-time data in excel format.
