### ISSUE TITLE
Dataset request: 2020 Weekly Dengue Cases

### ISSUE THREAD

**Issue by DanielLevitt32** [datagovsg/datagovsg-datasets#854]
### Please provide the name of the dataset or describe the dataset that you're requesting:
**2020 Weekly Dengue Cases — Weeks 1 to 35**

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
**I don't know the answer to this.**

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

**We're look to include a chart of weekly Dengue cases for a story in the Wall Street Journal**

**Comment by lennardl** [comment]
@DanielLevitt32 The data is currently updated till W20 here https://data.gov.sg/dataset/weekly-infectious-disease-bulletin-cases, I'll reach out to our Ministry of Health to request for an update.
