### ISSUE TITLE
Metadata for ACRA Information on Corporate Entities

### ISSUE THREAD

**Issue by YoungeunS** [datagovsg/datagovsg-datasets#855]
### Please provide the name of the dataset or describe the dataset that you're requesting:
'ACRA Information on Corporate Entities'

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Accounting and Corporate Regulatory Authority

### If there's an issue with a dataset, please provide a description of the problem
I need a detailed version of the UEN dataset. 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

I need a full version

### How frequently would you need this dataset to be updated?

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Research

**Comment by lennardl** [comment]
@YoungeunS is this the dataset you are looking for https://data.gov.sg/dataset/acra-information-on-corporate-entities?

**Comment by YoungeunS** [comment]
Yes, thank you!

Best regards,
Youngeun

2020년 9월 3일 (목) 오후 9:56, lennardl <notifications@github.com>님이 작성:
