### ISSUE TITLE
singapore building data with height

### ISSUE THREAD

**Issue by roselui** [datagovsg/datagovsg-datasets#856]
I would like to request the singapore building footprints with its height, in shapefile format

maybe the lands department
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@roselui We have data limited to https://data.gov.sg/dataset/master-plan-2019-sdcp-building-height-control-layer?resource_id=ac19ca74-5aa6-4001-9355-14832b080fc2
