### ISSUE TITLE
Dataset request: <Greenhouse Gases Emission 1970-1989>

### ISSUE THREAD

**Issue by Gunthiga** [datagovsg/datagovsg-datasets#858]
### Do you know which agency provides/can provide this **data?**
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
I do not know which agency to find data in Singapore, so I come to this website to request this data.

### If there's an issue with a dataset, please provide a description of the problem
I have an issue with data due to I search in data.worldbank and I can not data completely that I needed.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Annually | country | Greenhouse Gases Emission 
------|---------|-------------
1970-1989|Singapore| ?????

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by Gunthiga** [comment]
please contact me, kantika27576@gmail.com

**Comment by lennardl** [comment]
@Gunthiga We have approached NEA for this and am waiting on a response

**Comment by Gunthiga** [comment]
Thank you so much!

ในวันที่ พ. 9 ก.ย. 2020 เวลา 14:12 lennardl <notifications@github.com>
เขียนว่า:

**Comment by lennardl** [comment]
We do not have the data that goes back that far back
