### ISSUE TITLE
Dataset request: Private Residential Properties

### ISSUE THREAD

**Issue by sprmrkt** [datagovsg/datagovsg-datasets#86]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Private Residential Properties
(Data on prices, rentals and pipeline supply of private residential properties and executive condominiums)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Urban Redevelopment Authority
https://www.ura.gov.sg/Corporate/Property/Property-Data/Private-Residential-Properties

### If there's an issue with a dataset, please provide a description of the problem
The dataset only provides up to 3 years prior to the current date. 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Project Name | Street Name | Type | Postal District | Market Segment | Tenure | Type of Sale | No. of  Units | Price | ($) Nett Price | ($) Area (Sqft)¹ | Type of Area² | Floor Level | Unit Price ($psf)³ | Date of Sale⁴
------|---------|---------|---------|---------|---------|---------|---------|---------|---------|---------|---------|---------|---------|---------
#1 LOFT | LORONG 24 GEYLANG | Apartment | 14 | RCR | Freehold | Resale | 1 | 645,888 | - | 581 | Strata | 06 to 10 | 1,111 | Dec-17

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X] Monthly
- [x] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
A 5 year or 10 year dataset would provide a better overview of the market and help analyse trends in depth.

**Comment by iewil** [comment]
@1kc for data beyond the 3 year window, you'll have to subscribe to URA's Realis service.
