### ISSUE TITLE
Dataset request: ACRA weekly extract

### ISSUE THREAD

**Issue by cvera8** [datagovsg/datagovsg-datasets#861]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Please provide me with the Singapore business dataset.  I am looking for Entity name, UEN, address, contact number, email, business description, business activity codes.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
ACRA

### If there's an issue with a dataset, please provide a description of the problem
n/a

### Please provide the fields expected in this dataset:
month | entity name | business description | contact number | email | url | industry type | address | business status
------|---------|-------------
2017-09|ABC Pte Ltd|trading import export|91234567|test@gmail.com|www.web.com|Importing and Exporting | 33 Ubi Avenue 3 | Active

### How frequently would you need this dataset to be updated?
Example: 
- [X] Weekly

### Can you give a short explanation on how you're planning to use this dataset?
I would like to derive analytics based on where companies are migrating by address, what types of business activities are increasing or decreasing in popularity, and detecting when companies are becoming dormant.  These business signals can create sales hints for vendors to provide services to these companies.  For example, when a company moves from address A to address B, they may want assistance in concluding their business with the landlord of their prior address.  A weekly feed of this information would be valuable in providing these signals.

**Comment by cvera8** [comment]
I think I've answered my own question, apologies
It's this link, correct?
https://data.gov.sg/dataset/acra-information-on-corporate-entities

**Comment by lennardl** [comment]
Yes but the data is updated on an ad hoc basis
