### ISSUE TITLE
Dataset request: Traffic Throughput Along Orange Grove Road

### ISSUE THREAD

**Issue by Sentosa2012** [datagovsg/datagovsg-datasets#862]
### Please provide the name of the dataset or describe the dataset that you're requesting:

I am Looking for data on the traffic throughput along Orange Grove Road if possible

### Do you know which agency provides/can provide this data?

Possibly from the Land Transport Authority or the Ministry of Transport

### Please provide the fields expected in this dataset:

Year | Month | Number of Vehicles (Possibly per hour) | Location

### How frequently would you need this dataset to be updated?

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

I am doing a research paper for school in which we are investigating urban decay from the CBD to the suburbs. This data would let us estimate the amount of noise and/or pollution in the area

**Comment by lennardl** [comment]
@Sentosa2012 We do not have traffic data for specific roads or the road network in general. You could try to approach LTA to see if they have the data

**Comment by Sentosa2012** [comment]
Ok, I'll see what they'd be able to give me. Thanks!
