### ISSUE TITLE
Dataset request: <URA No of Dwelling Units (current year)>

### ISSUE THREAD

**Issue by GayatriAruchunan** [datagovsg/datagovsg-datasets#863]
### Please provide the name of the dataset or describe the dataset that you're requesting: A
Addresses of Dwelling Units for Private Residential Properties

### Do you know which agency provides/can provide this data? URA No of Dwelling Units (current year)
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Block / Building Name 
Floor
Unit
Postal Code

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually : Data accurate as of end Q4 of the previous year
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I would be using this dataset to perform random sampling of households for survey distribution to households for my thesis project.

**Comment by lennardl** [comment]
@GayatriAruchunan That data is not available, the next closest data we have is https://data.gov.sg/dataset/ura-no-of-dwelling-units-current-year
