### ISSUE TITLE
Dataset request: ACRA AGM Filing Date

### ISSUE THREAD

**Issue by kaizentric** [datagovsg/datagovsg-datasets#864]
### Please provide the name of the dataset or describe the dataset that you're requesting:

ACRA Filing due dates by UEN 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
ACRA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | UEN| Filing Type | Last filing date | Next Due Date
------|---------|-------------
2020-09|201818197G|AGM|30/06/2020|30/06/2021

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [x ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Accounting and Bookkeeping firms need to remind AGM filing dates to their customers. This date changes annually based on the last filing date. Is it possible to get the last filing date by UEN for all entities for download? We'll upload the same in our database and refresh it monthly.

**Comment by lennardl** [comment]
@kaizentric We only have the company data provided by ACRA here https://data.gov.sg/dataset/acra-information-on-corporate-entities?resource_id=3b8539bb-5c22-4540-a420-86db444810d3. I believe filing date is not one of the fields

**Comment by kaizentric** [comment]
Hi,

Could we have the contact person at ACRA to work with? We need this field.
Thank you

Regards, HR
Phone/whatsapp: +65-92719219 skype: azhagarasan
hr@kaizentric.com www.kaizentric.com

**Comment by lennardl** [comment]
@kaizentric All feedback to ACRA would have to go through their main feedback channel
