### ISSUE TITLE
Dataset request: <10year per month relative humidity parameter value>

### ISSUE THREAD

**Issue by Poonam0820** [datagovsg/datagovsg-datasets#866]
Weather relative humidity data of different city of India last 10year per month 
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@Poonam0820 Data.gov.sg data is limited to Singapore
