### ISSUE TITLE
Dataset request: <GTFS Realtime Data>

### ISSUE THREAD

**Issue by gzyszuuow** [datagovsg/datagovsg-datasets#867]
### Please provide the name of the dataset or describe the dataset that you're requesting:
GTFS(General Transit Feed Specification) Data

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Transportation 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ X] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Dear Sir/Madam, I am a PhD student in HKUST, I want to do some research about Singapore's public transportation.
Thanks for processing.

**Comment by lennardl** [comment]
@gzyszuuow We do not have that data, for that you will have to approach the Land Transport Authority of Singapore directly
