### ISSUE TITLE
Dataset request: <All Mac Addresses Of Wireless Hotspots in Singapore>

### ISSUE THREAD

**Issue by WassupZ321** [datagovsg/datagovsg-datasets#868]
All Mac Address of the Wireless Hotspots in Singapore: Downloaded the data with the .geojson file but there isn't any Mac address of all the wireless hotspots in it

Do you know which agency provides/can provide this data?
Infocomm Media Development Authority 

Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2020-09|Singapore|

Can you give a short explanation on how you're planning to use this dataset?
I'm planning to use this dataset for my Embedded Systems & Sensor Programming which uses geofencing for my assignment at Singapore Institute Of Technology.

**Comment by lennardl** [comment]
@WassupZ321 I'll ask IMDA but in the meantime would the X/Y location work to approximate the area?

**Comment by WassupZ321** [comment]
@lennardl. Thanks on the part for asking IMDA for me. Although the x/y coordinates its possible, using a gps sensor and feeding the x/y coordinates its power consuming thus a mac address is preferred

**Comment by lennardl** [comment]
@WassupZ321 IMDA reverted saying they are not able to share the MAC addresses for the hotspots.

**Comment by WassupZ321** [comment]
@lennardl Alright thanks for the help again , appreciate it alot 👍
