### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by Fam-needs-your-help** [datagovsg/datagovsg-datasets#869]
### Please provide the name of the dataset or describe the dataset that you're requesting:
How many people visit the polyclinic every week.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Health

### If there's an issue with a dataset, please provide a description of the problem
N/A

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

     Week         | Polyclinic |  People  
-----------------------------------------
13/09 - 19/09 |  Pasir Ris  |    2500
### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

Just one instance of a static worksheet, over a 2 years (2018 - 2019)

### Can you give a short explanation on how you're planning to use this dataset?

Am doing a project in SIT, that requires usage of a real-life dataset with multiple entries.
For further issues, please let me know at 1902036@sit.singaporetech.edu.sg

**Comment by lennardl** [comment]
We only have an annual number
https://data.gov.sg/dataset/attendances-at-accident-emergency-departments-specialist-outpatient-clinics-and-polyclinics

**Comment by Fam-needs-your-help** [comment]
Sure, that works too, as long as the polyclinics are distinctly stated (not
regional)

Thanks!
