### ISSUE TITLE
Dataset request: <Concentration/Visualization of Gymnasium Facilities in Singapore>

### ISSUE THREAD

**Issue by Jasonchoong** [datagovsg/datagovsg-datasets#87]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Gyms@SG
Location of exercise facilities around Singapore

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
HPB

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

name|address

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [X] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Publication

**Comment by iewil** [comment]
@Jasonchoong for a list of public gyms operated by SportSG, you can take a look at this [link](https://www.myactivesg.com/facilities/gyms)
