### ISSUE TITLE
Dataset request: All carpark locations 

### ISSUE THREAD

**Issue by nickng70** [datagovsg/datagovsg-datasets#871]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by nickng70** [comment]
Hi, I'm looking for a dataset with the locations of all carparks in Singapore including HDB, URA and commercial buildings and can't find an existing api that provides this. Can let me know if there is one pls? Thanks so much!

**Comment by lennardl** [comment]
HDB https://data.gov.sg/dataset/carpark-availability
URA https://data.gov.sg/dataset/ura-carpark-information
We do not have commercial buildings but this might help https://data.gov.sg/dataset/carpark-rates

**Comment by nickng70** [comment]
Good morning Lennard,

 

Thanks so much for your reply and deeply appreciate it! Was trying to write through github and wasn’t sure I’ll get a reply but so thankful to receive your reply with the confirmation as well as the links and yes, I’ll be able to make use of the carpark-rates API to get details for the commercial buildings. 😊

 

So sorry, have one last question for now while we are working on our app, is there an API where we can obtain the car plate number from the IU number? Our alternative is to capture both at the gantry but if the API is available, we can avoid using LPR to capture the car plate number. 😝

 

Thanks so much again for your help! Meanwhile, have a fantastic day and week ahead!


With warmest regards!

Nicholas

**Comment by lennardl** [comment]
@nickng70 We do not have such a dataset. You might need to approach LTA but from what I now it does not exist.

**Comment by nickng70** [comment]
Hi again Lennard!

 

Thanks so much again for your confirmation and yes! Will follow-up with LTA and use the alternative method of capturing the number plate at the gantry.

 

Thanks so much again for your help and it’s truly excellent and very fast! Meanwhile, have a fantastic day ahead!


With warmest regards! 

Nicholas

**Comment by nickng70** [comment]
Hi Lennard,

 

Can I seek your advice on the following pls?

1.	Is there an API that returns the longitude and latitude of the carparks returned from carpark-availability or the ura-carpark-information APIs?
2.	Is there a query parameter we can use to find nearby carparks by providing a reference coordinate for the above APIs?

 

Thanks so much again for your most appreciated help! 😃

 

With warmest regards!

Nicholas

**Comment by lennardl** [comment]
@nickng70 
1. https://data.gov.sg/dataset/hdb-carpark-information allows you to search by X/Y coordinates
2. You can also use the above to search via address but its fuzzy results

**Comment by nickng70** [comment]
Thanks so much again for your superb support! 😃

 

So sorry, still need more help, don’t quite understand the coordinates as they don’t seem to be latitudes and longitudes, i.e.

X Coord: 33602.3061
Y Coord: 31409.6032

 




Versus latitude and longitude values provided by Google maps.



 

Thanks so much again for your help and have a wonderful evening ahead!

 

With warmest regards!

Nicholas

**Comment by lennardl** [comment]
@nickng70 The X Y coordinates are the output from the government systems. You will need to convert it to Lat Long or unless the mapping services take in X Y Coordinates. There are multiple tools and packages that can help convert it from one form to another. 

I did a search on Google and found one such tool https://scienceweb.whoi.edu/marine/ndsf/utility/NDSFutility.html

**Comment by nickng70** [comment]
Thanks so much Lennard! Deeply appreciate your reply and kindly providing me with the tool as well!! It’s very helpful and thanks so much again for your superb help!

 

Meanwhile, have a fantastic day ahead!

 

With warmest regards!

Nicholas
