### ISSUE TITLE
Dataset request: <GIS with demographics >

### ISSUE THREAD

**Issue by leocanada2007** [datagovsg/datagovsg-datasets#872]
### Please provide the name of the dataset or describe the dataset that you're requesting:

I would like to request Singapore GIS shapefile with demographics (education level, income etc.)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

I am not sure

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2020-10|Canada|5

### How frequently would you need this dataset to be updated?
Example: 

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

My co-authors and I are planning to use this data to run some analysis on Singapore housing market.

**Comment by lennardl** [comment]
@leocanada2007 We do not have that data on a shapefile, you might need to approach URA for this
