### ISSUE TITLE
Dataset request: request for house plants datasets for school projects

### ISSUE THREAD

**Issue by glissando88** [datagovsg/datagovsg-datasets#874]
### Please provide the name of the dataset or describe the dataset that you're requesting:
require following information relating to house plants: 
1) Sun information, 
2) Soil information, 
3) Amt of water information, 
4) whether plant require trellis for support or grows individually

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Nparks

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

plant_name | attributes 
------------- |-------------------
orchid          | water_requirement, soil_requirement, sun_information, trellis_support?

### How frequently would you need this dataset to be updated?
Example: 
- [x] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
We are a group of student in coding bootcamp trying to work on a project to promote planting in SG. Our aim is to provide information that can be searchable via our platform to help new plant parents have access to essential information to help them grow better plants.

**Comment by lennardl** [comment]
@glissando88 Apologises but we do not have such data on our site. Perhaps NEA might be able to help on that
