### ISSUE TITLE
Dataset request: Singapore National Population Health Survey, 2017

### ISSUE THREAD

**Issue by acommar** [datagovsg/datagovsg-datasets#875]
### Please provide the name of the dataset or describe the dataset that you're requesting:
National Population Health Survey, 2017

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Health and the Health Promotion Board

### If there's an issue with a dataset, please provide a description of the problem
I don't know where to access the data set. I need to do a cross-tabulation of respondent's sex and age with their responses to tobacco use questions, to derive prevalence rates by age by sex.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
sex, age group (18-29, 30-39, 40-49, 50-59, 60-69), smoke_currently, smoke_daily, smoke_cigarettes_currently, smoke_cigarettes_daily, survey_weight). Please include any other tobacco-related variables. Different age grouping also fine.

### How frequently would you need this dataset to be updated?
Not applicable.

### Can you give a short explanation on how you're planning to use this dataset?
To be used for modelling underlying trends reported in national surveys, for all WHO Member States, to publish in the upcoming 2021 WHO global report on trends in prevalence of tobacco use 2000-2025. We will send the modelling results to MoH Singapore during the country consultation, between November 2020 and February 2021. The detailed data will not be published, only the numbers already shared with WHO by MoH.

**Comment by lennardl** [comment]
@acommar I've approached HPB for the data and waiting on their response

**Comment by acommar** [comment]
Thank you so much!

**Comment by lennardl** [comment]
MOH/HPB will not be releasing the results from the 2017 survey. You might need to approach them directly to try too.

**Comment by acommar** [comment]
Thank you for your efforts.
