### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by LRusiecki** [datagovsg/datagovsg-datasets#876]
### Please provide the name of the dataset or describe the dataset that you're requesting:
All Government contracts awarded via GeBiz for the last 5 years, including name of company awarded to, the amount in SGD, names of companies who also bid and their bid amount in SGD, date, which Agency released the tender.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
**Singapore Ministry of Finance**

### Please provide the fields expected in this dataset:
Date, Agency releasing the tender, date awarded, Winning bidder Company name, award amount in SGD, other bidders company names, their bid amounts, procurement category, procurement details

### How frequently would you need this dataset to be updated?
Ideally monthly, but a one-time data except would be fine

### Can you give a short explanation on how you're planning to use this dataset?
To build an understanding of public procurement in Singapore

**Comment by lennardl** [comment]
@LRusiecki The data can be found here, MOF updates it on a half-yearly basis https://data.gov.sg/dataset/government-procurement

**Comment by LRusiecki** [comment]
Thanks indeed Sir / Ma’am - I already got that file, but it only contains details of the winning bidder and amount. It is missing the unsuccessful bidders and the amounts they bid.

Is it possible to get this additional data?


Best Regards

Laurence

+65 9230 4796

On 30 Sep 2020, at 8:51 AM, lennardl <notifications@github.com<mailto:notifications@github.com>> wrote:



@LRusiecki<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLRusiecki&data=02%7C01%7C%7C6c032f0e1eb042bdf56308d864daeece%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637370238749441789&sdata=KAI%2B7V870UrBJD3pomDQJSd6vA6P8ebCY7bSL9%2FZin4%3D&reserved=0> The data can be found here, MOF updates it on a half-yearly basis https://data.gov.sg/dataset/government-procurement<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdata.gov.sg%2Fdataset%2Fgovernment-procurement&data=02%7C01%7C%7C6c032f0e1eb042bdf56308d864daeece%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637370238749451785&sdata=0bq2%2FnkemVyzRuzTLnwKqEcAvtMhReIjz5E%2FabqSI%2FQ%3D&reserved=0>

**Comment by lennardl** [comment]
@LRusiecki Those are the only fields provided.

**Comment by LRusiecki** [comment]
Thanks anyway

Best Regards

Laurence

+65 9230 4796

On 30 Sep 2020, at 2:47 PM, lennardl <notifications@github.com<mailto:notifications@github.com>> wrote:



@LRusiecki<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLRusiecki&data=02%7C01%7C%7Cfa757c1dd67c4ca746da08d8650ca655%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637370452281926017&sdata=wHHW0Eoh47V1VF3YFcp%2BBIlKLG0EodiQGeADL3d9rLg%3D&reserved=0> Those are the only fields provided.
