### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by zero474** [datagovsg/datagovsg-datasets#877]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ x] Annually
- [ ] Monthly
- [x] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

For project

**Comment by lennardl** [comment]
@zero474 I need more information on what you need
