### ISSUE TITLE
Dengue Clusters

### ISSUE THREAD

**Issue by ongjunwen** [datagovsg/datagovsg-datasets#878]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Dengue Clusters

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
National Environment Agency (NEA)

### If there's an issue with a dataset, please provide a description of the problem
Please provide a data set in Excel form.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Area | Zone | Number of people with dengue
------|---------|-------------
Hougang| Northeast |10

Area, Number of people with dengue fever

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

Use once

### Can you give a short explanation on how you're planning to use this dataset?
For a project

**Comment by lennardl** [comment]
@ongjunwen The dengue clusters are only provided in a KML format.
