### ISSUE TITLE
Dataset request: Live companies by industry

### ISSUE THREAD

**Issue by IllumiNinja** [datagovsg/datagovsg-datasets#879]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
ACRA

### If there's an issue with a dataset, please provide a description of the problem
Currently, there are dataset showing this (https://data.gov.sg/dataset/acra-information-on-corporate-entities) but this list comprises of all companies instead of live companies. Do we have a list for that and possible to have an API to get live data?

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

company | UEN | Primary industry | Secondary industry
----------|------|---------
ABC Company| 202121915A| Growing of fruits| Growing of orchids

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [X] Real-time

If real-time is not possible, it can be weekly, monthly or annually etc

### Can you give a short explanation on how you're planning to use this dataset?
Explanation can be shared privately

**Comment by lennardl** [comment]
@IllumiNinja We are not able to provide the details by live companies or industries. It is possible to use the dataset you mentioned to download the companies or retrieve by the API and sort by industries

**Comment by IllumiNinja** [comment]
@lennardl Sure, thank you for your response
