### ISSUE TITLE
Dataset request: Pollutant Standards Index (PSI)

### ISSUE THREAD

**Issue by alinakosch** [datagovsg/datagovsg-datasets#88]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Pollutant Standards Index (PSI)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
National Environment Agency

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country 
2017-05|Singapore
2017-06|Singapore
2017-07|Singapore
2017-08|Singapore
2017-09|Singapore
2017-10|Singapore
2017-11|Singapore
2017-12|Singapore

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [X] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Research

**Comment by iewil** [comment]
@alinakosch this dataset is already available in the form of an API. You can refer to this [page](https://data.gov.sg/developer) for more information.
