### ISSUE TITLE
Acra dataset corporate entities paid up capital

### ISSUE THREAD

**Issue by scarmaten** [datagovsg/datagovsg-datasets#881]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Acra dataset corporate entities paid up capital

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

https://data.gov.sg/dataset/acra-information-on-corporate-entities

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

paid_up_capital3_ordinary | paid_up_capital5_ordinary | paid_up_capital9_preference | paid_up_capital1_ordinary
-- | -- | -- | --
0 | na | na | 0
40000 | na | na | 100000
0 | na | na | 0
1600000 | na | na | 4178000
29647500 | na | na | 37381970

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

I would like to know how does the paid up capital works since there is paid_up_capital1 all the way to paid_up_capital9.
Does the highest paid up capital mean that it is the most updated/latest? Or are the different paid up capital accumulative?

**Comment by lennardl** [comment]
@scarmaten For this, I would need to refer you to ACRA as they are the owners of the data and would be in a better position to explain the data
