### ISSUE TITLE
Covid-19 Patients Xray of Lungs

### ISSUE THREAD

**Issue by peanutsee** [datagovsg/datagovsg-datasets#882]
Hello, datagovsg, 

I am a student at Nanyang Technological University reading Data Science and Artificial Intelligence (Year 1). I will be presenting on the use of Computer Vision to detect Covid-19 in patients for my Scientific Communication module. I wish to acquire more recent x-ray scans of Covid-19 infected patients to train a deep learning model to distinguish between a pair of healthy lungs and infected lungs. I have tried to source for other open-source datasets. I was wondering if I could get data images from our local patients (past and present).

Any help would be of great help!

### Do you know which agency provides/can provide this data?
1. Health Promotion Board
2. Health Sciences Authority
3. Ministry of Health

### Please provide the fields expected in this dataset:
gender | age | image (preferably in .jpg or any other formats) | infected or not

M | 21 | image | 0 (0 means False)

### How frequently would you need this dataset to be updated?
- [X] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I will be using this dataset to train a deep learning model to detect covid-19 infected lungs for a personal project as well as to showcase it during my Scientific Communication module's oral presentation. 
It would be great if my model can be utilised to help fight covid-19.

**Comment by lennardl** [comment]
@peanutsee We are informed by MOH to direct all Covid-19 related data to MOH itself.

**Comment by peanutsee** [comment]
Hello lennardl, how do I contact them for datasets?

**Comment by lennardl** [comment]
@peanutsee You can reach them on their contact us page https://www.moh.gov.sg/contact-us

**Comment by peanutsee** [comment]
Thank you.
