### ISSUE TITLE
Dataset request: < Number of Ex-offenders the different job sectors in Singapore>

### ISSUE THREAD

**Issue by jessicatizx** [datagovsg/datagovsg-datasets#883]
### Please provide the name of the dataset or describe the dataset that you're requesting:

I would like to request for datasets that shows the number of ex-offenders that have been hired across different years (2015-2019) in different job sectors.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Singapore Corporation of Rehabilitative Enterprises

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

H1 Project Work for A Levels, anything would be appreciated.
Thank you.

**Comment by lennardl** [comment]
@jeantanzj That data is not available
