### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by mcsloof** [datagovsg/datagovsg-datasets#888]
### Please provide the name of the dataset or describe the dataset that you're requesting:
We would like an overview of the HDB Towns in Singapore with boundaries on a map.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Housing and Development Board

### If there's an issue with a dataset, please provide a description of the problem

The current URA dataset only provides Neighbourhoods, not HDB Estates.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

HDB Estate | lat/long boundaries | Streets within

### How frequently would you need this dataset to be updated?
Example: 
- [x] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

On our website, 99.co we allow our property searchers to search within the boundaries of an HDB Town. However, the boundaries are now outdated as it was created in 2014 and our initial source is no longer available.

**Comment by lennardl** [comment]
Does this work https://data.gov.sg/dataset/sla-land-survey-district

**Comment by mcsloof** [comment]
This is districts though right? Not HDB Towns? Also does it have the mapping of the Survey District name to the HDB Town?

**Comment by lennardl** [comment]
We do not have the mapping by that
