### ISSUE TITLE
Dengue Cases in all areas

### ISSUE THREAD

**Issue by l-w99** [datagovsg/datagovsg-datasets#890]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Dengue (Cases) - South West
Dengue (Cases) - South East
Dengue (Cases) - North East
Dengue (Cases) - Central
Dengue (Cases) - North West

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
NEA

### If there's an issue with a dataset, please provide a description of the problem
Please provide the link to the kml file. The one on Data.gov.sg is a zipped file.

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*
- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [x] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
For a school project. The link will be used to retrieve the data from the kml file.

**Comment by lennardl** [comment]
@l-w99 the KML files are within the zip file

**Comment by l-w99** [comment]
> @l-w99 the KML files are within the zip file

Is there a link for just the KML files? I'm trying to use the link to retrieve the data in the KML files.

**Comment by lennardl** [comment]
@l-w99 No as we bundle it with other files on details about the dataset
