### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by JunHeyy** [datagovsg/datagovsg-datasets#891]
### Please provide the name of the dataset or describe the dataset that you're requesting:
https://data.gov.sg/dataset/resale-flat-prices
resale-flat-prices

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

Housing and Development Board
### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000
2020-08|Singapore|7900

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [] Annually
- [ X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
We are university students from NTU and we are requesting to use this dataset for a project.

**Comment by lennardl** [comment]
The data on the site is under the open data license so everyone is free to use as long as you attribute it back to us and not use it for commercial reasons.
