### ISSUE TITLE
Dataset request: Registered Recruitment Agencies

### ISSUE THREAD

**Issue by IllumiNinja** [datagovsg/datagovsg-datasets#894]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Registered Recruitment Agencies in Singapore

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Manpower (MOM) - https://www.mom.gov.sg/eservices/services/employment-agencies-and-personnel-search

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Company name | UEN number | Location | Personnel | Status | Number of previous offenses
------|---------|-------------|------|---------|-------------
ABC recruitment | 202221310A | 18 Havelock Road, Singapore 059764 Singapore | Jack | Live | 2

Above is just an example of what I think might be possible to be shared but anything similar would do from MOM.

I am looking at this search directory of data - https://www.mom.gov.sg/eservices/services/employment-agencies-and-personnel-search

### How frequently would you need this dataset to be updated?
- [X] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

Monthly or annually works fine.

### Can you give a short explanation on how you're planning to use this dataset?
For a school project to support employment

**Comment by lennardl** [comment]
@IllumiNinja I'll ask if the data can be made available on Data.gov.sg in the meantime can you access and use the data provided by MOM?

**Comment by IllumiNinja** [comment]
@lennardl thank you. Yes, that's possible but is search based which restricts the amount of information shown within a single search. Hence, might be a bit troublesome to use the current method.

**Comment by lennardl** [comment]
@IllumiNinja Understood, MOM is reviewing the request waiting for them to get back to me.

**Comment by IllumiNinja** [comment]
Thank you @lennardl
