### ISSUE TITLE
Dataset request: Minute-by-minute wind speed readings at weather-station level.

### ISSUE THREAD

**Issue by shaunpwl** [datagovsg/datagovsg-datasets#895]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Minute-by-minute wind speed readings at weather-station level.
https://api.data.gov.sg/v1/environment/wind-speed

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

National Environment Agency
--

### If there's an issue with a dataset, please provide a description of the problem
the API is missing data for the east coast weather station

### Please provide the fields expected in this dataset:
{"station_id":"S107","value":1.5}

station_id| value
S107.       |7

The station id S107 is missing from this dataset
![image](https://user-images.githubusercontent.com/32692177/96691401-705cb980-13b7-11eb-8c1f-fc0ffa2392ed.png)
![1](https://user-images.githubusercontent.com/32692177/96691516-91bda580-13b7-11eb-9995-8c150f4a9ca8.png)

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [X] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
to provide alerts on expected strong wind at the east coast area

**Comment by lennardl** [comment]
@shaunpwl Thanks for the feedback. We have informed NEA of this.
