### ISSUE TITLE
Dataset enhancement request: HDB Carpark information geo location

### ISSUE THREAD

**Issue by peaz** [datagovsg/datagovsg-datasets#896]
### Please provide the name of the dataset or describe the dataset that you're requesting:
HDB Carpark information
https://data.gov.sg/dataset/hdb-carpark-information

### If there's an issue with a dataset, please provide a description of the problem
The x and y coordinate not a true lat/long coordinate and there is no documentation details on how to convert the pixel based XY coordinates to the actual location.

Request for the data to be updated to lat/long geo data instead. This is definitely possible since LTA's dataset has the true lat long details for the HDB carparks: http://datamall2.mytransport.sg/ltaodataservice/CarParkAvailabilityv2

### Can you give a short explanation on how you're planning to use this dataset?
Building a car park availability web app to simplify getting my favourite carparks listed on a simplistic UI. Proper lat/long data will allow me to better display/link the geo location of the parking lot on the map.
http://sgcarparks.atpeaz.com/

**Comment by lennardl** [comment]
@peaz For the data set you mentioned, its own by HDB. We brought it up to them but they are only providing it in XY coordinates

**Comment by kenngyc** [comment]
Thanks for the clarification. Is there a feedback mechanism to HDB for the dataset?

**Comment by peaz** [comment]
@lennardl Thanks for the clarification. Is there a feedback mechanism to HDB for the dataset?

**Comment by lennardl** [comment]
Feedback to HDB needs to go through their public feedback channel
