### ISSUE TITLE
Dataset request: <EPU Registry>

### ISSUE THREAD

**Issue by katherinekerk** [datagovsg/datagovsg-datasets#897]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Gebiz Trading Partner - EPU Registry

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Gebiz 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
EPU Registry for supplier directory 

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Understanding the market with the supplier listing and assessment of new business opportunities.

**Comment by lennardl** [comment]
@katherinekerk We do not have the data less the results from GeBiz which is updated on a quarterly basis
