### ISSUE TITLE
Dataset request: <Traffic condition on expressway dataset>

### ISSUE THREAD

**Issue by Benjaminlw1** [datagovsg/datagovsg-datasets#898]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Traffic dataset that gives number of cars or traffic conditions on all expressways PIE,CTE,KPE etc...  for at least 3 to 5 years worth of data.

### Do you know which agency provides/can provide this  #data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Land Transport Authority

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
numberOfVehicles | day | time | month | year | nameOfExpressway  

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
University Final Year project on traffic prediction, need years of data for statistic and analysis and produce a machine learning model.

**Comment by lennardl** [comment]
@Benjaminlw1 There's only an overall number, LTA does not provide the numbers broken down by expressway https://www.mytransport.sg/content/mytransport/home/dataMall/search_datasets.html?searchText=road%20traffic%20conditions

**Comment by Benjaminlw1** [comment]
@lennardl Alright thanks so much for your help.
