### ISSUE TITLE
Backdated Dataset request: <Community Use Sites> & <SLA Vacant State land and properties>

### ISSUE THREAD

**Issue by accelyn** [datagovsg/datagovsg-datasets#899]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Community Use Sites & SLA Vacant State land and properties

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
SLA 

### If there's an issue with a dataset, please provide a description of the problem
Will like to request for the backdated versions of 2 datasets, both under SLA
1. Community Use Sites (Updated quarterly, created since May 2015)
2. SLA Vacant State land and properties (Updated monthly, created since Oct 2015)

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To study trends, duration of vacancy and change in use of vacant state land for a university project. It will be great if authors can provide the backdated KML files in half-yearly intervals. Thank you.

**Comment by lennardl** [comment]
@accelyn We do not host the previous versions of the file, but I would recommend using the past Masterplans as a proxy?

**Comment by accelyn** [comment]
@lennardl Alright then, noted. Thank you!
