### ISSUE TITLE
Dengue patient records like symtoms and blood reprts: <dengue>

### ISSUE THREAD

**Issue by ghost** [datagovsg/datagovsg-datasets#9]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by iewil** [comment]
closing issue due to incomplete submission
