### ISSUE TITLE
Dataset request: <number of children diagnosed with developmental problems >

### ISSUE THREAD

**Issue by itsdesc** [datagovsg/datagovsg-datasets#90]
### Do you know which agency provides/can provide this data?
*Ministry Of Health*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Year | country | passengers
------|---------|-------------
2016|Singapore|10000
2015|Singapore|10000
2014|Singapore|10000
2013|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To compare with the trends in allied health professionals to see how diverged the demand and supply is.

**Comment by itsdesc** [comment]
To compare with the trends in allied health professionals to see how diverged the demand and supply is.

**Comment by iewil** [comment]
@itsdesc could you please provide more details about what you might require from such a dataset? thank you.
