### ISSUE TITLE
Dataset request: <Live Births>

### ISSUE THREAD

**Issue by wshuxian** [datagovsg/datagovsg-datasets#902]
### Please provide the name of the dataset or describe the dataset that you're requesting:
More detailed and joined data of Live Births in Singapore, best if raw and masked data can be shared.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Home Affairs - Immigration & Checkpoints Authority

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | mother_age | mother_nationality | mother_race | mother_education | mother_occupation | father_age | father_nationality | father_race | father_education | father_occupation | martial_status | birth_order (from mother's perspective) | period_of_gestation | child_gender | birth_count
---------|--------|----------------|
2017-09|25 - 29|SINGAPOREAN|CHINESE|UNIVERSITY DEGREE|AGRICULTURAL & FISHERY WORKERS|30 - 34|AMERICAN|OTHERS|UNIVERSITY DEGREE|AGRICULTURAL & FISHERY WORKERS|MARRIED|1st|39|M|10
---------|--------|----------------|
2017-09|25 - 29|SINGAPOREAN|CHINESE|UNIVERSITY DEGREE|AGRICULTURAL & FISHERY WORKERS||||||SINGLE|1st|39|M|5

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To study factors affecting Live Births in Singapore.

**Comment by lennardl** [comment]
@wshuxian Only the top line numbers can be released

**Comment by wshuxian** [comment]
Hi @lennardl,
The data fields requested are collated and combined from existing datasets released, still considered top line numbers?
I understand that raw data cannot be released, but what's the max. number of fields that can be provided for a single dataset?
Thanks for your help.

**Comment by lennardl** [comment]
The datasets are split up into high-level aggregates that are provided here https://data.gov.sg/search?q=birth

SingStat also produces an annual report that can be referred to.
