### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by Andre66K** [datagovsg/datagovsg-datasets#903]
### Please provide the name of the dataset or describe the dataset that you're requesting:

 The dataset we need should be in csv or xlxs format and should include the following information: 

          - Date and time
          - Type of crime
          - Geolocation (preferably latitude and longitude, but block numbers, zip codes and police beats would work as well)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

Ministry of Home Affairs or Singapore Police Force

### If there's an issue with a dataset, please provide a description of the problem

I was able to find the Overall Crime cases statistic, and other crime related statistics that you have posted on your website. However, those statistics do not include any geolocation for the data or the ones that do include it - such as the Five Preventable Crime Cases Recorded by NPC datasets - only include some types of crime.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Date and time of the crime |Type of crime |Geolocation (preferably latitude and longitude, but block numbers, zip codes and police beats would work as well)

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

I work for a tech startup called Base Operations, which is based in Washington DC, USA. Base Operations visualizes security data to increase transparency and help people stay safe. Our intelligence platform provides street level threat assessments so that companies can provide security for their installations and personnel who are traveling or based in emerging market cities. We are currently gathering data on Singapore in order to create an interactive crime map of the city. You can find more information on our company on our website:  https://www.baseoperations.co/ .

**Comment by lennardl** [comment]
We only have topline crime numbers it is not broken down into the details you require https://data.gov.sg/dataset/overall-crime-cases-crime-rate
