### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by elloleo** [datagovsg/datagovsg-datasets#906]
### Please provide the name of the dataset or describe the dataset that you're requesting: 

Number of Applications for HDB Loan Eligibility Letters

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

Housing and Development Board

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Year | Month | No. of Applications 
------|---------|-------------
2017|09|10000

### How frequently would you need this dataset to be updated?
Example: 

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

I would like to use this dataset to analyse the change of HDB Loan application in the prevailing economic climate that has been impacted by COVID19.

**Comment by lennardl** [comment]
@elloleo The data is updated on a yearly basis by HDB here https://data.gov.sg/dataset/number-of-applications-for-hdb-loan-eligibility-letters the next update would be in Jan 2021
