### ISSUE TITLE
Dataset request: Traffic accidents

### ISSUE THREAD

**Issue by gummydelxue** [datagovsg/datagovsg-datasets#908]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Traffic accidents 2018-2020

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Home Affairs - Singapore Police Force 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Date | Time | Location of accident | Cause of accident 
------|-------|-----------------------|---------------------
29-12-2019 | 2359 | 1.384183, 103.738625 | Changing Lane without Due Care

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [x] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

It is part of school project. We are planning to have a warning pop-up integrated into our route planning service to warn user that past accident has occured before and to ask them to be careful when driving in the area.

**Comment by lennardl** [comment]
The data can be inferred from here https://data.gov.sg/dataset/causes-of-road-accidents-causes-of-accidents-by-severity-of-injury-sustained
