### ISSUE TITLE
Dataset request: HDB Carpark Information

### ISSUE THREAD

**Issue by bbhui13** [datagovsg/datagovsg-datasets#909]
### Please provide the name of the dataset or describe the dataset that you're requesting:
HDB Carpark Information

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
-

### If there's an issue with a dataset, please provide a description of the problem
When using the api link (https://data.gov.sg/api/action/datastore_search?resource_id=139a3035-e624-4f56-b63f-89ae28d4ae4c), it only provides the first 100 carparks.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

1 | car_park_no | Car Park No. | Text (General) | - | -
-- | -- | -- | -- | -- | --
2 | address | Address | Text (General) | - | -
3 | x_coord | X Coord | Geo Coordinate (X) | - | -
4 | y_coord | Y Coord | Geo Coordinate (Y) | - | -
5 | car_park_type | Car Park Type | Text (General) | - | -
6 | type_of_parking_system | Type Of Parking System | Text (General) | - | -
7 | short_term_parking | Short Term Parking | Text (General) | - | -
8 | free_parking | Free Parking | Text (General) | - | -
9 | night_parking | Night Parking | Text (General) | - | -
10 | car_park_decks | Car park decks | Numeric (General) | No. of decks | -
11 | gantry_height | Gantry height | Numeric (General) | Metres | -
12 | car_park_basement | Car park basement | Text (General) | - | -

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [x ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To draw out and display HDB carparks information in a website with google maps. (With markers) This is for a school project

**Comment by lennardl** [comment]
@bbhui13 you can add a limit param to retrieve everything like 
https://data.gov.sg/api/action/datastore_search?resource_id=139a3035-e624-4f56-b63f-89ae28d4ae4c&limit=4100
