### ISSUE TITLE
Bankruptcy: Bankruptcy List

### ISSUE THREAD

**Issue by siowchen** [datagovsg/datagovsg-datasets#91]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Bankruptcy list

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Law

### If there's an issue with a dataset, please provide a description of the problem
Could be a PDPA Issue

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Date of Bankruptcy | Bankruptcy No | Type ( Person/Company) | Identification No
--------------------|----------------|--------------------------|------------------
2017-09-01             |B 0009261932E|Personal/Company            | S123455D

### How frequently would you need this dataset to be updated?
Example: 

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Its a bankruptcy Search tied in when people are purchasing property, to know if the buyer is eligible to purchase the property, rather than find out later that the potential buyer is completely unsuitable, wasting time and money.

**Comment by iewil** [comment]
@siowchen as you've mentioned, there could be an issue with providing this issue as it contains personally identifiable data. If you would still like to access this data, you can approach the insolvency office at the Ministry of Law

**Comment by siowchen** [comment]
so its okay to sell it by the government but not give it away? and selling
it does not have any issue with personally identifiable data?
