### ISSUE TITLE
Dataset request: COVID Raw Data

### ISSUE THREAD

**Issue by 33479544** [datagovsg/datagovsg-datasets#910]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I would like to get COVID related dataset(singapore) and raw data for analysis.

### Do you know which agency provides/can provide this data?
Ministry of Health

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2019-12|Singapore|10000
2020-01|Singapore|10000
2020-02|Singapore|10000
2020-03|Singapore|10000
2020-04|Singapore|10000
2020-05|Singapore|10000
2020-06|Singapore|10000
2020-07|Singapore|10000
2020-08|Singapore|10000
2020-09|Singapore|10000
2020-10|Singapore|10000
2020-11|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [X] Hourly
- [X] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
After obtaining the dataset, I will be using tableau application to perform a visualisation graph and indepth details on the given dataset.

**Comment by lennardl** [comment]
@33479544 We have been informed to direct all Covid-19 related data to MOH's Covid site
