### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by LightPlayBr** [datagovsg/datagovsg-datasets#912]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Hey, I need information about gases pollutants: CO, NO2, SO2, PM10, O3;
This date is mean per state of USA.

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
https://www.sentinel-hub.com
https://openweathermap.org/api

### If there's an issue with a dataset, please provide a description of the problem
I need collect information about these gases for forecast about pneumonia with machine learning, this data will be collect weekly or monthly.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2013-2020|Per state USA|

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ x] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@LightPlayBr This site and issues created are for Data.gov.sg so the data would be limited to Singapore

**Comment by LightPlayBr** [comment]
I thinking use this resources:

https://www.sentinel-hub.com
https://openweathermap.org/api

**Comment by lennardl** [comment]
@LightPlayBr Sorry but I don't understand. The resource is external and not hosted by us. The data on our site is limited to Singapore provided by the different Singapore Government agencies themselves.
