### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by TanWeeSiang** [datagovsg/datagovsg-datasets#916]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Air pollution level

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Department of statistic enviroment
https://www.singstat.gov.sg/find-data/search-by-theme/society/environment/latest-data

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000
monthly and daily data 

Sulphur   Dioxide (Annual Mean)(Microgram Per Cubic Metre)
Sulphur   Dioxide (Maximum 24-hour Mean)(Microgram Per Cubic Metre)
Nitrogen   Dioxide (Annual Mean)(Microgram Per Cubic Metre)
Nitrogen   Dioxide (Maximum 1-hour Mean)(Microgram Per Cubic Metre)
Particulate   Matter (PM10) (Annual Mean)(Microgram Per Cubic Metre)
Particulate   Matter (PM10) (99th Percentile 24-hour Mean)(Microgram Per Cubic Metre)
Particulate   Matter (PM2.5) (Annual Mean)(Microgram Per Cubic Metre)
Particulate   Matter (PM2.5) (99th Percentile 24-hour Mean)(Microgram Per Cubic Metre)
Carbon   Monoxide (Maximum 8-hour Mean)(Milligram Per Cubic Metre)
Carbon   Monoxide (Maximum 1-hour Mean)(Milligram Per Cubic Metre)
Ozone (Maximum   8-hour Mean)(Microgram Per Cubic Metre)

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [x ] Monthly
- [ ] Weekly
- [x ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I need the data for my data science project

**Comment by lennardl** [comment]
The data is spread out over multiple dataset https://data.gov.sg/search?q=pollutant

**Comment by TanWeeSiang** [comment]
Hi,Able to get monthly data? This is yearly dataRegardsWee siangSent from my Huawei phone-------- Original Message --------Subject: Re: [datagovsg/datagovsg-datasets] Dataset request:  (#916)From: lennardl To: datagovsg/datagovsg-datasets CC: TanWeeSiang ,Author 
The data is spread out over multiple dataset https://data.gov.sg/search?q=pollutant

**Comment by lennardl** [comment]
@TanWeeSiang The historical data is provided to us as-is from NEA. For PSI, it's possible to retrieve the daily historical data to get a monthly but it would require more API calls.

**Comment by TanWeeSiang** [comment]
Hi,
Daily data  is also fine . Is there data for airpollution. Like the nitrogen dioxide. Pm 10 data.  Carbon monoxide. Where do I get those data ? I am using r language . I need 10  years of data. 
Regards Wee  siang


Sent from Yahoo Mail on Android 
 
  On Tue, 10 Nov 2020 at 9:04 AM, lennardl<notifications@github.com> wrote:   


@TanWeeSiang The historical data is provided to us as-is from NEA. For PSI, it's possible to retrieve the daily historical data to get a monthly but it would require more API calls.

**Comment by TanWeeSiang** [comment]
Hi,
I also need carbon dioxide data monthly of daily for ten years time frame.

Sent from Yahoo Mail on Android 
 
  On Tue, 10 Nov 2020 at 2:15 PM, Wee Siang<weelia@yahoo.com> wrote:   Hi,
Daily data  is also fine . Is there data for airpollution. Like the nitrogen dioxide. Pm 10 data.  Carbon monoxide. Where do I get those data ? I am using r language . I need 10  years of data. 
Regards Wee  siang


Sent from Yahoo Mail on Android 
 
  On Tue, 10 Nov 2020 at 9:04 AM, lennardl<notifications@github.com> wrote:   


@TanWeeSiang The historical data is provided to us as-is from NEA. For PSI, it's possible to retrieve the daily historical data to get a monthly but it would require more API calls.

**Comment by lennardl** [comment]
The PSI historical daily data can be retrieved from https://data.gov.sg/dataset/psi using a query for the API
We do not have the historical daily for the rest
