### ISSUE TITLE
Dataset request: Request on dataset about Woodlands and Tuas Checkpoint

### ISSUE THREAD

**Issue by phylliswai** [datagovsg/datagovsg-datasets#918]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Dataset on Woodlands and Tuas Checkpoint, in particular:
1) the distribution of commuters travelling from SG to Johor that travels through walk/bus/train (or all modes of transportation if possible) / generic arrival statistics of visitors to Singapore through the Johor-Singapore causeway 
2) average time taken for various types of commuters (Singaporeans / Non-Singaporeans to clear passport control

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

Ministry of Home Affairs - Immigration & Checkpoints Authority

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

At least 1 year worth of data if possible, any year between 2010-2019 would be good.

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [ X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Using for university project, as we intend to do up a simulation model to gain a better understanding of the key components on the process of commuting from Singapore to Johor through the Johor-Singapore causeway, such as fluctuating arrival rates of people via buses, and other means of transport, as well as varying service rates (of clearing passport control) depending on the citizens' background.

**Comment by lennardl** [comment]
We do not have data specific to the arrivals from the causeway
