### ISSUE TITLE
Dataset request: <Total Mobile Phone Subscriptions by prepaid and postpaid customers for 2019>

### ISSUE THREAD

**Issue by emilysmithzander** [datagovsg/datagovsg-datasets#919]
### Please provide the name of the dataset or describe the dataset that you're requesting:

https://data.gov.sg/dataset/total-mobile-phone-subscriptions?view_id=8f730dd2-35b3-4a46-854d-39b6d6760d57&resource_id=e50178d4-12f3-42c9-9735-777086b9e4e3

Referring to this link, I would like to request for 2019 data.

**Comment by lennardl** [comment]
@emilysmithzander I have approached IMDA to request an update to the dataset

**Comment by emilysmithzander** [comment]
Dear Sir/ Mdm,

Thank you.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by emilysmithzander** [comment]
Dear Sir/ Mdm,

May I follow up on the below mentioned request?

Further, I would like to clarify if the dataset includes MVNOs?

Best regards,
Emily Chen
Analyst

[cid:image001.jpg@01D428C0.579E48D0]
SMITH ZANDER INTERNATIONAL SDN BHD
15-01, Level 15, Menara MBMR
1, Jalan Syed Putra
58000 Kuala Lumpur
Malaysia
T: +603 2732 7537
M: +6019 421 3900

Visit us at www.smith-zander.com<http://www.smith-zander.com/>

**Comment by lennardl** [comment]
@emilysmithzander We reached out to IMDA but have not gotten any response from them.
Will need to check on MVNOs when they respond.

**Comment by emilysmithzander** [comment]
Dear sir/Mdm,

Thank you. Would appreciate if you could try to expedite the data request.

Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by emilysmithzander** [comment]
Hi,

May I check in the status of this request?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lennardl** [comment]
The data has been updated till Aug 2020

**Comment by emilysmithzander** [comment]
Hi Llenard,

Would you be able to furnish me with the updated data and let me know where are the subscribers captured from? Does it capture MVNOs like GIGA and GOMO?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by emilysmithzander** [comment]
Hi Llenard,

Would you be able to furnish me with the updated data and let me know where are the subscribers captured from? i.e. does it consider sub brands/MVNOs  like GIGA and GOMO, or it only captures MNOs (i.e. Singtel)?

Thanks.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lennardl** [comment]
@emilysmithzander The number is across all and IMDA does not provide the breakdown

**Comment by emilysmithzander** [comment]
Hi Llenard,

Thanks your for reply.

In the email dated 10 December @ 10.43am, you mentioned that there was updated data for 2020, can you furnish it to me?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/total-2g-mobile-subscriptions
