### ISSUE TITLE
Dataset request: <air-temperature>

### ISSUE THREAD

**Issue by mohan4krishna** [datagovsg/datagovsg-datasets#92]
### Please provide the name of the dataset or describe the dataset that you're requesting:
air-temperature (developers.data.gov.sg/environment/air-temperature)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
National Environment Agency

### If there's an issue with a dataset, please provide a description of the problem

We are extracting the data from data.gov.sg APIs "air-temperature" data set and found that there are missing data for alot of stations, But data is available in the file we received from  "National Environment Agency".  I have compared with data we received form "National Environment Agency" using the date range (1 Jan  2018 to 18 Jan 2018).

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Daily*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [x] Real-time

**Comment by iewil** [comment]
@mohan4krishna would you be able to provide examples of the missing data? we can help to follow up on this with our colleagues from NEA. Thank you.

**Comment by mohan4krishna** [comment]
In Feb -2018 month for the dates 7,8,17,18 and 19-Feb no data is available in the  "AIR-TEMPERATURE" data set.
