### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by Elizabai** [datagovsg/datagovsg-datasets#920]
### Please provide the name of the dataset or describe the dataset that you're requesting:
ACRA Information on Corporate Entities

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
https://data.gov.sg/dataset/acra-information-on-corporate-entities

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

all data set

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [x ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am trying to generate some features for different business entities

**Comment by lennardl** [comment]
The data is available but the updated is frequency is set to ad hoc
