### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by kimlan84** [datagovsg/datagovsg-datasets#922]
### Please provide the name of the dataset or describe the dataset that you're requesting: 

1) number of medium sized manufacturing companies in Singapore

2) number of large sized manufacturing companies in Singapore
 Latest data 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
We do not have that data
