### ISSUE TITLE
Spending data

### ISSUE THREAD

**Issue by kaihendry** [datagovsg/datagovsg-datasets#923]
### Please provide the name of the dataset or describe the dataset that you're requesting:

In light of the COVID situtation, governments are augmenting the economy with increased spend. I am curious at what the rate of increased spend is in the Singapore economy.

https://www.straitstimes.com/politics/budget-deficit-expected-to-hit-743-billion-largest-since-independence-in-1965

### Do you know which agency provides/can provide this data?

Committee of Supply (COS) 

* https://www.parliament.gov.sg/newsroom/speaker%27s-blog/details/the-budget-process
* https://www.singaporebudget.gov.sg/budget_2020/fortitude-budget

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | ministry | estimate (SGD)
------|---------|-------------
2017-09|MOM|27000000

### How frequently would you need this dataset to be updated?

- [X] Monthly

### Can you give a short explanation on how you're planning to use this dataset?

Track government spending. Keep an eye on national debt / deficit.

Similar to what is being asked in https://github.com/datagovsg/datagovsg-datasets/issues/717 and maybe https://github.com/datagovsg/datagovsg-datasets/issues/725

**Comment by lennardl** [comment]
We only have the budget data https://data.gov.sg/dataset/government-fiscal-position-annual
