### ISSUE TITLE
Dataset request: <List of Fast Food Outlets>

### ISSUE THREAD

**Issue by XLIM027** [datagovsg/datagovsg-datasets#926]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
     Singapore Food Agency 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Name | address | seating capacity  | Halal

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

Wish to use the data to check if staying near a fast food outlet would lead to weight gain
Also to calculate the possibility of unified reverse logistics

Thank you!

**Comment by lennardl** [comment]
We do not have a list of fast food outlets.
