### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by g33kym0nster** [datagovsg/datagovsg-datasets#928]
### Please provide the name of the dataset or describe the dataset that you're requesting:

List of companies in Singapore with ISIC starting with 47 and 56. Data should have the company name and full ISIC. 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

Accounting and Corporate Regulatory Authority

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Company name | UEN | ISIC CODE | Date of incorporation | Address 

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

To have a list of companies that are within retail and F&B space and to subsequently, do a survey on how badly are they impacted by Covid.

**Comment by lennardl** [comment]
@g33kym0nster the data is limited to what we have here https://data.gov.sg/dataset/acra-information-on-corporate-entities
This might also be relevant to you https://data.gov.sg/dataset/cessation-of-all-business-entities-by-type-monthly
