### ISSUE TITLE
Dataset request: household income distribution in subzones of Bukit Merah.

### ISSUE THREAD

**Issue by peter308** [datagovsg/datagovsg-datasets#929]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I have downloaded this dataset from data.gov.sg
https://data.gov.sg/dataset/resident-working-persons-aged-15-years-over-by-planning-area-gross-monthly-income-from-work-2015?resource_id=eef4ea00-1d8d-435f-8eb8-5792c4f2d602

Do you have same dataset on the subzone level of Bukit Merah? E.g. Tiong Bahru, Bukit Ho Swee, redhill, etc?

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

Ministry of Trade and Industry - Department of Statistics

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

We are trying to collect this data to conduct housing-related research.

**Comment by lennardl** [comment]
@peter308 The detailed breakdown is not provided to us from the department of statistics.
