### ISSUE TITLE
Dataset request: <Allotment Garden>

### ISSUE THREAD

**Issue by Ethan777100** [datagovsg/datagovsg-datasets#931]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I wish to propose inclusion of Allotment Gardens

[](https://www.nparks.gov.sg/gardening/allotment-gardens

https://www.nparks.gov.sg/-/media/nparks-real-content/gardening/allotment-gardening/locations-of-allotment-gardens-2020-nov-2020.pdf?la=en&hash=0571948B6D45CE39EB5F53B7E6651C8898FCF40F)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
NParks

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

**I would like a kml dataset of all the gardens. Perhaps each data point will contain some basic info about it - open for innovation.**

### How frequently would you need this dataset to be updated?
Example: 

- [ X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Facilitate problem solving in Sqkii Hunt From Home cash hunts.

**Comment by lennardl** [comment]
@Ethan777100 I've approached NEA to ask if they can put the data on data.gov.sg

**Comment by lennardl** [comment]
@Ethan777100 NParks responded that they do not have an existing file for the information.
