### ISSUE TITLE
Dataset request: Additionally Disaggregated Tables from Census 2000 and 2010

### ISSUE THREAD

**Issue by hwangii** [datagovsg/datagovsg-datasets#934]
### Please provide the name of the dataset or describe the dataset that you're requesting:

I am requesting additionally disaggregated version of some of the Tables from Census 2000 and 2010. More specifically, below are the tables and disaggregation that I am requesting:

1. Table 1 (age group) of Census 2000, additionally disaggregated by Chinese/non-Chinese population

2. Tables 5 (language spoken at home) and 10 (languages literate in) of Census 2000, additionally disaggregated by subzone

3. Tables 11 (religion), 12 (highest qualification attained), and 15 (monthly income) of Census 2000, additionally disaggregated by subzone and Chinese/non-Chinese population

4. Tables 19 (household structure), 20 (household size), and 21 (household monthly income) of Census 2000, additionally disaggregated by subzone and households with Chinese head/non-Chinese head

5. Table 1 (age group) of Census 2010, additionally disaggregated by Chinese/non-Chinese population

6. Tables 4 (language spoken at home) and 10 (languages literate in) of Census 2010, additionally disaggregated by subzone

7. Tables 11 (religion), 12 (highest qualification attained), and 15 (monthly income) of Census 2010, additionally disaggregated by subzone and Chinese/non-Chinese population

8. Tables 20 (household structure), 21 (household size), and 22 (household monthly income) of Census 2010, additionally disaggregated by subzone and households with Chinese head/non-Chinese head

The template for each of the tables that I am requesting is attached, with the titles of the attached files in the format of "request_census####_Table#_topic.xlsx". Essentially, what I am requesting is to have all the attached templates filled out. Thank you so much for your help in advance!

[request_census2000_Table1_age.xlsx](https://github.com/datagovsg/datagovsg-datasets/files/5589355/request_census2000_Table1_age.xlsx)
[request_census2000_Table5_language_spoken_at_home.xlsx](https://github.com/datagovsg/datagovsg-datasets/files/5589356/request_census2000_Table5_language_spoken_at_home.xlsx)
[request_census2000_Table10_language.xlsx](https://github.com/datagovsg/datagovsg-datasets/files/5589357/request_census2000_Table10_language.xlsx)
[request_census2000_Table11_religion.xlsx](https://github.com/datagovsg/datagovsg-datasets/files/5589358/request_census2000_Table11_religion.xlsx)
[request_census2000_Table12_qualification.xlsx](https://github.com/datagovsg/datagovsg-datasets/files/5589359/request_census2000_Table12_qualification.xlsx)
[request_census2000_Table15_income.xlsx](https://github.com/datagovsg/datagovsg-datasets/files/5589360/request_census2000_Table15_income.xlsx)
[request_census2000_Table19_household_structure.xlsx](https://github.com/datagovsg/datagovsg-datasets/files/5589361/request_census2000_Table19_household_structure.xlsx)
[request_census2000_Table20_household_size.xlsx](https://github.com/datagovsg/datagovsg-datasets/files/5589362/request_census2000_Table20_household_size.xlsx)
[request_census2000_Table21_household_income.xlsx](https://github.com/datagovsg/datagovsg-datasets/files/5589363/request_census2000_Table21_household_income.xlsx)
[request_census2010_Table1_age.xlsx](https://github.com/datagovsg/datagovsg-datasets/files/5589365/request_census2010_Table1_age.xlsx)
[request_census2010_Table4_language_spoken_at_home.xlsx](https://github.com/datagovsg/datagovsg-datasets/files/5589366/request_census2010_Table4_language_spoken_at_home.xlsx)
[request_census2010_Table10_language.xlsx](https://github.com/datagovsg/datagovsg-datasets/files/5589367/request_census2010_Table10_language.xlsx)
[request_census2010_Table11_religion.xlsx](https://github.com/datagovsg/datagovsg-datasets/files/5589368/request_census2010_Table11_religion.xlsx)
[request_census2010_Table12_qualification.xlsx](https://github.com/datagovsg/datagovsg-datasets/files/5589369/request_census2010_Table12_qualification.xlsx)
[request_census2010_Table15_income.xlsx](https://github.com/datagovsg/datagovsg-datasets/files/5589370/request_census2010_Table15_income.xlsx)
[request_census2010_Table20_household_structure.xlsx](https://github.com/datagovsg/datagovsg-datasets/files/5589371/request_census2010_Table20_household_structure.xlsx)
[request_census2010_Table21_household_size.xlsx](https://github.com/datagovsg/datagovsg-datasets/files/5589372/request_census2010_Table21_household_size.xlsx)
[request_census2010_Table22_household_income.xlsx](https://github.com/datagovsg/datagovsg-datasets/files/5589373/request_census2010_Table22_household_income.xlsx)

### Do you know which agency provides/can provide this data?

Singapore Department of Statistics.

### If there's an issue with a dataset, please provide a description of the problem

Not applicable.

### Please provide the fields expected in this dataset:

Please see the attachment.

### How frequently would you need this dataset to be updated?

Not applicable.

### Can you give a short explanation on how you're planning to use this dataset?
The datasets will be used for an academic research project on the effect of superstition on housing market in China and Singapore.

**Comment by lennardl** [comment]
@hwangii You would need to approach the Department of Statistics for the disaggregated numbers https://www.singstat.gov.sg/
