### ISSUE TITLE
Dataset request: <Private Residential Property Transactions with Sale Prices>

### ISSUE THREAD

**Issue by weiling-samtech** [datagovsg/datagovsg-datasets#936]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Private Residential Property Transactions with Sale Prices

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Urban Redevelopment Authority

### If there's an issue with a dataset, please provide a description of the problem
No sale price is provided

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

Project Name | Street Name | Type | Postal District | Market Segment | Tenure | Type of Sale | No. of Units | Price ($) | Nett Price ($) | Area (Sqft) | Type of Area | Floor Level | Unit Price ($psf) | Date of Sale
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

1 MOULMEIN RISE | MOULMEIN RISE | Apartment | 11 | CCR | Freehold | Resale | 1 | 2350000 | - | 1249 | Strata | 21 to 25 | 1882 | Jul-19
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Do data analysis. Currently available data on URA only provide up to 5 years frame.

**Comment by lennardl** [comment]
@weiling-samtech I will check with URA but the data given by URA would probably be limited to that time frame as well.

**Comment by weiling-samtech** [comment]
ok thank you! hope to hear from you. :)

**Comment by lennardl** [comment]
@weiling-samtech URA has responded that for data beyond the 5 years it is behind a paywall on https://www.ura.gov.sg/realis

**Comment by weiling-samtech** [comment]
Hi ok thank you for your help 👍
