### ISSUE TITLE
Dataset request: Master Plan 1998 Shapefile Codebook

### ISSUE THREAD

**Issue by hwangii** [datagovsg/datagovsg-datasets#937]
### Please provide the name of the dataset or describe the dataset that you're requesting:

In the Master Plan 1998 Shapefile available at https://data.gov.sg/dataset/master-plan-1998-subzone-boundary-no-sea, we only have variables "Planning Area Code" and "Subzone Number" but we do not have any information about the names of these planning areas and subzones. It would be helpful to be provided a codebook that contains the crosswalk from the "Planning Area Code" and "Subzone Number" to their actual names.

### Do you know which agency provides/can provide this data?

Urban Redevelopment Authority

### If there's an issue with a dataset, please provide a description of the problem

Master Plan 1998 Shapefile is coded but the codebook is not provided.

### Please provide the fields expected in this dataset:
Planning_area_code | Subzone_number | Planning_area_name|Subzone_name
------|---------|-------------|---------------------------
TN|1|XXX|XXX

### How frequently would you need this dataset to be updated?
Not applicable

### Can you give a short explanation on how you're planning to use this dataset?
To use in an academic research project

**Comment by lennardl** [comment]
@hwangii Apologises I've checked but the codebook is not available
