### ISSUE TITLE
Dataset request: Vehicle registration number, model, year of make and chassis number

### ISSUE THREAD

**Issue by clarence-simplex** [datagovsg/datagovsg-datasets#938]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Motor vehicles

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
LTA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Vehicle Registration Number|Chassis Number|Manufacturer|Model|Series|Year of Make
e.g. SMW1234G|29834729375|Renault|Megan|2.0|2020

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Helping auto-mobile spare part stockist to digitalize.
Needed to build mobile app where mechanics enters car plate number/chassis number and the list of maintenance parts will be available for adding to cart for purchases

**Comment by lennardl** [comment]
@clarence-simplex That data is not available. You would have to approach LTA for it.
