### ISSUE TITLE
Dataset request: MRT/LRT Station Live Crowdedness

### ISSUE THREAD

**Issue by cameronkyc** [datagovsg/datagovsg-datasets#939]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Live Crowding data of Singapore's Public Transport Network

### Do you know which agency provides/can provide this data?
Land Transport Authority via SBS Transit & SMRT

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

    "value": [
        {
            "StationCode": "EW1",
            "StationName": "Pasir Ris",
            "Crowdedness": "Low",
            "Updated": "1607359715"
        },
         {
            "StationCode": "EW2",
            "StationName": "Tampines",
            "Crowdedness": "Moderate",
            "Updated": "1607359715"
        },
        {
            "StationCode": "DT32",
            "StationName": "Tampines",
            "Crowdedness": "High",
            "Updated": "1607359715"
        },

### How frequently would you need this dataset to be updated?
Example: 

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ X] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

With Covid19 looming, public transport passengers may decide on their travel plan based on the crowdedness of public transport infrastructure. With this api/data, it can empower diverse app developers in Singapore to open up the offering of such information on their apps, thus increasing Singaporean confidence of travelling on Singapore's MRT and LRT networks.

**Comment by lennardl** [comment]
@cameronkyc The live data from MRTs are not made available to us.
