### ISSUE TITLE
Dataset request: Wireless@sg locations

### ISSUE THREAD

**Issue by asl97** [datagovsg/datagovsg-datasets#94]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Wireless@sg locations, something like the pdf provided by IMDA but with additional coordinates if available in a more parsable format (json, csv, or other open format with the availability to export to csv).

### Do you know which agency provides/can provide this data?
Infocomm Media Development Authority (IMDA)
https://www.imda.gov.sg/-/media/imda/files/community/consumer-education/wirelless-sg/hotspot-list1.pdf?la=en

### If there's an issue with a dataset, please provide a description of the problem
There exists another dataset by GovTech but it's outdated.
https://data.gov.sg/dataset/wireless-hotspots?resource_id=d8febd81-5873-4070-b2c0-095657d3b362
1935 (kml) vs 4074 (pdf)

### Please provide the fields expected in this dataset:
Same as pdf with additional latitude + longitude if available.

Hotspot S/N|Location Type|Location Name|Street Address|Description|PostalCode|Operator|latitude|longitude
---|---|---|---|---|---|---|---|---
1|F&B|117 Aljunied Avenue 2 Market and Food Centre|117 Aljunied Avenue 2|Near stall #01-72|380117|Singtel|x|x

### How frequently would you need this dataset to be updated?
When the pdf gets updated.

### Can you give a short explanation on how you're planning to use this dataset?
To create a map containing wireless@sg location
* So people can better plan their journey.
* To make the list much more practical/useful/informative

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/wireless-hotspots
