### ISSUE TITLE
Dataset request: Dry Bulb Temperature and Relative Humidity - Hourly

### ISSUE THREAD

**Issue by hanzohan** [datagovsg/datagovsg-datasets#940]
### Please provide the name of the dataset or describe the dataset that you're requesting:
dry-bulb-temperature-hourly.csv
relative-humidity.csv

Its basically a similar dataset like
**https://data.gov.sg/dataset/wet-bulb-temperature-hourly**

but i need _**dry bulb temperature**_ and _**relative humidity instead**_

### Do you know which agency provides/can provide this data?
https://data.gov.sg/organization

### Please provide the fields expected in this dataset:
*dbt_date| dbt_time| dry_bulb_temperature)*
*rh_date| rh_time| relative_humidity)*

### Can you give a short explanation on how you're planning to use this dataset?
I want to compare changi climate station historical weather data with my weather stations data

**Comment by hanzohan** [comment]
Do you know which agency provides/can provide this data?
National Environment Agency

**Comment by lennardl** [comment]
@hanzohan The humidity and temperature are only provided to us on a monthly basis. It is possible to grab historical data from this API https://data.gov.sg/dataset/realtime-weather-readings
