### ISSUE TITLE
Dataset request: Historical Weather Forecast 

### ISSUE THREAD

**Issue by hanzohan** [datagovsg/datagovsg-datasets#941]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Historical Weather Forecast 

### Do you know which agency provides/can provide this data?
National Environment Agency

### Please provide the fields expected in this dataset:
JSON, like 24 hours weather forecast API output 
https://data.gov.sg/dataset/weather-forecast?resource_id=9a8bd97e-0e38-46b7-bc39-9a2cb4a53a62

### Can you give a short explanation on how you're planning to use this dataset?
I have to experiment with Machine Learning, i need **2 years** historical weather forecast for my ML's predictors

**Comment by lennardl** [comment]
You can use this and get historical data https://data.gov.sg/dataset/realtime-weather-readings
