### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by spstudent** [datagovsg/datagovsg-datasets#942]
### Please provide the name of the dataset or describe the dataset that you're requesting:
HDB Roads Under Construction
HDB Cycling Paths Under-Construction

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
HDB

### Please provide the fields expected in this dataset:
*(e.g. month | country | coordinates)*

month | country | coordinates
------|---------|-------------
2019-01|Singapore| [x,y,deg]

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Just a 1 time view of the datasets

**Comment by lennardl** [comment]
The cycling network can be found here https://data.gov.sg/dataset/cycling-path-network it was last updated on July 2020

**Comment by spstudent** [comment]
@lennardl I was wondering if I could get the update for the dataset: 'hdb roads under construction', that is updated on July 2020 if it is available? or the July 2019 version of both the 'hdb roads under construction' and 'hdb cycling paths under construction'?

**Comment by lennardl** [comment]
@spstudent Understood. I've reached out to HDB asking if the data can be refreshed.
