### ISSUE TITLE
Dataset request: <Patents filed in Singapore by Country and Classification>

### ISSUE THREAD

**Issue by kevyapch** [datagovsg/datagovsg-datasets#943]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Patents filed in Singapore by Country and Classification

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Intellectual Property Office of Singapore
### Please provide the fields expected in this dataset:
year | country
------|---------|
1985-2017|Singapore

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To examine the innovation performance in Singapore

**Comment by lennardl** [comment]
@kevyapch The current data on Data.gov.sg is outdated. I would have to refer you to IPOS for the latest data

**Comment by AA-85** [comment]
> @kevyapch The current data on Data.gov.sg is outdated. I would have to refer you to IPOS for the latest data

Hi Lennard, may I know the cause for the data on Data.gov.sg to be outdated and whether the root cause of the issue can be rectified since the data on Data.gov.sg is pulled from IPOS rather than pushed by IPOS?

**Comment by lennardl** [comment]
@AA-85 The cause of the problem was on our end, we tried to do one round of rectification but there were still issues. We intended to delay this as there is a plan to revamp data.gov.sg next year
