### ISSUE TITLE
Dataset request: <public holiday>

### ISSUE THREAD

**Issue by hanwen8** [datagovsg/datagovsg-datasets#944]
### Please provide the name of the dataset or describe the dataset that you're requesting:
https://data.gov.sg/dataset/singapore-public-holidays-for-2020

### Do you know which agency provides/can provide this data?
Ministry of man power
URL:https://www.mom.gov.sg/newsroom/press-releases/2020/0624-public-holidays-for-2021

### If there's an issue with a dataset, please provide a description of the problem
The current data.gov.sg link provided only shows 2020 which doesnt allow me to have visibility for year 2021 especially now its at the year end.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

date | day | holiday
------|---------|-------------
2017-09|Tuesday|Chinese new year

### How frequently would you need this dataset to be updated?

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am a software developer from GovTech, i wanted to create a email module (For MSF project) where i need to avoid sending emails during public holidays as the email will be a request to banks for fund transfer. Note: banks do not operate during public holidays

**Comment by lennardl** [comment]
https://data.gov.sg/dataset/singapore-public-holidays?resource_id=550f6e9e-034e-45a7-a003-cf7f7e252c9a
