### ISSUE TITLE
Acra Entities Details Dataset

### ISSUE THREAD

**Issue by eyeveye** [datagovsg/datagovsg-datasets#946]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Acra entities details dataset (require frequent update)

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Acra

### If there's an issue with a dataset, please provide a description of the problem
The existing data set is not update frequently. The last updated on the entity details set is in Sept 2020

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Existing fields are good

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [x] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To provide a full set of information for user to refer.

**Comment by lennardl** [comment]
@eyeveye The ACRA data on the site is not updated frequently. If you need timely data, I would suggest approaching and using ACRA's system
