### ISSUE TITLE
Dataset request: Statistics on Depression in Singapore

### ISSUE THREAD

**Issue by zhaoyi98** [datagovsg/datagovsg-datasets#95]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Depression statistics in singapore

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
IMH

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by zhaoyi98** [comment]
For project

**Comment by iewil** [comment]
@zhaoyi98 please provide more details about the type of data you would require from such a dataset.
