### ISSUE TITLE
Dataset request: List of URA Planning boundaries region , area and subzone

### ISSUE THREAD

**Issue by chunleongyapMHC** [datagovsg/datagovsg-datasets#951]
### Please provide the name of the dataset or describe the dataset that you're requesting:

List of URA Planning boundaries region , area and subzone

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

URA
https://www.ura.gov.sg/maps/?service=demographics#

### If there's an issue with a dataset, please provide a description of the problem

N/A

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

Region | Area|Subzone
------|---------|-------------
EAST REGION| BEDOK|BAYSHORE

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

If the data is provided in API, we will integrate such API with our system, and when user inputs the address information, there will 3 different fields that called this API (region, area and subzone) for a user to select.

If the data is provided in excel, we will hardcoded our system and stored the list of region, area and subzone on our server.

**Comment by lennardl** [comment]
@chunleongyapMHC I've approached URA to ask if the data can be made available on data.gov.sg

**Comment by chunleongyapMHC** [comment]
hi @lennardl, I will close this issue because URA provided the data in KML format and we can retrieve the list by converting KML to Excel file format.
Thus, I will close this request now. :)
Thank you very much for your assistance.
