### ISSUE TITLE
Dataset request: flat price

### ISSUE THREAD

**Issue by marymountee** [datagovsg/datagovsg-datasets#953]
I would like to have access to the flat price data as provided as one of the data sets. The data set is available at following url. However, I would need the data to be downloaded either via API or in csv. I have tried the API but received a "HTTP Error 403: forbidden" error. I would need to get either the privilege to access via API or a set of the data. 

The data I need is all the flat price with following attributes: 
- Sales Transaction Month 
- Town
- Flat Type
- Postal Code
- Block
- Street Name
- Storey (ideally exact storey number) 
- Unit Number
- Floor Area (SQM)
- Flat Model
- Lease Commence Date
- Remaining Lease
- Resales Price

Ideally I will need the data to be refreshed in a daily basis. But weekly or even monthly is acceptable at the beginning. 

I am planning to use this data to develop a property index view to allow advanced property searching. Happy to have a call to clarify how to use it. You may call me at +65 93862568.

**Comment by lennardl** [comment]
We only have this data and HDB updates is on a monthly basis https://data.gov.sg/dataset/resale-flat-prices
