### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by jstout8425** [datagovsg/datagovsg-datasets#954]
### Please provide the name of the dataset or describe the dataset that you're requesting: 
Listing of Registered Therapeutic Products

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

Health Sciences Authority
--

Source URL | http://eservice.hsa.gov.sg/prism/common/enquirepublic/SearchDRBProduct.do?action=load
-- | --

### If there's an issue with a dataset, please provide a description of the problem
Current dataset has not been updated for over an year. Would it be possible to begin providing monthly update for this dataset.

### Please provide the fields expected in this dataset:

No. | Name | Title | Type | Unit of Measure | Description
-- | -- | -- | -- | -- | --
1 | licence_no | Licence no | Text (General) | - | -
2 | product_name | Product Name | Text (General) | - | Product name
3 | license_holder | License holder | Text (General) | - | -
4 | approval_date | Approval Date | Text (General) | - | Registration date of the product
5 | forensic_classification | Forensic Classification | Text (General) | - | Classification of a therapeutic product as "Prescription-Only Medicine", "Pharmacy-Only Medicine" or "General Sale List Medicine"
6 | atc_code | ATC Code | Text (General) | - | WHO Anatomical Therapeutic Chemical code"-" : Data is negligible or not significant
7 | dosage_form | Dosage Form | Text (General) | - | Physical form of the finished product e.g. tablet, capsule, injection
8 | route_of_administration | Route of Administration | Text (General) | - | Path by which the product is taken into the body
9 | manufacturer | Manufacturer | Text (General) | - | Name of the product manufacturer
10 | country_of_manufacturer | Country of Manufacturer | Text (General) | - | Country of product manufacturer
11 | active_ingredients | Active Ingredients | Text (General) | - | Ingredient in the product that is biologically active
12 | strength | Strength | Text (General) | - | Strength of the active ingredient

### How frequently would you need this dataset to be updated?

- [X] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Compare changes monthly for drug database maintenance for NGEMR

**Comment by lennardl** [comment]
@jstout8425 We have the dataset here but it only updated by HSA on an annual basis. To get the most updated version you might need to refer back to their site

**Comment by jstout8425** [comment]
@lennardl - Ok, so I need to contact HSA to get the annual file and maybe request for monthly updates from them. Thanks for your help

**Comment by lennardl** [comment]
@jstout8425 HSA would probably point you to the URL you have but yes they will have the past months data in storage

**Comment by jstout8425** [comment]
Thank you

Justin Stout
Manager, Content Editing
Global Drug Database | International & Domestic Embedded Content
Clinical Drug Information: UpToDate | Lexicomp | Medi-Span | Facts & Comparisons | Emmi Solutions

Justin.Stout@wolterskluwer.com <mailto:Justin.Stout@wolterskluwer.com>
[cid:image001.jpg@01D40DE9.AC471E30]<http://www.wolterskluwer.com/>

Join Wolters Kluwer on  Facebook<https://www.facebook.com/wolterskluwer>  Twitter<https://twitter.com/Wolters_Kluwer>  Linkedin<https://www.linkedin.com/company/wolters-kluwer>  Youtube<https://www.youtube.com/user/WoltersKluwerComms>

Confidentiality Notice: This email and any attachments may contain confidential or privileged information that is intended for the addressee only. If you are not an intended recipient of the original sender (or responsible for delivering the message to such person), you are hereby notified that any review, disclosure, copying, distribution or the taking of any action in reliance of the contents of and attachments to this email is strictly prohibited. If you have received this email in error, please immediately notify the sender at the address shown herein and permanently delete any copies of this email (digital or paper) in your possession. Wolters Kluwer shall not be liable for the incorrect or incomplete transmission of this email or any attachments, nor for unauthorized use by its employees.
