### ISSUE TITLE
Dataset request: <4 Day Weather Forecast API>

### ISSUE THREAD

**Issue by rick0222** [datagovsg/datagovsg-datasets#955]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [x] Real-time

**Comment by rick0222** [comment]
4 Day Weather Forecast API was working fine last week. But not sure why it become empty since 1st of January 2021. Please help to look into it. Thanks..

https://api.data.gov.sg/v1/environment/4-day-weather-forecast

**Comment by lennardl** [comment]
@rick0222 We are getting in touch with NEA to check on this

**Comment by rick0222** [comment]
Hi @lennardl , do you have any idea what happened to this API? It is still empty as of now. 
https://api.data.gov.sg/v1/environment/4-day-weather-forecast

**Comment by rick0222** [comment]
Hi @lennardl , Mind to help check?

**Comment by lennardl** [comment]
@rick0222 There's an issue on NEA's end. We're waiting on their end to resolve the issue.
