### ISSUE TITLE
Dataset request: <PSLE Math Score 2016 to 2020>

### ISSUE THREAD

**Issue by NYUsiong** [datagovsg/datagovsg-datasets#956]
### Please provide the name of the dataset or describe the dataset that you're requesting:
1. Dataset of scores of PSLE Math breakdown from 2016 to 2020. For example, the distribution of students who score A*, A, B, C, D and F every year from 2016 to 2020. 

2. Dataset of scores by PSLE Math topic / categories from 2016 to 2020. For example, on average how many points would students score for fractions, algebra OR MCQs, Problem Sums, Paper 1, Paper 2 every year from 2016 to 2020.  

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

MOE/SEAB

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

Year | Overall Score | Paper 1 Booklet A Score | Paper 1 Booked B Score | Paper 2 Score |  

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

I like to use the data to support how targeted my online teaching platform should be. Thank you.

**Comment by lennardl** [comment]
@NYUsiong MOE does not provide the breakdown to us at that level, you could potentially approach MOE to see if they are willing to share this
