### ISSUE TITLE
Dataset request: "Real-time" Data Updates for ACRA Company list

### ISSUE THREAD

**Issue by IllumiGit** [datagovsg/datagovsg-datasets#958]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Current dataset: ACRA Information on Corporate Entities

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
ACRA

### If there's an issue with a dataset, please provide a description of the problem
Currently, this Dataset sorts by alphabetical order and does not offers a curated list of companies is a file. In addition, an API would be very helpful to get updates whenever needed

### Please provide the fields expected in this dataset:
NA

### How frequently would you need this dataset to be updated?
- [X] Annually
- [] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
It's tedious to check back every time when an update of the company details are required. Hence, an API would be very helpful.

**Comment by lennardl** [comment]
@IllumiGit The current platform does not support real-time updates to end-users on whenever new items are inserted. Currently, the data is also updated roughly on a monthly basis.

**Comment by conghungypbn** [comment]
> @IllumiGit The current platform does not support real-time updates to end-users on whenever new items are inserted. Currently, the data is also updated roughly on a monthly basis.

According to the web site, the latest update is December 28, 2020. But the actual file contain uen issue_date to 2019-09-18.

**Comment by conghungypbn** [comment]
@lennardl Can you check for the data update, please?

**Comment by lennardl** [comment]
Will check in on the dataset as well as with ACRA. If you need a realtime list of ACRA companies I would advise using the ACRA system though
