### ISSUE TITLE
Dataset request: Incomplete Dataset - Missing value

### ISSUE THREAD

**Issue by IllumiNinja** [datagovsg/datagovsg-datasets#959]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Rate of Re-entry Into Employment for Retrenched Residents (Six Months Post-Retrenchment), Quarterly
https://data.gov.sg/dataset/rate-of-re-entry-into-employment-quarterly?resource_id=dfffd17c-d8eb-42ec-b98d-00c07e7c23a0

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
MOM

### If there's an issue with a dataset, please provide a description of the problem
Missing data

**Comment by lennardl** [comment]
@IllumiNinja Can I clarify you what is the missing data you're looking for?

**Comment by IllumiNinja** [comment]
@lennardl for certain rows in downloaded file, there is no data but a letter "s"

**Comment by lennardl** [comment]
@IllumiNinja Thanks for this, I've confirmed and informed MOM of this. Waiting on their response to fix.

**Comment by IllumiNinja** [comment]
@lennardl No worries, thank you!

**Comment by lennardl** [comment]
@IllumiNinja MOM has responded that ‘s’ means that data is suppressed. It's not missing its intentional.

**Comment by IllumiNinja** [comment]
@lennardl I see, thank you for clarifying
