### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by gary-chin** [datagovsg/datagovsg-datasets#960]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2019-01|Singapore|100000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [x] Annually
- [x] Monthly
- [x] Weekly
- [x] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@gary-chin Can you provide more details on what data you're looking for?
