### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by kuansong** [datagovsg/datagovsg-datasets#963]
### Please provide the name of the dataset or describe the dataset that you're requesting:
National Birth Defects Registry

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Health / National Birth Defects Registry

### If there's an issue with a dataset, please provide a description of the problem
N.A. 

### Please provide the fields expected in this dataset:

month for each year
Singapore 
List of birth defects
Number of births with such defects 

### How frequently would you need this dataset to be updated?
Example: 

Annually 

### Can you give a short explanation on how you're planning to use this dataset?

i'm planning to do some research on the impact of preventive measures for disability and would like to access the data. I do notice that some of this data has been published in academic articles in early years (1990-2004) but would like to know and see the entire data set instead of relying on such articles and also to get a clearer update for more contemporary times.

**Comment by lennardl** [comment]
@kuansong I've reached out to MOH asking if the data can be made available.

**Comment by kuansong** [comment]
Hello!

Sorry just checking if this request has been closed becos data has been provided or is it still pending?

Cheers
Vic
