### ISSUE TITLE
Dataset request: <acra-information-on-corporate-entities>

### ISSUE THREAD

**Issue by showall** [datagovsg/datagovsg-datasets#964]
### Please provide the name of the dataset or describe the dataset that you're requesting:
acra-information-on-corporate-entities

### Do you know which agency provides/can provide this data?
ACRA

### If there's an issue with a dataset, please provide a description of the problem
The dataset has been missing while I could not find anything listed on (https://www.acra.gov.sg/about-bizfile/updates-and-announcements/acra-s-open-data-initiative) that suggests this dataset will be removed. 

### Please provide the fields expected in this dataset:
Basic Entity Information (Business name, UEN, Date of incorporation/registration, Status, Entity type, etc.)
Registered office address
Singapore Standard Industrial Classification (SSIC) (Primary, Secondary, User Prescribed Activity)

### How frequently would you need this dataset to be updated?
Example: 

- [ ] Annually
- [ X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
To identify the business' industrial classification

**Comment by lennardl** [comment]
@showall The dataset was undergoing an update and it has been made available again.
