### ISSUE TITLE
Dataset request: Details of Registered Societies

### ISSUE THREAD

**Issue by IllumiNinja** [datagovsg/datagovsg-datasets#965]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Registry of Societies

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Home Affairs

### Please provide the fields expected in this dataset:
Depending on what's available

### How frequently would you need this dataset to be updated?
Example: 

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@IllumiNinja Been redirected to https://www.ros.mha.gov.sg/

**Comment by IllumiNinja** [comment]
@lennardl Sorry I meant the details of the registered societies such as their UEN and etc

**Comment by lennardl** [comment]
@IllumiNinja Would that be under the ACRA dataset for UEN?

**Comment by IllumiNinja** [comment]
Nope, Societies are registered with Ministry of Home Affairs so those UEN aren't included in the ACRA dataset

**Comment by lennardl** [comment]
@IllumiNinja I've approached MHA and waiting on a response from them.

**Comment by IllumiNinja** [comment]
@lennardl thank you

**Comment by IllumiNinja** [comment]
Hi @lennardl , can I check with you the status on this? Thank you

**Comment by lennardl** [comment]
@IllumiNinja Does it fall under https://data.gov.sg/dataset/entities-with-unique-entity-number

**Comment by IllumiNinja** [comment]
@lennardl thanks, I think this covers the dataset needed
