### ISSUE TITLE
Dataset request: Locations of Recycling Bins

### ISSUE THREAD

**Issue by arnav002** [datagovsg/datagovsg-datasets#966]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Recycling Bins
(https://data.gov.sg/dataset/recycling-bins)

### Do you know which agency provides/can provide this data?
National Environment Agency and/or OneMap (https://www.onemap.sg/home/)

### If there's an issue with a dataset, please provide a description of the problem
The data set is given on the data.gov.sg website, however, there is no data within it. There should be a map with the locations of all the recycling bins in Singapore, however, the map is empty at present. Kindly request you to look into this matter to see if the data can be obtained.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Name | Address Postal Code | Latitude | Longitude | Recycling Options for that Bin

### How frequently would you need this dataset to be updated?
- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I speak on behalf of a group of NTU students looking to develop a mobile app as part of a course project. Our motivation behind the app was to make it a 'Green App' in which one of the features is to find the nearest recycling bin around you so that you can recycle glass and plastics more and make Singapore even more eco-friendly! Hence, the data on the location of the recycling bins is required.

**Comment by lennardl** [comment]
@arnav002 Can you download the file and use Google Earth there's a problem with the display but there's data and its available within the layer
