### ISSUE TITLE
Dataset request: Traffic Accidents

### ISSUE THREAD

**Issue by chiamdj** [datagovsg/datagovsg-datasets#97]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Traffic Accidents

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Singapore Police Force, Ministry of Home Affairs

### If there's an issue with a dataset, please provide a description of the problem
The current accident data available (https://data.gov.sg/dataset/causes-of-road-accidents-causes-of-accidents-by-severity-of-injury-sustained?view_id=e80588ff-310c-4199-93bf-e6479e160634&resource_id=d68321b6-c438-425d-b9f4-d5777eee9e77) only have aggregated accident data for each accident cause, without specific attributes and details for each accident.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

DateTime | latitude | longitude | cause of accident | vehicle type | injury type|gender|age
------|---------|-------------|-----|-------|-------|----|----
2018-25-01_12:00:00 |1.32918048555782|103.885470079756|vehicle crash|lorry|fatal|M|40

### How frequently would you need this dataset to be updated?
- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [X] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

I am currently intending to do a thesis related to the identification of traffic accident hotspots in Singapore using geospatial technology and spatial statistics. My research aims to identify, classify and rank such hotspots and accident-prone areas in Singapore; and it is hoped that my findings could manifest within policy-led investigations that could increase the safety of our roads in Singapore.

**Comment by lucasarea** [comment]
I am doing my PhD research in traffic safety as well, and I am very interested in this data. How do I know the request was granted? If yes, do I have to create another request for myself to access it too?
