### ISSUE TITLE
Dataset request: Status of HDB Upgrading/ Estate Renewal Programmes

### ISSUE THREAD

**Issue by zxcvanessa** [datagovsg/datagovsg-datasets#970]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Status of the following HDB Upgrading/ Estate Renewal Programmes:
- Home Improvement Programme
- Neighbourhood Renewal Programme
- Lift Upgrading Programme
- Main Upgrading Programme
- Interim Upgrading Programme

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

HDB already shares this data publicly, at the following link: https://services2.hdb.gov.sg/webapp/BB33RESLSTATUS/BB33SEnquiry

However, it is presented in an inaccessible format - users have to navigate multiple drop-down fields and make many clicks just to access information for one block. Even then, the data cannot be easily copy-pasted into an Excel spreadsheet. 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

- block | street name | town | HIP | HIP announcement date | HIP billing date
- block | street name | town | NRP | NRP announcement date | NRP billing date
- block | street name | town | LUP | LUP announcement date | LUP billing date
- block | street name | town | MUP | MUP announcement date | MUP billing date
- block | street name | town | IUP | IUP announcement date | IUP billing date

### How frequently would you need this dataset to be updated?
Example: 

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

I'm planning to use it in my undergraduate dissertation. I'm running a hedonic regression, and this data would be incredibly useful. Thanks in advance!

**Comment by lennardl** [comment]
@zxcvanessa I've reached out to HDB to ask.

**Comment by zxcvanessa** [comment]
Thank you @lennardl! Appreciate it.

**Comment by zxcvanessa** [comment]
Hi @lennardl, wondering if there's any update on this request? Thanks so much.

**Comment by lennardl** [comment]
@zxcvanessa Apologises HDB did not provide the data, you probably have to reference their site
