### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by 20Data18** [datagovsg/datagovsg-datasets#971]
### Please provide the name of the dataset or describe the dataset that you're requesting:

Community club
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

People association 
### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

1. Tampines east community centre
2. Chai chee community centre 

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

- [X] Test

### Can you give a short explanation on how you're planning to use this dataset?
To compile the list of community centres in Singapore

**Comment by lennardl** [comment]
Does this work? 
https://data.gov.sg/dataset/community-clubs
