### ISSUE TITLE
Listing of Registered Therapeutic Products

### ISSUE THREAD

**Issue by MedicellRA** [datagovsg/datagovsg-datasets#973]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Updated listing of registered therapeutic products as of December 2020

### Do you know which agency provides/can provide this data? http://eservice.hsa.gov.sg/prism/common/enquirepublic/SearchDRBProduct.do?action=load
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [x] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@MedicellRA The Health Science Authority has stated that they are updating the data on an annual basis on Data.gov.sg if you need more recent data you would have to refer to their site.
