### ISSUE TITLE
Dataset request: <Pollution Standards Index>

### ISSUE THREAD

**Issue by seriousleet** [datagovsg/datagovsg-datasets#975]
### Do you know which agency provides/can provide this data?
NEA 

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | air pollutants
------|---------|-------------
2010-01|Singapore|

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ X] Annually
- [ X] Monthly
- [ X] Weekly
- [ X] Daily
- [ X] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@seriousleet We have a realtime API available here which will also allow you to retrieve previous data https://data.gov.sg/dataset/psi

**Comment by seriousleet** [comment]
> @seriousleet We have a realtime API available here which will also allow you to retrieve previous data https://data.gov.sg/dataset/psi

hi @lennardl , do you know how I can obtain the data over a period of time, instead of getting them one by one?

**Comment by lennardl** [comment]
@seriousleet currently that is not possible unless you run a loop to extract daily data
