### ISSUE TITLE
Dataset request: Amenities/Facilities

### ISSUE THREAD

**Issue by athenawisdoms** [datagovsg/datagovsg-datasets#977]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Amenities/facilities in Singapore, arranged into categories such as

- Clinics
- Groceries
- Childcare Centres
- Kindergarden
- Bus Stops
- MRTs
- Shopping Malls
- Dentists
- ATMs
- Bank Branches
- Libraries
- Parks
- Community Clubs
- Churches

### Do you know which agency provides/can provide this data?
Uncertain

### Please provide the fields expected in this dataset:

category | name | lat | long
------|---------|-------------|---
groceries|NTUC FAIRPRICE CO-OPERATIVE LTD|1.3483914|103.8409176

### How frequently would you need this dataset to be updated?

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?

Research into property prices

**Comment by lennardl** [comment]
@athenawisdoms We only have some of the data which can be found at the following links

https://data.gov.sg/search?q=nparks
https://data.gov.sg/search?q=childcare
https://data.gov.sg/dataset/community-clubs
https://data.gov.sg/dataset/master-plan-2019-rail-station-layer
https://data.gov.sg/dataset/libraries

We do not have the data on malls, dentist, churches, clinics, grocers and bank branches
