### ISSUE TITLE
half hourly

### ISSUE THREAD

**Issue by jerry-wuyuxin** [datagovsg/datagovsg-datasets#980]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by lennardl** [comment]
@jerry-wuyuxin Can you elaborate more on what half-hourly data you are looking for?

**Comment by jerry-wuyuxin** [comment]
Thanks for your reply：
I am looking for the historical electricity system demand data for
every half-hour period in Singapore from January 2020 to December 2020
thanks!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "datagovsg/datagovsg-datasets"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月2日(星期二) 上午9:36
收件人:&nbsp;"datagovsg/datagovsg-datasets"<datagovsg-datasets@noreply.github.com&gt;;
抄送:&nbsp;"雨芯"<532426341@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [datagovsg/datagovsg-datasets] half hourly (#980)





 
@jerry-wuyuxin Can you elaborate more on what half-hourly data you are looking for?

**Comment by lennardl** [comment]
@jerry-wuyuxin We have a few data points relating to electricity demand/usage that can be found here https://data.gov.sg/search?q=electricity but for the specifics on electricity demand per half-hour that is not available.
