### ISSUE TITLE
Dataset request: <Public Transport Utilisation - Average Daily Public Transport Ridership>

### ISSUE THREAD

**Issue by eatenlow** [datagovsg/datagovsg-datasets#981]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Public Transport Utilisation - Average Daily Public Transport Ridership

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Land Transport Authority

### If there's an issue with a dataset, please provide a description of the problem
The dataset is not updated

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [ X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I will be using it for a school assignment, to do a research relating to the usage of public transport

**Comment by lennardl** [comment]
@eatenlow The dataset can be found here https://data.gov.sg/dataset/public-transport-utilisation-average-public-transport-ridership 

I've approached LTA asking for an update to the dataset.
