### ISSUE TITLE
Dataset request: Deaths By Age Group, Occupation And Sex

### ISSUE THREAD

**Issue by spstudent** [datagovsg/datagovsg-datasets#983]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Deaths By Age Group, Occupation And Sex

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Home Affairs - Immigration & Checkpoints Authority

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

year | sex | Age Group | Occupation | Deaths

### How frequently would you need this dataset to be updated?
Example: 
- [] *Test*

- [ ] Annually
- [x] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I would like to find out the number of deaths by age_group and occupation and gender for 2020 for a school project

**Comment by lennardl** [comment]
The data is updated on an annual basis the data for 2020 would only be made available in the latter half of 2021
