### ISSUE TITLE
Dataset request: Live-Births (Single & Twins Births) by Period of Gestation, Birth Weight and Child Gender

### ISSUE THREAD

**Issue by spstudent** [datagovsg/datagovsg-datasets#984]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Live-Births (Single & Twins Births) by Period of Gestation, Birth Weight and Child Gender

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Home Affairs - Immigration & Checkpoints Authority

### If there's an issue with a dataset, please provide a description of the problem
-

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
Year | Period of Gestation | Birth Weight | Gender | Type of Birth | Birth Count

### How frequently would you need this dataset to be updated?
Example: 
- [] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am looking for the available data for 2020 for a school project

**Comment by lennardl** [comment]
Similar to the other datasets the 2020 data will only be made available at the latter half of the year by the data providers
