### ISSUE TITLE
Dataset request: Mothers by Age Group and Type of Birth

### ISSUE THREAD

**Issue by spstudent** [datagovsg/datagovsg-datasets#985]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Mothers by Age Group and Type of Birth

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Home Affairs - Immigration & Checkpoints Authority

### Please provide the fields expected in this dataset:
month | birth type | mother age group | total number of mother (number of mothers)

### How frequently would you need this dataset to be updated?
Example: 
- [] *Test*

- [ ] Annually
- [X] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am looking for the available data for 2020 for a school project

**Comment by lennardl** [comment]
@spstudent The data for 2020 will only be updated at the latter half of 2021
