### ISSUE TITLE
Dataset request: <Urological Cancer>

### ISSUE THREAD

**Issue by Ashtonz** [datagovsg/datagovsg-datasets#989]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Incidence rate of bladder cancer over recent years
Incidence rate of urological cancer(prostate + kidney + bladder cancer) in Singapore
Number of incidence of Hematuria (blood in urine) in Singapore
Estimated number of new cases of Urological cancer in 2020 compared to previous years 

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
MOH, HSA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month/year | incidence rate/occurances
------|---------|-------------

### How frequently would you need this dataset to be updated?
Example: 
- [X ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Doing market research on urological cancer and identifying if there is a need to develop a product to solve this issue

**Comment by lennardl** [comment]
@Ashtonz I've reached out to MOH asking if the data can be made available.
