### ISSUE TITLE
Dataset request: Government Procurement via GeBiz

### ISSUE THREAD

**Issue by aaronsothmann** [datagovsg/datagovsg-datasets#99]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Government Procurement via GeBiz
https://data.gov.sg/dataset/government-procurement?resource_id=b9d8d509-5cb6-45dc-bb46-9508e670e3c2

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Ministry of Finance

### If there's an issue with a dataset, please provide a description of the problem
The coverage for the dataset is January 2, 2015 to January 31, 2017. Is there a more recent update which includes data up to January 2, 2018?

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

**Comment by iewil** [comment]
@aaronsothmann the coverage of the current dataset only contains data up till dec 2017. We're still working with our colleagues from the Ministry of Finance to see if it'll be possible to get this updated more regularly.
