### ISSUE TITLE
Dataset request: Rainfall across Singapore

### ISSUE THREAD

**Issue by smaranan2019** [datagovsg/datagovsg-datasets#991]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Rainfall across Singapore

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
NEA

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
YYYY-MM-DD[T]HH:mm:ss (SGT)

### How frequently would you need this dataset to be updated?
Example: 
- [ ] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [X ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I plan to great a telegram bot that would show me if it is raining in dhoby ghaut right now

**Comment by lennardl** [comment]
You can get the data from https://data.gov.sg/dataset/realtime-weather-readings?resource_id=8bd37e06-cdd7-4ca4-9ad8-5754eb70a33d via Handy Road
