### ISSUE TITLE
Dataset request: Carpark Availability

### ISSUE THREAD

**Issue by Visvasruthi** [datagovsg/datagovsg-datasets#997]
### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
Housing Development Board(HDB)

### If there's an issue with a dataset, please provide a description of the problem
I need an authorisation code so that i can use the data from this API.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*
hourly data of carpark availability in the Kampong Glam area over the years.
month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [X] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
We are a group of students from SMU doing a Final Year Project on Kampong Glam. We are collaborating with URA. We want to analyse the usage of the carparks in the Kampong Glam area over the years to give us more insights on the carpark usage in the area.

**Comment by lennardl** [comment]
@Visvasruthi the APIs are open and not locked so you should be able to access the data and APIs without any authorisation code on our site.
