### ISSUE TITLE
Dataset request: Private Dwelling Units

### ISSUE THREAD

**Issue by rea-admin** [datagovsg/datagovsg-datasets#999]
### Please provide the name of the dataset or describe the dataset that you're requesting:
I would like an update of the private dwelling units.

https://data.gov.sg/dataset/ura-no-of-dwelling-units-current-year  
exist but there is no file?  

the latest available is https://data.gov.sg/dataset/ura-no-of-dwelling-units --- November 2018

**Comment by lennardl** [comment]
An update was done here https://data.gov.sg/dataset/ura-no-of-dwelling-units
